### ISSUE TITLE
uninitialized constant Api::V1::DependenciesController

### ISSUE THREAD

**Issue by qhwa** [rubygems/rubygems.org#1005]
Hi, I'm trying to setup a rubygems mirror with dependencies api requests served.
I was trying to figure out how gems dependencies are computed by playing around this project but got a routing error when requesting `http://127.0.0.1:3000/api/v1/dependencies'

~~~
Started GET "/api/v1/dependencies?gems=lfd" for 127.0.0.1 at 2015-07-04 09:46:28 +0800

ActionController::RoutingError (uninitialized constant Api::V1::DependenciesController):
  app/middleware/hostess.rb:47:in `call'
  app/middleware/redirector.rb:21:in `call'
~~~

I found `api/v1/dependencies` declared in `config/routes.rb` but no controller files available.
There seams to be no git submodules here.
Is api requests served in other project or is this controller somewhere else?

thanks.

**Comment by dwradcliffe** [comment]
Looks like this is a bug from leftover code. The dependency api is a [separate app](https://github.com/bundler/bundler-api) right now, running on heroku. We proxy requests to the app [from our load balancer](https://github.com/rubygems/rubygems-infrastructure/blob/dc5633b6cbc7cbd95479b1490df2cff0f837766d/cookbooks/rubygems-balancer/templates/default/site.conf.erb#L239-L242).

**Comment by qhwa** [comment]
got it, thanks @dwradcliffe
