### ISSUE TITLE
Replace as_json with ActiveModel::Serializers

### ISSUE THREAD

**Issue by sferik** [rubygems/rubygems.org#1027]
[Rationale](https://robots.thoughtbot.com/better-serialization-less-as-json)

**Comment by smoak** [comment]
I am interested in taking on this work. However, the article you linked to talks about [rails-api/active_model_serializers](https://github.com/rails-api/active_model_serializers), but there is also[ActiveModel::Serializers::JSON](http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html) in rails. Which one do you think I should use?

**Comment by sferik** [comment]
I think they’re basically the same thing. `ActiveModel::Serializers` used to be a separate project but has since been merged into Rails.

**Comment by bf4** [comment]
@sferik Not quite. `ActiveModel::Serializers::JSON` is part of the `ActiveModel::Serialization` interface that mixes in `serializable_hash`, `as_json`, and `as_xml`.   [rails-api/active_model_serializers (AMS)](https://github.com/rails-api/active_model_serializers) has serializers and adapter that use the `ActiveModel::Serializers::JSON`mixin or interface to serialize a resource into json, json-api, etc. formats.  AMS is a 'competitor' to jbuilder, https://github.com/RestPack/restpack_serializer, https://github.com/cerebris/jsonapi-resources etc.

For more info, see
- http://www.benjaminfleischer.com/2015/06/02/understanding-rails-model-serializers/
- https://groups.google.com/d/topic/rubyonrails-core/K8t4-DZ_DkQ/discussion
- See https://github.com/rails-api/active_model_serializers/pull/996/files#diff-56455571c4ba7a2b4c640b9e8168f522R42

**Comment by bf4** [comment]
(That said, if there's interest, it should be a pretty simple PR.  I'm somewhat active on the AMS 0.10.rcx releases)

**Comment by sferik** [comment]
@bf4 Thanks for explaining that! If you’re interested in working on that pull request, I’d say: “go for it!”

**Comment by bf4** [comment]
np, I've been digging into a bit. Fallout from working on a rails-api-based microservices architecture consumed by ember :)

**Comment by mcfiredrill** [comment]
@bf4 Have you got any PRs for this? 
I was thinking about working on it.

**Comment by bf4** [comment]
Not as yet but would be happy to pair or coach

B mobile phone

**Comment by mcfiredrill** [comment]
@bf4 I noticed most models have `to_xml` and `to_yml` methods as well. Any ideas if we can replace these with something else as well?

**Comment by bf4** [comment]
Ruby libs mix those in (or active::model). Not sure there's any valur if you have to go looking for it

B mobile phone

**Comment by jvanbaarsen** [comment]
@sonalkr132 Since the PR was closed, maybe we can remove the `Attached PR` label?

**Comment by sonalkr132** [comment]
Consider #1409 or #1464 as `attached PR` :paperclip: 
I would support closing both of those PRs along with this issue. Moving over to AMS is not as straight forward as it may seem [[1](https://github.com/rubygems/rubygems.org/pull/1409#r77448047)][[2](https://github.com/rubygems/rubygems.org/pull/1464#discussion_r98825243)]. @bf4 [mentions of a possible performance hit](https://github.com/rubygems/rubygems.org/pull/1464#discussion_r98925000).

**Comment by sonalkr132** [comment]
We are doing this. I don't see this as an obvious improvement (see my comment above).
