### ISSUE TITLE
announcements have no styles

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1030]
During the redesign it looks like we lost all the announcement styles.

![rubygems org your community gem host 2015-07-24 11-03-22](https://cloud.githubusercontent.com/assets/118850/8877473/acd708c6-31f3-11e5-8fb4-981c69c58e08.png)

**Comment by arthurnn** [comment]
what is the link?

**Comment by spk** [comment]
I think its an `Announcement` from `paul_revere` gem ? So its on every page when there is something on database.

**Comment by dwradcliffe** [comment]
Yep exactly. From rails console: `Announcement.create(body: 'This is a test')` then view any page.

**Comment by Zanadar** [comment]
Hey guys.  I just put up a fix for this here https://github.com/rubygems/rubygems.org/pull/1082.
