### ISSUE TITLE
Consider adding rubygems version on the right side on a per-project basis

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1037]
Hello.

Currently, on a given project, on the right side, we can see something such as:

"Required Ruby Version:
>= 2.2.0 "

Could, below that, also be added a:

"Required Rubygem Version:
> 2.4.8"

?

This may give people the ability to quickly check out which rubygem version they need prior to installation. Thanks.

**Comment by qrush** [comment]
There is a `required_rubygems_version` [part of the gemspec](http://guides.rubygems.org/specification-reference/#required_rubygems_version)...however I have rarely seen this used. Perhaps if you're willing to do a survey of some popular gems and see if it's actually implemented in their `gemspec`, that might be a better argument for including this on the gem page. I'm starting to feel that it's getting pretty cluttered already so I'd like there to be more rationale for including this on the page.

**Comment by dwradcliffe** [comment]
We need this for the dependency api and the new index. We need to parse this from the gemspec when gems are pushed and save it to the database. We will also need a backfill task to go back and fill in the data for all existing gems.

@sonalkr132 is going to work on this.

**Comment by dwradcliffe** [comment]
cc: @maclover7 @indirect @segiddins

**Comment by dwradcliffe** [comment]
FYI this was added to the gem/version page in #1307
