### ISSUE TITLE
Suggest change the gem page layout

### ISSUE THREAD

**Issue by huacnlee** [rubygems/rubygems.org#1052]
#### Current：

<img width="1063" alt="2015-08-27 10 22 34" src="https://cloud.githubusercontent.com/assets/5518/9511284/89fa2774-4ca7-11e5-886f-93cf57452d97.png">

#### Better:

<img width="1008" alt="2015-08-27 10 31 38" src="https://cloud.githubusercontent.com/assets/5518/9511296/b51053f2-4ca7-11e5-8eda-ad03520cd89a.png">

#### Optimal:

<img width="1001" alt="2015-08-27 10 36 22" src="https://cloud.githubusercontent.com/assets/5518/9511305/d33818ce-4ca7-11e5-8642-b6a74cf7352a.png">

## Why?

1. The right-side it always long than left-side, for example: [mongoid](https://rubygems.org/gems/mongoid), [puma](https://rubygems.org/gems/puma), [devise](https://rubygems.org/gems/devise)
2. Why not give more space for Gemfile and Installation?
3. The links: HomePage, Source Code, Documentation it often for help us to found more informations, so put them in the top of the page.

**Comment by indirect** [comment]
It mostly seems like an improvement to me, although I'm not a fan of the huge empty space in the gemfile and install areas.

**Comment by linjunpop** [comment]
:+1:

**Comment by qrush** [comment]
Agreed, I'm missing the paste buttons being more prominent. However, the problem still exists where the copy/paste buttons are down low if the gem has a large description/summary.

A rebound: How about moving it above the Required Ruby Version and License? Keeps it "above the fold" and easily accessible, without any wasted space.

<img width="1024" alt="screen shot 2015-09-01 at 7 26 43 am" src="https://cloud.githubusercontent.com/assets/12610/9602956/dc067974-507a-11e5-8fed-01ed417e032d.png">

**Comment by arthurnn** [comment]
fixed by https://github.com/rubygems/rubygems.org/pull/1073
