### ISSUE TITLE
Bootstrap css warnings on test suite

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#1064]
Bummer. Making an issue so we don't forget to address it.

```
autoprefixer: /Users/qrush/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/doorkeeper-3.0.0/vendor/assets/stylesheets/doorkeeper/bootstrap.min.css:8:95901: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
autoprefixer: /Users/qrush/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/doorkeeper-3.0.0/vendor/assets/stylesheets/doorkeeper/bootstrap.min.css:8:96282: Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".
```

**Comment by jvanbaarsen** [comment]
@qrush I can't seem to be able to reproduce this error when running the tests. So either it has been solved, or I'm doing something wrong. Can you confirm?

**Comment by dwradcliffe** [comment]
I can't reproduce either.

**Comment by dwradcliffe** [comment]
Oh, this is inside the doorkeeper gem in the oath branch. But it's not something we can fix here.

**Comment by farukaydin** [comment]
@jvanbaarsen @dwradcliffe I guess it's related with https://github.com/rubygems/rubygems.org/pull/1062 and noted to remember this warnings.

**Comment by farukaydin** [comment]
@dwradcliffe I didn't see your last message when I was writing. You're faster :smile:

**Comment by dwradcliffe** [comment]
@jvanbaarsen @farukaydin thanks for tracking this down!
