### ISSUE TITLE
site shown in Chinese, difficult to read by Japanese

### ISSUE THREAD

**Issue by mtasaka** [rubygems/rubygems.org#1068]
Accessing https://rubygems.org/ from Japan, site message is shows in Chinese, very difficult to read by Japanese. Also I cannot find where to change language.

**Comment by indirect** [comment]
Hello! Rubygems.org is displayed in Chinese only to browsers that request Chinese before English. For example, if I set Chrome to request Japanese, then English, then Chinese, rubygems.org is sent in English.

Please change your browser settings to request English before Chinese to see the rubygems.org site in English.
