### ISSUE TITLE
Consider switching from Flash to JS for "Copy to clipboard"

### ISSUE THREAD

**Issue by zenorocha** [rubygems/rubygems.org#1072]
I noticed you guys still use Flash for that "Copy to Clipboard" button. What do you think of switching to [clipboard.js](http://zenorocha.github.io/clipboard.js/)? It's IE9+ and gracefully degrades on Safari.

**Comment by arthurnn** [comment]
I am ok with that... if we can remove as much flash as possible and things still work i am +1

**Comment by jvanbaarsen** [comment]
@zenorocha Is this something you're working on? If not I would like to take a stab at this!

**Comment by zenorocha** [comment]
Hey @jvanbaarsen, I'm not working on this. Go ahead lol

**Comment by jvanbaarsen** [comment]
@zenorocha / @arthurnn I have been looking at this to implement it. One thing I run into, is that for safari there is only a selection fallback, see: http://zenorocha.github.io/clipboard.js/ in safari for demo.

Would this be an acceptable fallback?

**Comment by arthurnn** [comment]
oww Safari =( . I would say I prefer living the flash option than.

**Comment by jvanbaarsen** [comment]
I was thinking the same :-) @arthurnn Can you close this issue? Unless @zenorocha has some compelling arguments against this decision :-)

**Comment by arthurnn** [comment]
thanks @jvanbaarsen for investigating this.

**Comment by zenorocha** [comment]
I think it's a pretty damn acceptable trade-off. You would be dropping a Flash dependency (which is a failed plugin that not as many people have it installed anymore) and 30kb less on each request.

@arthurnn if you haven't seen how this looks in practice, here's an example on Chrome, Opera, Firefox, and IE9+

![supported](https://cloud.githubusercontent.com/assets/398893/10467807/a70efece-71b0-11e5-9e32-71b96bc0d380.gif)

And here's how it would look like on Safari

![not supported](https://cloud.githubusercontent.com/assets/398893/10467811/aa78e138-71b0-11e5-946b-7f4e9ba83a5b.gif)

**Comment by jvanbaarsen** [comment]
@arthurnn Can you re-open this? @dgraham explained how Github is doing this: https://gist.github.com/dgraham/cda03d4a4a528d2b4d17. I think its worth taking another look!

**Comment by zenorocha** [comment]
FYI... Bootstrap 4 is now using clipboard.js ;)

**Comment by arthurnn** [comment]
yeah i think i am ok with the trade off. just waiting for someone send a PR :)

**Comment by vincedevendra** [comment]
Didn't mean to double up on this.  Didn't see PR #1072 on this. I'll take a look at it and see if there's any important differences.

**Comment by arthurnn** [comment]
fixed by https://github.com/rubygems/rubygems.org/pull/1182 .

thanks everyone ❤️  great work on this

**Comment by zenorocha** [comment]
Awesome! Is it live already?

**Comment by arthurnn** [comment]
it is now 🎉

**Comment by zenorocha** [comment]
yay!
