### ISSUE TITLE
Add a way to disable translations

### ISSUE THREAD

**Issue by jvanbaarsen** [rubygems/rubygems.org#1075]
It would be great to have an option to disable the local translation. Even though I live in The Netherlands, doesn't automatically mean I want to see the website in Dutch :smile: 

What do you think about this? And if you're interested, I would like to take a stab at this!

**Comment by simi** [comment]
It is already [possible via locale parameter](https://github.com/rubygems/rubygems.org/blob/288d09935cb04cdc9501dcd873d002253c0184fa/app/controllers/application_controller.rb#L17-L18) and it is persisted in session.

You can try:
https://rubygems.org/?locale=en
https://rubygems.org/?locale=nl

I think only the link is missing somewhere on the page.

**Comment by dwradcliffe** [comment]
Yeah it would probably be good to have a language picker somewhere in the
layout.

On Monday, October 5, 2015, Josef Šimánek <notifications@github.com> wrote:

> It is already possible via locale parameter
> <https://github.com/rubygems/rubygems.org/blob/288d09935cb04cdc9501dcd873d002253c0184fa/app/controllers/application_controller.rb#L17-L18>
> and it is persisted in session.
>
> You can try:
> https://rubygems.org/?locale=en
> https://rubygems.org/?locale=nl
>
> I think only the link is missing somewhere on the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/issues/1075#issuecomment-145559560>
> .
>


-- 
---
David Radcliffe

**Comment by arthurnn** [comment]
I would have it at the bottom. maybe a list of links in the footer.

**Comment by jvanbaarsen** [comment]
Ok, will send a PR for that this week :)
