### ISSUE TITLE
You do not have permission to push to this gem

### ISSUE THREAD

**Issue by saigkill** [rubygems/rubygems.org#1076]
I asked erich for picking up his project (https://github.com/erikh/hoe-reek).

So i've updated it, and tried to push it. I'm got:

/home/sascha/.rvm/rubies/ruby-2.2.3/bin/ruby -S gem push pkg/hoe-reek-1.1.0.gem
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.

Exists any way to solve this?

Greetings
Sascha

**Comment by simi** [comment]
Let him add you.

details http://guides.rubygems.org/command-reference/#gem-owner

**Comment by saigkill** [comment]
Oh easier than i thought. I had informed him. Thanks :-)
