### ISSUE TITLE
Consider changing approach to WebFonts

### ISSUE THREAD

**Issue by nateberkopec** [rubygems/rubygems.org#1095]
Currently, I see several problems with the way the main site font, Akzidenz Grotesk, is currently handled on Rubygems.org:

* **Free-as-in-beer or OSS fonts allow more collaboration** Taking a look through #732, you can see that issues with fonts have to go through one person (or a cabal of a few people), the person that has access to the Typekit account. I think anywhere that we can avoid these kinds of situations in an OSS project like Rubygems.org, we should do it. With an OSS font, or a solution like Google Fonts (where anyone can create a new font bundle/there is no 'account'), we can all debug and work on the site's fonts. 
* **Fonts currently represent a whopping 434 out of 600 total KB of page size (that's 72%!)**. It looks like a *huge* amount of weights are downloaded. I'm not sure if other fonts are in the bundle, it's hard to tell because Typekit sort of obfuscates everything (see point above). Again, it's hard for me to open a PR here and say "well XYZ weights aren't required, or we could easily eliminate XYZ weights by doing ABC". In addition, I think this download size is inappropriate for this site - in low-bandwidth/high-latency environments, like mobile networks or developing countries, we're delaying page loads just to serve this one font. [As an example, here's a webpagetest.org screenshot from a browser in Israel](http://i.imgur.com/shPJ78w.png). We're delaying the page render by a full 1.5 seconds just to download this font. 
* **This particular font seems to have Windows and Linux issues** #732 and #785 point this out well enough. 

Now, I think it's awesome that Rubygems.org is probably one of the prettiest open-source community sites there is (I think that's thanks to EngineYard's designers, IIRC?) and it seems like design on a OSS project like this can be a big can of worms. But it seems like the way we're using fonts is imposing a big cost. Akzidenz is not a particularly unique font (I mean it's literally Proto-Helvetica), so I think there's other ways we could be approaching this:

* **Google Fonts.** Open Sans seems appropriate, though there's lots of choices here and I won't pretend I'm a designer and pick one.
* **Something OSS or Free-as-in-Beer** For instance, we could use the default `sans-serif` font for most text, and then for the thin-weighted accent text used throughout the site, add an OSS/free "accent" font such as [Raleway](https://www.theleagueofmoveabletype.com/raleway). This would probably be the most performant, as we could serve it from our own domain/CDN (eliminating some network overhead) and it would probably involve the smallest font download weight in total.

EDIT: The performance impact is even worse on mobile. Using Chrome Timeline and throttling the network to 3G delays page load by more than 5 seconds (!!!), and even 4G clients still see roughly doubled load times.

**Comment by dwradcliffe** [comment]
I've noticed many times when the page gets stuck attempting to download the font. I would like to see a switch to a font that we could serve ourselves.

**Comment by bai** [comment]
Are we really bound to having a custom font? I'm not a designed, but changing a font to Helvetica Neue doesn't seem to make things ugly? And that's win-win: pageloads get 72% faster, fewer dependencies, no weird Flashes of Unstyled Text on slow connections et al.

Not to mention that with growing popularity of content blockers, fonts are getting blocked too (hey, TypeKit tracking pixel!)

Here's how the front page looks with Helvetica Neue:

<img width="1440" alt="screenshot 2015-10-21 08 16 16" src="https://cloud.githubusercontent.com/assets/17348/10628297/6abee426-77cc-11e5-94ff-af7991879fa6.png">

N.B. The only change I made was adding `font-weight: 100` to "Find, install, and publish RubyGems." headline.

**Comment by JuanitoFatas** [comment]
> I think it's awesome that Rubygems.org is probably one of the prettiest open-source community sites there is (I think that's thanks to EngineYard's designers, IIRC?) and it seems like design on a OSS project like this can be a big can of worms.

DockYard. Designed by @acacheung :clap: :blush:

**Comment by nateberkopec** [comment]
@bai That works for anyone who has Helvetica Neue installed - so basically anyone on a Mac. Windows is stuck with Arial, and who knows what you'll get on a Linux box. Arial doesn't have a 100-weight version (or 200-weight for that matter), and IMO the light-weight accents are one of the most important parts of the whole design. If I had to guess, Akzidenz was chosen as a sort of "cross-platform Helvetica" for this reason.

I don't think "no web fonts at all" is an option for this reason. The light weight accents are a huge part of the design, and there's just no good way to ensure that cross platform w/o Webfonts.

**Comment by nateberkopec** [comment]
Closed by #1109
