### ISSUE TITLE
Gems in S3 buckets are served without Cache-Control headers

### ISSUE THREAD

**Issue by j-manu** [rubygems/rubygems.org#1100]
I have been facing some performance problems with fastly and while debugging it, I found that gems in the S3 bucket (which is the origin for fastly) are served without Cache-Control headers

Try `curl -I http://production.s3.rubygems.org/gems/devise_token_auth-0.1.32.gem`

Adding Cache-Control headers should improve caching at Fastly PoPs. There is dramatic difference between a request for gem in fastly cache and a gem which has to be fetched from origin.

https://gist.github.com/j-manu/8eebd9157b307e65c48e

Apologies, if this is not the right forum to raise this issue.

**Comment by indirect** [comment]
Nice catch, thanks!

**Comment by arthurnn** [comment]
@dwradcliffe can you change this config?
thanks @j-manu

**Comment by dwradcliffe** [comment]
Yeah I've been working on it. It's not as simple as it sounds. Hopefully next week.

**Comment by arthurnn** [comment]
thanks @dwradcliffe . ❤️  ❤️  ❤️

**Comment by sonalkr132** [comment]
What needs to be done here? It seems like one needs to add `x-amz-meta-Cache-Control : max-age= <value in seconds>` to the PUT request of the object. Where is the setting for that PUT request?
