### ISSUE TITLE
Running the server in production mode locally results in a hang

### ISSUE THREAD

**Issue by nateberkopec** [rubygems/rubygems.org#1107]
Running `SECRET_KEY_BASE=sasds RAILS_ENV=production rails s` locally with a database set up (and Redis running) results in a hang when rendering the homepage:

```
I, [2015-11-11T16:53:15.458007 #8357]  INFO -- : Started GET "/" for ::1 at 2015-11-11 16:53:15 -0500
^C
```

...which never finishes.

**Comment by dwradcliffe** [comment]
SSL is forced in production, so that one log line is probably the redirect and then your browser errors out trying to connect to https://localhost:3000.

**Comment by nateberkopec** [comment]
Ah, it was a redirect, but not an SSL-related one. The `Redirector` Middleware tries to redirect you to `http://rubygems.org:3000`.

I can't figure out how `Gemcutter::HOST` gets set. How do I change that?

**Comment by dwradcliffe** [comment]
https://github.com/rubygems/rubygems.org/blob/bab1e6f90ea1f22eece21a57d97d3abcd191eba5/config/rubygems.yml#L18

Why are you trying to run in production mode locally?

**Comment by nateberkopec** [comment]
*Aha!*. I'm writing a PR for #1095, and trying to get some numbers on how much swapping fonts reduces total page weight and load time. Running in production mode gives the best analogue (asset compilation being the obvious one) to actual perf on the live site.
