### ISSUE TITLE
Runtime dependency count

### ISSUE THREAD

**Issue by olivierlacan** [rubygems/rubygems.org#1115]
I was trying to compare two gems recently and expected a runtime dependency count on the gem page but couldn't find one.

I can manually count the dependencies of course but I feel like offering this data (per `Version` of course) could be valuable to API users and end-users of rubygems.org alike.

I can get working on this feature if this sounds reasonable.

**Comment by dwradcliffe** [comment]
:+1:

**Comment by sonalkr132** [comment]
Hi @olivierlacan 

Feature you requested creates n+1 on `versions#show` and ends up adding 4 times more cost. It is one of the heavily used endpoints.
[We added dependencies count to gem show page](https://github.com/rubygems/rubygems.org/pull/1474).
If you can come up with a solution which won't add significant cost, we may consider it. I am closing this.

See Also https://github.com/rubygems/rubygems.org/pull/1485

**Comment by olivierlacan** [comment]
Will think about it. Thanks @sonalkr132.
