### ISSUE TITLE
Set up Locale for RubyGems.org

### ISSUE THREAD

**Issue by olivierlacan** [rubygems/rubygems.org#1123]
[Locale](https://www.localeapp.com) is a neat way to keep track of translations and localizations: https://www.localeapp.com/projects/370

These are the set up instructions for public projects: https://github.com/Locale/localeapp/wiki/Create-Public-Projects

![image](https://cloud.githubusercontent.com/assets/65950/11431171/cf77de5c-9457-11e5-92af-93dfdcc0d4d0.png)

I don't know if there's a newer service that does this better but it seems like we should use one to get a sense for how thorough each of our languages translation sets are. I've been working on a PR that adds a ton of new translation variables and this seems like an obvious next step.

/cc @arthurnn @abelards @nateberkopec

**Comment by dwradcliffe** [comment]
I was just wondering if there was a good way to keep track of all these locales. I looked at localleapp just a little bit... looks interesting! I think I would want to only pull in the updates manually so that production has no knowledge of this. That would require also manually pushing translations when we add things, but I think that's ok.

**Comment by dwradcliffe** [comment]
FYI current status:
![rubygems org locale 2015-11-26 23-57-18](https://cloud.githubusercontent.com/assets/118850/11434380/742ebf9c-9499-11e5-994e-c3a6f46abf92.png)

**Comment by olivierlacan** [comment]
Nice!

**Comment by nateberkopec** [comment]
:+1: Was definitely feeling the need for something like this.

**Comment by olivierlacan** [comment]
This is now public here so I'm closing: https://www.localeapp.com/projects/8883

**Comment by olivierlacan** [comment]
@dwradcliffe Is there something needed to push new translations? A key of some sort?

**Comment by dwradcliffe** [comment]
Locale App is a good idea but the implementation doesn't work well for our project. There are a few issues that make it hard to use for this so I'm not going to invest any more time to making it work right now.
