### ISSUE TITLE
dependency name constraints

### ISSUE THREAD

**Issue by farukaydin** [rubygems/rubygems.org#1136]
Detail information about why we need it can be found here: https://github.com/rubygems/rubygems.org/pull/1046

I start to work on it. Firstly, I divide the processes as fix 49 edgecases, add necessary custom constraints to db and/or activerecord, and write necessary tests to make sure it's working correctly.

However, I encountered there is a resolving/unresolving dependency process inside of codebase, and I try to understand why it was needed before. If the main reason is we have dependencies that is not tracked by rubygems, the solution is getting complex because we marked dependencies as unresolved first in dependency model and update as resolved inside of rubygem model. So, we may have to check in both sides to control whether dependency has a name or not.

Before I start to coding, I just want to make sure what is the main reason of unresolved dependency names. Besides that other recommendations about my solution are very welcome.

cc: @arthurnn

**Comment by jvanbaarsen** [comment]
@farukaydin Is this still relevant?

**Comment by sonalkr132** [comment]
> from dougc84/carrierwave_securefile#5, crypt19 was deleted and then added again as crypt19-rb, I suspect it should either show the name, perhaps unlinked or striked or remove the line

AFAIU, only issue we had was unresolved rubygem didn't show up in UI. 

> we marked dependencies as unresolved first in dependency model and update as resolved inside of rubygem model. So, we may have to check in both sides to control whether dependency has a name or not.

we only need to update dependencies to where `unresolved_name` is rubygem name and we have always done it. crypt19 wasn't marked resolvable when crypt19-rb was pushed because they have different name.
