### ISSUE TITLE
The latest version of the "down" gem cannot be downloaded

### ISSUE THREAD

**Issue by janko-m** [rubygems/rubygems.org#1152]
I wrote a gem called "[down](https://rubygems.org/gems/down)" some time ago, and releases were working good. However, today when I've pushed the latest version 1.0.5 (it was 20 minutes ago) I cannot download it, even though RubyGems.org confirms the latest is 1.0.5:

```sh
$ gem install down -v 1.0.5
ERROR:  Could not find a valid gem 'down' (= 1.0.5) in any repository
ERROR:  Possible alternatives: down
```

**Comment by janko-m** [comment]
After 1 hour it started working, it can be downloaded now. I will leave this open in case this delay can be debugged.

**Comment by qrush** [comment]
Maybe was a delay with delayed job processing? Weird. Closing this for now.
