### ISSUE TITLE
Reserve ruby core lib gem namespaces

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#1155]
From http://help.rubygems.org/discussions/suggestions/7892-reporting-abuse-on-openssl

I think we should have a "reserved" namespace, and disallow gems to be pushed matching that name. All gems from the stdlib are good candidates for this.

**Comment by indirect** [comment]
This seems good--can we just push empty gems with those names for now to reserve them?

**Comment by dwradcliffe** [comment]
Should be pretty easy to add a validator for this. Can we compile a list of names here?

**Comment by sferik** [comment]
> Can we compile a list of names here?

The dependencies of https://rubygems.org/gems/rubysl (minus the `rubysl-` prefix) is a good start.

**Comment by arthurnn** [comment]
thanks all
