### ISSUE TITLE
Add dependency information to /versions API result

### ISSUE THREAD

**Issue by balasankarc** [rubygems/rubygems.org#1157]
Hi,
I am a member of the Debian Ruby packaging team and am currently using rubygems API for my project [gemdeps](http://github.com/balasankarc/python-gemdeps). It is a project to collect the dependency chain of a RoR app (like diaspora or gitlab, which we are currently packaging). 

Right now, I am using rubygems API to get dependency of the **latest** version of each gem. But, the ideal case is to find out the dependencies of the **exact version** of each gem specified in Gemfile. Can you add dependency information also to /version API result, so that it is more complete?

Thanks.

**Comment by sonalkr132** [comment]
You can use https://rubygems.org/api/v1/dependencies.json?gems=rails
You would just need to parse it to find what you are looking for.

**Comment by balasankarc** [comment]
Oops. Didn't know this is still open. The bug #950 talks about this. Let the discussion happen there.
