### ISSUE TITLE
specs 0.21 gem present from website and some API endpoints but not all API endpoints

### ISSUE THREAD

**Issue by mcandre** [rubygems/rubygems.org#1158]
# Summary

I published a new version of my `specs` gem today. I can see the gem available on the RubyGems website, and in the list of available remote gems. But when I try to install it, I either get the old one (v 0.20), or an error about v 0.21 not being found.

https://rubygems.org/gems/specs

# Trace

```
gem list -r specs

*** REMOTE GEMS ***

betterspecs (0.0.1)
ctrlspecs (0.0.1)
has_specs (0.0.4)
mithril-specs (0.2.0)
motion-screenspecs (0.1.0)
parallelized_specs (0.4.84)
set_specs (0.1.6)
smart_specs (1.0.3)
specs (0.21)
specs_watcher (0.0.2)
specserv (0.0.5)
specstar-controllers (0.2.0)
specstar-models (0.2.9)
specstar-remarkable (0.0.0)
specstar-support-random (0.1.2)
specstat-rspec (0.1.0)
timed_specs (0.0.2)
xpath-specs (0.1.0)

$ gem install -r specs -v 0.21
ERROR:  Could not find a valid gem 'specs' (= 0.21) in any repository
ERROR:  Possible alternatives: specs
```

# System

```
$ ruby -v && gem -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
2.5.1

$ chruby --version && rvm -v
chruby: 0.3.9
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.11.2 (15C50)
```

# Mitigation

`gem` can find v 0.21 if I use my Mac's system Ruby. Unfortunately, my work requires using rvm/chruby to manage multiple, non-system Rubies.

**Comment by shevegen** [comment]
Someone else on IRC also reported the same issue with another game:

<greenhat> was seeing the same issue with rgeo-geojson - cannot install the latest but it is listed on the website

I am not sure if this can easily be resolved, but perhaps if it can not easily be resolved (assuming here), could an icon or something be used to indicate that syncing has not happened yet? Something small like a coloured dot or anything.

**Comment by teeparham** [comment]
I'm also using chruby.

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]

$ gem -v
2.5.1

$ which ruby
/Users/tee/.rubies/ruby-2.3.0/bin/ruby

$ which gem
/Users/tee/.rubies/ruby-2.3.0/bin/gem
```

I tried with ruby 2.2.3 also, so it's not related to ruby 2.3.

Here's a verbose log:

```
$ gem in rgeo-geojson -v0.4.0 -r -V
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rgeo-geojson
200 OK
ERROR:  Could not find a valid gem 'rgeo-geojson' (= 0.4.0) in any repository
GET https://api.rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
304 Not Modified
ERROR:  Possible alternatives: rgeo-geojson
```

The gem release appeared to work:
https://rubygems.org/gems/rgeo-geojson/versions/0.4.0

**Comment by mcandre** [comment]
Update: `gem install specs [-v 0.21]` now works as expected. Looks like the endpoint just took a few hours to fully sync.

**Comment by teeparham** [comment]
Update: working normally for me now too. Thanks, internet!

**Comment by dwradcliffe** [comment]
There was a problem with the dependency API earlier today which caused a delay in indexing. There were about 75 gems pushed but not indexed for a couple hours.

You can always check our status page at https://status.rubygems.org or our twitter account https://twitter.com/rubygems_status for latest information.
