### ISSUE TITLE
A class is missing in the documentation

### ISSUE THREAD

**Issue by Thomas008** [rubygems/rubygems.org#1159]
We pushed a gem to rubygems.org, and the documentation does not show a class.
(The gem is called "robust_excel_ole", and the missing class is "Book".)
We have checked this with yard 0.8.7.6. There the documentation book.html is being produced.
What can we change to get the class displayed.
Thank you,
Thomas

**Comment by dwradcliffe** [comment]
The documentation is not part of RubyGems.org. You will need to ask http://www.rubydoc.info/ for help with documentation render issues.
