### ISSUE TITLE
Versions API is missing some versions

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#1164]
Bundler API needs these versions, but can't find them in the versions API JSON:

```
gem="quick_target-0.0.1" message="Could not download https://rubygems.org/api/v1/versions/quick_target.json" 
gem="quick_target-0.0.0" message="Could not download https://rubygems.org/api/v1/versions/quick_target.json" 
gem="gitlapse-0.0.0.pre" message="Could not download https://rubygems.org/api/v1/versions/gitlapse.json"
```

**Comment by dwradcliffe** [comment]
@segiddins and I dug into the code a bit and it looks like we're filtering out versions that have a future `built_at` date. https://github.com/rubygems/rubygems.org/blob/47193268cf77aed48443c0c5a82a26855af1ce92/app/models/version.rb#L143

This code goes way back to @qrush in https://github.com/rubygems/rubygems.org/issues/17

**Comment by indirect** [comment]
is this deployed? I'm still seeing this error as of 30 minutes ago

**Comment by dwradcliffe** [comment]
Deployed last night, about an hour after you saw the errors. Should be fixed now.
