### ISSUE TITLE
Redis version_history data truncated

### ISSUE THREAD

**Issue by DamirSvrtan** [rubygems/rubygems.org#1169]
It seems all data in Redis for `rubygems:downloads:version_history` that happened before 2014-07-14 has been wipedout.

Am I seeing everything clear or am I missing something?

And if that's true, is there any other way of retreiving downloads stats besides those two ways?

I see there's a version_history model but it's data also seems incomplete - there's no version_history data for Rails nor Rake versions.

Thnx upfront.

**Comment by dwradcliffe** [comment]
At this point we are only storing download totals and not per-day stats. Any per-day stats found in redis will go away at some point in the future. Sorry!
