### ISSUE TITLE
Same version date

### ISSUE THREAD

**Issue by arthurnn** [rubygems/rubygems.org#1171]
I just noticed, that for some reason, all the versions of this gem are marking the same date:
https://rubygems.org/gems/apn_sender

Not sure why this is happenin

**Comment by dwradcliffe** [comment]
The date is set by the person who built the gem, and we allow any date to show on RubyGems.org. It's certainly not helpful to always use the same date, but (at the movement) it's allowed.

**Comment by arthurnn** [comment]
Correct, I just removed the date from the gemspec https://github.com/arthurnn/apn_sender/commit/af603c069019dd3930f1cfedf101747923752b98 and it worked. I wonder if we should keep allowing this behaviour or change it?
Maybe we should not do anything about it, but it does seems strange

**Comment by dwradcliffe** [comment]
Maybe we should also display the uploaded date if it's not within a day of the build date?

**Comment by jvanbaarsen** [comment]
@dwradcliffe Is this still an issue? If so, you proposed adding the Uploaded Date if the build date is the same. Is that something you're still interested in?

**Comment by sonalkr132** [comment]
Closed by #1504
