### ISSUE TITLE
add missing apple-touch-icon.png

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1175]
We're missing the `apple-touch-icon.png` file and a few other variations. We get a lot of requests which result in 404s so we should provide these icons.

**Comment by EtienneDepaulis** [comment]
http://iconifier.net/ is pretty useful to create all the variations in one clic :)

**Comment by davidcelis** [comment]
It might be worth mentioning that it's unlikely for these 404 requests to actually be from someone adding rubygems.org to their home screen. Safari, even on the desktop, will always try requesting apple-touch-icon.png for some reason. I wrote [a small library like quiet_assets](https://github.com/davidcelis/quiet_safari) to remove these 404s from logging as most of them just don't make sense.

Of course, if it's considered low effort to add a set of touch icons, Apple's default is a weird screenshot of the website when there is no touch icon. So it does look weird if anybody is adding it to their home screen. I just doubt that anybody really is 😉

**Comment by arthurnn** [comment]
We use quiet_assets https://github.com/rubygems/rubygems.org/blob/master/Gemfile#L56 on development already. Maybe we want to promote that dependency?

**Comment by bradly** [comment]
@dwradcliffe @arthurnn This was resolved by #1215 and can be closed. Thanks!
