### ISSUE TITLE
Refused to execute script from 'https://rubygems.org/api/v1/owners/{user}/gems.json' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by sibinx7** [rubygems/rubygems.org#1183]
I have this issue while i send ajax request to fetch some repo details, When i use GET, i got some 
`“No 'Access-Control-Allow-Origin' header is present on the requested resource”` error method,

```
$resource('https://rubygems.org/api/v1/owners/:user/gems.json',{user:user},{
        "getGems":{
          method: "JSONP",
          isArray: true,
          responseType: "json" 
        }
      }).getGems(function(success){
        console.log(success)
      })
```

**Comment by simi** [comment]
probably related to https://github.com/rubygems/rubygems-infrastructure/pull/31

**Comment by sibinx7** [comment]
@simi  Is there any solution from client side to solve this issue ? or is it a server side issues?

**Comment by simi** [comment]
Meanwhile you can use some CORS proxy. You can try to build some own or use some public available service like https://crossorigin.me/.

**Comment by sibinx7** [comment]
Thanks @simi
