### ISSUE TITLE
Reserved gem name issues

### ISSUE THREAD

**Issue by ajb** [rubygems/rubygems.org#1190]
(Moved from https://github.com/rubygems/rubygems/issues/1474)

Hi there,

I'm trying to publish a new version of Sync: https://github.com/chrismccord/sync/releases/tag/v0.4.0

However, despite being an owner, I'm getting this error:

> There was a problem saving your gem: Name 'sync' is a reserved gem name.

<img width="671" alt="screen shot 2016-02-06 at 8 59 39 am" src="https://cloud.githubusercontent.com/assets/1270317/12867014/fbffadfc-ccaf-11e5-999d-8464938d331f.png">

Any advice? Thanks!

**Comment by ajb** [comment]
From https://github.com/rubygems/rubygems.org/pull/1156#issuecomment-180770630:

> Looks like this is the cause of https://github.com/rubygems/rubygems/issues/1474.

> I understand the impetus behind this PR, but as a gem maintainer, it would have been nice to have a heads-up. [We're aware](https://github.com/chrismccord/sync/pull/162#issuecomment-68098811) that `Sync` is already a module in the stdlib, but nobody has been able to dedicate the effort to renaming the gem.

> > we can remove the existing gems in a second PR.

> This obviously hasn't happened yet... but are there any details on what this will look like? Will folks' deployments start breaking suddenly?

**Comment by arthurnn** [comment]
@ajb As you can see, I removed `sync` from the list of private names. I added a warning to add it back on May 1st, 2016. So that gives you almost 3 months to rename the gem.
Thanks for reporting the issue.

If I find some spare cycles I can help out on renaming it. What is the desired name from your part?

cheers.

**Comment by ajb** [comment]
@arthurnn thank you! I'll make sure this gets discussed over in chrismccord/sync#215.
