### ISSUE TITLE
Gemfile line suggested for pre-release versions is invalid

### ISSUE THREAD

**Issue by connorshea** [rubygems/rubygems.org#1191]
The RubyGems page for [Devise 4.0.0.rc1](https://rubygems.org/gems/devise/versions/4.0.0.rc1) suggests adding `gem 'devise', '~> 4.0', '>= 4.0.0.rc1'` to the Gemfile in order to install that specific version of the gem. Bundler gives me the following:

```
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'devise (>= 4.0.0.rc1, ~> 4.0)' in any of the gem sources listed in your Gemfile
or available on this machine.
```

This might technically be a Bundler issue, but for the time being RubyGems probably shouldn't suggest that, would confuse other users. `gem 'devise', '>= 4.0.0.rc1'` *does* work, however. I'd suggest using that for now.

A friend had this issue and asked me for help, so it's definitely not a problem on my end. You can recreate this relatively easily with a Gemfile that's just:

```ruby
source 'https://rubygems.org'

gem 'devise', '~> 4.0', '>= 4.0.0.rc1'
```

**Comment by dwradcliffe** [comment]
Cc: @indirect

**Comment by indirect** [comment]
pretty sure this is how prereleases have always worked, since 4.0.0.pre is (I think) lower than `~> 4.0`. This looks like it's a bug in the suggested Gemfile line.

**Comment by nettofarah** [comment]
Just created a PR to try to address this: https://github.com/rubygems/rubygems.org/pull/1251
