### ISSUE TITLE
Smoother handling of yanked gems

### ISSUE THREAD

**Issue by johnnyshields** [rubygems/rubygems.org#1192]
Firstly apologies if this is not the right repo to raise this issue.

I recently encountered this error due to a yanked gem.

```
Gem::RemoteFetcher::FetchError: bad response Forbidden 403 (http://rubygems.global.ssl.fastly.net/gems/rb-inotify-0.9.6.gem)
An error occurred while installing rb-inotify (0.9.6), and Bundler cannot
continue.
Make sure that `gem install rb-inotify -v '0.9.6'` succeeds before bundling.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

It would be nice if there could be a message indicating that the gem was yanked. One option would be make the file on the CDN a dummy text file with the word "yanked" or something. The error message to me above indicates that there might be an infra problem with Rubygems itself, and forces me to dig around for the exact problem.

**Comment by johnnyshields** [comment]
Hmmm maybe this was a one-off issue with a bad upload of the specific lib: https://github.com/nex3/rb-inotify/issues/52. Please close this issue if there's nothing to be improved on Rubygems.org side...

**Comment by dwradcliffe** [comment]
Thanks for mentioning this. We had a storage configuration problem that caused missing files to return as 403s. This should have returned a 404, and will now.

I'm not sure exactly what happened with 0.9.6 originally but it's yanked now and will return a 404. Depending on your Gemfile, bundler shouldn't suggest that a yanked version is available in the first place.

**Comment by johnnyshields** [comment]
OK got it thanks!
