### ISSUE TITLE
Remove redis

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1208]
We would like to remove redis from the RubyGems.org infrastructure. It has been painful to run and it's a dependency that we don't need. We want to store the gem download stats in postgres, which will be much easier and faster. This is related to rubygems/rubygems-infrastructure#35 but this is a separate task.

Here's what I think we need to do:

- [x] add any database columns necessary to store number of downloads per gem and per version (not sure if they are there yet or not)
- [x] add methods/rake tasks that will sync the gem and version download counts from redis to postgres (this should be able to run many times, to sync things as we work on this)
- [x] update app views to pull stats from the model instead of redis
- [x] update `FastlyLogProcessor` to push to postgres instead of redis
- [x] should be able to remove all redis?

@arthurnn @evanphx @skottler @indirect @ktheory

**Comment by simi** [comment]
> it has been painful to run

Is there more info available related to this part?

**Comment by dwradcliffe** [comment]
Our data set was* about 26G which requires a lot of memory to run, and redis doubles memory usage while it saves. It takes about 10-15 minutes to load the data so restarts are really painful. Sometimes when it does start it just OOMs right away and kills the box. We had an hour outage a few weeks back because redis would not boot up properly. Also we don't want the website to be dependent on 2 data stores. Removing redis will improve resiliency and page speed because we're already loading the records from postgres that we need.
_* we removed some old per-day data to get redis to start after that outage_

**Comment by arthurnn** [comment]
I started working on this , for the stats pipeline.. I will post more info, why I think we can remove redis from there, in my PR.

**Comment by nateberkopec** [comment]
>  add any database columns necessary to store number of downloads per gem and per version (not sure if they are there yet or not)

May be worth doing this in a separate table to minimize locking.

**Comment by technoweenie** [comment]
You can use the slotted counter pattern to reduce the locking even further. Works well for us.

http://samlambert.com/posts/mysql-slotted-counter

**Comment by skottler** [comment]
First off, let me just say this: **yes**. Getting rid of Redis is something I've wanted to do for a long time; it's been a significant burden on the infrastructure and it's finally time for it to go.

Is it necessarily required to do this via Postgres? I'd love to see us map out some of the data storage requirements so we can figure out if there might be a better fit.

**Comment by dwradcliffe** [comment]
@skottler here's our previous discussion about that https://github.com/rubygems/rubygems-infrastructure/issues/35
