### ISSUE TITLE
Add a "recent uploads", last 10 programs

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1217]
Hello.

I was looking at CPAN lately:

http://www.cpan.org/

You can see in the middle part a "Recent Uploads" section.

I tried to find the same on https://rubygems.org/ or https://rubygems.org/stats but I could not find such an entry.

Now, rubygems already has this available on twitter, interestingly enough:

https://twitter.com/rubygems

This is ok; you can see the last entries there too. But I'd like a simpler view for the last top ten together with links, similar to cpan. It takes a bit longer to scroll through the twitter links and I don't really need the display of when the message was generated there (not that I mind that it exists, I am neutral on that part).

Perhaps this 10 "recent uploads" should not be on the rubygems.org mainpage, but in a separate section; either a new entry, or perhaps as part of the https://rubygems.org/stats overview.

Would this be a useful addition?

**Comment by dwradcliffe** [comment]
Sure, sounds useful to me. And I agree, not on the home page.

**Comment by BobWhitelock** [comment]
Hi, this looks like a useful feature, I've started looking into this and should hopefully have a PR ready at some point soon.

**Comment by dwradcliffe** [comment]
@BobWhitelock awesome! :smile:

**Comment by tadityar** [comment]
Hello! I realize the PR hasn't been updated in sometime. I'm interested to work on this, maybe I'll create another PR.

**Comment by sonalkr132** [comment]
In #1618, we created [new page](https://rubygems.org/news) which shows uploads from last one week.
