### ISSUE TITLE
Availablity of locale "de"

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [rubygems/rubygems.org#1223]
When will be the **German**-translated RubyGems website for everybody available: https://rubygems.org/?locale=de-DE?

**Comment by nateberkopec** [comment]
As soon as you submit a pull request! ;)

There is no designated or special "team" working on translations, we just accept them as they come in.

**Comment by SuriyaaKudoIsc** [comment]
@nateberkopec I already submited a PR (#1140). :smile: 

> See the file here: https://github.com/rubygems/rubygems.org/blob/master/config/locales/de.yml!

**Comment by dwradcliffe** [comment]
Ah, we just needed to add it to the list of available locales. I've added it here: https://github.com/rubygems/rubygems.org/commit/e1456a67c9b10634ad1d5e6e4e98653d276a63f9

**Comment by SuriyaaKudoIsc** [comment]
@dwradcliffe :+1: Thanks.

**Comment by SuriyaaKudoIsc** [comment]
When will this updated with the website?

**Comment by dwradcliffe** [comment]
Should be deployed in the next hour or so.

**Comment by SuriyaaKudoIsc** [comment]
:+1: Thanks for the information! :smile:
