### ISSUE TITLE
unannounced endpoint removal

### ISSUE THREAD

**Issue by AaronLasseigne** [rubygems/rubygems.org#1237]
It looks like the "/api/v1/versions/[gem_name]-[gem_version]/downloads/search.json" endpoint was intentionally removed.

I cannot find a location that indicated that this was going to happen. If it was announced somewhere and I'm missing it then I apologize. Otherwise, please consider giving at least a few weeks notice when removing endpoints.

**Comment by dwradcliffe** [comment]
You're right we did not do a great job of communicating this. I'm sorry about that. :disappointed: 

We've been discussing the changes in various PRs over the past year. The endpoints were not documented and the search endpoint was not actually working quite a bit of the time the past few months.

I'm curious what you were using those endpoints for, and if maybe there's another way to get what you're looking for?

**Comment by dwradcliffe** [comment]
You can try downloading the full redis data dumps from https://rubygems.org/pages/data although the redis data for daily downloads is not complete.
