### ISSUE TITLE
Add autocompletion on gem search inputs

### ISSUE THREAD

**Issue by nicolasleger** [rubygems/rubygems.org#1246]
It could be cool to have autocompletion on gem search input like on [npmjs.com](https://www.npmjs.com/) or [ruby-toolbox.com](https://www.ruby-toolbox.com/) :smirk:.

To be defined:
- Whether we do it on our own or use a Search Provider?
- If so which Search Provider ([algolia.com](https://www.algolia.com/) or [constructor.io](https://constructor.io/) other)? and how we transfer the data?
- Which criteria to use to select and order results (name, downloads count)?

**Comment by dwradcliffe** [comment]
We have a new search system in the works! Autocomplete is on the list to
do. :)

We are using elasticsearch. We have a beta version working but we haven't
had a chance to polish it up for real use yet.

On Friday, April 8, 2016, Nicolas Leger <notifications@github.com> wrote:

> It could be cool to have autocompletion on gem search input like on
> npmjs.com <https://www.npmjs.com/> or ruby-toolbox.com
> <https://www.ruby-toolbox.com/> [image: :smirk:].
>
> To be defined:
>
>    - Whether we do it on our own or use a Search Provider?
>    - If so which Search Provider (algolia.com <https://www.algolia.com/>
>    or constructor.io other)? and how we transfer the data?
>    - Which criteria to use to select and order results (name, downloads
>    count)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/issues/1246>
>


-- 
---
David Radcliffe

**Comment by shevegen** [comment]
Since I love auto-completion in most cases (on the terminal at the least; not sure I care for the google type of autocompletion as much), I am in support of this.

**Comment by clamoris** [comment]
@dwradcliffe Are you still working on it? It looks like a very useful thing and I would like to help if it possible.

**Comment by sonalkr132** [comment]
@clamoris It is on my to-do list and happens to be very next one :smile: However, feel free to take it up. We are also working on introducing `facets` and other advanced search features. I can work on them.

We are going to use elasticsearch. So, take a look into this 03-expert.rb template: https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-rails#rails-application-templates
It has autocomplete feature implemented.

**Comment by clamoris** [comment]
@sonalkr132 I'll take it then.

**Comment by clamoris** [comment]
@sonalkr132 Actually 03-expert.rb do not implement autocompletion but only suggestions. PR is open, btw.

**Comment by yazfield** [comment]
I see the PR for this was closed long time a go, I could work on it if you're interested

**Comment by sonalkr132** [comment]
Hi, we tried to get this done in GSoC 2019 https://github.com/rubygems/rubygems.org/pull/2047.  It is in workable state but `js` part needs cleanup/improvement. cleanup is on my todo list, it would super helpful if you can take it up.
If you prefer, you can also start from scratch. Just don't add additional library for this (use JS/JQuery only).

**Comment by erlend-sh** [comment]
We made a working demo of this with the open source [MeiliSearch](https://github.com/meilisearch/MeiliSearch):

https://rubygems.meilisearch.com/
https://github.com/meilisearch/meilisearch-ruby

This could also be extended to support more advanced features like the `facets` mentioned earlier in this issue. If the rubygems devs are interested in using MeiliSearch we'd be happy to discuss it here or by email: erlend@meilisearch.com

**Comment by sonalkr132** [comment]
closed by https://github.com/rubygems/rubygems.org/pull/2047. Please let us know if you have any feedback.
