### ISSUE TITLE
ruby-prof is stuck at "0.8.1" in search results; 0.15.9 in its dedicated page

### ISSUE THREAD

**Issue by gioele** [rubygems/rubygems.org#1249]
The search results for the query `ruby-prof` (<https://rubygems.org/search?utf8=%E2%9C%93&query=ruby-prof>) incorrectly say that the current version of that gem is `0.8.1`, see the screenshot at the end of this issue.

The current version of the `ruby-prof` gem is `0.15.9` and this is what is correctly shown in its dedicated page (<https://rubygems.org/gems/ruby-prof>).

Stale version info cached somewhere?

![ruby-prof-0 8 1](https://cloud.githubusercontent.com/assets/237141/14402933/83c5a45c-fe43-11e5-8316-4c5da036314f.jpg)

**Comment by arthurnn** [comment]
It is probably search related indeed. if you just scroll on the /gems pages, you see the latest version, see https://rubygems.org/gems?letter=R&page=362 . 
I will see what is going on.

**Comment by dwradcliffe** [comment]
I'm guessing this is related to the change we made to latest version logic.

On Saturday, April 9, 2016, Arthur Nogueira Neves <notifications@github.com>
wrote:

> It is probably search related indeed. if you just scroll on the /gems
> pages, you see the latest version, see
> https://rubygems.org/gems?letter=R&page=362 .
> I will see what is going on.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/issues/1249#issuecomment-207784070>
>


-- 
---
David Radcliffe

**Comment by arthurnn** [comment]
still not fixed

**Comment by chrismo** [comment]
fyi, seeing the same right now for `json` gem. showing 1.1.1 on search result.
