### ISSUE TITLE
Search API endpoint performance problems

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1256]
The search api endpoint has some performance problems related to the recent gem download changes. Eventually we will be changing that to use Elasticsearch but until then we should try to fix the queries.

@arthurnn

**Comment by simi** [comment]
Are there any metrics or details?

**Comment by dwradcliffe** [comment]
![transactions - rubygems org production - new relic 2016-04-27 16-58-05](https://cloud.githubusercontent.com/assets/118850/14867979/4abc8e0a-0c99-11e6-93c0-7d761c6542f2.png)

**Comment by sonalkr132** [comment]
Not relevant anymore. we moved to ES.
