### ISSUE TITLE
Non-existing gems - link - suggestion to make them more easy to spot

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1258]
Hello. I try to keep it short. Consider this gem:

https://rubygems.org/gems/bioroebe/versions/0.0.250

On the bottom, you see a link to a gem called:

"chemical_paradise >= 0"

This was a typo; I meant chemistry_paradise

There is no gem called chemical_paradise so I assume that people could not actually use that gem. (This will soon be corrected in my gem anyway, I just wanted to report the part about non-existing gems here.)

I actually only noticed this as of today. I could have noticed it earlier, e. g. via some script that checks for existing gems and such. I discovered this because chemical_paradise appears on the bottom, and the other entries are sorted alphabetically so I assume the code already does some checking here.

My proposal is simple:

- If a gem does not exist, assume that the gen author may have made an error. This may not always be true, sometimes a gem author may link in to non-existing gems at the time of publishing, and lateron publish that other gem too. BUT I think I have a suggestion that will be both EASY to implement and will also cover those cases where a gem will be provided lateron anyway.

I suggest that perhaps a slightly red colour is used; or perhaps it should appear in italic instead. (And if someone hovers over this, perhaps add a "This gem currently is not registered on rubygems.org" This should cover both cases I think, both gem author mistake, and gem author wanting to publish said gem lateron).

**Comment by dwradcliffe** [comment]
I think this makes sense. The page already knows this so it is just a view/design change.
