### ISSUE TITLE
[RFE] Allow to specify range for /api/v1/activity/just_updated

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems.org#1266]
Currently, the /api/v1/activity/just_updated api returns 50 items. Unfortunately, if I were checking this API every hour, there is not possible to know, if I missed some updates or not.

Would it be possible to extend this API to let me specify something like "give all udpates since gem foo 1.2.3 was released" or alternatively "give me all updates since this timestamp".

I am asking for this feature, since Anitya (aka. https://release-monitoring.org/) is going to use this API and in turn several Linux distributions to monitor RubyGems updates.

**Comment by qrush** [comment]
Have you tried using a gem webhook instead? This API seems better for just infrequent checking/updates.

**Comment by voxik** [comment]
RubyGems is the only platform which supports webhooks, so there is no infrastructure for such feature on Anitya side.

**Comment by qrush** [comment]
@voxik sounds like a perfect opportunity to support it then! especially since it's going to give you the real-time data you need. Please take a look into it, it's just one HTTP endpoint to consume.

http://guides.rubygems.org/rubygems-org-api/#webhook-methods

**Comment by jvanbaarsen** [comment]
@voxik Is this still relevant?

**Comment by voxik** [comment]
Yes, it is

**Comment by jvanbaarsen** [comment]
@voxik Ok, did you consider the comment made by qrush?

**Comment by voxik** [comment]
release-monitoring/anitya/issues/328

But no matter if Anitya is using webhooks or not, this API is missing this functionality.

**Comment by sonalkr132** [comment]
Closed by #1759 
See also: https://guides.rubygems.org/rubygems-org-api/#get---apiv1timeframe_versionsjson
