### ISSUE TITLE
Using svg for database layout smushes text together

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1288]
I am using chrome `Version 49.0.2623.110 (64-bit)` on Fedora 23 and this what I see on [database layout](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#database-layout):

![screenshot from 2016-05-24 19-11-23](https://cloud.githubusercontent.com/assets/7680662/15506066/b2d2281a-21e3-11e6-927d-a5fd869024df.png)

What do others see? I propose that we use png instead.
cc: @simi

**Comment by simi** [comment]
Version 50.0.2661.102 (64-bit), Fedora 23 also.

I see this:

![screenshot-github com 2016-05-24 15-52-13](https://cloud.githubusercontent.com/assets/193936/15506354/912abb6c-21c7-11e6-9aba-eeadf9055a65.png)

With PNG I have no idea what picture size should be used.

**Comment by sonalkr132** [comment]
@simi  I am pretty sure you are seeing this on wider screen. My screen size is 15.6 in.

**Comment by simi** [comment]
I have 13'', but 4k.

That's the reason for keeping svg. I'm not sure what's your screen resolution, but svg should fit for most screens. You can still download it and open "unstreched".

**Comment by sonalkr132** [comment]
4k = 3840 pixels × 2160 lines.  :computer:  Mine is 1366 x 768
> svg should fit for most screens. You can still download it and open "unstreched".

Totally agree. png would be stretched. However I think png serves the purpose without people with smaller screen resolution seeing jumbled words.

May be we can use third opinion :sweat_smile: :v:

**Comment by dwradcliffe** [comment]
The svg looks correct on my screen as well (OS X Chrome Version 50.0.2661.102 (64-bit)).

What if we keep the svg but also render a png to the `doc/` directory?

**Comment by sonalkr132** [comment]
> What if we keep the svg but also render a png to the doc/ directory?

naah! It would just add 233KB to repo size. I was only saying that may be we should use png because svg didn't look good on my screen(and probably others as well).

But again, it more about the data it conveys than aesthetic. We can close this if we are going to keep svg :no_entry_sign:
