### ISSUE TITLE
Self serve remove account

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1295]
As mentioned in the [recent blog post](http://blog.rubygems.org/2016/05/20/rubygems-org-2016-push.html) we would like to make a way for users to remove their account if they wish.

This would be implemented as a link/button probably from the user's own profile page (or maybe the edit profile page). This would lead to a confirmation page with the following:
- strong warning that this is apermanent, irreversible action. this can't be undone by contacting support
- a list of the gems the user owns that have other owners - saying that they will no longer have access to these gems but the other owners (list them) will continue to have access
- a list of the gems the user owns that have NO other owners - saying that these gems will be orphaned and they will be allowed to be adopted by someone else (with admin approval, for now?)
- maybe a box to type in the username to confirm?

cc: @qrush

**Comment by sonalkr132** [comment]
Are we going to delete the user data from database or just flag that user as deleted?

**Comment by qrush** [comment]
For support requests I have been hard deleting from the database. I think
that would be a fine way to start.

**Comment by simi** [comment]
There's another approach to keep user, mark as deleted and wipe all personal informations like name, email, ...

**Comment by shevegen** [comment]
Good idea.

+1

**Comment by alexiamcdonald** [comment]
I would really like to work on this. I think archiving the user and deleting their personal data seems like the way to go.

**Comment by sonalkr132** [comment]
Thank you for your interest @alexiamcdonald

#1301 already exists for the issue. You are welcome to leave comments on it :recycle: I am sure you can also find other interesting issue to work on :smiley_cat:
