### ISSUE TITLE
Support for alternate emails in the profile

### ISSUE THREAD

**Issue by zamith** [rubygems/rubygems.org#1299]
I personally have multiple emails, and I think it is common to have at least a personal and a work one. What do you think about allowing a profile to be referenced from a `gemspec` by more than one email?

**Comment by dwradcliffe** [comment]
The emails in the `gemspec` are not actually tied to the profiles on RubyGems.org in any way. Any email in the gemspec is okay.

**Comment by zamith** [comment]
Really? Didn't know that. Then how do you get the owners picture and so on?

**Comment by dwradcliffe** [comment]
The gem authors come from the gemspec but the gem owners are a separate thing. Owners are tied to user profiles and are based on the authenticated user, not the gemspec.

**Comment by zamith** [comment]
Yes, I saw that after your comment. Then what about adding the possibility of having more than one email per profile? Is this not useful?

**Comment by dwradcliffe** [comment]
I'm not sure that is useful. Can you explain why you would want that?

**Comment by zamith** [comment]
As far as I can understand from [this PR](https://github.com/rubygems/rubygems/pull/1569), the email is used as a fallback if no owner is given. I had a situation where the email on the gemspec was not the email I have on my rubygems.org profile, since I have multiple emails, and as such I was not added as an owner of the gem.

Changing the email on the gemspec fixed that. That's why I assume they were related.

**Comment by dwradcliffe** [comment]
Not quite. We allow users to hide their email address from their profile, which also hides their email address from the owners api endpoint. That PR adapts the client to handle that situation and display the username instead of the (missing) email.

I'm not sure about your specific situation. The email in your gemspec does not matter, only the account that is signed in on your computer when you `gem push`.

**Comment by zamith** [comment]
Hum... This was someone else pushing the gem. Maybe this was a misusage on our part that led me to think this would be a nice feature. Sorry about that.
