### ISSUE TITLE
Add twitter handle to profile

### ISSUE THREAD

**Issue by jaredbeck** [rubygems/rubygems.org#1302]
As a visitor,
I want to see the twitter handles of gem owners,
because I want to follow them on twitter

I can try to implement this if it's something people want.

**Comment by lucianosousa** [comment]
Firstly, we should allow at gemspec file this info, don't?

**Comment by shevegen** [comment]
Yes, possibly an optional extra field. I for instance do not have a twitter handler but I can see that others may want to know more about some gem owners.

**Comment by dwradcliffe** [comment]
👍 I think this is a good idea. Sometimes it's hard to find someone just based on their username. This would (optionally) be on the RubyGems.org user profile, not on the gem or gemspec.

**Comment by LoChanHi5** [comment]
I would like to work on this if nobody has started yet. It'll be my first open-source contribution 😄

**Comment by sonalkr132** [comment]
This was implemented in #1361. Users can go to https://rubygems.org/profile/edit to add their twitter handle.
