### ISSUE TITLE
Dependency endpoint only needs name, number and platform

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1308]
Before https://github.com/bundler/bundler-api/pull/80 bundler-api's dependency endpoint only had `name`, `number` and `platform`. Following is [comment](https://github.com/bundler/bundler-api/pull/80#discussion_r32080402) left from @indirect :
> I think we probably need two different classes—the old DepKey is for the current dependency API, and the new structure should be used only for the /info files. We don't want to query for the ruby and rubygems version and checksum in the regular dependency API, which also uses this class.

Changes introduced in the PR were for compact index. Does this mean we can drop `:required_ruby_version, :required_rubygems_version, :sha256, :created_at` from [dependency endpoint we have imported](https://github.com/rubygems/rubygems.org/blob/master/app/models/gem_dependent.rb#L38-L69) in rg.org? I suppose it will only improve the response time.
I haven't spent much time on making sure that bundler actually does not use those, however first look gives the impression that it does not.
* [Search](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=required_rubygems_version) of `required_rubygems_version` shows that is only used in compact index side of things. 
I downgraded my rubygems version and tried to install gems which required higher rubygems version, [rubygems has code](https://github.com/rubygems/rubygems/blob/39fe061ea3c7b652d907b4ff48b657c374164632/lib/rubygems/installer.rb#L611-L619) which made sure that installation does not go through. So, it might not be responsibility of bundler to ensure it in the first place?

* [Search](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=checksum&type=Code) for checksum shows that again it is only used in compact index side of things. Also, we saw yesterday that despite having mismatched format of checksum stored in bundler-api DB, everything worked.

cc: @fotanus @segiddins

**Comment by segiddins** [comment]
👍 sounds about right to me

**Comment by sonalkr132** [comment]
How are we even going to go about this! I don't think we can just drop those columns and deploy it to production.

**Comment by segiddins** [comment]
@sonalkr132 two different DepKey classes (or a subclass) would probably be a viable way to do this
