### ISSUE TITLE
Download graph

### ISSUE THREAD

**Issue by dmathieu** [rubygems/rubygems.org#132]
Hello,

It'd be quite cool to have a graph displaying the number of downloads every week.
I've already started to look into the code for that. But before to start implementing it on a fork, I'd like your opinion on the library to use for generating the graph.

I have a preference for [flot](http://code.google.com/p/flot/) and [flotilla](http://github.com/joshuamiller/flotilla) libraries.
But I'd like your opinions on this library or any other one to use.

**Comment by Foggalong** [comment]
Out of curiosity, what happened to this feature? I was just looking for where the download stats page was and this was thread was about the only relevant search result

**Comment by flavorjones** [comment]
@Foggalong the Ruby Toolbox project scrapes stats and graphs them over time, e.g.: https://www.ruby-toolbox.com/projects/rake
