### ISSUE TITLE
For yanked gems - consider distinguishing between gems that were completely yanked (all versions removed), and projects where only some old/buggy versions were removed yet that project still existing (and being actively maintained in some cases)

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1322]
Hi rubygems.org folks,

I noticed something strange but also trivial and tiny, not sure if
I should even report it, but I'll do anyway - if this is not useful
it can be closed. :)

If you go to this URL here:

    https://rubygems.org/gems/bioroebe/versions/0.0.81

You can read this:

"This gem has been yanked, and it is not available for download directly
or for other gems that may have depended on it."

Now, the statement is correct in the sense that THAT particular gem version
of the project was yanked, but not the whole project was yanked. Meaning,
the project called "bioroebe" still exists, just with more recent, newer
versions.

If you go to this instead though:

    https://rubygems.org/gems/cut_audio

Or even better, this one here:

    https://rubygems.org/gems/cut_audio/versions/1.0.1

Then the very same content is displayed:

"This gem has been yanked, and it is not available for download directly
or for other gems that may have depended on it."

But if you compare these two projects, then the same wording in use
describes two different projects - one that is still active (bioroebe),
another one that no longer is active and has no gem versions for
download either (cut_audio).

So my proposal is mostly a cosmetic one.

In pseudocode:

"IF the particular gem version has been yanked BUT a more recent 
gem version exists, consider changing the text to this here instead:"
 
"This gem has been yanked, and it is not available for download directly
or for other gems that may have depended on it. However had, there is
a more recent version available, at INSERT_URL_HERE."

I am not sure if it is worth to change it, but then again, small changes
are often easier to do than big new features!

**Comment by dwradcliffe** [comment]
I think you're right; your proposed change does make sense.

**Comment by shevegen** [comment]
I noticed the change. I think it is probably fine as it is now? Guess it can be closed unless someone thinks otherwise. :)
