### ISSUE TITLE
add an option to specify SemVer.org compliance

### ISSUE THREAD

**Issue by pravi** [rubygems/rubygems.org#1325]
I maintain debian packages of many rubygems (so rails apps like gitlab and diaspora can be just 'apt-get install' for end users who don't know ruby).

I have been collecting SemVer.org compliance info here https://wiki.debian.org/Teams/Ruby/UpstreamPledge as it helps those apps to specify a looser dependency and it makes our job of updating gems without breaking existing apps easier.

It would be good if this information can be captured in gemspec/rubygems.org page for the gem.

This will give confidence to users of this gem about changes to minor/patch updates. It will make life easier for app developers and packagers.

**Comment by jvanbaarsen** [comment]
@pravi How would you see this working? There is a item on the right side on the page that states: "Follows SemVer: Yes / No"?

This would mainly be a "Trust" system, right? Since there is no real way of checking if the gem is following SemVer.

If the maintainer of the gem is not stating if they are following SemVer, do you think they will add it to their gem page?

My concern with adding this kind of information is that we get an information overload on the gem page.

**Comment by pravi** [comment]
@jvanbaarsen. Yes, on the right sidebar. Yes, it is based on trust, we don't have to verify compliance.

Some projects mention it in README, but having it in gemspec directly makes it standard and easy to find. I think SemVer compliance is a very important information for a library. I personally find it important becauase I maintain debian packages of hundreds of rubygems (those required for gitlab and diaspora) and it helps a lot to ensure compatibility when two apps have different minor version requirements and we really like to keep only one version of a rubygem in debian.

Many projects are happy to add it in README on request and having it standardized in gemspec will enourage more people to mention it.

**Comment by jvanbaarsen** [comment]
@dwradcliffe What do you think about the above? ☝️

**Comment by dwradcliffe** [comment]
Hmm, personally I'm not sure how much value I would get from this. That said if enough people want this then maybe it's a good idea. I'm not saying 🚫  but I'm not 💚  quite yet either. Let's see what other people say.

**Comment by sonalkr132** [comment]
I don't see much value in this either. @pravi I am sorry this makes your work harder but this is more of a community practice and would be better communicated through individual project READMEs than something on rubygems.org.
