### ISSUE TITLE
Please advise on openssl rubygem

### ISSUE THREAD

**Issue by mbailey** [rubygems/rubygems.org#1373]
[[moved from here](https://github.com/rubygems/rubygems/issues/1663#issuecomment-232228387)]

I created [openssl rubygem](https://rubygems.org/gems/openssl/versions/0.2.0) to [verify a security vulnerability](http://help.rubygems.org/discussions/suggestions/7892-reporting-abuse-on-openssl).

I was pleased to see rubygems.org respond by [reserving core libs namespaces](https://github.com/rubygems/rubygems.org/issues/1155).

I have been contacted by people wanting me to transfer ownership of the gem. I'm not in a position to verify the authenticity or appropriateness of these requests. I don't know the parties involved personally.

**I would love for rubygems.org to take openssl rubygem away from my control**. 

You guys can take full responsibility for who controls this gem. 

I don't want to take any actions personally in regard to this Gem for security reasons.

**Comment by hsbt** [comment]
@dwradcliffe Would you handle this request? We have plan to ship openssl gem extracted from stdlib in CRuby repository at 2.4.0 preview 2 release.

**Comment by dwradcliffe** [comment]
@hsbt You have ownership now. You can add whoever else needs it. I'll also remove it from the blacklist.

**Comment by hsbt** [comment]
@dwradcliffe Thanks always.
