### ISSUE TITLE
Command 'gem list {{REGEXP}}' fails on Git for Windows on Windows XP

### ISSUE THREAD

**Issue by MarkDBlackwell** [rubygems/rubygems.org#1375]
A prerequisite is to do `gem install jsonb multi_json`.

On my 64-bit Windows 7 system, using the Git Bash prompt of Git for Windows (version 2.8.1), `gem list {{REGEXP}}` works:

    $ gem list json

    *** LOCAL GEMS ***
    json (1.8.2, default: 1.8.1)
    jsonb (0.0.1)
    multi_json (1.12.1)

    $ gem list ^json$

    *** LOCAL GEMS ***
    json (1.8.2, default: 1.8.1)

    $ gem list "^json$"

    *** LOCAL GEMS ***
    json (1.8.2, default: 1.8.1)

However, on my 32-bit Windows XP SP3 system, also using the Git Bash prompt of Git for Windows (version 2.8.1), I haven't found a way that works successfully:

    $ gem list json

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)
    jsonb (0.0.1)
    multi_json (1.12.1)

    $ gem list ^json$

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)
    multi_json (1.12.1)

    $ gem list "^json$"

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)
    multi_json (1.12.1)

    $ gem list '^json$'

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)
    multi_json (1.12.1)

    $ gem list \^json\$

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)
    multi_json (1.12.1)

However, on cmd.exe, it can succeed:

    >gem list "^json$"

    *** LOCAL GEMS ***
    json (1.8.3, 1.8.2, default: 1.8.1)

On Windows XP:

    $ gem env
    RubyGems Environment:
      - RUBYGEMS VERSION: 2.6.6
      - RUBY VERSION: 2.2.5 (2016-04-26 patchlevel 319) [i386-mingw32]
      - INSTALLATION DIRECTORY: C:/progra/ruby/lib/ruby/gems/2.2.0
      - USER INSTALLATION DIRECTORY: C:/Documents and Settings/Mark/.gem/ruby/2.2.0
      - RUBY EXECUTABLE: C:/progra/ruby/bin/ruby.exe
      - EXECUTABLE DIRECTORY: C:/progra/ruby/bin
      - SPEC CACHE DIRECTORY: C:/Documents and Settings/Mark/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: C:/Documents and Settings/All Users/Application Data
      - RUBYGEMS PLATFORMS:
        - ruby
        - x86-mingw32
      - GEM PATHS:
         - C:/progra/ruby/lib/ruby/gems/2.2.0
         - C:/Documents and Settings/Mark/.gem/ruby/2.2.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
         - "gem" => "--conservative --no-rdoc --no-ri --run-tests"
         - "rdoc" => "--all --inline-source --line-numbers"
      - REMOTE SOURCES:
         - https://rubygems.org/
      - SHELL PATH:
         - C:\Documents and Settings\Mark\bin
         - C:\Program Files\Git\mingw32\bin
         - C:\Program Files\Git\usr\local\bin
         - C:\Program Files\Git\usr\bin
         - C:\Program Files\Git\usr\bin
         - C:\Program Files\Git\mingw32\bin
         - C:\Program Files\Git\usr\bin
         - C:\Documents and Settings\Mark\bin
         - C:\progra\ruby\bin
         - C:\WINDOWS\system32
         - C:\WINDOWS
         - C:\WINDOWS\System32\Wbem
         - C:\Program Files\Common Files\Adaptec Shared\System
         - C:\Program Files\Common Files\Adobe\AGL
         - C:\progra\gtk\bin
         - C:\Program Files\Intel\DMIX
         - C:\Program Files\Medialink\MWN-USB54G
         - C:\Program Files\Common Files\Teleca Shared
         - C:\Program Files\VDMSound
         - C:\Program Files\7-Zip
         - C:\Program Files\gs\gs9.16\bin
         - C:\progra\lilypond\current\usr\bin
         - C:\progra\nano\bin
         - C:\Program Files\Skype\Phone
         - C:\progra\Python32
         - C:\Documents and Settings\All Users\Application Data\Oracle\Java\javapath
         - C:\Program Files\Inno Setup 5
         - C:\Program Files\Git\usr\bin\vendor_perl
         - C:\Program Files\Git\usr\bin\core_perl
         - C:\Documents and Settings\Mark\.ec2\bin

On Windows 7:

    $ gem env
    RubyGems Environment:
      - RUBYGEMS VERSION: 2.6.6
      - RUBY VERSION: 2.2.5 (2016-04-26 patchlevel 319) [i386-mingw32]
      - INSTALLATION DIRECTORY: C:/progra/ruby/lib/ruby/gems/2.2.0
      - USER INSTALLATION DIRECTORY: C:/Users/Mark/.gem/ruby/2.2.0
      - RUBY EXECUTABLE: C:/progra/ruby/bin/ruby.exe
      - EXECUTABLE DIRECTORY: C:/progra/ruby/bin
      - SPEC CACHE DIRECTORY: C:/Users/Mark/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
      - RUBYGEMS PLATFORMS:
        - ruby
        - x86-mingw32
      - GEM PATHS:
         - C:/progra/ruby/lib/ruby/gems/2.2.0
         - C:/Users/Mark/.gem/ruby/2.2.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
      - REMOTE SOURCES:
         - https://rubygems.org/
      - SHELL PATH:
         - C:\Users\Mark\bin
         - C:\Program Files\Git\mingw64\bin
         - C:\Program Files\Git\usr\local\bin
         - C:\Program Files\Git\usr\bin
         - C:\Program Files\Git\usr\bin
         - C:\Program Files\Git\mingw64\bin
         - C:\Program Files\Git\usr\bin
         - C:\Users\Mark\bin
         - C:\Windows\system32
         - C:\Windows
         - C:\Windows\System32\Wbem
         - C:\Windows\System32\WindowsPowerShell\v1.0
         - C:\Program Files\Common Files\Microsoft Shared\Windows Live
         - C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
         - C:\Program Files (x86)\Windows Live\Shared
         - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
         - C:\Program Files (x86)\AMD APP\bin\x86_64
         - C:\Program Files (x86)\Intel\iCLS Client
         - C:\Program Files\Intel\iCLS Client
         - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
         - C:\Program Files (x86)\Common Files\Adobe\AGL
         - C:\ProgramData\Oracle\Java\javapath
         - C:\progra\gtk\bin
         - C:\Program Files\Python33
         - C:\progra\ruby\bin
         - C:\Program Files (x86)\archduke\midi
         - C:\Program Files (x86)\gs\gs9.16\bin
         - C:\Program Files (x86)\gs\gs9.16\lib
         - C:\Program Files (x86)\Heroku\bin
         - C:\Program Files (x86)\LilyPond\current\usr\bin
         - C:\Program Files (x86)\Skype\Phone
         - C:\progra\nano\bin
         - C:\Program Files (x86)\Inno Setup 5
         - C:\Program Files\Git\usr\bin\vendor_perl
         - C:\Program Files\Git\usr\bin\core_perl

**Comment by dwradcliffe** [comment]
This should be in https://github.com/rubygems/rubygems/issues

**Comment by MarkDBlackwell** [comment]
@dwradcliffe, my regrets. Deleted and resubmitted [there](https://github.com/rubygems/rubygems/issues/1669).
