### ISSUE TITLE
Compact index errors when gem name has capitalization

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#1379]
The `rack` gem somehow has some versions with the name `Rack`, and the compact index serves two completely separate files as a result:

```
$ curl https://rubygems.org/info/rack
---
1.0.0 camping:>= 0,fcgi:>= 0,memcache-client:>= 0,mongrel:>= 0,ruby-openid:~> 2.0.0,test-spec:>= 0,thin:>= 0|checksum:b1147fd2991884dfbac9b101b0c88a0f0fc71abbd1bd24fb29cde3fdfc8ebd77,rubygems:>= 0
[...]
```

```
$ curl https://rubygems.org/info/Rack
---
1.1.1 |checksum:a9209252a19ff761925788bd8a15bd45d4b45308a54908dba0cda1375ec39030,rubygems:>= 0
[...]
```

We need to serve all versions (both `rack` and `Rack`) inside the file at /info/rack.

**Comment by indirect** [comment]
Nope, this is a total lie. Those are two different gems. This is gonna be a problem. :(

**Comment by sonalkr132** [comment]
We have the real issue[1] documented here https://github.com/rubygems/rubygems.org/issues/1356

[1] gems with same name (ignoring case) won't be able to release same versions.
