### ISSUE TITLE
API responses for gem `youtube-dl.rb` are incorrect

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#1386]
At the page https://rubygems.org/gems/youtube-dl.rb/versions, there are 75 versions listed. In the v1 API versions response, though, there are only 72 versions provided in the response:

```
$ curl -s https://rubygems.org/api/v1/versions/youtube-dl.rb.json | jq '.[] | .number' | wc -l
72
```

Using the v2 API, all versions are missing entirely:

```
$ curl -s -I https://rubygems.org/api/v2/rubygems/youtube-dl.rb/versions/0.3.1.2016.08.12.json | head -n 1
HTTP/1.1 404 Not Found
```

(But this is the URL scheme that is supposed to work for API v2, as demonstrated by `https://rubygems.org/api/v2/rubygems/rack/versions/1.0.0.json`, which does work).

**Comment by indirect** [comment]
@sonalkr132, do you think you could look into this?

**Comment by sonalkr132** [comment]
@sonalkr132 was catching zzz's.
