### ISSUE TITLE
`Rubygem.search` does not support search like « RubyGem11 » anymore

### ISSUE THREAD

**Issue by spk** [rubygems/rubygems.org#1395]
Searching with this pattern result to an error like `PG::SyntaxError: ERROR:  syntax error in tsquery: "RubyGem:* & :* & 6:*"`

This is maybe due to usage of `tsvector` introduced recently, cc @sonalkr132  

Failing build: https://travis-ci.org/rubygems/rubygems.org/jobs/155570866#L1122

**Comment by indirect** [comment]
@spk whoa, thanks for pointing this out! I'm going to back out that change for now, and we can merge it again later once we're sure it won't cause this problem.

**Comment by spk** [comment]
@indirect no problem all props to @sonalkr132 for inspecting my commits, thanks for the feedback.
