### ISSUE TITLE
Gem name not released after using gemcutter

### ISSUE THREAD

**Issue by bonzofenix** [rubygems/rubygems.org#1411]
I'm having a problem.

My current problem is that I removed a gem from my personal rubygem account to move it to a corporate one. After using gemcutter the gem disappeared from my personal rubygems, but the namespace was not release.

This issue is related to:

 Network problems
 Installing a library
 Publishing a library
 The command line gem
 Other
I will abide by the code of conduct.

**Comment by dwradcliffe** [comment]
Are you trying to remove the gems or transfer ownership?
Sounds like this is probably better suited for http://help.rubygems.org/

**Comment by sonalkr132** [comment]
Discussion was opened on help site: http://help.rubygems.org/discussions/problems/22723-gem-name-not-released-after-using-gemcutter
