### ISSUE TITLE
Search function should not rely on the ordering of the terms

### ISSUE THREAD

**Issue by lynnco** [rubygems/rubygems.org#1412]
Problem description:

Searching [async rails](https://rubygems.org/search?utf8=%E2%9C%93&query=async+rails) returns distinct results from searching [rails async](https://rubygems.org/search?utf8=%E2%9C%93&query=rails+async).

Intended behavior:

The search returning results regardless of of the ordering of the terms, and the results from "async rails" and "rails async" being identical.

**Comment by dwradcliffe** [comment]
With new search on the way soon™️, I'm going to say this is "won't fix".

However, I'd love to see a test added for new search to ensure this works there.

**Comment by jvanbaarsen** [comment]
@dwradcliffe How far along is the work for the new search? Is this test something that can already be added?

**Comment by dwradcliffe** [comment]
We rolled out the new search last week, so this is now solved!
