### ISSUE TITLE
Gem owner has push rights to reserved namespace

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1413]
When a [namespace is reserved](https://rubygems.org/gems/deviantart) by rubygems.org[1], the gem page says:
> This namespace is reserved by rubygems.org. Contact rubygems team if you would like to take over this namespace.

This :point_up: statement is false. `ownership` record is not deleted when a user yanks all versions of a gem. Thus, gem owner still has all control of the namespace. ie. they can `gem push ..`, `gem owner  ..` etc.

Probably it is acceptable that canonical gem owner has some control over the namespace (for 100 days) in case they change their mind and want to come back? This would require that we display a better reserved namespace message.

Alternately, if gem owner should not have any special right, we should delete the `ownership` record.

[1] namespace is reserved for 100 days when all versions of a gem older than a month are yanked.

cc: @indirect, @aycabta

**Comment by indirect** [comment]
After some discussion, we decided that this is a good thing, and we will keep it this way. We can improve the message in #1408. <3
