### ISSUE TITLE
429 Rate limit from API

### ISSUE THREAD

**Issue by calvinalvin** [rubygems/rubygems.org#1415]
Hi is there a newly enforced rate limit on your api now?

We have some chef cookbooks that install some rubygems and we are consistenly running into 429's which cause our deploys to fail. 

For example:

```
[2016-09-08T22:53:43+00:00] INFO: Installing chef-gem fog = 1.37.0
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
bad response  429 (https://api.rubygems.org/api/v1/dependencies?gems=fog-profitbricks)
```

**Comment by calvinalvin** [comment]
Actually I think we found a solution. 
http://help.rubygems.org/discussions/problems/22721-bundlerhttperror-nethttptoomanyrequests
Thanks

**Comment by dwradcliffe** [comment]
Yes we do have new rate limits in place this week. See the help issue above for more information.
