### ISSUE TITLE
Ability to ’star’ gems?

### ISSUE THREAD

**Issue by danielbayley** [rubygems/rubygems.org#1424]
Like on npm. Maybe you could even just use a little gem symbol rather than a star…

**Comment by sonalkr132** [comment]
Or show how many **starts** it has on github and send staring request to github?
https://cocoapods.org/pods/Alamofire
> Github
Stars	19,046
Watchers	940
Forks	3,072
Issues	3
Contributors	100
Pull Requests	1

https://developer.github.com/v3/activity/starring/

**Comment by shevegen** [comment]
I am unfamiliar with how npm stars work. Could someone give an example perhaps please, just to satisfy my curiousity?

**Comment by arthurnn** [comment]
TBH I don't see much value in this feature. 
And if we can avoid as much input from the rubygems.org site I would prefer.
Thoughts @qrush @evanphx @dwradcliffe ?

**Comment by qrush** [comment]
You can already subscribe to gems for updates - and they appear when you sign in.

**Comment by s2t2** [comment]
Facilitating/enabling/encouraging github repo starring might elevate the popularity of all gems on github and therefore make Rubygems as an ecosystem more popular.

**Comment by lynnco** [comment]
@sonalkr132's suggestion of sending star requests to github and having the stars be read from there, should be a fairly low weight addition.

I also agree with @s2t2's comment that it would make Rubygems more popular as a whole. Although how much more popular and whether or not that popularity is worth the added UI elements is up for debate.

I'm not familiar with the use / implementation of stars on npm besides those two points. @danielbayley could you elaborate?

**Comment by arthurnn** [comment]
I like the integration idea. 👍 , should be simpler, and easy to remove if we find there is no value in the future.

**Comment by simi** [comment]
I don't agree with popularity argument, but what about to start with something really really simple similar to [ghbtns.com](https://ghbtns.com/#star)?

**Comment by dwradcliffe** [comment]
Note: we don't always have a good mapping between gems and GitHub repos. Most gems probably follow the pattern of putting a good GitHub url in the project url field but not always.

I would definitely prefer to use a simple button like @simi suggested rather than lots of backend api interactions with a 3rd party.

**Comment by shlok007** [comment]
>I would definitely prefer to use a simple button like @simi suggested rather than lots of backend api interactions with a 3rd party.

Since, no one is currently working on it, I'll be happy to take this up. Will be ready with a PR with that implementation soon. :slightly_smiling_face:
