### ISSUE TITLE
Pushing a new gem

### ISSUE THREAD

**Issue by micalexander** [rubygems/rubygems.org#1426]
I am trying to push a new gem, however I keep getting the error `You do not have permission to push to this gem.`

The gem name is `trio`.

I don't see that this name is being used, however going to https://rubygems.org/gems/trio it seems to be reserved and says I need to submit a ticket.

I am not seeing where I can submit a ticket so I came here.

Any ideas?

**Comment by sonalkr132** [comment]
`trio` was yanked `2016-06-28`. rubygems.org has [reserved the namespace for 100 days](https://github.com/rubygems/rubygems.org/pull/1371).
You can do one of the following things:

* wait until October 6, 2016, when the namespace will be release automatically.

* request previous owner of `trio` to add you as owner.

* request to release the namespace before 100 days using [help.rubygems.org](http://help.rubygems.org/)

See also: https://github.com/rubygems/rubygems.org/issues/1413

**Comment by micalexander** [comment]
Nice.

On help.rubygems.org<http://help.rubygems.org> I do not see where I can make the request to have the namespace released. Can you link me directly to that form or instruct me where to click to begin the process?

--
MIchael Alexander


On September 12, 2016 at 10:17:12 PM, Aditya Prakash (notifications@github.com<mailto:notifications@github.com>) wrote:

trio was yanked 2016-06-28. rubygems.org has reserved the namespace for 100 days<https://github.com/rubygems/rubygems.org/pull/1371>.
You can do one of the following things:

  *   wait until October 6, 2016, when the namespace will be release automatically.

  *   request previous owner of trio to add you as owner.

  *   request to release the namespace before 100 days using help.rubygems.org<http://help.rubygems.org/>

See also: #1413<https://github.com/rubygems/rubygems.org/issues/1413>

**Comment by sonalkr132** [comment]
Here you go: http://help.rubygems.org/discussion/new

**Comment by sonalkr132** [comment]
Request to release the namespace was made on help site.
