### ISSUE TITLE
web_hook enhancements

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1434]
Our [webhook failure rate](https://github.com/rubygems/rubygems.org/blob/master/app/jobs/notifier.rb#L28) is unreasonably high (3 failures : 1 success). We have global web_hooks with `example.com` as url :sweat:  We have some [validation on url of web_hook ](https://github.com/rubygems/rubygems.org/blob/master/app/models/web_hook.rb#L7)for formatting. I believe this situation can be way better if we send [the post request](https://github.com/rubygems/rubygems.org/blob/master/app/jobs/notifier.rb#L16-L21) as part of validation.
Alternatively, we can disable the failing web_hook if they have failed a threshold number of times? This would also curb down the number of existing failing hooks. It would require that we allow users to re-enable web_hook after it has been disabled.

Apparently we can also remove `validates_formatting_of` dependency if we copy over [following line](https://github.com/mdespuits/validates_formatting_of/blob/664b7c8b1ae8c9016549944fc833737c74f1d752/lib/validates_formatting_of/method.rb#L19)(?):

``` Ruby
    add :url, %r{\Ahttps?:\/\/([^\s:@]+:[^\s:@]*@)?[A-Za-z\d\-]+(\.[A-Za-z\d\-]+)+\.?(:\d{1,5})?([\/?]\S*)?\z}i, "is not a valid URL"
```

We have only used `validates_formatting_of ...  using: :url` and validating url against that regex is all what the gem seems to do.

**Comment by sonalkr132** [comment]
Check https://github.com/rubygems/rubygems.org/issues/138 for previous discussion.

**Comment by shlok007** [comment]
I'll work on this. :+1:

**Comment by simi** [comment]
This problem seems outdated, since app moved to external webhooks solution, closing.
