### ISSUE TITLE
Move "Previous version" and "Next version" buttons down

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#1444]
Just noticed these buttons -

I think they're too far up on the page - they're not as important as the info of the gem, authors, etc. I think they must be useful for some folks - but maybe below the checksum would be a better spot.

Now:

![before](https://cloud.githubusercontent.com/assets/12610/19138665/484b3248-8b4c-11e6-9500-04c1326b03e6.png)

Perhaps this?:

![after](https://cloud.githubusercontent.com/assets/12610/19138666/4c0b6628-8b4c-11e6-852c-4e126f764967.png)

**Comment by simi** [comment]
:+1:, also I'm not sure why those links are there when no prev/next version is available (linked just to #).

**Comment by qrush** [comment]
Agreed, that would be another nice thing - hide previous or next if they don't exist.

**Comment by shevegen** [comment]
I am fine by it either way - remember that perhaps... a month ago or so we had no such link; the placement is probably not as important as them existing in the first place. :D

There is another link called "Show all versions (n total)" which can be clicked, so I think it may make sense to have another clickable action closer to it. Perhaps right after the description itself? However had, I am also fine for it being at the very bottom after other content.
