### ISSUE TITLE
Add hackerone to security page

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1445]
We have bounty program for rubygems (client). I believe the security page should include that. It could also use the mention that security bugs found on rubygems.org can be reported on hackerone as well.

**Comment by shevegen** [comment]
I guess you mean https://rubygems.org/pages/security ?

If so I concur, a paragraph could be added. If this is done, perhaps ~2 sentences should briefly mention what hackerone is, IF it is mentioned - for instance, I did not know about hackerone before this issue request here, I had to google for it. :)
