### ISSUE TITLE
Bulk update gem downloads

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1457]
I am curious whether bulk update was considered in implementation of gem downloads with `FastlyLogProcessor`. Using following sql:

``` sql
# updating versions download  
update gem_downloads as gd 
  set count = gd.count + versions_downloads.count
  from 
    (select
     # ensure that array has unique keys 
     unnest(array['edamame-0.3.0', 'lspace-0.9', 'codeclimate-engine-rb-0.2.0', 'poodle-rb-0.1.6'])
     as full_name, unnest(array[44, 50, 10, 12]) as count) as versions_downloads, versions as v
  where v.full_name = versions_downloads.full_name and v.id = gd.version_id
    and v.rubygem_id = gd.rubygem_id;
```

and similar one for updating rubygems download would make 3100(avg) fewer sql queries in each job.

**Comment by sonalkr132** [comment]
cc @arthurnn 
[Why are batch inserts/updates faster? How do batch updates work?](http://stackoverflow.com/questions/1006969/why-are-batch-inserts-updates-faster-how-do-batch-updates-work/1007006#1007006)

**Comment by dwradcliffe** [comment]
I thought we tried a few ways but couldn't for some reason. I can't remember exactly.

**Comment by arthurnn** [comment]
I didn't try batch updates as far as I remember. 
We could try it.

**Comment by simi** [comment]
closed by https://github.com/rubygems/rubygems.org/pull/2527
