### ISSUE TITLE
ERROR:  While executing gem ... (Errno::ECONNREFUSED) Connection refused - recvfrom(2)

### ISSUE THREAD

**Issue by Astuid** [rubygems/rubygems.org#1462]
first i installed ruby on my redhat 6.6 , and then i installed rubygems
when i use gem to install something , erros occurred as follows:

[root@slave2 rubygems-2.6.6]# gem install  pry
ERROR:  While executing gem ... (Errno::ECONNREFUSED)
    Connection refused - recvfrom(2)
[root@slave2 rubygems-2.6.6]# gem install rest-client
ERROR:  While executing gem ... (Errno::ECONNREFUSED)
    Connection refused - recvfrom(2)

any help willed be appreciated!

**Comment by dwradcliffe** [comment]
Sounds like you have system network issues. Or a misconfigured proxy somewhere along the way. Make sure you can connect to the internet and if you still have problems you can open a help ticket at help.rubygems.org/discussion/new.

**Comment by Astuid** [comment]
@dwradcliffe 
problem is my server could not connect to internet because of its behavior as intranet for

**Comment by Astuid** [comment]
@dwradcliffe 
does i have to connect to internet?
problem is my server could not connect to internet because of its behavior as intranet..

**Comment by Astuid** [comment]
@dwradcliffe 
does it have to connect to internet?
problem is my server could not connect to internet because of its behavior as intranet..

**Comment by dwradcliffe** [comment]
Yes, the gems come from the internet.
