### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1465]
- [ ] Remove Sinatra app references from [readme](https://github.com/rubygems/rubygems.org#organization). [bundler-api is dead](https://github.com/rubygems/rubygems.org/pull/1461) :skull_and_crossbones: 
- [ ] Update [database layout](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#database-layout). [This rake task](https://github.com/rubygems/rubygems.org/blob/master/lib/tasks/gen_erd.rake) should work.

**Comment by tadityar** [comment]
hello! I'll work on this

**Comment by sonalkr132** [comment]
Change this

> If you need the index available - needed when working in conjunction with bundler-api - then run bundle exec rake gemcutter:index:update. This primes the filesystem gem index for local use.

to

> If you need the index available then run bundle exec rake gemcutter:index:update. This primes the filesystem gem index for local use.
