### ISSUE TITLE
Cosmetic change: display latest version and gem size of that version in a small font on the main profile page of a gem-author

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1478]
Hello. I am not sure if this proposal is useful or not; it is mostly a cosmetic change only.

I think it would be easy to implement because code for what I will suggest, already
appears to exist. But allow me to first describe my idea.

Right now, if you go to the profile of an author on rubygems.org, you can see the
following (let's pick chris2 just as example):

```
https://rubygems.org/profiles/chneukirchen
```

Ok, what do we see specifically new on that profile-page?

Well, we see how many downloads are in total, how many gems
are authored or co-authored - and we also see a listing of all
gems in total by that author. The latter part is where I refer to in
my proposal.

Take this listing here:

"rack 2.0.1 116,192,673 Downloads"

First line.

Next line is:

"rack-contrib 1.4.0 3,272,456 Downloads"

And so on and so forth. So we have:

NAME     VERSION   N_DOWNLOADS

_Would it be possible to add the size of that particular
gem version into that line as well?_

So for example, with rack, we would see:

"rack 2.0.1 (248 KB) 116,192,673 Downloads"

We already see the size of a gem if we click on:

https://rubygems.org/gems/rack

So the code should already exist. Probably no code
would have to be added at all! :)

I am not sure how well this suggestion is received,
it really is truly minor, no problem if this is not good 
to have either.

The main reason why I wanted to have this is mostly
to more easily calculate the total amount of code or
documentation available in all my ruby gems. It's no
problem to write a script to do that in ruby anyway,
but I just wanted to have something simpler and
visual for my eyes. Thanks for reading and no worries
to close that suggestion anyway, there are more
important suggestions out there!

**Comment by sonalkr132** [comment]
> Probably no code would have to be added at all! 

This would only need 
```Ruby
<span class="gems__gem__version">(<%= number_to_human_size(rubygem.latest_version.size) %>)</span>
```
in `profiles/rubygem` and won't add any sql query. If this change is acceptable, preferably `rubygems/rubygem` should be updated as well for consistency.

**Comment by sonalkr132** [comment]
adding size to list of gems on users profile doesn't add much. info is already there on gem show page.
