### ISSUE TITLE
Missing OpenSSL, unable to install gems or update system

### ISSUE THREAD

**Issue by marcus-cr** [rubygems/rubygems.org#1479]
Hello,

I'm beginning to explore Ruby and Ruby Gems and I'm very unfamiliar with both. Normally I use Homebrew and have OpenSSL brewed. I'm trying to use bundle to install snorby however I get these error messages while running `$ bundle`

> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> ...
>An error occurred while installing eventmachine (1.0.8), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.8'` succeeds before bundling.

But after running `gem install eventmachine -v '1.0.8'` I receive this error:
>current directory: /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.8/ext
make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

>make failed, exit code 2

Would I not be able to use Homebrew's OpenSSL (figured this would cause some conflicts), or do I need to have OpenSSL with Homebrew **and** RubyGems (again, seems like it would cause conflicts)?

**Comment by segiddins** [comment]
How did you install your ruby?

**Comment by marcus-cr** [comment]
I don't remember installing it, just RubyGems..

I'm assuming it came with macOS.

**Comment by segiddins** [comment]
So you're using OS X's system ruby? 
What's the output of `gem env`?

**Comment by marcus-cr** [comment]
Ah yes, wow... I used rbenv to get Ruby 2.3.1.

>RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.7
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/marcus/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/var/rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/var/rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/marcus/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/var/rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /Users/marcus/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/var/rbenv/versions/2.3.1/bin
     - /usr/local/Cellar/rbenv/1.0.0/libexec
     - /usr/local/var/rbenv/plugins/rbenv-update/bin
     - /usr/local/var/rbenv/shims
     - /Users/marcus/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/pcre/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin

**Comment by sonalkr132** [comment]
hi marcus-cr,

Please check http://stackoverflow.com/questions/30818391/gem-eventmachine-fatal-error-openssl-ssl-h-file-not-found
I am closing this because issue has nothing to do with rubygems.org.
