### ISSUE TITLE
Correct name argument of statsd_count_success method

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1480]
`statsd_count_success` method's name argument doesn't need `.success` suffix. [This](https://github.com/rubygems/rubygems.org/blob/cb09831cd8e827a821b8cdc203fecd8bbab6b722/app/jobs/notifier.rb#L28) gets reported as `Webhook.perform.success.success` and `Webhook.perform.success.failure`.

http://www.rubydoc.info/gems/statsd-instrument/2.0.10/StatsD%2FInstrument%3Astatsd_count_success

**Comment by LoChanHi5** [comment]
I'll work on this
