### ISSUE TITLE
Fix images on maintenance and 404 page 

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1486]
Read discussion on #1468 

Previously used [sea_floor.png](https://github.com/rubygems/rubygems.org/blob/af86e4a921123b18e51a1d989f24afd5f82a6ef0/public/images/sea_floor.png) image and currently used [sea_floor.svg](https://github.com/rubygems/rubygems.org/blob/master/public/images/sea_floor.svg).

Previously used [gem_wrench.png](https://github.com/rubygems/rubygems.org/blob/af86e4a921123b18e51a1d989f24afd5f82a6ef0/public/images/gem_wrench.png) and currently used [gem_wrench.svg](https://github.com/rubygems/rubygems.org/blob/4f4a7672bc09fdf843f2c6f8597abac2d89ce1e2/public/images/gem_wrench.svg)

cc: @acacheung

**Comment by jvanbaarsen** [comment]
@sonalkr132 do you know if the design files are posted somewhere? In that case I can generate the original PNG into an SVG.

/cc @acacheung

**Comment by sonalkr132** [comment]
Sorry, links mentioned above [[1](https://github.com/rubygems/rubygems.org/blob/af86e4a921123b18e51a1d989f24afd5f82a6ef0/public/images/sea_floor.png)][[2](https://github.com/rubygems/rubygems.org/blob/af86e4a921123b18e51a1d989f24afd5f82a6ef0/public/images/gem_wrench.png)] are only files I know of. [Converting them to SVG didn't seem to go very well](https://github.com/rubygems/rubygems.org/pull/1468#issuecomment-253800063):
> I tried tracing sea_floor.png with Inkscape, and the SVG that came out was 50% smaller than the PNG. It looked OK but the colors were all messed up.

**Comment by indirect** [comment]
Reverting seems reasonable for now.

@nateberkopec, can you add the design source files to a new repo? That way @jvanbaarsen (or you, or someone else) can take another shot at a conversion that doesn't change the colors or the design.

**Comment by sonalkr132** [comment]
> Reverting seems reasonable for now.

[404 page](http://rubygems.org/404) seems fine. I probably added it only to point out that it had changed. Only maintenance one needs a bit fixing. :construction:

**Comment by indirect** [comment]
@sonalkr132 sadly, the 404 page image is also different enough that I think we should revert it: the colors are dramatically changed, and some elements of the illustration are missing completely, like the stripes in the sand.

**Comment by colby-swandale** [comment]
@inidrect does this still need fixing?

**Comment by colby-swandale** [comment]
@indirect Is this still worth fixing? This issue has been silent for a while, otherwise i can make a PR to restore the originals.

**Comment by indirect** [comment]
@colby-swandale good catch! I think the png-based error pages looked much better. I'd like to go back to them, since larger assets don't seem like a huge deal on pages that only load if an error has occurred. 👍

**Comment by simi** [comment]
I did quick check and images look ok. Is there still anything needed to fix this? :thinking:

**Comment by indirect** [comment]
I have no memory of this at all, I am guessing it's fixed since the pages seem good for now!
