### ISSUE TITLE
Getting SSL error trying to update gems

### ISSUE THREAD

**Issue by jgeiglein** [rubygems/rubygems.org#1507]
C:\Windows\System32>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError) SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by shevegen** [comment]
I believe that you may have commented on the wrong issue tracker perhaps?

The rubygems issue tracker is at https://github.com/rubygems/rubygems/issues

**Comment by sonalkr132** [comment]
Hi @jgeiglein,

Please follow instructions on our ssl page[1] to update your rubygems.
You can open support ticket[2] if you encounter any issues which we hope you won't :rainbow:
[1]http://guides.rubygems.org/ssl-certificate-update/
[2] http://help.rubygems.org/discussion/new
