### ISSUE TITLE
rename handle to username for clarity/useability

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#1510]
Just got a friend to sign up for rubugems.org and she was stopped by "what is handle" ... so please rename it to username or add `(username)`

https://rubygems.org/sign_up

**Comment by grosser** [comment]
I can make a PR ... but don't know what would be mergeable ...
 - add `(username)` in the UIs
 - rename the label in the UIs
 - alias_attribute and rename everywhere
 - db migration and rename everywhere

**Comment by sonalkr132** [comment]
I labeled it starter assuming we would only *rename the label in the UIs*, however if you have time for PR I would prefer *alias_attribute and rename everywhere*.
