### ISSUE TITLE
Changing email address should not invalidate user account

### ISSUE THREAD

**Issue by GBH** [rubygems/rubygems.org#1512]
This is what's happening right now:

- User edits profile and changes email to `typo@wrong.email`
- https://github.com/rubygems/rubygems.org/blob/master/app/models/user.rb#L26 is marking account as unconfirmed.
- https://github.com/rubygems/rubygems.org/blob/master/app/controllers/profiles_controller.rb#L21 and this immediately logs user out.
- User realizes that email address was incorrect.
- User is screwed as it's impossible to confirm account as that email went someplace else. It's also impossible to login (with correct username/password) or use password recovery functionality.

I'm thinking that this invalidating functionality should be completely removed. I don't really see why it's a thing.

Does this make sense? I can create PR if it's OK.

BTW: I just locked myself out this way: http://help.rubygems.org/discussions/problems/24406-locked-myself-out-cant-log-in-anymore

**Comment by shevegen** [comment]
That is indeed an interesting assumption. What happens if the email is not delivered or if the user can not access the email server anymore? E. g. if someone has been cut off from gmail or something.

Perhaps the old email should only become invalid once this was confirmed. And if not confirmed the old way would still work (and the new way would not work UNTIL it was confirmed).

**Comment by sonalkr132** [comment]
> I'm thinking that this invalidating functionality should be completely removed. I don't really see why it's a thing.

We need it to verify that the new/updated email address actually exists and is owned by the user.

>  What happens if the email is not delivered or if the user can not access the email server anymore? 

If the user can't access their mail, they should not use it. A valid email address is crucial, both for us (deals with fake accounts) and the user (needed when they forgot password).

I understand that typo situation is a problem we need to fix.
> Perhaps the old email should only become invalid once this was confirmed. And if not confirmed the old way would still work (and the new way would not work UNTIL it was confirmed).

This is lot of work. I think I will be able to add more to conversation after I have researched the issue.

**Comment by GBH** [comment]
@sonalkr132 Is it really an issue with people creating accounts with valid email and then changing it to an invalid one in order to have a "fake" account? I understand not enabling account until email is validated on registration, but invalidating account on email change seems wrong. I've never seen something like this done on any other service. 

Additionally, it would make a lot more sense to have email confirmation field when changing (also a thing on 99% of sites I've seen).

Also, is there anybody to look at my help ticket? I have a gem to publish that I can't for a week now :(

**Comment by sonalkr132** [comment]
> it would make a lot more sense to have email confirmation field when changing

I think we can accept a PR introducing this change. Thank you for your suggestion :smiley_cat: 

> is there anybody to look at my help ticket? I have a gem to publish that I can't for a week now

I am sorry to hear that. I will bug people to help resolve your ticket :wink:

**Comment by GBH** [comment]
I resubmitted PR so it's not from my master branch. I stand that it's the correct way to handle this problem. Looked at adding email confirmation field, but honestly it's not needed if it's harder to lock yourself out.
