### ISSUE TITLE
Short password on existing account

### ISSUE THREAD

**Issue by alexbel** [rubygems/rubygems.org#1517]
I have an old account. It has password less than 10 characters. Also it attached to the old email domain which doesn't exist anymore.
Because of the password validation on update action I can't update my email address and as a result I can't reset/update the password.

Edit: Also the message "This request was denied. We could not verify your password." is misleading in this scenario. It probably should show the standard rails validation text: "Password is too short..."

cc @sonalkr132

**Comment by GBH** [comment]
Can confirm that it's an issue. Password editing should be changed, really. I have ancient account that is not editable because of this.

**Comment by GBH** [comment]
@alexbel you should be able to request pass change and then change it. That appears to be working just fine.

**Comment by alexbel** [comment]
@GBH you mean though the email? As I mentioned before, I'm no longer able to access my old email (famous lavabit case).

**Comment by GBH** [comment]
@alexbel Oh right. Can login but can't even change email to a new one.
