### ISSUE TITLE
Multiple API keys

### ISSUE THREAD

**Issue by radar** [rubygems/rubygems.org#152]
As a developer for Mocra and an open source guy, sometimes I publish gems under the dev@mocra account and other times at my own personal account. In order to do this however I need to edit the ~/.gem/credentials file every time I need to switch. Whilst it would be easy for me to make a script to just mv the file elsewhere and copy over the new one, I think there would also be other people in this situation.

**Comment by johnl** [comment]
as this is the top search result for this problem and since I spent 20 minutes trying to figure out the right config format, I thought I'd clarify it here for others. Just specify each key as a symbol in `~/.gem/credentials` and specify which you want with `-k`

```
---
:work: b026324c6904b2a9cb4b88d6d61c81d1
:personal: b026324c6904b2a9cb4b88d6d61c81d1
```

```
gem push -k work mygem
```
