### ISSUE TITLE
Create good looking html mail for user email confirmation

### ISSUE THREAD

**Issue by sagarkaurav** [rubygems/rubygems.org#1523]
Use foundation gem for sending html email.

**Comment by dwradcliffe** [comment]
I would love to see a pull request to spruce up the emails a bit. I'm hesitant to add new gems and I'm not familiar with the foundation gem. Care to elaborate?

**Comment by sagarkaurav** [comment]
visit. the link

**Comment by sagarkaurav** [comment]
Visit the link http://foundation.zurb.com/emails/docs/gem-guide.html.There is vey good documentation about foundation for emails.
