### ISSUE TITLE
Missing translation for Reverse Dependencies

### ISSUE THREAD

**Issue by marceloboeira** [rubygems/rubygems.org#1544]
Page: https://rubygems.org/gems/functional_operations/reverse_dependencies

<img width="479" alt="screen shot 2017-01-13 at 19 29 37" src="https://cloud.githubusercontent.com/assets/1898225/21933467/d2313956-d9a5-11e6-9c60-e1cfcd838ab5.png">

It is probably: 
https://github.com/rubygems/rubygems.org/blob/master/app/views/reverse_dependencies/_reverse_dependencies.html.erb

I couldn't find the translation for `.search_reverse_dependencies` index ...

e.g.: https://github.com/rubygems/rubygems.org/search?utf8=✓&q=search_reverse_dependencies

**Comment by dwradcliffe** [comment]
Fixed here: https://github.com/rubygems/rubygems.org/pull/1543
