### ISSUE TITLE
Restoring a yanked gem

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1548]
Suppose world is coming to an end :volcano: and only way it can be saved is if we can restore yanked versions of the gem. As you may know, gem yank removes the .gem file from S3 and our CDN.
>  someone could maliciously or accidentally remove gems that others depended on. However, we’ve been using an Amazon S3 bucket to store the gems for years now with versioning on - so if someone does remove gems that are necessary, we can easily restore them. ([Read more](http://blog.rubygems.org/2015/04/13/permadelete-on-yank.html)).

We can restore S3 bucket of yanked version using [this](https://github.com/rubygems/rubygems.org/blob/master/lib/rubygem_fs.rb#L85) restore function. Now we need to index its version, expire memcache and fastly accordingly and destroy the deletion record. Taking hint from [this comment](https://github.com/rubygems/rubygems.org/pull/935#issuecomment-92158836) I came up with [this](https://github.com/rubygems/rubygems.org/commit/f2c94d7e1e8c35888a787d72f700c4e5937f7e9b). It wouldn't be enough for our [versions endpoint](https://github.com/rubygems/rubygems.org/blob/master/config/routes.rb#L101). After yanking a version our versions endpoint would look something like this:
> created_at: 2017-01-10T17:22:53-07:00
     ---
loremoooooooo 0.1.10 aa1f05eb62bf701bd42359b5f9b47059
loremoooooooo 0.1.11 157dcfb0bb0368c1532c20d9d1bcdfb5
loremoooooooo -0.1.10 0991bfe2958a19e18d6ccb9c89a8ef28

Since it is intended to be append only, after restoring `0.1.10` it should look like following:
>  created_at: 2017-01-10T17:22:53-07:00
     ---
loremoooooooo 0.1.10 aa1f05eb62bf701bd42359b5f9b47059
loremoooooooo 0.1.11 157dcfb0bb0368c1532c20d9d1bcdfb5
loremoooooooo -0.1.10 0991bfe2958a19e18d6ccb9c89a8ef28
loremoooooooo 0.1.10 aa1f05eb62bf701bd42359b5f9b47059

I am not exactly sure how are we going to make `0.1.10` appear a third time.
Alternatively, we can create a new `versions.list` file which would expire clients' cache. We won't want to do that either because it's expensive.

cc: @indirect,  @segiddins

**Comment by segiddins** [comment]
I thought we didn't want to make yanks reversible?

**Comment by sonalkr132** [comment]
It is not to make yanking reversible. Someday, we might to restore a gem which has been yanked in rage quit or by mistake. Hence the script, which is meant to be used only by admins.

**Comment by indirect** [comment]
since we’ll only use this script if the world is ending 😆 it seems fine to recreate the versions list

**Comment by segiddins** [comment]
@sonalkr132 in that case, you could just delete the `yanked_at` and `yanked_info_checksum` fields and save a fair bit of complexity

**Comment by sonalkr132** [comment]
> it seems fine to recreate the versions list

I was hoping we could achieve this without having to recreate versions list so that we can entertain requests like one recently received on help site.

> you could just delete the yanked_at and yanked_info_checksum fields

I hope you meant [delete the yanked_at and yanked_info_checksum fields **and mark version indexed**](https://github.com/rubygems/rubygems.org/commit/f2c94d7e1e8c35888a787d72f700c4e5937f7e9b#diff-175d93318045eb4395c87409e05dc6cfR51). It would remove the yanked version line, leaving our versions response as following:
> created_at: 2017-01-10T17:22:53-07:00
    ---
loremoooooooo 0.1.10 aa1f05eb62bf701bd42359b5f9b47059
loremoooooooo 0.1.11 157dcfb0bb0368c1532c20d9d1bcdfb5

We can't remove a line once it has been added to versions response because clients will be [making partial requests on basis of what they have already cached](https://github.com/bundler/bundler/blob/master/lib/bundler/compact_index_client/updater.rb#L36-L37). I bet you already know that. :stuck_out_tongue:
If this is not what you mean or if I am mistake, please elaborate.

**Comment by segiddins** [comment]
if the downloaded file's checksum doesn't match the etag, the client will re-request the entire file

**Comment by sonalkr132** [comment]
>  the client will re-request the entire file

That is same as regenerating the versions.list file. When I say expensive, I don't mean expensive to regenerate the file. I mean it would be expensive for all the clients to download the complete file. Given the stakes we won't be able to do very often.
