### ISSUE TITLE
Please consider an API endpoint for listing all available gems.

### ISSUE THREAD

**Issue by vincentwoo** [rubygems/rubygems.org#1554]
Hi everyone! I noticed that the current API does not appear to offer an endpoint to simply enumerate all gems (and gem versions) that exist (but that it does allow [search](http://guides.rubygems.org/rubygems-org-api/#gem-methods)).

For my purposes (attempting to make a Ruby sandbox with essentially every Ruby gem installed) being able to enumerate the world would be very useful. Any chance that could be something we add to rubygems.org?  I've learned that one may do `gem list --remote --all` when I [opened this issue against the wrong repo](https://github.com/rubygems/rubygems/issues/1828), but having an official endpoint would be pretty useful too!

**Comment by dwradcliffe** [comment]
If you installed every single gem I think it would likely be too slow to be usable. Also that would use quite a bit of bandwidth and time to download everything.

That said, if you need a list of every gem, please take a look at the new index files ([this](https://rubygems.org/names) and [this](https://rubygems.org/versions)). If that's not enough information you can download the [database dumps](https://rubygems.org/pages/data) and that has everything.

We're not going to add an unbounded all gems api endpoint. Any legitimate use case for a list of all gems can be solved with one of the options above.
