### ISSUE TITLE
Add configuration to add custom owner to data dump

### ISSUE THREAD

**Issue by anuccio1** [rubygems/rubygems.org#1571]
Currently, the script here: https://github.com/rubygems/rubygems.org/blob/master/script/load-pg-dump loads the rubygems backup and assigns ownership to Postgres user 'Postgres'. It would be great if users were able to change this to fit their own needs.

Would be glad to help implement this! (If doable)

**Comment by dwradcliffe** [comment]
Does `-u USER` do what you need?

**Comment by anuccio1** [comment]
I was actually referring to the data dump script downloaded from here:
https://rubygems.org/pages/data

It appears that "Postgres" is hardcoded

**Comment by shevegen** [comment]
The shell script is here:

https://github.com/rubygems/rubygems.org/blob/master/script/load-pg-dump

Line 23 hardcodes it:

pg_user=postgres

I have stopped using shell scripts many years ago so I don't know o a simple fix but what 
I commonly see in shell scripts is to make use of environment variables. So perhaps a
check could be added if a certain variable is set... like PG_USER or something like
that. Alternatively perhaps there could be some option to set it rom the commandline.

As a work-around I guess you can also hardcode the script on your system for the
time being anuccio1 :D

**Comment by jvanbaarsen** [comment]
@shevegen On line 56 (https://github.com/rubygems/rubygems.org/blob/master/script/load-pg-dump#L56) it get's overridden. 

@anuccio1 I just checked locally, the `-u` flag should help you out!

**Comment by colby-swandale** [comment]
ping @anuccio1 where you able to solve your problem?
