### ISSUE TITLE
just_updated and latest

### ISSUE THREAD

**Issue by UShan89** [rubygems/rubygems.org#1572]
Hi, 

For the API requests at 
1. /api/v1/activity/just_updated.json
2. /api/v1/activity/latest.json

How Can I get all the updates and not just 50 Updates? Is there a field that I can specify? 

How frequent does the latest and just_updated change? Is it hourly OR 24-hours OR instantaneous?

**Comment by sonalkr132** [comment]
> How Can I get all the updates and not just 50 Updates? Is there a field that I can specify?

Sorry, the endpoints support only 50 updates.

> How frequent does the latest and just_updated change?

New versions show up as soon as they are pushed. You can probably query it hourly to stay up to date.

**Comment by dwradcliffe** [comment]
If you need all updates you can use a webhook to get real-time updates for every new gem push.
http://guides.rubygems.org/rubygems-org-api/#webhook-methods

**Comment by UShan89** [comment]
Thank you @sonalkr132 and @dwradcliffe 
This is helpful
