### ISSUE TITLE
Rubygems.org API Error 503 Service unavailable

### ISSUE THREAD

**Issue by MLauper** [rubygems/rubygems.org#1578]
I noticed that the dependency API reacts in a strange way, if the number of Gems included in the request exceeds about 200. 

I receive a 503 Service Unavailable error from the Rubygems API during dependency resolution. The error seems to be returned from the Varnish cache:

> <?xml version="1.0" encoding="utf-8"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html>
>   <head>
>     <title>503 Service Unavailable</title>
>   </head>
>   <body>
>     <h1>Error 503 Service Unavailable</h1>
>     <p>Service Unavailable</p>
>     <h3>Guru Mediation:</h3>
>     <p>Details: cache-hhn1528-HHN 1488788176 499936067</p>
>     <hr>
>     <p>Varnish cache server</p>
>   </body>
> </html>

Is this behavior desired?
The expected behavior for me would be to return an appropriate error message to the user.
Would this be a possibility to implement as an improvement? What do you think?

For everyone receiving the same issue, it can be resolved by using the Full Index.

**Comment by dwradcliffe** [comment]
Yeah we should fix this. There is a hard limit on the number of gems allowed on the dependency API (200 is correct). You should be getting an error message that explains that but our CDN is not forwarding the error properly. I'll look into fixing this.

**Comment by shevegen** [comment]
Interesting. :D

My biggest gem uses 60 gems so far; 90% of these gems are just tiny, like 50-200 lines of code max.

Is there a reason for the cap? I assume it is to avoid proliferation of unlikely dependencies. And I am far from reaching that - I am even trying to get rid of several gems these days or trying to combine them into somewhat bigger, unified projects. But 200 also seems a bit like an arbitrary limit to me (not that any other number would not be arbitrary much at all either ... like 250 instead of 200. Just wondering anyway.).

**Comment by prcongithub** [comment]
I am getting the same error with just  the following gems
```
source 'https://rubygems.org'

gem 'rails', '3.2.13'
group :assets do
  gem 'sass', '3.2.14'
  gem 'sass-rails', '3.2.6'
  gem 'bootstrap-sass', '2.3.1.0'
  gem 'uglifier', '1.0.3'
end

gem 'oauth2', '1.0.0'

gem 'haml-rails', '0.3.4'
gem 'jquery-rails', '2.2.1'

gem 'puma','2.9.0'

gem 'kaminari', :github => "amatsuda/kaminari", :branch => "master", :ref => "c7c88c576786"

gem 'wicked_pdf','0.9.6'

gem 'faraday', :github => "prcongithub/faraday", :branch => "handle-unprocessable-entity", :ref => "dca594d4664e42476826d098053135b304242614"

gem 'her', '0.6.8'
gem 'spreadsheet', '1.1.1'

gem 'faraday_middleware','0.9.1'
gem 'awesome_print','1.1.0'
gem 'request_store','1.0.5'
#gem 'roo'
gem "exception_notification", :github => "pmahoney/exception_notification", :branch => "jruby", :ref => "5ac9f405fd53ee"
gem 'aws-sdk', '1.14.1'
gem 'slim', "2.0.0"
gem 'sinatra', '1.3.6', :require => nil
gem 'sidekiq', '2.12.1'

platform :ruby do
  group :development do
    gem 'better_errors','0.8.0'
    gem 'binding_of_caller','0.7.1'
  end
end
```

**Comment by MLauper** [comment]
@shevegen 
The problem arises when you import multiple large modules, that have many dependencies on their own. See [this Gemfile](https://github.com/puppetlabs/puppetlabs-dsc/blob/master/Gemfile) as an example for about 230 used Gems in one project.

@prcongithub 
Since HTTP 503 is a general error, your issue is either not related, or you actually are using more than 200 Gems. 
You should be able to resolve the issue by building the dependency tree locally. If you are using bundler, try using

`bundle install --full-index`

If this doesn't do it for you, you have an unrelated issue and should either post to Stackoverflow or if you think there is something wrong with rubygems.org, open another issue here.

**Comment by dwradcliffe** [comment]
> Is there a reason for the cap?

Yes. It's expensive for the server to compute the response and the more gems the longer it takes. We've found that 200 is about the threshold for when it is faster to download the full index compared to computing and transmitting the dependency api response.

**Comment by dwradcliffe** [comment]
I'm not able to reproduce the 503 errors mentioned above. If you pass more that 200 gems, you will get the appropriate error message. The 503s must have been a different problem, possibly a transient issue. If you have a reproducible case or see further issues please let us know.

Also worth noting that modern bundler versions will use the new index format, which does not use this endpoint.
