### ISSUE TITLE
/api/v1/versions/rubygem-rubygems-mirror/latest.json does not work

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems.org#1579]
The api call https://rubygems.org/api/v1/versions/rubygem-rubygems-mirror/latest.json does not return any version:

~~~
$ curl https://rubygems.org/api/v1/versions/rubygem-rubygems-mirror/latest.json
{"version":"unknown"}
~~~

The version should be "1.1.0" according to [[1]] if I am not mistaken.

[1]: https://rubygems.org/gems/rubygems-mirror

**Comment by simi** [comment]
I think you should use https://rubygems.org/api/v1/versions/rubygems-mirror/latest.json.

**Comment by dwradcliffe** [comment]
Yep @simi is correct. The gem in the original url does not exist.

**Comment by voxik** [comment]
Oh ... silly me ... sorry for the noise.

**Comment by voxik** [comment]
But I have one additional question, how to query for latest version of jruby-openssl?

https://rubygems.org/api/v1/versions/jruby-openssl/latest.json

vs

https://rubygems.org/gems/jruby-openssl

**Comment by segiddins** [comment]
It looks like it's returning the latest version of the ruby-platform gem

**Comment by voxik** [comment]
Yep, I think so.
