### ISSUE TITLE
Move lost account to new email address

### ISSUE THREAD

**Issue by kamstrup** [rubygems/rubygems.org#1581]
I seem to have got myself stuck between a rock and a hard place. I am the owner of this account https://rubygems.org/profiles/kamstrup, but it is tied to my old mikkelDOTkamstrupATxamarin.com email address. I have lost the password and no longer have access to that email address. Is there any chance I can have the account moved to my personal email mikkelDOTkamstrupATgmail.com?

If you have doubts about my authenticity you can verify that I am indeed the github account holder that my points to (eg. https://rubygems.org/gems/command_runner_ng points to my repo http://github.com/kamstrup/command_runner_ng).

**Comment by dwradcliffe** [comment]
Please submit a help issue: http://help.rubygems.org/discussion/new
