### ISSUE TITLE
Feature Request: Filter gems by most recent version date

### ISSUE THREAD

**Issue by georgeu2000** [rubygems/rubygems.org#1582]
Use Case: Recently I wanted to find a gem to do statistics. I went to [rubygems search](https://rubygems.org/search?utf8=%E2%9C%93&query=statistics) .

Although the gems are relevant, they probably won't work because most have not been updated in years.

So, the feature is a dropdown at the top right of the page that lets you filter by recency. Specifically, the latest version must be dated within 1 year (for example).

The dropdown options would be: 3 months, 6 months, 9 months, 1 year and 2 years.

I will be happy to do a PR, but didn't know if it would be accepted.

**Comment by sonalkr132** [comment]
Hi @georgeu2000 

You are in for a surprise :wink: . We already support(unofficially) features you requested. Set `new_search` cookie to `true` (`document.cookie = "new_search=true";`) and [search again](https://rubygems.org/search?utf8=%E2%9C%93&query=statistics). You can tinker with `updated:` field as per your need. Feel free to report any bugs you can find.
**NOTE**: [It is WIP](https://github.com/rubygems/rubygems.org/milestone/8).

**Comment by georgeu2000** [comment]
@sonalkr132 - I set `document.cookie = "new_search=true";` but did not see any difference. 

Is there any way I can help?

**Comment by sonalkr132** [comment]
[This code](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/searches_controller.rb#L13-L15) ensures that your search is performed using elasticsearch. Following is the page you should see:
![screenshot from 2017-03-21 07-09-09](https://cloud.githubusercontent.com/assets/7680662/24129043/f4a462ee-0e05-11e7-8df5-f73a9b577fc9.png)

Can you please try [this query](https://rubygems.org/search?query=statistics+AND+updated%3A%5B2017-02-19+TO+%2A%7D) after ensuring that your new_search cookie to true.

**Comment by sonalkr132** [comment]
> Is there any way I can help?

Yes! :bowing_man: You are welcome to review https://github.com/rubygems/rubygems.org/pull/1315. Let us know your opinion about using typehead.js or writing something of our own for autocompletion :speech_balloon:
We are yet to implement a help page for prefixes we support and an advanced search page. See https://github.com/rubygems/rubygems.org/pull/1312

**Comment by georgeu2000** [comment]
RE `typehead.js`, I don't know anything about Front End or JS. Having said that, their demo looks good and it works.

RE [#1315 ](https://github.com/rubygems/rubygems.org/pull/1315), LGTM. Seems like it is waiting for a rebase.

RE [#1312](https://github.com/rubygems/rubygems.org/pull/1312), I don't think anyone will figure out how to enter prefixes and do complex searches. So, the fewer the better. I will be happy to write a help page. Would it be a few simple examples?

**Comment by sonalkr132** [comment]
>  I will be happy to write a help page. Would it be a few simple examples?

[These examples](https://github.com/rubygems/rubygems.org/pull/455/files#diff-cf625a69da6ea404abe4b4c62202d1d9R1) seem fine. They would probably need a few modifications as per [current implementation](https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/rubygem_searchable.rb).

**Comment by simi** [comment]
@mslinn this is now visible by default (no custom cookie is needed). Do you have any idea how to make it more visible?

Maybe we can include date of latest release at the index page next to the total downloads and make it somehow highlighted when certain threshold is reached (like older than 2 years).

![latest-update](https://user-images.githubusercontent.com/193936/159269397-9a26acb8-ff3d-442a-979e-ea986906edbe.png)

Something similar is already implemented at ruby-toolbox.com.

![ruby-toolbox](https://user-images.githubusercontent.com/193936/159269695-c1cb440e-487c-4fe7-9fe8-7ecb5707a607.png)
