### ISSUE TITLE
tar file header (toc.dat)

### ISSUE THREAD

**Issue by UShan89** [rubygems/rubygems.org#1584]
Continued from #1583, 

I tried to download the tar file from the URL that gets echoed on the screen. Next, I use pg_restore instead of psql 

`pg_restore -c -U postgres -d rubygems -v "public_postgresql.tar" -W`
and get error from pg_restore 
`pg_restore: [tar archiver] could not find header for file "toc.dat" in tar archive`

I am on postgres95 and am using a mac

**Comment by dwradcliffe** [comment]
You need to extract the file first.
