### ISSUE TITLE
Stats: I can't page to "Next" set of pages from page 10

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/rubygems.org#1585]
The stats page is wonderful. It's paginated, too.

My problem is that on the 10th page, I couldn't use the "Next" link from will_paginate (?) to see the next set of Pages. The word "Next" was not a link.

This is a screenshot where I changed the `?page=` querystring parameter to 11 and the page displays items "101" and onwards.

<img width="1269" alt="screenshot 2017-03-16 08 57 12" src="https://cloud.githubusercontent.com/assets/211/23986856/9be8f300-0a26-11e7-9951-418ecdf2b3f4.png">

**Comment by sonalkr132** [comment]
Here is the pagination code in use:
```Ruby
paginate(page: @page, per_page: 10, total_entries: 100)
```
According to https://github.com/mislav/will_paginate/issues/316
> total_entries is only an override used to avoid the COUNT query, but doesn't affect the results returned from both SQL queries or Array pagination.

In other words, the observed behaviour is not a bug, it's a feature :joy:
I suppose we can check `@page` with a *conditional* :nauseated_face:

**Comment by olleolleolle** [comment]
Thanks for explaining this with the trade-off and docs quote. 

The reason I paged past the top pages was that they were almost only Rails-related. I wanted to see the "near the top" for inspiration and exploring the RubyGems ecosystem. This page doesn't try to do that. 

The bestgems website, which was linked in the Slack channel a while ago, fits my use case much better.  

The reported inconsistency of only making navigable the Top 100 is not an inconsistency. There is more data but that's irrelevant to this page. 

Cool, I'm closing this as explained.
