### ISSUE TITLE
Rubygems assets download link gives wrong filename in Safari

### ISSUE THREAD

**Issue by orta** [rubygems/rubygems.org#1600]
At the bottom of https://rubygems.org/pages/about

The link goes to`https://rubygems.org/logos.zip`, but the file Safari downloads is called "RubyGems Assets" with no filetype. I renamed it to a `.zip` and it extracted fine. Just somewhere Safari is generating a bad filename.

**Comment by segiddins** [comment]
issue is probable the `download="RubyGems Assets"`, since it doesn't have an extension
