### ISSUE TITLE
add note to password reset email about timeout

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1606]
Password reset links expire after 15 minutes. We should note that in the password reset email.

_Idea from http://help.rubygems.org/discussions/problems/26156-cant-reset-password_

**Comment by jvanbaarsen** [comment]
@dwradcliffe Does the `Starter` label has special meaning? Otherwise I can work on this?

**Comment by dwradcliffe** [comment]
It just means it's probably easier/smaller. Feel free to take it!
