### ISSUE TITLE
Move search api to ES

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1610]
The web frontend is now using ES for everyone. We should move the search API to use ES too.

**Comment by sonalkr132** [comment]
Search api delivers a [huge payload](https://github.com/rubygems/rubygems.org/blob/master/app/models/rubygem.rb#L136-L164). It has been [slow historically](https://github.com/rubygems/rubygems.org/issues/1256) for this very reason.
We don't have all that information stored in our es indexes. It doesn't seem meaningful that a search query should deliver such an elaborate response. IMHO, we should conform our search api response to that of our web response.
I understand this would be a breaking change, however, I believe we are only fixing an unintended behavior here.

**Comment by sonalkr132** [comment]
Alternatively, we can provide an `api/v2/search` which uses elasticsearch. At least [one person complained](https://github.com/rubygems/gems/issues/36), last time I made the benign change of [`text` responses to `plain`](https://github.com/rubygems/rubygems.org/pull/1524).
I would very much love to *fix* :speak_no_evil: the existing api but I am not sure about consequences.

**Comment by dwradcliffe** [comment]
Yes if we do remove this information we should add a v2 search endpoint and slowly deprecate the v1 search api.

That said I'm not totally sure we can't add this additional data to ES. I think ES can handle it just fine. Any opinions here? @arthurnn @bai

**Comment by bai** [comment]
Default ES document size is limited at 100MB via HTTP Content-Length and there's a hard limit in Lucene that's north of 2GB — so it will be _untrivial_ to hit those. From the top of my head it won't be hard for ES to handle those documents nor it will require a large cluster.
