### ISSUE TITLE
Feature Request: Get latest version for multiple gems at once

### ISSUE THREAD

**Issue by theflow** [rubygems/rubygems.org#1611]
Hi,

In order to lookup which gems are outdated it would be great if the latest version endpoint would support passing in multiple gem names instead of just a single gem. So either a completely new endpoint or something like this:

    curl https://rubygems.org/api/v1/versions/rails,rake,json/latest.json

If you think this a good idea I would love to take a stab myself at implementing it, but I wanted to ask first if it makes sense for the project.

thanks,
Florian

**Comment by dwradcliffe** [comment]
`bundle outdated` shows the gems that are outdated. Would that help you? If not, what API does that command use?

**Comment by theflow** [comment]
no, `bundle outdated` is not quite what I need.

I think it uses the source index to get the latest versions. It would be possible to use that, but it's quite heavy and not sure if that's considered a public API?

**Comment by colby-swandale** [comment]
Thanks for the suggestion but i don't think this should be implemented. This idea goes against the idea of a RESTful API and introduces a fair amount of complexity that we may not want to support as well.

I suggest instead that If you want to know the latest version for a set of rubygems that you just make a query for each gem.

**Comment by cheshire137** [comment]
I was hoping for a similar endpoint to the one described here, but one that would load the version info, particular version creation date, for a list of multiple gems and a specified version rather than just the latest version.

**Comment by simi** [comment]
@theflow @cheshire137 would you mind to explain on your usage? I do agree with @colby-swandale to keep REST API simple and based on individual resources (where possible). But maybe there is some interesting usecase to break this. :thinking:

**Comment by simi** [comment]
Looking at this again, I do agree with @colby-swandale, this is behind REST API common patterns. Using multiple requests is OK.
