### ISSUE TITLE
The 404 page for gems ("It will be mine. Oh yes.") is broken

### ISSUE THREAD

**Issue by jaredbeck** [rubygems/rubygems.org#1622]
Tried chrome and brave. Tried soft and hard refresh.

What happened to the cute treasure chest?

![rg404](https://cloud.githubusercontent.com/assets/380809/25858169/14cef7ae-34a9-11e7-89e5-f91b64e1926e.jpg)

Possibly broken by frontend work done in 2016, e.g. https://github.com/rubygems/rubygems.org/issues/1486

**Comment by dwradcliffe** [comment]
This was fixed in https://github.com/rubygems/rubygems.org/pull/1614 but it hasn't been deployed yet. It will be fixed later today.

**Comment by jaredbeck** [comment]
Thanks David. :heart:

**Comment by dwradcliffe** [comment]
And fixed!
