### ISSUE TITLE
limit search pagination (links) to 100 pages too

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1624]
Now that we limit search results to 100 pages we need to limit the pagination links to 100 pages as well.

Follow up from https://github.com/rubygems/rubygems.org/pull/1604

@sonalkr132

**Comment by hd719** [comment]
Hello can I work on this?

**Comment by sonalkr132** [comment]
Hi @hd719 :wave:
Checkout my proposed solution at #1632. If you can come up with a better solution, please feel free to send a PR :+1:

**Comment by sonalkr132** [comment]
Closed by #1624
