### ISSUE TITLE
Link to github compare on gem version page

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#1630]
To reward projects that track their releases with tags and to make diff navigation easier the version show page for example: 

https://rubygems.org/gems/cassandra-driver/versions/3.2.0

should link to the compare:

https://github.com/datastax/ruby-driver/compare/v3.1.0...v3.2.0

... now upgraders have a good reason to subscribe to gem updates and can easily see what changed.

This should work for the major projects out of the box ... and for everyone else it's an incentive to properly version tag their releases.

**Comment by shevegen** [comment]
I do not have anything against it in principle. It may be useful.

However had, not everyone is using github. So your suggestion would leave alone those who don't use github.

So the suggestion to it being an "incentive" can also mean to be a determent.

Again, I have nothing against the suggestion - I just do not think that your argument works in the way that you wrote it.

If we leave side your reasoning though then it could still be useful for github only probjects. In that case, it may be ok. But even then not everyone would want to have it, neither developers nor all users.

There is currently a "Homepage" link. Where should the link reside? Under Homepage? I guess the latter may be useful to know for dwradcliffe or whoever may want to add support to it (it would actually be easy if it is just a link alone; I am just not entirely sure whether all should have it per se).

**Comment by grosser** [comment]
The compare should only be shown if the homepage or source-code url are
github.com
It is supposed to be a `determent` against the practice of not tagging
releases (which is super helpful and simple with the bundler provided tasks)

**Comment by simi** [comment]
I like this idea, but I'm not sure if this is possible without coupling to 3rd party service.

I think it is **not** good idea to couple rubygems.org with GitHub directly and do some "guessing" based on metadata for gems.

Maybe it will be enough to introduce some kind of "releases_link" to [Linkset](https://github.com/rubygems/rubygems.org/blob/ce59a20491bea56638024fc425bc10cd701b4cf4/app/models/linkset.rb#L4) and show that somewhere. Authors will be able to link to [release page](https://github.com/datastax/ruby-driver/releases) for example.

There are also specialized services for purpose described in the first post (ex. https://gemnasium.com/) if I understand that well.

**Comment by grosser** [comment]
having a releases page in general might be a good idea ... maybe even with
a dynamic %{version} so it could link directly to
https://github.com/datastax/ruby-driver/releases/tag/v3.2.0 for example.

... if that is the release link the maybe we can add diff_url or so with
 `foo/bar/%{previous}..%{current}`

**Comment by simi** [comment]
You can update that release link manually in gemspec (or during gem build phase) to fit your needs having it updated on every gem push.

**Comment by grosser** [comment]
That would mean custom code for every project ... A static link would be
nicer ... And if we know it's customized for this version it could be shown
in the page and not the sidebar

**Comment by simi** [comment]
@grosser you need to fill in current linkset manually also.

**Comment by sonalkr132** [comment]
superseded by #1853
