### ISSUE TITLE
404 page pegs browser CPU

### ISSUE THREAD

**Issue by matthewd** [rubygems/rubygems.org#1635]
Steps to reproduce:

1. Look at local CPU graph, hovering near zero
2. Go to https://rubygems.org/404 (especially in Chrome)
3. Look at local CPU graph again, note at least one core pegged

Opening https://rubygems.org/images/sea_floor.svg directly has similar (though somewhat less dramatic) results.

Deleting the `<style>` element which defines the bounce animation drops CPU to zero, as one might expect.

I understand that people aren't generally going to spend a lot of time looking at that page, but I tend to have a lot of windows open and am careless about closing things I don't need -- but still prefer a non-toasty lap. :heart:

cc @nateberkopec / #1468

**Comment by nateberkopec** [comment]
*looks at 404 page*

*cpu fan slowing whirrs*

*wwhhhhhiIRRRRRRRRRRRRRR*

*laptop flies away, never to be seen again*

Taking a look, once I find my laptop again.

**Comment by dwradcliffe** [comment]
It's not 100% for me but enough that we should do something about it. Thanks for bringing this up @matthewd

**Comment by simi** [comment]
What about to temporarily disable that animation?

**Comment by nateberkopec** [comment]
Right, one option would be to make the animation ~3 seconds or so, rather than infinite.

I tried some various [null transform hacks](https://gist.github.com/roybarber/8406299) but none of them really make a dent in the CPU usage.

**Comment by shevegen** [comment]
You guys scared me - I am not clicking on that link above so I will never know what animation is there, until I'll be redirected ... :(
