### ISSUE TITLE
Just a comment about the new search-functionality

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1640]
Today, right now, I noticed a new information:

"Filter: Name (114) Description (432) Summary (359) Updated last week (5) Updated last month (17)"

When searching for gems.

In particular I was searching for .pdf files:

https://rubygems.org/search?utf8=%E2%9C%93&query=pdf

The new functionality is very useful in my opinion. I especially like the updated last week and updated last month part - that can help people when they try to estimate which one was the most active one.

This is just a little thank you post, sorry for that - feel free to close it at any time. :)

**Comment by sonalkr132** [comment]
It can do more. Check https://hackernoon.com/you-know-for-search-de62b6126a86
