### ISSUE TITLE
Multiple html elements with the same id

### ISSUE THREAD

**Issue by camachom** [rubygems/rubygems.org#1650]
Hello!

I found an html bug. This is one of my first contributions to open source, so please let me know your thoughts or critiques if you have any.

TL:DR There are multiple elements with the same id on the `index.html` page.

## Bug

If you're on `index.html`, the search bar in the navbar is set to `display:none` to avoid redundancy with the search bar being featured in the body.

This leads to some duplicate code:
```
# application.html.erb
<%= form_tag search_url, id: "main-search", class: search_form_class, method: :get do %>
  ...
  <%= submit_tag "⌕", id: "search_submit", name: nil, class: "header__search__icon" %>
<% end %>
```

and:

```
# index.html.erb
  <%= form_tag search_url, :id => "main-search", :method => :get do %>
    ...
    <%= submit_tag '⌕', :id => 'search_submit', :name => nil, :class => "home__search__icon" %>
  <% end %>
```

The issue is that despite the nav search bar being hidden, it's still in the DOM and both of the form_tags and submit_tags end up having the same id.

If you try to select the search form like this:

```javascript
document.getElementById('main-search')
```

You will actually get the hidden navbar search form instead of the visible one.

## Solution 1

I could not find any css or js that was actually using those ids. A simple solution would be to just remove them. If they need to be selected individually in the future, they should be appropriately labeled then.

## Solution 2

Make one of the ids more specific. Maybe changing the navbar search id to `main-search-navbar`.

**Comment by yhirano55** [comment]
+1

**Comment by dwradcliffe** [comment]
If we're not using the ids then let's just remove them (option 1). Thanks for finding this!

**Comment by camachom** [comment]
@dwradcliffe Awesome! Will do. I will double check nothing is using the ids, remove them and submit a PR.

**Comment by camachom** [comment]
After taking a careful look, the  `main-search` duplicate ids can be deleted without repercussion.

However, `search_submit`, which is also a duplicate, does appear in a couple of different places. It's actually duplicated on two routes:

In:
`application.html.erb`
`index.html.erb`

and
`application.html.erb`
`advanced.html.erb`

And lastly, it appears in some integration tests:

```ruby
# ./test/integration/search_test.rb

class SearchTest < SystemTest
  test "searching for a gem" do
    ...
    visit search_path

    fill_in "query"-, with: "LDAP"
    click_button "search_submit"
    ...
  end
```

Since this test is using the `search_path`, they mean to select the `search_submit` in the navbar. Deleting the id from the body of `index.html.erb` and `advanced.html.erb` should solve the problem.

Before submitting the PR, I wanted to make sure the changes did not affect the tests, but I can't get them to pass as they currently stand. I keep getting the following error:

```
Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/rubygems-test]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/rubygems-test]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```
I would love some help with this exception to get started on the PR.

**Comment by sonalkr132** [comment]
@camachom Did you install elasticsearch with x-pack? You might want to [disable security](https://www.elastic.co/guide/en/x-pack/current/security-settings.html#general-security-settings):
```
xpack.security.enabled: false`
```

**Comment by camachom** [comment]
@sonalkr132 thank you so much! I followed the instructions in the development setup that asked to pull the image using docker:
```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.1.2
```
I ended up adding it as an environmental variable to the command above:
```
-e 'xpack.security.enabled=false'
```
Maybe that should be the default for the development setup. What do you think?

**Comment by sonalkr132** [comment]
> Maybe that should be the default for the development setup. What do you think?

We shouldn't be installing anything other than elasticsearch. I will update it accordingly :+1: 
I am closing this as  #1654 is merged.
