### ISSUE TITLE
Consider adding a "most recent update" to rubygems.org

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1657]
Lately I looked at perl cpan:

  http://www.cpan.org/

They have a "Recent Uploads" section showing the ten most recent uploads (and a more link below).

I propose that rubygems.org also adds something similar, for new ruby gem updates, recently.

We can already see new gems like here:

https://twitter.com/rubygems?lang=en

This works ok but it's a bit verbose. A single entry per line would be nicer IMO, on the rubygems.org page itsef.

If you look at:

https://rubygems.org/

Perhaps it can be added to the right hand side, above or below the SECURITY link.

I assume that code that watches the most recent entries is already available so I hope that this issue is not too difficult to implement (IF people + the core maintainers of rubygems.org deem this ok). Thank you for reading - feel free to close this issue at any moment in time.

**Comment by sonalkr132** [comment]
hi @shevegen Did you check https://rubygems.org/news ?

**Comment by sonalkr132** [comment]
Feel free to open this if the link I provided above is not what you were looking for.
