### ISSUE TITLE
Weird search result (aka no result) - but the gem exists

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1662]
Is this to be expected?

Search URL:

  https://rubygems.org/search?utf8=%E2%9C%93&query=term-ans

That is, search for "term-ans".

No result turns up.

The gem I was looking for does exist though:

  https://rubygems.org/gems/term-ansicolor

I would have assumed that a sub-string would match.

Is the above expected behaviour or is it a bug?

**Comment by shevegen** [comment]
Interestingly, this query finds term-ansicolor:

https://rubygems.org/search?utf8=%E2%9C%93&query=term-ansi

Whereas if you chop off one character at the end:

https://rubygems.org/search?utf8=%E2%9C%93&query=term-ans

It says no gem is found. Can it be that there is some code that checks in an awkward manner based on the amount of input character or some possible query, which then may lead to some wrong result?

**Comment by TamerShlash** [comment]
Looking at the source code, the search functionality uses ElasticSearch:
https://github.com/rubygems/rubygems.org/blob/421e841adc3f97c9e1b25accc7faa3ae1036d7c2/app/models/concerns/rubygem_searchable.rb#L52-L62

So it's either a problem with the elastic search query constructed in `elastic_search` method, or in ElasticSearch itself.

**Comment by colby-swandale** [comment]
Thanks for reporting this, yes this search should be listing the term-ansicolor gem in the results

**Comment by dwradcliffe** [comment]
This is related to how elasticsearch indexes the gem names. There's a spectrum of too little to too much but I'm sure we can tweak it a bit.

**Comment by aditya-pr** [comment]
sure :+1: have at it.

**Comment by sonalkr132** [comment]
sure :+1: have at it.

**Comment by sghosh968** [comment]
Okay, thanks for the heads up @sonalkr132 .
