### ISSUE TITLE
Statistics - Perhaps the licence usage for the available gems could be shown, on rubygems.org

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1670]
Hello,

Some time ago, in rubygems, some code was added to check whether the license tag in use in .gemspec files, conforms to some list of licenses.

I think the idea was to get people to write the license more specifically, without having to make any second guesses. (I don't remember the URL off-hand, but I guess many of you know to which list/change I may refer here.)

Some time ago, I think it was on github or some git-related stats, that showed how many projects would use the MIT licence or some GPL variant and so forth.

Now I was thinking - may it be useful to also have something like this for rubygems.org?

I assume that you want to keep https://rubygems.org/stats small-ish, but perhaps there could be some additional page that could show some lesser-queried statistics about gem projects hosted on rubygems.org.

The code should not be too difficult; I assume that it would go along the lines of:

a) iterate over the list of available .gem files
b) query and obtain the licence in use
c) keep track of it via a simple hash
d) convert that hash into a viewable entry ... in the simplest way, it could be a simple HTML table.

Not every licence has to be shown, perhaps keep a threshold of +0.1% or something like that, so the smaller licences aren't shown.

I think quite a few people may be interested in knowing about this. I assume that MIT dominates, but it would be interesting to see by how much.

This licence-query does not have to be run every day either;, a weekly cron job should suffice fine to update the information, with a tag on the sub-webpage to show when it was last updated. I am not sure if anyone else wants this though or not.

**Comment by dwradcliffe** [comment]
The license is already parsed out and stored in our database. This is something that should and can be indexed in elasticsearch and exposed via the search interface.

**Comment by sonalkr132** [comment]
licenses field is indexed in elasticsearch and can be searched using a query like `licenses: MIT`. The field is returned on versions or search API endpoints.
