### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by ciembor** [rubygems/rubygems.org#1672]
If I create yml with Polish translation, would it be merged, or there is no need for yet another translation?

**Comment by dwradcliffe** [comment]
Sure! We usually like to get one or two other reviews of translations before we merge so if you could ping a few people who could help review on your PR that would help. Thanks!

**Comment by colby-swandale** [comment]
I'm closing this for now as this looks answered but feel free to re-open it if you have any questions.
