### ISSUE TITLE
Suggested Version Constraints Not Exposed in API

### ISSUE THREAD

**Issue by mvastola** [rubygems/rubygems.org#1673]
So maybe I'm missing something and this isn't even really a setting, but for different gems there are different version constraints suggested for use when adding the gem to your `Gemfile`. 

Presumably, this coincides with how the owner of the gem releases breaking changes and is therefore important information to set/get when adding a gem to a ruby project. This, however, isn't exposed at --  for instance -- https://rubygems.org/api/v1/gems/rails.json (which shows the version constraints needed for dependencies, but not for the gem queried).

If what I'm saying isn't clear, for instance, the Gemfile texbox contains: 
- For `rails`: `gem 'rails', '~> 5.1', '>= 5.1.4'`
- For `rake`: `gem 'rake', '~> 12.1'`
- For `mysql2`: `gem 'mysql2', '~> 0.4.9'`

Unless these are completely random, which I doubt, they must come from somewhere, but I'm not exactly sure as to where.

**Comment by mvastola** [comment]
Just wanted to add that I just noticed `rubocop` in particular, [in their README.md](https://github.com/bbatsov/rubocop/blob/0f319cb7968b902d05301865163750f2ce32f8ac/README.md#installation) explicitly encourages a certain level of specificity with regard to the version constraint used to include their gem in `Gemfile`s, saying:

> RuboCop's development is moving at a very rapid pace and there are often backward-incompatible changes between minor releases (since we haven't reached version 1.0 yet). To prevent an unwanted RuboCop update you might want to use a conservative version locking in your `Gemfile`:
> ```ruby 
> gem 'rubocop', '~> 0.50.0', require: false
> ```

So obviously this level of suggested 'conservatism' (as they put it) is something that at least one very popular gem wishes to publicize.

**Comment by colby-swandale** [comment]
RubyGems.org suggests using the pessimistic version operator when adding new gems as it's a safe default to prevent updating a version that introduces breaking changes. However RubyGems supports a variety of other operators which have their own advantages and disadvantages depending on the situation that people can choose from.

You can read more information about version constraints here: http://guides.rubygems.org/patterns/#semantic-versioning

**Comment by mvastola** [comment]
Right, so I guess what I'm saying is I can't see (in the API) where the versioning policy gets set or can be fetched for a specific gem.

**Comment by colby-swandale** [comment]
There is no policy or attribute that can be set or fetched,  it's just a suggestion we recommend.

**Comment by mvastola** [comment]
Then how do some gems have different policies (see the examples above)?

**Comment by colby-swandale** [comment]
It suggests different version constraints depending on the current version. See #870 for more information

**Comment by mvastola** [comment]
Ahh. That explains it. Will close this then. 

I personally think it might be a good idea to let authors choose their own policy.. many use a different one; `~> 5.1` obviously isn't the ideal constraint to use for `rails`. But I'll leave that feature request up to a gem author to make.
