### ISSUE TITLE
Unscubribe/Cancel for monitored (subscribe) gems that were yanked?

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1677]
Hello ruby-people.

It's me again. :)

This time an easier report, I think.

Situation: If we or someone else yank(s) a gem, so that it is completely gone, the menu
interface on the right side of the gem's homepage on rubygems.org, such as including
the various sublinks "Homepage", "Documentation", "Download", "Badge" or "Subscribe",
disappears. That is, it is no longer shown when the gem is yanked.

Example:

https://rubygems.org/gems/beautiful_url

(Actually I just noticed the "count down" there, just now, in how many days remain;
nice! I did not notice that yet, great work) 

Anyway - that the right menu part disappears, is of course ok when a gem is yanked;
after all the project is, more or less, gone. So subscribing makes not a lot of sense.
For most projects at the least; in theory, people can of course push new gems to
that namespace. But I think that most people who want to yank their old gems 
away, they do not want to be associated with that namespace and it is fine if
others use it. (In my case, I think I used to have many tiny gems, such as I think
150 gems or so; I am now down to perhaps 125 or so and this will continue to
dwindle, largely because I integrate the functionality mostly into gems of medium
or larger size - it is just easier to handle and maintain this for me if I do not have
that many gems).

However had, I noticed just very recently, that subscriptions, aka via the  "Subscribe"
link, will still appear in the list of the user's subscription even if the gem is yanked.
This may be because the display there happens via a cache or something, but I
think that even then, for yanked gems, perhaps showing the cache of subscriptions
isn't ... that useful. Since the gem is gone. Nonetheless, I think that my suggestion
may still make some sense here, because people may want to be able to unsubscribe
still, and not show such a gem at all - and this possibility is, as far as I am aware, 
right now not possible. 

I do not see any simple way to cancel a subscription for a removed gem; at the
least not via the "Subscribe" link, because that one is no longer shown.

This is really a very minor issue, mostly just cosmetic but on the bright side, if
it is minor, I think fixing it would also be minor.

I suggest two ways to solve this:

(1) The simpler one may be to automatically cancel a subscription
if a gem is yanked. The advantage is that this should be trivial
to add, since the code is already there in the "Subscribe" link,
right?

This may already be the case, I have no idea because I do not see
a way to query to which gems I am subscribed, but I think that 
this is NOT yet the case, because inactive, yanked gems appear in
the listing of subscribed gems. 

Specifically, if you go to this link:

https://rubygems.org/dashboard

You will see on the right side a listing of "Subscriptions", that is, on
gems subscribed. And there I see also the gem that was yanked 
away. This is why I think that the code does not yet check whether
a gem has been completely removed. If I am wrong then please do
feel free to close this issue request here.

The disadvantage of auto-canceling a gem that you subscribed to,
may be that not every user may want to have this auto-cancel situation.

But we could reason that "if the gem is completely yanked, subscribing to
it does not make a lot of sense anymore, anyway, since no new updates may
happen" - for most gems. This would be valid perhaps in 95% of the cases or
so or even higher. So I propose (1), mostly due to it being so trivial to
implement. It may not be always the right choice but I think for most people,
this option will be perfectly fine.

(2) However had, there may be users may also want to control on their
own perhaps. I can think of a few use cases ... perhaps they may
want to monitor the namespace still, to see if someone else takes
the namespace or a new project may go there (may be rare, but who
knows). Or perhaps they know that a gem was completely yanked, but
is still being worked on, like in a rewrite (this is actually the
case for a very few gems that I am writing on; I intend to upload a
few more of them lateron, but no idea when, may take more than 
4 months, although also perhaps in another namespace. This may be
a very rare use case, admittedly so, but I am just trying to find possibilities
for use cases where a subscription may still be useful, even though the
old gem is yanked away already).

So for these reasons and more, option (2) here, I suggest that, if a
gem is completely yanked BUT a user was subscribed, to still show the
"Subscribe" link, or perhaps simpler, make that text "Unsubscribe"
instead, with a pop-up hover message aka "If you wish to Unscribe from
this removed gem, then click on this link". And the action would be 
already existing, that is, via the subscribe/unsubscribe mechanism
that already exists. So this should also be quite trivial, the code could
be re-used from the Unsubscribe action.

However had, I favour Option (1) because this will probably cover most 
use cases and should be a lot less work to implement/add, since it is
an action that, I think, goes into very few lines of ruby code:

    if gem_has_been_yanked_away?
      unsubscribe(:name_of_gem) # This is really just pseudo-code...

Thanks for reading!

**Comment by sonalkr132** [comment]
we do show unsubscribe link on gems which has been yanked. check https://github.com/rubygems/rubygems.org/blob/master/app/views/rubygems/show_yanked.html.erb#L15
