### ISSUE TITLE
Reserved gem names, and gem owner's still having gems in their listing that are of the same name: example, the gem called "ruby"

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1679]
Hello rubygem team,

A tiny "issue", mostly just cosmetic; not sure if it is worth reporting
but I guess it is better to report it, than not even mention it.

The webpage rubygems.org has some reserved names; an example for such
a reserved name is "ruby". There are other names too... I believe it was
sonkal or someone who added some list of reserved names to some older
github issue report here. But anyway.

For people who want to "test" this and see how this looks, here is the
URL to one such page

    https://rubygems.org/gems/ruby

The generic description there states:

"This namespace is reserved by rubygems.org."

So far this is perfectly fine. How did I discover the above, though?

That's somewhat curious, at the least to me. I was looking at zenspider's
rubygems.org page, due to minitest actually, at:

    https://rubygems.org/profiles/zenspider

And there, if you scroll down a bit, you can see an entry called:

"ruby 0.1.0 108,915 Downloads"

This of course does not make a lot of sense if it is a reserved namespace 
now, right? People can not push towards that namespace as far as I was
able to gather. Now clicking on that link will lead to the above reserved
namespace, so this is a bit ... well, unexpected perhaps? At the least for
those people who did not yet know about reserved namespaces on rubygems.org.
I myself knew about namespaces, but most other gems simply show you that
gem-homepage of that particular project if you click on it. In other words, I
did not expect to be directed towards a "this is a reserved name" page. :)

Oddly enough, the "versions/" URL still works there and leads to a different
(!) result, as can be seen here:

    https://rubygems.org/gems/ruby/versions/0.1.0

ruby!

So ... is the namespace really reserved? :)

I guess the "versions/" query can "bypass" the check for reserved namespaces
and was perhaps not fully intended.

The author of the above page is listed as John Mair (banisterfiend) though,
no mention of zenspider, which is also a bit confusing. Perhaps zenspider
was de-registered prior to that? But then, if the versions gem mentions
it, why is it listed at zenspider's page? A bit confusing to me ... perhaps
there is a non-obvious reason, but this is not the important part anyway,
just a curious thing IMO.

I can not say how to best resolve the above because I think this depends
on the policy that the rubygems.org team has in regards to gems.

The "reserved names" came at a later time, so the above gems could be
considered "legacy" gems by now; to be honest, I think if you look at the
gem "ruby", it is also more of a pun by banister rather than meant to be a
a "real" gem. People do all sorts of weird stuff with namespaces ... may
not have been a wrong decision to reserve some of the names, if only to 
reduce the confusion a little bit. ;)

I will propose two things now in regards to the above situation but again,
I am not sure if these are good proposals - I just want to mention them:

(1) I believe that gems that were already reserved by the rubygems team,
should be automatically removed/de-registered from the user's profile.

So, in the above example, the rubygems-webpage by zenspider but also other
ruby hackers registered at rubygems.org, it should no longer be shown that
such a gem, like the "ruby" gem, exists there.

The amount of downloads can be retained in the total count to the top right,
since it was true in the past that the gem was download. And I guess some
people enjoy having a higher download count (it may motivate people, which
may be especially useful for newcomers; perhaps not so much for oldtimers
that already have lots of gems and lots of downloads; but I just wanted to
mention that, too, since I like the download count).

There may be a small amount of people who may still want to download the old,
same-named gems like that, I have no idea. Would people really want to download
the "ruby" gem? Most probably do not want to. Plus, they could always put
it onto github anyway, so not really necessary to keep reserved gems on
rubygems.org.

But some people may want to have a look at older gems at rubygems.org? Well,
in this case, my additional proposal here is that, rather than delete these
gems right away, to perhaps move them to some "de-registered" directory or
so. legacy_gems/ or reserved_name_gems/ or some name like that.

Then such gems may be reserved and be kept there in this directory. I am
not sure if that is worth it, I guess it depends on how many such gems 
that are now reserved, have become unavailable. The amount may be really
small ...

But if there are some gems, and the rubygems.org team wants to keep them
as backup-archive just for whatever reason, well - they could be kept 
there for perhaps 10 years or so, until really nobody ever asked for
them. And then delete them. (Or perhaps delete them right away, which
may be much simpler altogether; the reason why I do not propose it
so easily is because there may indeed be other people who want to have
a look at these gems. Not me, but others perhaps.)

I guess if nobody asks in like 10 years, nobody really wanted them
anyway. But in the case someone asks, one could point them to that 
directory and perhaps add a simple ftp-like listing towards that 
directory. Actually, come to think about it, this may also be combined
with "gems that were completely yanked away" ... but I am not sure
if it is good to have that. Or worth the time investment - I am just
mentioning it for the sake of ... mentioning it. :)

I myself try to keep my gems up to date, or remove them when I no longer
maintain them or try to find other people who may want to maintain 
them - whatever. Freeing the namespace up for other people to use is
fine by me. (I guess most people who have gems that were not updated
in many years, are completely inactive anyway. One could call them
orphaned or semi-orphaned gems perhaps ...)

Now to the other suggestion:

(2) In cases such as the above, where "versions/" still provides old
versions of gems that were not yet reserved, such as the situation
with banister above and the "ruby" gem, I am not quite sure how to
best resolve this.

The simple approach may be to not only re-register these gems altogether,
but also to completely remove them; or, as written in (1), to move them
into that new directory where such legacy gems could be retained.

Then the above may lead to some redirect page, which could have something
like this as text or a similar wording, perhaps shorter:

"There may have been gems that were written by other people, whose names
have been considered problematic, such as 'ruby' or [xyz].

These gems are no longer available at the individual author's page,
but instead, they are kept in an archive, which can be accessed at
this URL:

  INSERT URL HERE

"

The above could be kept as a minimal interface, just a simple directory
listing like in ftp may be enough for the archives of old heroes, I
mean, archives of old gems that have a reserved namespace.

On a side note, perhaps it may also be useful to be able to query
which namespaces are reserved AND/OR to show that in a link to some
page, where one entry-per-line could display it. But this is also a
side issue, feel free to ignore that - the more important question
is how the rubygems.org team (a) regards reserved gems, (b) whether
these should be shown at the gem owner's page even though they can
no longer easily downloaded and (c) whether the "versions/" URL
query is a bug or a feature. I have no idea myself but I am sure
someone else may know or give better answers to the above
questions. :) 

I hope the above is not too convoluted or too confusing, even though
it is a bit long.

It's a really tiny issue in the end. But in the event that someone
is perhaps bored and wants to have a look, well, there you go! :)

Thanks for reading - do feel free to close this issue at any moment
in time!

**Comment by colby-swandale** [comment]
The gems using the reserved namespaces are intended to be removed but we just have not gotten around to that task yet.

**Comment by colby-swandale** [comment]
I'm closing this for now. if you have any more questions you're more then welcome to open a new issue.
