### ISSUE TITLE
Minor glitch when showing popular gems e. g. URL such as: https://rubygems.org/news/popular?page=7

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1682]
Hello rubygems.org maintainers,

Have a look at this URL for showing **popular gems**:

https://rubygems.org/news/popular?page=7

In case it changes, it shows:

"Displaying gems 61 - 62 of 100 in total"

Now go to the next page:

https://rubygems.org/news/popular?page=8

It says:

"Displaying gems 71 - 78 of 100 in total"

Is there a reason why it shows only two gems in one case, but 7 or
8 in the other example?

It seems to me as if the listing should be consecutive, e. g.
60 to 69, then 70 to 79. Perhaps I am missing something but
to me it looks like an (semi-arbitrary?) bug right now. Anyway,
just reporting in case it is a bug - feel free to close this issue
at any moment in time. The feature seems to be new or at
the least I have not noticed it some months ago, so kudos for
whoever implemented this - I think it's nice. It also took me a
while to notice the "News" entry there to have a look at new 
gems. :)

**Comment by mjankowski** [comment]
If anyone wants to look at this - I think the interaction between eager loading via `includes` and the other usages of `latest_version` and `gem_download` are a good place to start.

**Comment by johnfrancismccann** [comment]
This bug can also appear with [items in the news section](https://web.archive.org/web/20191119222140/https://rubygems.org/news).

**Comment by sonalkr132** [comment]
closed by #2244
