### ISSUE TITLE
Wrong tzinfo dependency mentioned for rufus-scheduler

### ISSUE THREAD

**Issue by gagan93jtg** [rubygems/rubygems.org#1687]
[Here](https://rubygems.org/gems/rufus-scheduler/versions/3.0.0) it is mentioned that rufus-scheduler v3.0.0 needs tzinfo >=0 but going through the codebase of rufus-scheduler for v3.0.0, it is visible that rufus-scheduler uses code from tzinfo >= v1.0.0 and the same code is not present in tzinfo v0.x.x.  
The class which bothers me is` TZInfo::TransitionDataTimezoneInfo`

**Comment by colby-swandale** [comment]
This is an issue for the gem authors and not rubygems.org itself. I suggest you raise the issue with them.
