### ISSUE TITLE
Feature Request: index action for `versions` endpoint

### ISSUE THREAD

**Issue by shanecav84** [rubygems/rubygems.org#1689]
I'd like to be able to access version information for multiple gems at once. The endpoint would look like: `/api/v1/versions?gems=[COMMA DELIMITED GEM NAMES]`, similar to the `dependencies` endpoint.

I'd be happy to put a PR together for this if I can get the go-ahead.

**Comment by shanecav84** [comment]
*bump*

**Comment by colby-swandale** [comment]
What's the use case for this? Why does making a request to `/api/v1/versions` not fulfill your needs?

**Comment by shanecav84** [comment]
The use case is checking version information for a Gemfile full of gems. I'm using `/api/v1/versions` currently, but I'd like the batch action for performance.
