### ISSUE TITLE
500 error returned when an invalid gem date is used

### ISSUE THREAD

**Issue by clandry94** [rubygems/rubygems.org#1690]
### Problem
A gemspec with `gem.date` being an impossible year such as 1000 responds with a 500 error from the api on `gem push`. Below is the verbose output on an affected push:

```
$ gem push --verbose fanciful-0.0.1.gem 
GET https://api.rubygems.org/latest_specs.4.8.gz 
304 Not Modified 
Pushing gem to https://rubygems.org... 
POST https://rubygems.org/api/v1/gems 
500 Internal Server Error 
There was a problem saving your gem. Please try again
```

### Reproduction Steps
1. Set `gem.date = %q{1017-11-09}` in a Gemspec
2. Try to push the gem to https://RubyGems.org

### Solution
@dwradcliffe replied to my post on the [help forums](http://help.rubygems.org/discussions/problems/28678-500-internal-server-error-when-pushing-a-gem) that we should probably return a 4xx error instead. 

I haven't tested it, but this likely happens when other fields are invalid as well. Perhaps we can respond with a 400 Bad Request as well as which gemspec fields have an error in them? If this sounds good, I can open up a PR for this.

**Comment by dwradcliffe** [comment]
Full report at https://app.honeybadger.io/projects/40972/faults/35413468

Error for this one was:
`ArgumentError: year too big to marshal: 1017 UTC`

**Comment by shevegen** [comment]
Would it help if gem itself would check for correct values including proper years?
