### ISSUE TITLE
Rubygems.org hiccups - in this context, via "gem yank"ing several old gems on the commandline

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#1694]
Hello rubygems.org team,

Some time ago, I remember another issue report by someone who has had problems with unicorn at rubygems.org. And some failure message. I also noticed something similar, that is, some problems,
but in another context. So this could perhaps be related in one way or another.

I just noticed it right now, at european time:  26.11.2017 (dd.mm.yyyy notation, sunday), at 20:32:53 o'clock (that should be +8 pm or something... I am so bad at  converting pm/am notation into 24 hours but I guess you can see that only less than 3 hours are left before it will be the next day, Monday).

I was trying to remove some old gems, from my cookbooks gem.

I use an alias here, "gemyank" which is ... "gem yank" :D

The strange thing is that I SOMETIMES get an error, but sometimes
not. It is almost semi-random; but when I DID get an error, and then
tried to manually view it at the usual URL (for example
https://rubygems.org/gems/cookbooks/versions) then I ALSO got
an error on that homepage; and on the commandline, I strangely
enough get a lot of HTML output, which confuses me. The next
example shows that ... all "gemyank cookbooks" line I used in the
commandline.

Starting next:

-----------
```
gemyank cookbooks --version 0.0.1073  #  November 15, 2017 (827 KB)

Yanking gem from https://rubygems.org...

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <!--[if IE 7]>
      <link href="/stylesheets/ie7.css" media="screen" rel="stylesheet" type="text/css" />
    <![endif]-->
    <title>Unicorn! | RubyGems.org</title>
  </head>
  <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <div style="margin-right: auto; margin-left: auto; width: 90%; max-width: 940px;">
      <div style="padding-top: 60px; position: relative;">
        <object height="530" type="image/svg+xml" alt="503 error" style="width: 100%;" data="/images/sea_level.svg"></object>
      </div>
      <div style="margin-right: auto; margin-bottom: 120px; margin-left: auto; max-width: 680px; text-align: center;">
        <h1 style="margin-top: 25px; margin-bottom: 8px; font-weight: 200; font-size: 60px; ">Unicorn!</h1>
        <p style="font-weight: 300; font-size: 18px; line-height: 1.66; ">We are having a bad problem and the app server will not talk to us.</p>
        <a href="/" style="font-weight: 300; font-size: 18px; line-height: 1.66;  text-decoration: none; color: #e9573f;">Back to RubyGems.org</a>
      </div>
    </div>
  </body>
</html>

      
gemyank cookbooks --version 0.0.1072  #  November 15, 2017 (827 KB)
Yanking gem from https://rubygems.org...
Successfully deleted gem: cookbooks (0.0.1072)
gemyank cookbooks --version 0.0.1071  #  November 13, 2017 (826 KB)
Yanking gem from https://rubygems.org...
Successfully deleted gem: cookbooks (0.0.1071)
gemyank cookbooks --version 0.0.1070  #  November 13, 2017 (826 KB)
Yanking gem from https://rubygems.org...
```
-----------

So as you can perhaps see, the commands after the first one work fine.

I do not know the code so I can not tell you if all behaved correctly or 
not, but I believe that the html output above, is different from the 
other results starting with "Yanking gem from https..."

I hope that this can somehow be of little help to anyone who has more
knowledge about this seemingly semi-random hiccups. I do not know
how to easily reproduce them, but I can tell you that this literally happens
every time I batch-yank several gems, say 20 at once or so. Perhaps
there is some cool-down phase ... next time, I will perhaps try to use
"sleep 5" or so before the next gem yank command, just to see if this
makes any difference.

Please do feel free to close this issue at any moment in time; it is purely
meant to provide a bit more information - perhaps it is related to the
other issue report by someone else about unicorn being a bit strange
at times. It usually works again after a few seconds or at worst a very
few minutes. I am of course not sure if this issue is related to the other
one, but both have in common that unicorn has problems and a 404
page is displayed instead (I think; next time I perhaps also make a 
screenshot).

**Comment by shevegen** [comment]
I just got another hiccup when I was yanking another gem (old cookbooks gem).

When I tried to look at another project of mine, diamond_shell, I suddenly got
a unicorn error again. And on the commandline:


/Depot/j/gemyank cookbooks --version 0.0.1089   # November 28, 2017 (835 KB)
Yanking gem from https://rubygems.org...
Successfully deleted gem: cookbooks (0.0.1089)
/Depot/j/gemyank cookbooks --version 0.0.1088   # November 27, 2017 (834 KB)
Yanking gem from https://rubygems.org...

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    
    <title>Unicorn! | RubyGems.org</title>
  </head>
  <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <div style="margin-right: auto; margin-left: auto; width: 90%; max-width: 940px;">
      <div style="padding-top: 60px; position: relative;">
        <object height="530" type="image/svg+xml" alt="503 error" style="width: 100%;" data="/images/sea_level.svg"></object>
      </div>
      <div style="margin-right: auto; margin-bottom: 120px; margin-left: auto; max-width: 680px; text-align: center;">
        <h1 style="margin-top: 25px; margin-bottom: 8px; font-weight: 200; font-size: 60px; ">Unicorn!</h1>
        <p style="font-weight: 300; font-size: 18px; line-height: 1.66; ">We are having a bad problem and the app server will not talk to us.</p>
        <a href="/" style="font-weight: 300; font-size: 18px; line-height: 1.66;  text-decoration: none; color: #e9573f;">Back to RubyGems.org</a>
      </div>
    </div>
  </body>
</html>

I can not prove anything but I am beginning to believe that yanking a gem
may take quite some resources and put stress on rubygems.org itself
perhaps? If so, perhaps it may be better to just register that the user
wants to get rid of a gem, and then, when it is more convenient for
unicorn or the whole gem infrastructure, to delete the gem?

The first some removals of old gems releases, from the commandline,
work fine. At some point though, I then suddenly get that weird long
HTML output instead - and although I can not be absolutely sure, 
this is also at a time when I am more likely to see these unicorn 
error pages. Not sure if this is of any help but perhaps it may be
of help eventually. :)

**Comment by shevegen** [comment]
Actually, come to think about it, perhaps gem itself should not 
return a HTML page on the commandline in the first place,
and instead should return just some error message or 
warning.

I will report the latter one to rubygems gem maintainers.

**Comment by sonalkr132** [comment]
Sorry about delay in response here. I agree that `gem yank` shouldn't show html output for 502 response, however it bit difficult to fix it on server side. It would be much easier if client could check for response code and layed out appropriate error message.
Adding `sleep` between consecutive yank commands would definitely help.
