### ISSUE TITLE
Fastly cache not being invalidated

### ISSUE THREAD

**Issue by matthewd** [rubygems/rubygems.org#1698]
I just ran the following two commands locally:

```
tango:~% curl -I -X GET https://rubygems.org/versions\?1
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; script-src 'self' https://secure.gaug.es; style-src 'self' https://fonts.googleapis.com; img-src 'self' https://secure.gaug.es https://gravatar.com https://secure.gravatar.com; font-src 'self' https://fonts.gstatic.com; connect-src https://s3-us-west-2.amazonaws.com/rubygems-dumps/; frame-src https://ghbtns.com
ETag: "f9138146c74d6e6a979e9b03724464f5"
Cache-Control: max-age=60, public
X-Request-Id: 3e554f68-36dc-4ac7-bd6a-a78b719a3009
X-Runtime: 1.205320
Strict-Transport-Security: max-age=0
X-UA-Compatible: IE=Edge,chrome=1
X-Backend: F_Rails 54.186.104.15:443
Content-Length: 15699885
Accept-Ranges: bytes
Date: Sat, 02 Dec 2017 05:05:42 GMT
Via: 1.1 varnish
Age: 10
Connection: keep-alive
X-Served-By: cache-mel6520-MEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1512191130.402777,VS0,VE11598
Vary: Accept-Encoding,Fastly-SSL
Server: RubyGems.org

tango:~% curl -I -X GET https://rubygems.org/versions
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; script-src 'self' https://secure.gaug.es; style-src 'self' https://fonts.googleapis.com; img-src 'self' https://secure.gaug.es https://gravatar.com https://secure.gravatar.com; font-src 'self' https://fonts.gstatic.com; connect-src https://s3-us-west-2.amazonaws.com/rubygems-dumps/; frame-src https://ghbtns.com
ETag: "c99bd4f10b9ac9a9ededdcee58f64566"
Cache-Control: max-age=60, public
X-Request-Id: e7636a23-d794-4d04-87f5-6158557a2252
X-Runtime: 1.255091
Strict-Transport-Security: max-age=0
X-UA-Compatible: IE=Edge,chrome=1
X-Backend: F_Rails 54.186.104.15:443
Content-Length: 15699838
Accept-Ranges: bytes
Date: Sat, 02 Dec 2017 05:05:45 GMT
Via: 1.1 varnish
Age: 957
Connection: keep-alive
X-Served-By: cache-mel6525-MEL
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1512191146.729913,VS0,VE25
Vary: Accept-Encoding,Fastly-SSL
Server: RubyGems.org
```

The first one, bypassing the cache because of the `?1`, gives an up-to-date response of length 15699885. The second one uses the proper `/versions` URL, and thus provides a cached response: a 15-minute-old version of length 15699838.

From what I've seen in by brief exploration, Fastly is consistently retaining the cached response for the full hour [it's allocated](https://github.com/rubygems/rubygems.org/blob/7d3826c698c9840e22adf05321d6bd60dfcbf83d/app/controllers/api/compact_index_controller.rb#L29). But while that'd be fine in theory if no releases were occuring, in practice, [it's not](https://github.com/rubygems/rubygems.org/blob/421b8b746374bb1c97d41bc1cfc581661a9c35f7/app/models/pusher.rb#L108) [supposed to](https://github.com/rubygems/rubygems.org/blob/38f5e73d124e97f2b8ed5bc9c3758f5677176715/lib/gem_cache_purger.rb#L10) [do that](https://github.com/rubygems/rubygems.org/blob/38f5e73d124e97f2b8ed5bc9c3758f5677176715/lib/fastly.rb#L10). :confused:

**Comment by matthewd** [comment]
I've worked out that this is because I'm talking to `https://rubygems.org/`, but the invalidation is for `https://index.rubygems.org/`.

I guess I'm missing a protocol step to get from the user-supplied remote URL to the one I should actually talk to?

**Comment by indirect** [comment]
@matthewd there isn't a protocol step, there's just a hard-coded exception in the compact index client for `rubygems.org` itself to always use `index.rubygems.org`. The original webapp serving the compact index was not this Rails app, and we used the subdomain as the way to swap out which app served the requests without any changes in the client. It's probably worth cleaning up, but we'll need to keep the existing endpoint live until the current versions of Bundler and RubyGems reach EOL.

I'm going to close this ticket, since you seem to have figured out the place to look for up-to-date gem metadata, but feel free to continue this discussion if there's anything I've missed.

**Comment by matthewd** [comment]
> there's just a hard-coded exception in the compact index client for `rubygems.org` itself to always use `index.rubygems.org`

Ah okay, thanks.

> It's probably worth cleaning up

Does that suggest my original complaint might still be valid? i.e., that the Fastly invalidations should be applied to both hostnames, so future versions can safely drop the exception?
