### ISSUE TITLE
[BROWSER-DISPLAY] Display of the version number on the rubygems.org webpage

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1699]
I just noticed that the version string is a bit hard to read on my computer (and my bad eyesight).

Take the prawns gem at:

https://rubygems.org/gems/prawn

"prawn" is easy to read - black on white background, and ok-size.

Then there is "Versions:" which is also ok to read but a bit more difficult.

Below the "versions:" string are several versions of prawn. 
2.2.2 and 2.2.1 and so forth. These are also ok to read - black on
white background. The default font size on my computer is a bit
smaller than the main name of the gem, e. g. prawn, but this is
also ok.

What I find VERY difficult to read, though, is the version string
right next to the name of the gem "prawn". It reads 2.2.2 but
this is hard to read ... it's almost grey colour on white backgound.

My suggestion is twofold here:

a) could the font of that version to the upper side, be made a 
bit larger, if possible?

b) more importantly though, could we perhaps get a slightly better 
constrast-colour? Does not have to be black, although that
is perhaps not so bad ... but perhaps a more darkish-grey
or so?

Here is an image - this may be easier; to the top right, the
version string is difficult to read for me:

https://i.imgur.com/CWGZ5OG.png

**Comment by DanielAmah** [comment]
Hi I will love to work on this design issue. @colby-swandale

**Comment by colby-swandale** [comment]
@DanielAmah sure! let us know if you have questions.

**Comment by DanielAmah** [comment]
I have two sample design in mind. 
**The first one is :**
![screen shot 2018-01-26 at 4 14 21 pm](https://user-images.githubusercontent.com/28534124/35446237-611e94dc-02b4-11e8-937a-09644f45f12a.png)
**The second one is**
![screen shot 2018-01-26 at 4 15 53 pm](https://user-images.githubusercontent.com/28534124/35446265-77104a1a-02b4-11e8-9e3f-0c7297185b18.png)
I prefer the first one.  I believe it brings a new look and feel to that page and it is also readable by users of this application. What do you think?
@colby-swandale

**Comment by DanielAmah** [comment]
@colby-swandale I sent a message above

**Comment by colby-swandale** [comment]
i suggest creating a PR so that we can discuss any proposed changes there.

**Comment by DanielAmah** [comment]
@colby-swandale.  I have a quick question. I am done with this design fix but I want to know which branch to branch off from so that I can raise the PR ASAP.

**Comment by colby-swandale** [comment]
You want to branch from `master`

**Comment by sonalkr132** [comment]
@shevegen , please let us know what do think of changes. I would consider this fixed.
