### ISSUE TITLE
Intermittent SSL Errors for Gems in AWS eu-west-1

### ISSUE THREAD

**Issue by awagneratzendesk** [rubygems/rubygems.org#1703]
Hello!

We've experienced an interesting issue pulling down RubyGems from a single availability zone in AWS's eu-west-1a. Other AZs in the region with the exact same software/network stack work just fine. Below is the gem install error message we're seeing:

```
Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/specs.4.8.gz)
```

This is replicable via curl as well:

```
curl -I -v https://api.rubygems.org/specs.4.8.gz
```

Roughly 1 in 4 requests seemed to fail with an SSL error.  Oddly enough, none of the other AZs in the same region had this issue. We tried cycling our NAT gateways and even tested in other VPCs with the same result of roughly 1 in 4 request failures. Any CDN issues in that area that might be causing the SSL failures?

**Comment by dwradcliffe** [comment]
It looks like this is actually a known issue. See: https://status.fastly.com/incidents/k3zzxnkz4vcd
I'm going to close this and I recommend following up with Fastly and AWS.
