### ISSUE TITLE
API for knowing gems that use a particular gem as dependency

### ISSUE THREAD

**Issue by v0dro** [rubygems/rubygems.org#1705]
Knowing the dependencies of a Ruby gem is very simple, but knowing which gems use a particular gem (along with the version of the dependency and whether it is for testing or runtime) would be very useful so that gem creators can know which versions of the gem are being used and for what purpose.

This can allow gem writers to focus on important features with help from actual usage data.

**Comment by shevegen** [comment]
I agree, would be nice for convenient and simple ways to query that information as well.

**Comment by tanmayforgit** [comment]
@v0dro , This is what I got from http://guides.rubygems.org/rubygems-org-api/

GET - /api/v1/gems/[GEM NAME]/reverse_dependencies.json
List dependants of the specified gem. This is all the dependants whose latest version depend on the particular gem. Returns an array that includes names of the dependant gems.

**How is this different from what you are asking for? Am I missing something?**

**Comment by sonalkr132** [comment]
I am sorry @vodro, I don't think at the moment we are at place where we can support reverse dependencies' versions and platform info. Finding reverse dependencies is very expensive operation as it is. As @tanmayforgit mentioned you can use `GET - /api/v1/gems/[GEM NAME]/reverse_dependencies.json` as well as [ui](https://rubygems.org/gems/coveralls/reverse_dependencies) to find gems whose latest version depend on your gem.
If you really need to know this info you can dig through our [data dump](https://rubygems.org/pages/data).
