### ISSUE TITLE
Exactly matching gem is displayed twice in search

### ISSUE THREAD

**Issue by m1kit** [rubygems/rubygems.org#1709]
<img width="968" alt="2018-03-31 9 02 06" src="https://user-images.githubusercontent.com/37488201/38157486-3cefc622-34c2-11e8-8444-419a052bbad7.png">
This is redundant

# Suggestion
- Remove `EXACT MATCH`
<img width="971" alt="2018-03-31 9 03 52" src="https://user-images.githubusercontent.com/37488201/38157516-8ad6da9c-34c2-11e8-8582-26baab81ed84.png">

OR

- Remove from the list
<img width="991" alt="2018-03-31 9 04 25" src="https://user-images.githubusercontent.com/37488201/38157521-9f6648a8-34c2-11e8-9997-0942cd922939.png">

**Comment by enodi** [comment]
@segiddins I'll like to handle this issue

**Comment by enodi** [comment]
I was able to set up the application locally but I haven't been able to replicate the issue stated above.

This is what is displayed when I search for a gem e.g `capybara` on my local
![image](https://user-images.githubusercontent.com/29783644/41814886-73423b1a-7752-11e8-8b20-f49ed5becb27.png)




This is what is displayed when I search for the same gem on production
![image](https://user-images.githubusercontent.com/29783644/41814846-81d28884-7751-11e8-9ea8-3e7c05f03a12.png)

I'll be truly grateful if someone can point me in the right direction. Thank you
@m1kit @segiddins

**Comment by sonalkr132** [comment]
> This is what is displayed when I search for a gem e.g capybara on my local

When only one gem is found in search result, we redirect directly to the gem page ([code](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/searches_controller.rb#L12)). If you really care about your local set up matching our prod, you can load our [data dump](https://rubygems.org/pages/data). Alternatively, you can also create more gems with `capybara` word in it using `rails c`.

**Comment by sonalkr132** [comment]
Closed by #2140
