### ISSUE TITLE
Updating RubyGems.org Footer

### ISSUE THREAD

**Issue by rubymorillo** [rubygems/rubygems.org#1719]
Currently, the footer of most pages on RubyGems.org reads as follows:

> RubyGems.org is the Ruby community’s gem hosting service. Instantly publish your gems and then install them. Use the API to find out more about available gems. Become a contributor and improve the site yourself.

> RubyGems.org is made possible by many sponsors, with development funded by the Ruby trade association, Ruby Together.

> We need your help to fund the developer time that keeps RubyGems.org running smoothly for everyone. Join Ruby Together today.

To help the community understand how different partnerships work around RubyGems.org—specifically, what roles Ruby Together and Ruby Central play in its ongoing development—I'd like to rewrite these sections to clarify those points.

cc @indirect

**Comment by shevegen** [comment]
Has this patch addressed the above?

https://github.com/rubygems/rubygems.org/commit/f4ad75a3b894ecfe403c544685423d5530413d44

**Comment by rubymorillo** [comment]
PR https://github.com/rubygems/rubygems.org/pull/1722 closes this issue.
