### ISSUE TITLE
Purpose of the index.rubygems.org service

### ISSUE THREAD

**Issue by salsa-dev** [rubygems/rubygems.org#1728]
_I'm having a problem in the corporate network with strict firewall rules that restrict access to rubygems.org.
Chef-client requests "index.rubygems.org" and I cannot find the description of the service._

**Is it being used only for fetching index or could also be used for downloading gems?**

**Comment by segiddins** [comment]
Looks like it serves the same content as `rubygems.org` to me

**Comment by indirect** [comment]
The _purpose_ is to allow serving the index from a separate DNS entry if needed. However, we don't provide any guarantees about whether gems will or will not be downloadable from it.

**Comment by salsa-dev** [comment]
Having separate DNS entry to serve the index is a good idea but serving all the gems with it just spoils it down.

May I ask this restriction to be implemented ?

**Comment by shevegen** [comment]
Perhaps this could be enabled, with a disclaimer such as "there will not be any guarantees whether downloading gems will work; use at your own risk" or something.

**Comment by indirect** [comment]
I might be missing something, but why would we want to restrict index.rubygems.org to only serve the index and not serve other gems?

**Comment by sonalkr132** [comment]
Please feel free to reopen if your question was not answered to your satisfaction. You may also use our slack channel https://slack.bundler.io/
