### ISSUE TITLE
Use latest gemspec info for Rubygems Metadata, not last release

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems.org#1734]
I would expect Rubygems to use either the latest version from 4.x-beta or 3.x (LTS) to pull metadata, instead it looks like it uses the last pushed version. Here's what happened with sprockets https://github.com/rails/sprockets/issues/557

**Comment by schneems** [comment]
Would be closed by https://github.com/rubygems/rubygems.org/pull/1735

**Comment by sonalkr132** [comment]
You will have to do a minor point release of your latest version to fix this on your gem page.
