### ISSUE TITLE
Add a way to get gem information for a specific version

### ISSUE THREAD

**Issue by dsymonds** [rubygems/rubygems.org#1745]
If I fetch `https://rubygems.org/api/v1/gems/rdoc.json`, I always get information about the most recent version of the `rdoc` gem. However, if want to see the information for a specific version of that gem (e.g. `2.0.0`) then there does not appear to be a way to do that through the API.

**Comment by segiddins** [comment]
`https://rubygems.org/api/v1/versions/rdoc.json` has some info per-version

**Comment by dsymonds** [comment]
Yes, I can use that to get the list of versions, but it is a subset of the data available. It doesn't include dependencies, for instance.

**Comment by sonalkr132** [comment]
https://rubygems.org/api/v2/rubyems/rdoc/versions/2.0.0.json has dependency info as well. It suffers from #1692, but it is on my todo and should be fixed this week.

**Comment by dsymonds** [comment]
Ah, that works for me. Thanks!
