### ISSUE TITLE
Ability to add bio in profile!

### ISSUE THREAD

**Issue by TheCodersHangout** [rubygems/rubygems.org#1747]
Feature Request: Ability to add bio in profile!

**Comment by sonalkr132** [comment]
why would we want to do this?

**Comment by TheCodersHangout** [comment]
explains about the user!

**Comment by sonalkr132** [comment]
I am sorry, I don't understand need for this. rubygems.org is not really social networking platform. gem authors have option to show their email as well as twitter handle on their profile, which IMHO are sufficient info in case anyone wants to know more about author.
