### ISSUE TITLE
Cannot access the rubygems.org website

### ISSUE THREAD

**Issue by Diogomartf** [rubygems/rubygems.org#1752]
I can't access https://rubygems.org/ in the browser, sometimes it works if I refresh a lot of times.

Also I cannot install gems, it's seems something related with certificates. 

<img width="338" alt="screenshot 2018-07-09 at 12 07 05" src="https://user-images.githubusercontent.com/5664434/42447136-a7c47ebe-8370-11e8-9d9f-5ff3b22522f7.png">

I'm getting this error when:
`gem install rails`

ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/specs.4.8.gz).

I'm really lost, if someone could guide me, I really apreciate.

**Comment by segiddins** [comment]
Try running through the guide at https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

**Comment by Diogomartf** [comment]
I found out that was a network problem blocking an IP address.
