### ISSUE TITLE
Courier type face is poor for programming symbols

### ISSUE THREAD

**Issue by adg** [rubygems/rubygems.org#1755]
If you look at the docs for [declaring dependencies](https://guides.rubygems.org/patterns/#declaring-dependencies) you might be forgiven for mistaking the `~>` operator for `->`, since the specified font, Courier, does a poor job of distinguishing `~` and `-`.

I suggest removing `"courier",` from these lines, as they override the user's default monospace font:

https://github.com/rubygems/rubygems.org/blob/36c78ebafded72185abd7121ba612327b3bf5ef2/app/assets/stylesheets/type.css#L161

https://github.com/rubygems/rubygems.org/blob/e77edc08c11d2eea891bd1e5ac4117b0902aa21f/app/assets/stylesheets/modules/gem.css#L107

Sincerely, someone who just got very confused by this.

**Comment by ecnelises** [comment]
Below is different fonts in `~>` sign.
![Fonts](https://ecnelises.com/images/monospace-fonts-word.png)
But default monospace font under macOS is _Courier_. I remember default on Windows is _Consolas_.
