### ISSUE TITLE
Unknown gem in dependency graph

### ISSUE THREAD

**Issue by bestwebua** [rubygems/rubygems.org#1758]
Hello! I found little bug with gem info display in dependency graph. My rspec_file_chef gem has correct gemspec, and looks okay on RubyGems: https://rubygems.org/gems/rspec_file_chef

But, in dependency graph on GitHub my gem looks like unknown gem. I contacted GitHub support and they says:

> This normally means we haven't been able to link the Dependency to a repository. We use the data at the link below to search for Gems: https://rubygems.org/

![screenshot from 2018-07-23 10-12-43](https://user-images.githubusercontent.com/14002692/43062282-fe9f1e60-8e60-11e8-9fb2-811e3912bdf9.png)

Could you help me to fix this issue? Thanks!

**Comment by arthurnn** [comment]
This is not a rubygems.org issue. It is something on our(github) parse algorithm. I will try to fix it internally.
Thanks anyways.

**Comment by bestwebua** [comment]
Thanks for you answer, @arthurnn! Cheers!
