### ISSUE TITLE
api.rubygems.org  Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by mphilipps** [rubygems/rubygems.org#1760]
hi,
Since about 5 days ago 1 out of ~15 https connections to api.rubygems.org fails.

> gem list -V --debug --remote '\Ayard\z'
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/resolv.rb:171 - LoadError

> *** REMOTE GEMS ***

>Exception `Errno::EEXIST' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/fileutils.rb:230 - File exists @ dir_s_mkdir - /root/.gem/specs/api.rubygems.org%443
>Exception `Errno::ECONNRESET' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/net/protocol.rb:44 - Connection reset by peer - SSL_connect
>Exception `Errno::ECONNRESET' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/net/http.rb:964 - Connection reset by peer - SSL_connect
>Exception `Gem::RemoteFetcher::FetchError' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:311 - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/latest_specs.4.8.gz)
>Exception `Gem::RemoteFetcher::FetchError' at /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/spec_fetcher.rb:265 - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/latest_specs.4.8.gz)

The server in question is behind a NAT, but not a popular one (aws/google/azure) and is also  the only server behind it that is regularly connecting to rubygems.org

**Comment by sonalkr132** [comment]
Hi @mphilipps 

Can you please follow [this troubleshooting guide](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors) let us know about results?

**Comment by mphilipps** [comment]
hi,
Not using bundler here so that fails as expected:

Other than that it looks like this:  

Bundler connection to rubygems.org:       failed  ❌  (uninitialized constant Bundler)
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅

except when it fails in that case it shows:  

Bundler connection to rubygems.org:       failed  ❌  (uninitialized constant Bundler)
RubyGems connection to rubygems.org:      failed  ❌  (Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org))
Ruby net/http connection to rubygems.org: success ✅

With that it seems the behaviours is exactly the same as in my original report.

Skiming over the rest of the page:
- ntp is installed, running and the time is correct.
- I don't think messing with the installed versions/certificates is going to fix it, given that is works 95% of the time.

It feels more like a load balancing issue on rubygems.org side.

**Comment by indirect** [comment]
@mphilipps our frontend servers are run by Fastly. I recommend visiting http://fastly-debug.com and using the widget in the bottom right to open a ticket about the connection resets you are seeing. 👍

**Comment by sonalkr132** [comment]
hi @mphilipps are you still facing this issue?

**Comment by mphilipps** [comment]
Not at the moment, after a couple of days it disappeared and then resurfaced like once or twice.  
I am closing this as it has been fine for the last few weeks.
