### ISSUE TITLE
Finish rails 5.0, 5.1, & 5.2 default configuration migrations.

### ISSUE THREAD

**Issue by thomasdziedzic** [rubygems/rubygems.org#1773]
I've been working on the rails 5.2 migration at https://github.com/rubygems/rubygems.org/pull/1771 and I discovered that the previous configuration migrations were not completed. As a result, I opened this issue to track this so that I can complete the rails 5.2 pull request without having to worry about setting all the rails new default migrations.

### finish rails 5.0 migration
- [ ] Rails.application.config.action_controller.per_form_csrf_tokens
- [ ] Rails.application.config.action_controller.forgery_protection_origin_check
- [ ] ActiveSupport.to_time_preserves_timezone
- [ ] Rails.application.config.active_record.belongs_to_required_by_default
- [ ] config.load_defaults 5.0

### finish rails 5.1 migration
- [ ] Rails.application.config.action_view.form_with_generates_remote_forms
- [ ] Rails.application.config.assets.unknown_asset_fallback
- [ ] config.load_defaults 5.1

### finish rails 5.2 migration
- [ ] Rails.application.config.active_record.cache_versioning
- [ ] Rails.application.config.action_dispatch.use_authenticated_cookie_encryption
- [ ] Rails.application.config.active_support.use_authenticated_message_encryption
- [ ] Rails.application.config.action_controller.default_protect_from_forgery
- [ ] Rails.application.config.active_record.sqlite3.represent_boolean_as_integer
- [ ] Rails.application.config.active_support.use_sha1_digests
- [ ] Rails.application.config.action_view.form_with_generates_ids
- [ ] config.load_defaults 5.2

**Comment by dwradcliffe** [comment]
Now that we are running 5.2 it would be great if we could cleanup these old things.

**Comment by sonalkr132** [comment]
Closed by #1983.
Check milestone for all PRs.
