### ISSUE TITLE
Use of strong parameters in the API code 

### ISSUE THREAD

**Issue by shlok007** [rubygems/rubygems.org#1774]
Currently, the API code does not contain the use of strong parameters anywhere. I am not sure if this is the correct approach. As described in the documentation:
>With strong parameters, Action Controller parameters are forbidden to be used in Active Model mass assignments until they have been permitted. This means that you'll have to make a conscious decision about which attributes to permit for mass update. This is a better security practice to help prevent accidentally allowing users to update sensitive model attributes.

Not just that, [permitting scaler value](https://edgeguides.rubyonrails.org/action_controller_overview.html#permitted-scalar-values) via strong params prevents arrays, hashes, or any other objects to be injected.
Will using strong params improve our security?

**Comment by ecnelises** [comment]
Didn’t we?
https://github.com/rubygems/rubygems.org/blob/d8a48488d29cbfc83efd2e936c74290c54041288/app/controllers/profiles_controller.rb#L46
https://github.com/rubygems/rubygems.org/blob/d8a48488d29cbfc83efd2e936c74290c54041288/app/controllers/rubygems_controller.rb#L71

**Comment by johnsonberry** [comment]
On a project I am working on now I also check in a before an action that the data[: type] param matches the correct type and return a 422 if it does not.
[Brother Wireless Printer Setup](https://www.brotherprintersupportnumber.com/brother-printer-setup/)

**Comment by smithtaylor247** [comment]
After the router has determined which controller to use for a request, [Netgear Wifi Extender Setup](https://www.netgearroutersupportnumber.com/blog/netgear-wifi-extender/) controller is responsible for making sense of the request and producing the appropriate output.

**Comment by sonalkr132** [comment]
We recently [fixed a issue](https://github.com/rubygems/rubygems.org/commit/b6c2777219242ff317dea1aad0ec71aeb0fc8ac0) where one could have improved chances of guessing api key by sending api_key param as array.
We may have a few other places in api where we are unintentionally allowing `WHERE table.column IN ($1, $2)  [["val1", "val2"]`. It would be nice to fix those.
