### ISSUE TITLE
Establish a preliminary list of typo-protected gems

### ISSUE THREAD

**Issue by claudijd** [rubygems/rubygems.org#1777]
In support of #1776, this issue is to help establish a preliminary list of critical gems that we should initially provide typo-protection for.

**Comment by claudijd** [comment]
I would propose starting with top 10 from here (https://rubygems.org/stats) as starting point for a preliminary test, and then expand over time.  Currently, that list is....

rspec-core
diff-lcs
rspec-expectations
rspec-mocks
rspec
bundler
rspec-support
multi_json
rack
rake

**Comment by sonalkr132** [comment]
We released initial rules for this in #2037. Post comments for improvements on #2058.
