### ISSUE TITLE
Need to upgrade from Ruby 2.3.5

### ISSUE THREAD

**Issue by jhsu802701** [rubygems/rubygems.org#1780]
The current version of Ruby used is 2.3.5.  This app should be upgraded to 2.3.7, then 2.4.4, and then 2.5.0 or 2.5.1.

**Comment by dwradcliffe** [comment]
Yep, you're right. Unfortunately this is a task that's mostly done on the servers. The medium/long term plan is to use docker images to allow this to be configured here so we don't need to do anything on the servers to do an upgrade like this.

**Comment by jhsu802701** [comment]
I can make a pull request that upgrades the Ruby version.  I'll be sure to upgrade .ruby_version, .travis.yml, etc.
