### ISSUE TITLE
Failed to open TCP connection to localhost:22221

### ISSUE THREAD

**Issue by jhsu802701** [rubygems/rubygems.org#1782]
* During the "bundle exec rake environment elasticsearch:import:all DIR=app/models FORCE=y" process, I get the following error:
```
[!!!] Index does not exist (Elasticsearch::Transport::Transport::Errors::NotFoun
d)
```
* When I run the full test suite, I get the following message:
```
[!!!] Index does not exist (
Elasticsearch::Transport::Transport::Errors::NotFound)
```
* When I run the full test suite, I get the following errors in the individual tests:
  * 1:
```
RubygemSearchableTest#test_: #search exception handling Elasticsearch::Transport
::Transport::Errors should fallback to legacy search and give correct error mess
age. :
Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:22221 (Cannot a
ssign requested address - connect(2) for "localhost" port 22221)
    app/models/concerns/rubygem_searchable.rb:57:in `search'
    test/unit/rubygem_searchable_test.rb:247:in `block (5 levels) in <class:Ruby
gemSearchableTest>'
    test/unit/rubygem_searchable_test.rb:246:in `block (4 levels) in <class:Ruby
gemSearchableTest>'
```
  * 2:
```
SearchesControllerTest#test_: with elasticsearch down should fallback to legacy 
search. :
Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:22221 (Cannot a
ssign requested address - connect(2) for "localhost" port 22221)
    app/models/concerns/rubygem_searchable.rb:57:in `search'
    app/controllers/searches_controller.rb:8:in `show'
    test/functional/searches_controller_test.rb:149:in `block (3 levels) in <cla
ss:SearchesControllerTest>'
    test/functional/searches_controller_test.rb:147:in `block (2 levels) in <cla
ss:SearchesControllerTest>'
```
  * 3:
```
GemDownloadTest#test_: .bulk_update with multiple versions of same gem should up
date total_count when elasticsearch is down. :
Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:22221 (Cannot a
ssign requested address - connect(2) for "localhost" port 22221)
    app/models/gem_download.rb:108:in `update_gem_downloads'
    app/models/gem_download.rb:85:in `bulk_update'
    test/unit/gem_download_test.rb:83:in `block (4 levels) in <class:GemDownload
Test>'
    test/unit/gem_download_test.rb:82:in `block (3 levels) in <class:GemDownload
Test>'
```

**Comment by dwradcliffe** [comment]
Are you running toxiproxy? It seems like the code thinks it's running but is unable to use it properly.

**Comment by jhsu802701** [comment]
Yes, I'm running toxiproxy in a window.  The command I use is "toxiproxy".  Are there any parameters I'm supposed to add?

How many windows do I need?  I have one for running the Rails server, one for Redis, one for toxiproxy, and one for entering the normal commands, such migrations and tests.

**Comment by sonalkr132** [comment]
> How many windows do I need?

You can also use our docker-compose file to set up your dev env and it won't need any windows :wink: 
You should check [install_toxiproxy.sh](https://github.com/rubygems/rubygems.org/blob/master/script/install_toxiproxy.sh) and [toxiproxy docs](https://github.com/shopify/toxiproxy) for its use and setup. You could also skip setting up toxiproxy, in dev toxiproxy tests will be skipped if you don't have toxiproxy running.

**Comment by jhsu802701** [comment]
Given that the error message is "Failed to open TCP connection to localhost:22221", I believe that my system isn't recognizing the transport.host parameter as 127.0.0.1.  I tried adding the line "transport.host: 127.0.0.1" to /etc/elasticsearch/elasticsearch.yml, but this didn't fix the matter.  Exactly how do I set the transport.host parameter?

PLEASE don't tell me to run ElasticSearch with the docker-compose command.  I already run Rails in Docker, and my attempts to install Docker in Docker didn't pan out.  I don't have Ruby on Rails installed on my host system.

PLEASE don't tell me to install Ruby on Rails in my host system.  It's a long and painful process, and relying on a Ruby on Rails installation in a host system means that I can't just reset everything willy-nilly like I can with Rails in Docker.

All I need is to get the transport layer in ElasticSearch working.  How do I do this?

**Comment by dwradcliffe** [comment]
If you’re running rails in docker then localhost is not the same localhost as your host system localhost. You will need to use the IP of your actual host system instead.

**Comment by jhsu802701** [comment]
I noticed that the message I'm getting when I enter "sudo service elasticsearch restart" is:
```
[....] Starting Elasticsearch Server:sysctl: setting key "vm.max_map_count": Read-only file system
. ok 
```
The Travis log shows no mention of setting vm.max_map_count or a read-only file system.  How do I set ElasticSearch to be writable?  It looks like ElasticSearch is stuck in read-only mode.  Or is this a red herring?

**Comment by jhsu802701** [comment]
> If you’re running rails in docker then localhost is not the same localhost as your host system localhost. You will need to use the IP of your actual host system instead.

@dwradcliffe , I have SparkyLinux as my host OS, and I have Ruby on Rails pre-installed in Docker.  What I'm trying to do is have Rails and ElasticSearch running within the same Docker container.  I know that the ElasticSearch configuration file is at /etc/elasticsearch/elasticsearch.yml.  Exactly what do I need to do to properly configure ElasticSearch?

At the moment, entering "hostname -I" in my host system gives me:
```
192.168.1.103 172.17.0.1 172.18.0.1 172.19.0.1 172.20.0.1
```
Entering "hostname -I" in my Docker container gives me "172.17.0.2".

**Comment by jhsu802701** [comment]
I've gone into the ElasticSearch Docker image used in the official setup, and here are my notes:
* The contents of /etc/os-release:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.4
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
* The configuration file is /usr/share/elasticsearch/config/elasticsearch.yml.  Its contents are:
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
```

**Comment by NSidharthaN** [comment]
> If you’re running rails in docker then localhost is not the same localhost as your host system localhost. You will need to use the IP of your actual host system instead.

Thank you .

**Comment by simi** [comment]
I was able to start development locally using `docker-compose start` to start all needed services up quickly.

**Comment by sonalkr132** [comment]
Please open a new issue or ask in #rubygems-org if you are still having trouble with our development setup.
