### ISSUE TITLE
The Dutch translation is not good enough

### ISSUE THREAD

**Issue by sharkwouter** [rubygems/rubygems.org#1794]
Today I noticed that there is a button for viewing rubygems.org in Dutch. I tried this and I noticed about half of the text on the website is not translated. I've also noticed grammar mistakes, spelling errors and lines which flat out don't mean the same as what they are trying to translate.

I can fix this and I was planning to do this and make a pull request, but I don't think it is worthwhile. The target audience is developers and system administrators from what I've seen. Dutch IT staff is used to reading documentation is English, from what I've seen they generally prefer this. My question here is: Is there a significant amount of users for this language?

If there is, I will try my best to update it. If there isn't, I would suggest removing the Dutch language from the website.

**Comment by sonalkr132** [comment]
> Is there a significant amount of users for this language?

Depends on your definition of significant. I can see pages being requested with `locale=de`, and we would prefer not to remove it all together. 
> I can fix this and I was planning to do this and make a pull request

PR sounds good.

**Comment by simi** [comment]
PR was already created - https://github.com/rubygems/rubygems.org/pull/1802. I think this can be closed.
