### ISSUE TITLE
Reverse dependencies page error 500

### ISSUE THREAD

**Issue by markets** [rubygems/rubygems.org#1798]
Hi 👋 

I'm trying to visit the `/gems/GEM_NAME/reverse_dependencies` page for different gems and I get a 503 error:

> Unicorn!
> We are having a bad problem and the app server will not talk to us.

Examples (gems under my account): 
- https://rubygems.org/gems/mini_i18n/reverse_dependencies
- https://rubygems.org/gems/invisible_captcha/reverse_dependencies

Then, I realized this page crashes also for other gems:
- https://rubygems.org/gems/rails/reverse_dependencies
- https://rubygems.org/gems/bundler/reverse_dependencies
- https://rubygems.org/gems/sinatra/reverse_dependencies

**Comment by aleksandrs-ledovskis** [comment]
Interestingly enough, REST API seems to be unharmed / can be used while web page is down.

https://rubygems.org/api/v1/gems/mini_i18n/reverse_dependencies.json

**Comment by sonalkr132** [comment]
Half the response time is count(distinct ...) query, for total entries count used by will_paginate. I am working on migration to [kaminari](https://github.com/kaminari/kaminari), which has option to only show `next` and `previous` page navigation.
[Feature was requested](https://github.com/mislav/will_paginate/issues/447#issuecomment-253986051) on will_paginate but it was not accepted.

**Comment by markets** [comment]
Thank you guys for your response and taking a look! 

@aleksandrs-ledovskis maybe this is because API doesn't respond with pagination? Since @sonalkr132 is pointing out that pagination is what causes the issue...

**Comment by sonalkr132** [comment]
pagination is half the problem. Other half is `by_downloads` (ORDER BY gem_downloads.count) used [in controller](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/reverse_dependencies_controller.rb#L10). I don't think we can keep order by downloads either.

**Comment by simi** [comment]
@sonalkr132 are there any easy steps to reproduce this problem? Is loading data dump and visitng that url locally enough?

**Comment by sonalkr132** [comment]
> Is loading data dump and visitng that url locally enough?
yes

**Comment by sonalkr132** [comment]
> I don't think we can keep order by downloads either.

My PR cuts response time in half but it is still going to be above 700-800ms for popular gems. Removing `by_downloads` brings it down to ~200ms.
@dwradcliffe what would be acceptable response time here? Could we use rails cache?

**Comment by dwradcliffe** [comment]
Our overall goal for the service is 100ms, but 200ms should be ok for this endpoint. The before disabling it, this endpoint was averaging 2700ms.

Also we were getting some traffic with garbage query string values which bypasses Fastly. So I think it would make sense to use Rails cache to ensure that repeated calls for the same gem are cached.

**Comment by dwradcliffe** [comment]
Well it seems like the kaminari PR was a huge help! I've re-enabled this endpoint and it's looking better over the last 12 hours.

![image](https://user-images.githubusercontent.com/118850/47574255-2e562580-d90d-11e8-9503-0b6a9edbd17b.png)

**Comment by markets** [comment]
Thank you guys for working on this! 👏
