### ISSUE TITLE
Pagination is currently broken

### ISSUE THREAD

**Issue by ashmaroli** [rubygems/rubygems.org#1812]
I discovered this issue while browsing the `/news` page.

1. Click on any pager (e.g `4`) to go to the associated URL. (proceeds as expected)
2. Observe that while the addressbar shows the correct context, `https://rubygems.org/news?page=4`, the
pagination at the bottom is still at **page 1**
3. The `next` link always points to `page 2`

**Comment by dwradcliffe** [comment]
@sonalkr132 this might be related to your recent changes?

**Comment by ashmaroli** [comment]
@sonalkr132 Sorry to say, as of this writing, **the reported issue has not been resolved**

**Comment by sonalkr132** [comment]
Right now the fix the deployed in staging. Please until the PR says following:
>  ... deployed to production .. ago
