### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1824]
```
RubygemsControllerTest#test_: On GET to show for a blacklisted gem should respond with 200. :
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"rubygems", :id=>"#"}, possible unmatched constraints: [:id]
    test/functional/rubygems_controller_test.rb:472:in `block (2 levels) in <class:RubygemsControllerTest>'
bin/rails test vendor/bundle/ruby/2.3.0/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:346
```

**Comment by simi** [comment]
@sonalkr132 any steps to reproduce (or link to broken build)?

**Comment by sonalkr132** [comment]
`$ rails test test/functional/rubygems_controller_test.rb -n "/blacklisted/" -v  --seed 26689`

**Comment by nikobozi** [comment]
Tried to run this test with an each loop for all elements multiple times (and not just one random  `Patterns::GEM_NAME_BLACKLIST.sample`) and they passed without failing.
My guess is that this commit solved the issue by removing commented out lines:
https://github.com/rubygems/rubygems.org/commit/bd9b2220572653195013d38d56f311f5f668dc37

**Comment by sonalkr132** [comment]
So thats what `:id=>"#"` is.. Thank you looking into this @nikobozi :+1: 
confirmed that above seed is passing on master now.
