### ISSUE TITLE
Remove highline from Gemfile

### ISSUE THREAD

**Issue by sonalkr132** [rubygems/rubygems.org#1838]
We don't really need this. `permadelete` and `merge_user` scripts can `use gets.chomp`. 
Check: https://github.com/rubygems/rubygems.org/search?q=highline&unscoped_q=highline

**Comment by jvanbaarsen** [comment]
I would like to pick this one up :)

**Comment by lucianosousa** [comment]
@jvanbaarsen how it's going in your side?

**Comment by ohbarye** [comment]
Could I try this as a good first issue?
