### ISSUE TITLE
trouble with rate limits

### ISSUE THREAD

**Issue by pfaffman** [rubygems/rubygems.org#1841]
I'm trying to rebuild Discourse and am hitting rate limits from 38.242.7.194. 

I'm doing only a couple hundred requests, but about 30 are HTTP 429s.

**Comment by dwradcliffe** [comment]
_Note: This is probably better for http://help.rubygems.org/_

If you are installing gems, there should be no reason to hit the rate limits unless you are using old version of bundler that does not use the newest APIs. All requests using the new APIs are cached at the CDN and should not hit the rate limits.

**Comment by deivid-rodriguez** [comment]
I fixed a problem with bundler and rate limits in https://github.com/bundler/bundler/pull/6728, but it has not yet been merged.

**Comment by sonalkr132** [comment]
Above mentioned PR is merged. I am closing this as it is unclear if there was any issue on rg.org. Please use help.rubygems.org to file a support ticket if you are still having issue with rate limit.
