### ISSUE TITLE
gem version on webpage title is not the latest

### ISSUE THREAD

**Issue by JesseChavez** [rubygems/rubygems.org#1854]
I noticed the version of a gem in the title of the page is not the latest.
If we look at:
![image](https://user-images.githubusercontent.com/1594073/50190201-54d58300-02f6-11e9-842d-9a02519e8b0c.png)

or

https://rubygems.org/gems/jruby-openssl

 It seems to be JRuby specific issue.

If it is not a issue, do we need to do something else besides `rake release` ?

**Comment by dwradcliffe** [comment]
In the code we explicitly look for the latest `ruby` platform gem.
https://github.com/rubygems/rubygems.org/blob/5249f1039a86930d714760c838e69d7926f6fdb2/app/models/version.rb#L126-L128

I'm not sure exactly why, or what the correct behavior should be.

**Comment by sonalkr132** [comment]
Clients use latest version of ruby platform when no platform or version is specified. IMHO, it is only logical that we do the same in UI.
Most gems have ruby as primary platform. Changing this to latest version release (by date) would only cause further confusion as users will see `0.10.1` as latest version but running `gem install jruby-openssl` installs `0.9.4`. Not to mention, it would also be a breaking change for latest version api endpoint.
