### ISSUE TITLE
No way to downgrade rubygem-update to specific version

### ISSUE THREAD

**Issue by shivrajbadu** [rubygems/rubygems.org#1876]
__ISSUE__

- I see rubygems-update version 3.0.1 was build on december 22, 2018
- After this build, whenever I run

```sh
gem install rubygems-update -v 2.7.7
sudo update_rubygems
Bundler 1.17.2 installed
RubyGems 3.0.1 installed
Regenerating binstubs
Parsing documentation for rubygems-3.0.1
Installing ri documentation for rubygems-3.0.1

=== 3.0.1 / 2018-12-23
...
```

It always install `rubygems-3.0.1` and there is no way I can install older version. With this latest version, I am getting issues with my existing gems which depends on rubygems <= 3.0.0.

![screen shot 2018-12-28 at 3 09 01 pm](https://user-images.githubusercontent.com/4639903/50510624-8991c900-0ab2-11e9-9d3d-0d3721a7f0e8.png)

**Comment by colby-swandale** [comment]
You can downgrade to a specific RubyGems version using `gem update --system=<version>`
