### ISSUE TITLE
Translation missing for week_update and month_update on search index

### ISSUE THREAD

**Issue by remomueller** [rubygems/rubygems.org#1879]
When you search for a gem on the site, https://rubygems.org/search?utf8=%E2%9C%93&query=gem, hovering over "Week Update" and "Month Update" filters show a missing translation in the tooltips.

```
translation missing: en.searches.aggregations.week_update, count: 104
translation missing: en.searches.aggregations.month_update, count: 483
```

![screen shot 2019-01-03 at 1 16 59 pm](https://user-images.githubusercontent.com/316479/50654209-12e54780-0f5a-11e9-9f53-c7b53126afc3.png)
![screen shot 2019-01-03 at 1 17 09 pm](https://user-images.githubusercontent.com/316479/50654210-12e54780-0f5a-11e9-9a6f-a3780053beb9.png)

Fairly minor issue, I only stumbled on it by chance (was exploring the filters).

**Comment by ohbarye** [comment]
Fixed! 

![image](https://user-images.githubusercontent.com/1811616/51437072-17408d00-1cdc-11e9-91a6-f74a7520c144.png)
