### ISSUE TITLE
API endpoint for full gem info of historical versions?

### ISSUE THREAD

**Issue by eropple** [rubygems/rubygems.org#1889]
Hi there --

I'm in the process of writing a RubyGems implementation that I'd like to have play nicely with rubygems.org. This implementation has to act as a mirror/cache for Rubygems, and in order to provide a shallow mirror that doesn't pummel rubygems.org into the ground, I'm watching the compact index and trying to react to changes. I need to be able to surface the same information that the gem info endpoint `/api/v1/GEM_NAME.json` provides, but for versions other than latest. I've been looking at the source code and I'm not finding a way to do this; the `versions` endpoint is a more limited set of data, while the gem info endpoint doesn't seem to support a query string or the like.

The RubyGems API documentation seems to be very stale, so I'm a bit stuck; for all the security reasons you'd expect, I do not want to be pulling down and `Marshal.load`ing data coming out of rubygems.org, so parsing gemspec.rz files is really undesirable. Am I missing something here?

**Comment by sonalkr132** [comment]
>  the versions endpoint is a more limited set of data

have you tried [v2](https://guides.rubygems.org/rubygems-org-api-v2/)?
```
curl https://rubygems.org/api/v2/rubygems/coulda/versions/0.7.1.json | jq                                           
{
  "name": "coulda",
  "downloads": 57008,
  "version": "0.7.1",
  "version_downloads": 3663,
  "platform": "ruby",
  "authors": "Evan David Light",
  "info": "Behaviour Driven Development derived from Cucumber but as an internal DSL with methods for reuse",
  "licenses": null,
  "metadata": {},
  "sha": "777c3a7ed83e44198b0a624976ec99822eb6f4a44bf1513eafbc7c13997cd86c",
  "project_uri": "https://rubygems.org/gems/coulda",
  "gem_uri": "https://rubygems.org/gems/coulda-0.7.1.gem",
  "homepage_uri": "http://coulda.tiggerpalace.com",
  "wiki_uri": null,
  "documentation_uri": "http://www.rubydoc.info/gems/coulda/0.7.1",
  "mailing_list_uri": null,
  "source_code_uri": null,
  "bug_tracker_uri": null,
  "changelog_uri": null,
  "dependencies": {
    "development": [],
    "runtime": [
      {
        "name": "yourdsl",
        "requirements": "~> 0.7"
      }
    ]
  },
  "built_at": "2011-08-08T04:00:00.000Z",
  "created_at": "2011-08-08T21:23:40.254Z",
  "description": "Behaviour Driven Development derived from Cucumber but as an internal DSL with methods for reuse",
  "downloads_count": 3663,
  "number": "0.7.1",
  "summary": "Test::Unit-based acceptance testing DSL",
  "rubygems_version": ">= 0",
  "ruby_version": null,
  "prerelease": false,
  "requirements": null
}
```

**Comment by sonalkr132** [comment]
Closing for lack of response.
