### ISSUE TITLE
Unable to edit gem online

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#1899]
Maybe I'm crazy, but I'm sure that was a thing.
I own https://rubygems.org/gems/recaptcha but I cannot edit the documentation url.
The gemspec no longer has it set, but rubygems still links it.

**Comment by sonalkr132** [comment]
We had the edit page deprecated for months before we removed it: #1815 . Please use spec [metadata](https://guides.rubygems.org/specification-reference/#metadata) to set those links (you get per version links, check [metadata milestone](https://github.com/rubygems/rubygems.org/milestone/7) for details). 
You have actually hit a bug in our implementation. As of now, these is no way to remove values from linkset. Please leave your take on PR I proposed.
