### ISSUE TITLE
Data dump download links not shown in non-EN locales

### ISSUE THREAD

**Issue by colszowka** [rubygems/rubygems.org#1902]
Hey everyone,

I noticed that for a while on https://rubygems.org/pages/data there has not been any actual links to data dumps. Did maybe something break with the export process?

**Comment by sonalkr132** [comment]
> there has not been any actual links to data dumps

What do mean by actual links? I tried to download `2019-02-04T21:21:38 (248 MB)` and it is working for me.
Dump for last week should be available after 11 Feb, 21:21 UTC.

**Comment by sonalkr132** [comment]
if you don't see link for `2019-02-04T21:21:38 (248 MB)`, please check browser console for any errors (it is generated by js).

**Comment by colszowka** [comment]
@sonalkr132 Oh, interesting! What are browser are you on?

I was using Chrome, and there I only see a blank page. I cross-checked against Firefox, there I can actually see the download links.

On Chrome, I tried both regular and incognito mode (so extensions that might interefere are disabled), on both the dump links are not being shown to me. I also do not get any JS errors on the console.

**Comment by sonalkr132** [comment]
I am using chrome 71.0.3578.98 (Official Build) (64-bit). 
Can you please check your network requests, are all of them completing? Script is triggered on `document.load`. Also, please try disabling any extensions you may be using

**Comment by colszowka** [comment]
I'm on Version 71.0.3578.98 (Official Build) (64-bit) as well. In incognito mode on desktop extensions are disabled, so that should not interfere. On android, chrome does not have extensions so that should also not be an issue there.  I cannot see any XHR requests going out when I check the network panel, so it seems the fetch query is never triggered. 

I think I found it though: Since I'm in DE locale, I see rubygems.org in that locale by default. I tried https://rubygems.org/pages/data?locale=en and that actually works, so it seems it's the "localized" version (the content is in english anyway ;) that breaks

**Comment by colszowka** [comment]
Ok, cross-checked against some of the other locales available, the download links only seem to work on the en locale. This is the same for Chrome and Firefox actually (firefox worked initially because my system is EN, but Chrome is configured to DE, so when I tested firefox that worked not because it's firefox but because it requested EN)

**Comment by sonalkr132** [comment]
Please check above PR.

**Comment by colszowka** [comment]
@sonalkr132 Works for me now, thanks for the quick fix!
