### ISSUE TITLE
Api::V1::DeletionsController#create is very slow

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#1908]
Over the past week the response time for this action averaged 5 seconds. This has caused degradation of service as the unicorn workers were all tied up. Let's see what we can do to optimize this code. Maybe something can be moved to a background job?

https://rpm.newrelic.com/accounts/12126/applications/4488593/transactions#id=5b22436f6e74726f6c6c65722f6170692f76312f64656c6574696f6e732f637265617465222c22225d&app_trace_id=fca39d1c-3307-11e9-8501-0242ac11000b_16299_44443

At first glance it seems that maybe the biggest amount of time is updating the position on all the remaining versions of the gem. Can we move this process to a background job?

**Comment by dwradcliffe** [comment]
![image](https://user-images.githubusercontent.com/118850/52921337-063b6980-32e4-11e9-8520-78916e0451e4.png)

**Comment by sonalkr132** [comment]
> the biggest amount of time is updating the position on all the remaining versions of the gem.

This is a problem for gems with significant number of version releases. Above PR fixes issue of reorder being triggered twice for each `gem yank` with caveat that it introduces Active Model Dirty (not among best of Active.. gems).
We could further improve this if we bulk update versions.

> Maybe something can be moved to a background job?

We have open issue for versions being delayed after push (#1877), IMHO, we should avoid things which can potentially make it worse until we fix the issue.
