### ISSUE TITLE
Publish anonymous owners information in the data dumps

### ISSUE THREAD

**Issue by mensfeld** [rubygems/rubygems.org#1918]
Hello. I'm building a set of tools that I plan to open-source that prevent against typosquatting attacks, license changes, etc for Ruby. While the majority of my work and analysis can be done thanks to the data dumps, it lacks the possibility to track owners and to track the releaser (pusher) of the gem.

Would it be possible to share this data (only ids are fine for me) publically? It does not need to contain any user sensitive information. Ids and information on the ownership of gems + info on the author of the release would be more than enough to craft even more tools. This data can already be obtained by crawling the website. Owners are available on the gem page (example: https://rubygems.org/gems/karafka) so I don't see a reason not to publish them within the data dump.

**Comment by sonalkr132** [comment]
>  I don't see a reason not to publish them within the data dump.

We intend to keep data dump [loadable on local instances](https://github.com/rubygems/rubygems.org/tree/master/script) of our app. I doubt exposing limited columns of users table will keep the dump loadable.

**Comment by mensfeld** [comment]
I do understand your reasoning, yet it prevents me from building and opening to the community several tools. Isn't there a way to provide both? That is to have a fully loadable with an anonymized set of ownership relations (maybe as a second DB or anything?)?

**Comment by dwradcliffe** [comment]
I'm not sure yet but there may be a way. We need to make some changes to the process anyway, so we can see if there's an easy way to do this. Please don't expect an immediate solution here, but I'll keep this open and update when I have a chance.

**Comment by mensfeld** [comment]
> I'm not sure yet but there may be a way. 

Thank you. This would allow me to create some tools to keep track of releasers and ownership changes for rub gems inspection.

> We need to make some changes to the process anyway, so we can see if there's an easy way to do this.

If I can help in any way, please ping me.

>  Please don't expect an immediate solution here, but I'll keep this open and update when I have a chance.

I am aware of how that works and that it isn't a simple thing. Thank you!

**Comment by mensfeld** [comment]
FYI having this would allow me to detect changes in the ownership of strong_password gem...

**Comment by dwradcliffe** [comment]
I think the ownerships table might provide this without exposing any personal information. @sonalkr132 can you confirm?

**Comment by sonalkr132** [comment]
We would have to replace `user_id` with `user.handle` and drop `notifier` (push email preference) column.

Btw, if anyone wants to track releases of a particular gem(s), they can `subscribe` to the gem or register a `webhook`.

**Comment by mensfeld** [comment]
> Btw, if anyone wants to track releases of a particular gem(s), they can subscribe to the gem or register a webhook.

I track that (I have a webhook for all the releases) however last time I checked it did not provide info on the releaser nor the owners.

**Comment by sonalkr132** [comment]
> it did not provide info on the releaser nor the owners

We have started storing pusher/yanker since https://github.com/rubygems/rubygems.org/pull/1954. Adding pusher/yanker to webhook makes sense. Feel free to send a PR with this change.

**Comment by mensfeld** [comment]
Since I was the only one needed, I was able to work around my ways using the existing APIs and other RubyGems team members help.
