### ISSUE TITLE
yank responds with permission issue 

### ISSUE THREAD

**Issue by djezzzl** [rubygems/rubygems.org#1919]
**This issue was copy/pasted from https://github.com/rubygems/rubygems/issues/2641 as one of contributors suggested.**

I'm having a problem or would like to suggest a feature.

My current problem is:

I just released a new version of my gem `database_validations` but I found a bug after few minutes and wanted to yank that version but I got the error.

```
gem yank database_validation -v 0.8.7
Yanking gem from https://rubygems.org...
You do not have permission to delete this gem.
```

We have two owners on the gem and another did `yank` succesfully. Is that a non-documented feature?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by sonalkr132** [comment]
Can you please let us know owner handle for which yank is failing?
Also, make sure that the key you see in following request is same as one in `~/.gem/credentials`.
```
curl -u <handle> https://rubygems.org/api/v1/api_key.yaml
```

**Comment by djezzzl** [comment]
I checked credentials, they're the same. 

The owner handler is `djezzzl`

**Comment by dwradcliffe** [comment]
Is the gem `database_validation` or `database_validations`?

Looking at https://rubygems.org/gems/database_validation/versions it doesn't look like you ever pushed that version. I'm guessing this isn't your gem and was just a typo in your report.

Looking at https://rubygems.org/gems/database_validations/versions it looks like you already yanked that version.

Maybe the server is responding with the permissions error if the gem was already yanked? We can probably provide a better error here.

**Comment by dwradcliffe** [comment]
Just re-read the report and I noticed `We have two owners on the gem and another did `yank` succesfully.` So they must have done it first, and that's why yours failed.

**Comment by djezzzl** [comment]
I'm talking about `database_validations` gem. 

No, I tried to yank it few times before I asked another owner. If you re-check once again you see we did that twice. Second version was also yanked by another owner after.

**Comment by dwradcliffe** [comment]
I looked back at the logs and it seems you might have typo'd the yank command and tried to yank the wrong gem (as shown in the output you posted). I think everything is working as it should.
