### ISSUE TITLE
allowed_push_host and Error Message

### ISSUE THREAD

**Issue by bewitchingme** [rubygems/rubygems.org#1921]
Filed an issue against rubygems [here](https://github.com/rubygems/rubygems/issues/2633) regarding an error I received after yanking a gem and trying to push a different (unique, unseen version number prior to that push) version of it.  The push did not go well and it had to do with the value of allowed_push_host:
```
GET https://rubygems.org/latest_specs.4.8.gz
304 Not Modified
Pushing gem to http://rubygems.org...
POST http://rubygems.org/api/v1/gems
307 Temporary Redirect
```
The above errors are not very specific with regards to what went wrong (aside from knowing how the web server responded to it) and I found that allowed_gem_host has to be set to https://rubygems.org in the `.gemspec` file and not http://rubygems.org

Is it possible to add a better error message for `gem push` to ensure that future gem owners will have a strong indication on how to resolve this issue?

**Comment by sonalkr132** [comment]
> The push did not go well

hey, sorry about delay in response here. what do you mean by push didn't go well? what was the error message, I don't notice any in your code snippet.

>  an error I received after yanking a gem and trying to push a different (unique, unseen version number prior to that push) version of it. 

further clarification on this would be appreciated as well. I don't think yanking of version has to do anything with whatever error you saw?

**Comment by sonalkr132** [comment]
Please feel free to reopen when you have time to reply. I don't see any issue here.

**Comment by bewitchingme** [comment]
> Please feel free to reopen when you have time to reply. I don't see any issue here.

Hi there,

The above is actually all that is output by the gem push command.  The reason why there's no lengthy or explanatory error message is why I created the issue in the first place.

**Comment by sonalkr132** [comment]
Thank you for explaining. This needs to be fixed in the gem client. I am not sure why it was redirected here. Please free to reopen a new issue on rubygems/rubygems if the existing issue doesn't get any response.
