### ISSUE TITLE
Please provide SHA256 (or equivalent) checksums for releases

### ISSUE THREAD

**Issue by mudler** [rubygems/rubygems.org#1922]
Hi,

Could you please provide checksums for releases? We think https://github.com/rubygems/rubygems/issues/939 still is relevant as by today, because even if the downloads happens via https, we have no way to check if we had a corrupted file in the end.

In our case, we need that because we verify that we have a consistent download inside our build infrastructure. I'm aware that gemfiles can be checked via API 
e.g. ```curl https://rubygems.org/api/v2/rubygems/rubygems-update/versions/3.0.2.json |jq .sha -r```. Also, we store those checksums in manifests files that other users are consuming and we use that to automatically verify the package integrity.

But this unfortunately doesn't applies to tgz releases of rubygems itself that can be downloaded [from the website](https://rubygems.org/pages/download), because the content from the gem differs.

cc: @dragonchaser
Thank you

Original discussion: https://github.com/rubygems/rubygems/issues/2656

**Comment by dwradcliffe** [comment]
I hate to do this but I'm going to throw this back to the other repo (for now). If the client release process could upload the checksum to s3 we can setup a url for it on this side no problem.
