### ISSUE TITLE
Docker commands needed to set up the project

### ISSUE THREAD

**Issue by jhsu802701** [rubygems/rubygems.org#1925]
I know that starting up PostgreSQL, memcached, and ElasticSearch is simply a matter of entering "docker-compose up", which makes use of the docker-compose.yml file.

What's the command for starting up the Rails server AND being able to view the app at http://localhost:3000?

While I use Docker for Rails projects, I use it differently than everyone else does.  For more details go to https://www.differentdockertutorial.com/ and https://www.legacyrailsapps.com/docs/a-00.html .  And I rely heavily on Bash scripts, because I can't remember every command, parameter, and flag necessary to do what I need to do.

**Comment by sonalkr132** [comment]
> What's the command for starting up the Rails server 

`rails s`

**Comment by jhsu802701** [comment]
"rails s" is what you use when you're working on the app in the host system.  Exactly what is the command to use given the use of Docker in this app?

**Comment by dwradcliffe** [comment]
We use Docker in two ways:

In **development**, we use docker-compose (as you mentioned) for easy setup of the dependencies. We typically don't use docker for running the actual application in development. Personally, I've found that it's much easier to just run rails locally on my computer than run it inside docker. So as @sonalkr132 mentioned, once you have [everything setup](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#development-setup) you can just run `bin/rails s` to run the local server.

In **production** (and staging), we run the application in docker. This image is built with the Dockerfile you see in this repo.

Hopefully that helps clear it up! 😄

**Comment by jhsu802701** [comment]
Thanks.  Since I'm not responsible for the production environment (and don't even have access to it), the Dockerfile doesn't concern me.  Now I understand that the official way of doing things is to run Rails in the host OS but use Docker (through the docker-compose.yml file) for other servers.
