### ISSUE TITLE
Should I be able to download a gem marked as yanked? (bootstrap-sass 3.2.0.3)

### ISSUE THREAD

**Issue by uri** [rubygems/rubygems.org#1941]
Here is the gem in question: https://rubygems.org/gems/bootstrap-sass/versions/3.2.0.3

Original issue: twbs/bootstrap-sass#1195

This gem is marked as yank but from my testing I can still install it via Ruby gems. I'm not entirely sure that this is not a local caching issue but I'm [seeing the same behavior on Heroku](https://github.com/twbs/bootstrap-sass/issues/1195#issuecomment-479047836).

**Comment by evanphx** [comment]
Yes, we normally only remove gems from the index on yank, not from the backend storage. Because everything should be using the index, the fact that they exist in the backend storage doesn't matter.

We only delete gems from the backend storage in very specific situations.

**Comment by D-system** [comment]
If it's in your `Gemfile.lock` it'll be able to download/install to avoid breaking builds too often. Imagine if Rails block all yanked versions.

**Comment by lirantal** [comment]
A bit of a plug but I feel it's more relevant than ever - I also read in the other thread about the issue where users had complained about cached versions of modules etc. If you however scan your project with Snyk we don't actually need your gems to be installed and instead can make use of the `Gemfile.lock` to figure out your dependency tree and alert of any vulnerabilities you have, including this malicious version of bootstrap-sass.

You can try it out here https://snyk.io/signup and connect with GitHub/BitBucket etc and test your repos.

**Comment by glebm** [comment]
> We only delete gems from the backend storage in very specific situations.

3.2.0.3 contains malware, could you please delete it?

**Comment by dwradcliffe** [comment]
Evan's original message was actually incorrect. [Since 2015](https://blog.rubygems.org/2015/04/13/permadelete-on-yank.html) we do remove the file from the backend storage which makes it impossible to download from RubyGems.org. (This doesn't impact any 3rd party mirrors, which we have no control over.)

In this case, since the gem was not yanked via the normal methods it was yanked incorrectly which left it in an invalid half-yanked state, as you noticed. This has been resolved and the gem should no longer be able to be downloaded.

**Comment by schmijos** [comment]
A follow up question:
Do you still store yanked versions somehow, lets say for research? Or are the CVEs and the [Github issue](https://github.com/twbs/bootstrap-sass/issues/1195) the only sources to get first hand information?

**Comment by dwradcliffe** [comment]
> Do you still store yanked versions somehow, lets say for research?

Yes, as mentioned in the blog post the s3 bucket is versioned, but they are not accessible without admin interaction.
