### ISSUE TITLE
2FA: make UI+Api the default ?

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#1958]
when enabling 2FA it was set to "web only"
would be more secure to default UI+API ... whoever wants less security can disable it easily
... maybe wait for this until bundlers `rake release` works with OTP https://github.com/bundler/bundler/pull/7005

**Comment by dwradcliffe** [comment]
Sounds like a good idea 👍

**Comment by ecnelises** [comment]
Good advice. I think it won't break any existing tool/workflow.
