### ISSUE TITLE
pp gem exists but not on the rubygems.org website

### ISSUE THREAD

**Issue by localhostdotdev** [rubygems/rubygems.org#1959]
e.g. https://rubygems.org/gems/pp says "This namespace is reserved by rubygems.org."

but having `gem "pp"` in my Gemfile and doing `bundle open pp` reveals an actual gem (which is not what I expected (e.g. pretty print from ruby):

gemspec:

```ruby
Gem::Specification.new do |spec|
  spec.name          = "pp"
  spec.version       = Pp::VERSION
  spec.authors       = ["claudiob"]
  spec.email         = ["claudiob@gmail.com"]
  spec.description   = %q{Super Pretty Print}
  spec.summary       = %q{A Super Pretty Print}
  spec.homepage      = "https://www.github.com/claudiob/pp"
  spec.license       = "MIT"

  spec.files         = `git ls-files`.split($/)
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]
end
```

```
Pp.run subdomain: ENV['CAMPFIRE_SUBDOMAIN'], room_id: ENV['CAMPFIRE_ROOM_ID'], token: ENV['CAMPFIRE_TOKEN']
```

which is actually something to do with campfire.

pinging @claudiob in case

**Comment by dwradcliffe** [comment]
I haven’t looked in depth yet but I’m guessing there was a non-stdlib version before we reclaimed the name and you have that version installed.

Cc @hsbt

**Comment by hsbt** [comment]
@dwradcliffe I listed the same case of `pp` to https://gist.github.com/hsbt/f0ea1c4c214828a09b4d808b72b9bb24

Can you transfer their ownership to me (and ruby core team)? We handle to yank or update them.

**Comment by dwradcliffe** [comment]
I can later today

**Comment by dwradcliffe** [comment]
@hsbt You should be able to access it now

**Comment by sonalkr132** [comment]
Hi, I yanked the only version of pp. Nothing more to do here. 
Thank you for reporting.

**Comment by PartTimeLegend** [comment]
And here I am running a legacy project that required pp and finding this gem has been yanked today.

**Comment by sonalkr132** [comment]
I am sorry you had to find out about it this way. It was meant to be removed way back. Do not have any downloaded copy of the version?

**Comment by sonalkr132** [comment]
We have re-uploaded the yanked version here: https://rubygems.org/gems/legacy-pp
We sincerely suggest migrating away from its use in any project.
