### ISSUE TITLE
Executables missing in API

### ISSUE THREAD

**Issue by manveru** [rubygems/rubygems.org#1992]
i'm trying to get the `executables` field from the gemspec via the API:

```
>> dep = Gem::Dependency.new('t', '3.1.0')
=> <Gem::Dependency type=:runtime name="t" requirements="= 3.1.0">
>> Gem::SpecFetcher.fetcher.spec_for_dependency(dep).flatten.first.executables
=> []
```

And here, when loading it from the gemspec directly:

```
>> gem = Gem::RemoteFetcher.fetcher.download_to_cache(dep)
=> "/home/manveru/.gem/ruby/2.5.0/cache/t-3.1.0.gem"
>> Gem::Package.new(gem).spec.executables
=> ["t"]
```

This was rather surprising, so I checked the underlying APIs:

```sh
$ curl -s https://rubygems.org/api/v1/gems/t.json | jq .executables
null
$ curl -s https://rubygems.org/api/v2/rubygems/t/versions/3.1.0.json | jq .executables
null
```

i assume the data comes from https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/rubygem_searchable.rb which doesn't seem to add the executables to the ES index.

Could you please add this information?

UPDATE: I also found that the licenses field is missing, which would be quite handy to have.

**Comment by sonalkr132** [comment]
> Could you please add this information?

We are not storing this information as of now. I don't see any downside to adding this to versions table.
I am closing this as dup of #1563. Feel free to add your comments there.

> I also found that the licenses field is missing

license is there. please check the links you shared.
