### ISSUE TITLE
 cannot edit profile

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems.org#1994]
when I login and visit profile/edit then I get redirected back to the homepage. cc/ @evanphx

**Comment by rubyFeedback** [comment]
For what's its worth, it works for me, so the issue may be particular for some profiles but not all (not sure if that helps, just providing some feedback; guess the re-direct action may be a helpful indicator as to where the problem may occur in the code).

**Comment by schneems** [comment]
The issue was a cached page, it’s been fixed
