### ISSUE TITLE
Supporting tags/tagging + searchable API

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2011]
This may be a better fit in https://github.com/rubygems/rubygems/issues but the reason I started
it here is that I think the search-functionality may be better to consider for the rubygems.org team, before it may (should?) be suggested to integration into "core" rubygems.

Anyway - I would like to propose the addition of tags to a rubygem.

What I mean with tag is something that can be used to describe a rubygem.

For example, if you build a game, and publish it as a gem it may be useful to tag it as "game".

This could then be used to allow people to search for this on rubygems.org.

The ruby toolbox exists, and it is nice, but I think some of the functionality could/should be provided by rubygems.org e. g. in particular when people may want to find something.

Now - people might be tempted to misuse this so I suggest to keep the tags as an array with not more than 3 entries. If this is too low, it can always be extended at a later time; I just don't want people adding 50 tags or something.

Additionally we may have to add a listing of allowed tags, but it may be simpler to be a bit more flexible and just allow the gem author any arbitrary tag (as long as it is not more than three); while some people might still misuse it, I think it could be tested for liberal/loose (don't think tags can be abused for much at all; internally these should just be a simple Array).

Why might this functionality be useful? Well, take games - people could search for games written in ruby here on rubygems. Same with other tags (we actually may have to settle for some tags at the least initially, so that we know how people may classify certain projects).

I am not sure if I am way off with my idea so I think I will stop for now. If the idea is far off, don't hesititate to state so. If the idea may have merit, it may be nice to hear what could/should be improved upon or discussed about in regards to giving ruby gem authors the ability to tag (additionally classify) their gems.

I'd prefer to keep this all simple, though, both implementation-wise and from a user-point of view (simple API; just extend the .gemspec a bit) - but obviously the tags are most useful only if there is some way to search for it via the search interface on rubygems.org.

**Comment by qrush** [comment]
My feeling on this for a long time has been that https://www.ruby-toolbox.com/ is a way better "category" search. It's also a project that is old as this one :bowtie: 

I'd rather defer to them for tagging/associating/classifying gems and leave the hosting challenges here. Clearly it's worked out well so far! I'd be curious if you've checked that project out at all.

**Comment by sonalkr132** [comment]
dup of #1651
