### ISSUE TITLE
Visual inconsistency: Continue link in "2FA successful" page

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/rubygems.org#2012]
After enabling 2FA successfully, the text link *Continue* at the bottom of the screen has a weird symbol next to it, instead of some arrow or other "next" indicator.

Screenshot:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/211/58401625-a250db80-805e-11e9-87a5-64254d520782.png">

**Comment by dwradcliffe** [comment]
Looks like this was added in https://github.com/ecnelises/rubygems.org/commit/a8e7c0062266919f26e6efbc18748f41622d5d15#diff-37c9b835927e3c363588f172de9bb6faR184

@sonalkr132 do you know what's up here?
