### ISSUE TITLE
Need to more precisely report a failure to push caused by a previously yanked gem

### ISSUE THREAD

**Issue by keithrbennett** [rubygems/rubygems.org#2013]
This issue was originally posted on the rubygems (not rubygems.org) page as https://github.com/rubygems/rubygems/issues/2771, but it was closed and I was asked to post it here instead.

It was born out of https://github.com/rubygems/rubygems/issues/2769. The poster of that issue (@matheussilvasantos) went through a lot of time and effort troubleshooting his failure to push his gem. It turned out that the name of his gem was used by another gem, but that other gem had been yanked, so the cause of the problem was not apparent.

For example:

User #0 sometime in the past pushed DynamoRB version 0.1.0, and probably other versions.
User #0 subsequently yanked the gem.
User #1 writes a new gem named dynamorb, and tries to push version 0.1.0, but gets this error:

```
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

However, `gem list --remote dynamorb` shows no gem by that name.

On the high level, I think we need a better way to identify and report this error.

Would it be possible for `gem push` to somehow consult the list of gem names at https://rubygems.org/names and output a more precise error message if this problem occurs?

**Comment by rubyFeedback** [comment]
I can relate to this and agree. On a not completely related issue, I once removed an old gem completely to see what happens after e. g. ~100 days. When I re-pushed the gem after 100 days, the old versions that were previously yanked, appeared again in the list. (I actually only did so to try out what would happen, and whether I could clear the old history that way. :D)

The issue here seems fairly simple to fix, e. g. the check probably does a .downcase somewhere or something. (I personally only use downcased names in general, it simplifies lots of things IMO).

**Comment by dwradcliffe** [comment]
What if we changed the output to this:

```
Pushing gem to https://rubygems.org...
There is already a yanked gem with this version (foo-gem 1.1.1).
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases and choose a new version number to push.
```

**Comment by keithrbennett** [comment]
@dwradcliffe Yes, the addition of "There is already a yanked gem with this version (foo-gem 1.1.1)." would help, but I don't think version should be relevant, because wouldn't the 2nd pusher be unauthorized to push _any_ version of this gem? As a test, I just tried to push a gem of mine with a different rubygems user, and got this error message:

`You do not have permission to push to this gem. Ask an owner to add you with: gem owner [gem_name] --add [your_email_address]`

I think testing this first before testing the existence of the version would be better. The resulting error message would have made the situation much clearer.

@rubyFeedback, I agree, the gem name should be compared case insensitively on the server, but I think that's happening already, and that's why there is the error version that there is. 

My gut reaction was that gem names should be permitted in different cases, but then I remembered that by default Mac filesystems preserve case but are case insensitive! For example, this is what happens on my Mac(!):

```➜  temp   ls
➜  temp   mkdir a
➜  temp   ls
a
➜  temp   mkdir A
mkdir: A: File exists
➜  temp   ls
a
➜  temp   ls -d a A
A a
```

**Comment by dwradcliffe** [comment]
If all versions of a gem are yanked, the namespace eventually becomes available for anyone to use.

**Comment by keithrbennett** [comment]
@dwradcliffe I don't think that's true. The problem was that all versions _had_ been yanked, and the gem name was not listed in the list of available gems. Or are you saying that when more time had elapsed that would have been the case? Even if this is true, we still have the problem until that time.

**Comment by matheussilvasantos** [comment]
@dwradcliffe the problem with the message `There is already a yanked gem with this version (foo-gem 1.1.1).` is that it is not clear if it is our gem or if it is a gem from another user that has been yanked.

**Comment by sonalkr132** [comment]
Hi, https://github.com/rubygems/rubygems.org/issues/2110#issue-484361908 better explains the issue. I hope its fine if we track it there and close this.
We are working on adding [a filter for yanked gems in search](https://github.com/rubygems/rubygems.org/pull/2262) and a guide for checking availability of gem name.

**Comment by keithrbennett** [comment]
@sonalkr132 #2110 addresses the same underlying problem but makes no mention of the manifestation of it that is the subject of this issue. Would the fix for #2110 include making the error message that is the subject of this issue clearer?

**Comment by sonalkr132** [comment]
> makes no mention of the manifestation of it that is the subject of this issue.

yeah, I guess we should also add a yank check before this message.

**Comment by keithrbennett** [comment]
The code change (see https://github.com/rubygems/rubygems.org/compare/3614d30..f880b72, issue PR #2317) does _not_ resolve this issue, because the messages do not give the reader any clue that the reason for this could be someone else's gem.

I am not clear about the branch condition, so I don't know which message, or both, should be changed, but I think adding something like this would be helpful and would address this issue:

"This is sometimes caused by your gem name having been used in the past by a different owner."

I also think this should be added, to save the person the time of researching a workaround:

"There is currently no way to reuse this version number for this gem name."

**Comment by sonalkr132** [comment]
> A yanked version already exists (#{version.full_name})

Would this message not be enough for user to check if a yanked gem already exists? I understand as of now, there are only indirect ways of checking yanked gems and we are trying to address that with #2110. We will also add a guide for checking availability for gem name.

> This is sometimes caused by your gem name having been used in the past by a different owner.

For a precise message we should be further checking if current pusher is same as owner of yanked version. IMHO, this would not be needed with update error message and fixes we planning for #2110. Feel free to open PR with your preferred message tho, we can discuss there.

> There is currently no way to reuse this version number for this gem name

I would not recommend this. We don't allow for this for reasons I mentioned in my reply on #2110.

**Comment by sonalkr132** [comment]
> I would not recommend this.

I meant this about "currently" part. 

> Please use a new version and retry

It would be awesome if you can open a new issue about why this message shouldn't be recommended workaround.

Sorry, I forgot to update this issue when I opened my PR. I feel I would have more receptive to your suggestions had I not merged it already :sweat_smile:

**Comment by sonalkr132** [comment]
See https://github.com/rubygems/rubygems.org/pull/2324
