### ISSUE TITLE
"API Access" section of profile suggests invalid command with 2FA

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems.org#2026]
If you go to https://rubygems.org/profile/edit , under "API Access" it lists this command:

```
curl -u $YOUR_USERNAME_HERE https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials
```

However, if you have 2FA enabled, you'll just wind up with this:

```
~$ cat ~/.gem/credentials 
You have enabled multifactor authentication but no OTP code provided. Please fill it and retry.
~$
```

So, in light of that:

1. Is there an equivalent command to do this with 2FA enabled?
2. If so, what is it?
3. If not, how could one be added?

**Comment by duckinator** [comment]
Okay, looks like running `gem signin` handles it entirely -- should we just recommend that instead?

**Comment by ecnelises** [comment]
`/api/v1/api_key` requires a `OTP` field in HTTP header if 2FA is enabled for API. So try `curl -H "OTP: $YOUR_OTP_HERE" -u $YOUR_USERNAME_HERE https://rubygems.org/api/v1/api_key.yaml`.

So we may need to change the description..
