### ISSUE TITLE
Malware packages on RubyGems

### ISSUE THREAD

**Issue by lingfennan** [rubygems/rubygems.org#2028]
Package jOjOjO is malware that steal user information. Please consider removing it. This package upload information to a remote server including: name of the downloaded package, name of the intended package, the ruby version and whether the process was running as sudo. It seems to be part of the malware campaign that was identified and removed in NpmJS registry. Please find links to the package and NpmJS report below.

In addition, the corresponding author Homografo has uploaded 225 other packages, which currently do nothing, but may turn malicious according to their description. Please consider removing them as well.

https://www.npmjs.com/advisories/838
https://rubygems.org/gems/jOjOjO
https://rubygems.org/profiles/homografo

**Comment by rubyFeedback** [comment]
https://rubygems.org/profiles/homografo is evidently a fake-user; e. g. package names listed like jeykll, which attempts to focus on making a typo when wishing to install jekyll instead.

I believe that manual banning and prevention is not an ideal solution, though, as people who have malicious intentions can easily create new users and publish gems. Perhaps we can come up with some ideas and changes that could make it simpler to distinguish between fake accounts and fake users, and real users on rubygems.org.

Using levenshtein distance to estimate which gems may be deliberate typos is a useful suggestion but I think this will only detect some possibly malicious gems. Perhaps in the long run we can have some credibility system, something like some ranking system or so ... I have no good suggestion how this should look like at this point, though, but perhaps someone else can come up with something that can a) handicap malicious accounts without b) handicapping real people without malicious intentions.

**Comment by simi** [comment]
Anyone looking into this?

**Comment by lingfennan** [comment]
Any update? Seems that nobody tries to yank the jOjOjO package. Is it because that the information that it collects is not sensitive? If so, is there any policy for allowed/disallowed user tracking on RubyGems? Thanks!

**Comment by lingfennan** [comment]
For the corresponding NpmJS campaign, the author started typo-squatting years back (e.g. earliest version of requesst is published in 2015). All of the relevant packages were then updated to be malicious on April 2019. 
https://libraries.io/npm/requesst/versions

**Comment by sonalkr132** [comment]
Hi @lingfennan. I have yanked all gems of the user and locked the account. 
I had plans of blocking new releases on these gems, however, on further analysis of [the potentially blockable gems](https://gist.github.com/sonalkr132/4d1c9ecf28ce980791554f428ba38d55) I dropped the idea. 880 gems out of 1300 on the list we either already yanked or belonged to `homografo` user. 
> Is it because that the information that it collects is not sensitive? 

Kind of. Historically we have only yanked gems which try to steal keys or cookies.
The real issue for me personally was reducing the volume of typo-squatting tickets we routinely get on the help site. Yanking them manually doesn't help much, there are always more typos to be squatted. 168 out of 226 gems of the user would have been blocked by the Levenshtein distance rule we are using, I am hoping we have made some progress on this.

#2058 has suggestions on improving our rules. Please leave any comments you may have there.
