### ISSUE TITLE
Email notification on new version push

### ISSUE THREAD

**Issue by ohaddahan** [rubygems/rubygems.org#2053]
Send an email to all the Gem registered authors whenever a new version was pushed with the details by whom it was pushed.

More people have 2FA on their email than on their RubyGems account so the chance of it
being hacked is lower.

They will know they / their colleagues didn't push this version and will
notify RubyGems about it.

**Comment by colby-swandale** [comment]
See #1950

**Comment by rubyFeedback** [comment]
Seems to be sort of a duplicate indeed, but nonetheless +1 from me for this feature.

**Comment by sonalkr132** [comment]
Users will receive the gem push notification once #2112 gets deployed.
