### ISSUE TITLE
Send notification to users on account login

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2056]
Similar to #1950 and the way Netflix does this, we should send an email to users when their account has logged into rubygems.org. This would help users in identifying if their account was compromised and needing to perform a password reset/contacting support.

**Comment by rubyFeedback** [comment]
I agree with the basic idea.

**Comment by indirect** [comment]
Definitely agree this would help. We should probably only send the email when it's a new device logging in, though, and not anytime anyone logs in ever. :)
