### ISSUE TITLE
MFA 2D barcode too large for 1Password desktop

### ISSUE THREAD

**Issue by gshutler** [rubygems/rubygems.org#2060]
I use 1Password and when setting up MFA the desktop application was unable to capture the 2D barcode as it was too large. To set it up I had to use the mobile app which could capture a barcode of any size.

The 2D barcode presented by rubygems.org is particularly large, probably around double the width of most I've encountered, and the first I've not been able to use 1Password with.

I can't see a way to go back to the screen to see it again, but have taken a screenshot to give an approximation of what 1Password's capture size is. I would guess it would capture anything 200-300px wide, and it rendered on my screen at around 500px.

![1Password_-_Code_Scanner_and_New_Issue_·_rubygems_rubygems_org](https://user-images.githubusercontent.com/81344/61202882-b325e100-a6e0-11e9-85b3-31cbbf3ee372.png)

**Comment by gshutler** [comment]
I would guess the [container here](https://github.com/rubygems/rubygems.org/blob/8d922fd9b211859ed694ddd169afc61e1f1a7029/app/views/multifactor_auths/new.html.erb#L4-L6) would need some modification.

**Comment by sonalkr132** [comment]
Closed by #2090
