### ISSUE TITLE
Translation missing for "PUSHED BY" (all locales)

### ISSUE THREAD

**Issue by fukayatsu** [rubygems/rubygems.org#2071]
example: https://rubygems.org/gems/rails/versions/6.0.0.rc2?locale=en

![image](https://user-images.githubusercontent.com/1041857/61680557-f61d2f80-ad44-11e9-84a4-d987c347825b.png)

```
translation missing: en.rubygems.gem_members.pushed_by
```

**Comment by Akrabut** [comment]
I think the problem lies [here](https://github.com/rubygems/rubygems.org/blob/master/config/locales/en.yml#L301), where `Pushed_by` and `Yanked_by` are missing.
I'll open a PR with the fix.

**Comment by sonalkr132** [comment]
Closed by #2094
