### ISSUE TITLE
datagrid version 1.0.6 is compromised and a malware, please yank!

### ISSUE THREAD

**Issue by lingfennan** [rubygems/rubygems.org#2072]
Hi,

datagrid version 1.0.6 is compromised and a malware. Please remove it! The attack is similar to the recently reported bootstrap-sass malware! It leaves a backdoor on the affected server.

The code snippet is located at:
datagrid-1.0.6/lib/datagrid/drivers/abstract_driver.rb

https://rubygems.org/gems/datagrid/versions/1.0.6
https://snyk.io/blog/malicious-remote-code-execution-backdoor-discovered-in-the-popular-bootstrap-sass-ruby-gem/

**Comment by indirect** [comment]
Yanked, thanks for reporting.
