### ISSUE TITLE
simple_captcha2 version 0.2.3 is compromised and a malware, please yank!

### ISSUE THREAD

**Issue by lingfennan** [rubygems/rubygems.org#2073]
Hi,

simple_captcha2 version 0.2.3 is compromised and a malware. Please remove it! The attack is similar to the recently reported bootstrap-sass malware! It leaves a backdoor on the affected server.

The code snippet is located at:
simple_captcha2-0.2.3/lib/simple_captcha/middleware.rb

https://rubygems.org/gems/simple_captcha2/versions/0.2.3
https://snyk.io/blog/malicious-remote-code-execution-backdoor-discovered-in-the-popular-bootstrap-sass-ruby-gem/

**Comment by indirect** [comment]
Yanked, thanks for reporting.
