### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS occurs when accessing some gem paths

### ISSUE THREAD

**Issue by koic** [rubygems/rubygems.org#2098]
AFAIK, ERR_TOO_MANY_REDIRECTS occurs when accessing the following URLs.

- https://rubygems.org/gems/faker
- https://rubygems.org/gems/rails

ERR_TOO_MANY_REDIRECTS does not occur when the URLs ends with a slash.

- https://rubygems.org/gems/faker/
- https://rubygems.org/gems/rails/

The following URLs (and others) does not occur ERR_TOO_MANY_REDIRECTS even if it does not end with a slash.

- https://rubygems.org/gems/bundler
- https://rubygems.org/gems/rubocop

**Comment by dwradcliffe** [comment]
I'm not able to reproduce this. Is this just in your browser? Can you try clearing your browser cache and see if it still does it?

**Comment by koic** [comment]
I was wrong. This issue was caused by the connection using VPN in my environment. Thank you for your quick response.
