### ISSUE TITLE
Allow gem authors to opt into their gems requiring 2FA.

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2106]
We should add a way for gem authors to opt into having their gems require 2FA being enabled to perform any actions on the gem. This will help popular gems that are being maintained by a team ensure that everyone is protecting their accounts.

I'm not sure about how to go about this one yet, maybe the metadata in gemspec?

**Comment by colby-swandale** [comment]
If we want to go for maximum security, we may want to make this rule something that cannot be undone once enabled

**Comment by rubyFeedback** [comment]
Opt into (aka non-forced) seems fine. For the smaller gems, or possibly gems not maintained or updated often, it is most likely not worth it to enable 2FA, considering that ... well. A 150 downloaded gem of age 10 years or more, is probably not downloaded by anyone anyway.  Some of my gems are like that, sort of. :P

Metadata should be the simplest approach. Perhaps something a bit longer, such as:
    .two_factor_authentification= or so (2FA looks a bit strange in ruby code or gemspecs alone).

I have no substantial opinion on the "it can not be undone" part; either way how it is decided, I think it should be noted down, in particular if it can not be undone - perhaps there may be legitimate reasons to undo it; I understand the idea to not allow impersonators more power to cause damage of course.
