### ISSUE TITLE
[Security] gaug.es marketing tracker has unreasonable levels of access

### ISSUE THREAD

**Issue by DanielHeath** [rubygems/rubygems.org#2109]
Anyone with deploy access at gaug.es or fastly-insights.com has access to obtain the following:

 * API keys for all logged-in users who load the tracker.
 * Unhashed passwords for all users who login with the tracker loaded.
 * Secret key used for MFA

I'm sure they have wonderful security practices, but this still seems super risky.

Worse, it's not enough to remove it only from 'sensitive' pages, as they can replace the links and use `history.pushstate` to avoid navigation.

**Comment by sonalkr132** [comment]
fastly is our sponsor and all our traffic flows through fastly cdn hosts, so we really do much for fastly besides trusting them.
We are removing  gaug.es in https://github.com/rubygems/rubygems.org/pull/2517

**Comment by sonalkr132** [comment]
closed by #2517
