### ISSUE TITLE
"Advanced" Features for gems + services on rubygems.org

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2127]
I would like to have a bug-tracker, on a per-gem basis, on rubygems.org.

This may be wishful thinking; and "long-term goals". And, most importantly, people
could say: "hey, just use github".

Now this is possible, yes; but it would not be quite the same. For example, right
now we require a github account in order to comment on issues, report bugs etc..
(excluding direct emails, but I think it may be a bit overkill to email the rubygems.org
devs directly).

But even aside from the github account requirement, there are other reasons
for not necessarily HAVING to have an account at github. For example, github
implies the use of git. Most people love git, I get it. But does it mean that in
order to publish ruby code, we all must use git? IMO git is mostly useful for
collaborative work; for solo projects on rubygems where the total amount of
users is, well, a single person most of the time, it does not really seem to be
all that necessary. And while I get that you can browser history, look for
which code broke something, for smaller gems it is not that important.

You could also connect this with e. g. donation-based support, e. g. people
who may donate something, could get some more advanced functionality
on rubygems.org. I am not necessarily advocating this, because it would
also add an apartheid-situation where some functionality is hidden away,
BUT I also wanted to specifically mention it too (or you could say that
e. g.a fter a grace period, the functionality will become available to 
everyone, after the initial funding).

I could work around the above issue of course, and just add github
projects to all my gems. And there were people who filed issues there
as well (since I am notoriously chaotic, I often did not notice these
issues for a long time ... this is also a reason why I'd like a sort of
bugtracker directly on rubygems.org).

Writing a fully fledged bug tracker is probably quite a lot of work, so
I don't suggest per se to make everything perfect from the get go,
add loads of functionality, but instead add simple things - basically
the most important part would be HTML textarea for people to 
comment on, and you can respond there. Initially I would limit
it solely to accounts on rubygems.org, although at a later time
you could allow for guest accounts or something like that, to
limit the entry barrier (though the spam-problem may also be 
real).

Anyway - this is really just an idea. It obviously depends a LOT on
what the rubygems.org folks and maintainers think. If they think
it is a horrible idea then please close the suggestion. :)

If it is thought that the suggestion may have some merit in one or
the other way, I would suggest to keep it open for a few months
or so (I don't like open issues myself, so I would suggest to keep
this issue to a maximum time life between 6-12 months, in order
to not pollute the issue tracker with too many hard-to-implement
suggestions).

Thanks!

**Comment by dwradcliffe** [comment]
Over the years we've tried really hard to keep focused on hosting and serving gems reliably. We have said no to lots of cool ideas to ensure that we can keep doing our mission. There are lots of good options for bug trackers out there, and we provide a way to link to anything you want from your gem. Thanks for the idea, but we're not interested in building and maintaining a bug tracker inside RubyGems.org.
