### ISSUE TITLE
Licence field in general (or perhaps the display part on rubygems.org): GPLv2 versus GPLv2 (no later clause)

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2128]
As some of you may know or not know, RMS has recently retired from
the FSF.

I will not go into the why here, as it is not important for this
issue request, but during some discussions it was pointed out
that GPLv2 projects with the "or later" clause can be updated
to GPLv3, which then may make it incompatible with GPLv2 - thus
restricting our freedom to incorporate changes back into 
GPLv2 because GPLv2 is not compatible to GPLv3 (since the 
latter does not allow for re-licence to a lower number, whereas
GPLv2 with the "or later" allows it). I was actually unaware
of that being a possibility but it was convincing to me.

This brought me to rubygems.org.

Most of my projects are GPLv2, but without the later clause.
(I did this independent of the recent news in regards to
RMS; and it was evidently also independent of the situation
that GPLv2 "or later" projects can be changed into GPLv3
and then be incompatible, which I consider as unfair - but
I actually specifically did NOT include the "or later" clause
because the GPLv3 has many problems, regardless of the "or
later" situation).

I would like to propose a slight change to rubygems.org or
rubygems in the sense that people should be able to specify,
optionally, whether the "or later" clause applies or not.

This could either be an entry such as "GPLv2"; and another
one "GPLv2 or later", or vice versa.

The field is mostly just for notification purpose; most
licence is noted down in e. g. LICENCE.md or some similar
file, where we can specify that there is "no later" clause,
but most people may assume that GPLv2 software, as-is, 
includes the "or later" clause.

See also the linux kernel:

https://www.kernel.org/doc/html/v4.16/process/license-rules.html

"The Linux Kernel is provided under the terms of the GNU General
Public License version 2 only (GPL-2.0)"

For example, right now in my projects there is a statement such
as:

  GPL-2.0

But this could include GPL-2.0 with later, and without later.

I am not sure if it is actually worth to add this to the 
licence entry, but I thought I should mention it nonetheless,
since sometimes licences do not seem to apply fully; and I
think we can not "invent" random licences to display.

Otherwise I might include something like "GPL-2.0 (no later clause)"
or something like that, a bit like BSD 2 versus BSD 3 clause
licences (or 4 clauses ... don't remember how many clauses
they used to have).

This here could be filed at rubygems instead, but I think it
may also relate to the display at rubygems.org on a per
page setting. Perhaps it may also be worthwhile to add
some way to provide some link to the licence at hand,
but I am not sure if this is a useful addition either.

**Comment by dwradcliffe** [comment]
We just display whatever license is put in the gem spec. Gem owners can specify any license they want.
