### ISSUE TITLE
Response format of dependencies endpoint is unspecified for multiple version requirements

### ISSUE THREAD

**Issue by dnrce** [rubygems/rubygems.org#2130]
The specification for the `/api/v1/dependencies` endpoint does not define the format of the response when a gem has a dependency with a complex version requirement such as `foo (~> 1.1, >= 1.1.3)`.

The de facto spec is that such a dependency will be represented as a single string separated by commas and spaces, e.g. `["foo", "~> 1.1, >= 1.1.3"]`. This is what [bundler expects](https://github.com/bundler/bundler/blob/0b5da910e71760eb585b34d08d43ea31b988ca24/lib/bundler/fetcher/dependency.rb#L69).

However, the lack of codification here has contributed to issues such as https://issues.sonatype.org/browse/NEXUS-17477 with third-party gem servers, and having an explicit spec would be helpful toward resolving differences.

**Comment by simi** [comment]
@dnrce closing this since related API was deprecated and currently is mostly not available for public usage anymore.

> However, the lack of codification here has contributed to issues such as https://issues.sonatype.org/browse/NEXUS-17477 with third-party gem servers, and having an explicit spec would be helpful toward resolving differences.

AFAIK gem server API spec is planned to help third-party gem servers keep in sync with rubygems.org.
