### ISSUE TITLE
Pushing a gem multiple times 

### ISSUE THREAD

**Issue by asantosca** [rubygems/rubygems.org#2131]
I have a question.

My current problem is I would like to push a gem many times a day to validate what is the time between pushing x publishing x download.
I know that there are download rates for the API, but there's no documentation on the maximum number of uploads for a gem.
You provide a very valuable service to the community and I wouldn't like to cause any actions that could be seen as abuse according to the code of conduct.
If possible, please let me know how many times a day would be acceptable for a gem to be pushed.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by dwradcliffe** [comment]
The gem push limits are:
- 150 pushes in 10 min
- 450 pushes in 1000 min
- 600 pushes in 10000 min

defined here:
https://github.com/rubygems/rubygems.org/blob/d2f0e0781622775afdbb0a7a24bb8b1e2afe415f/config/initializers/rack_attack.rb#L63-L73

I'm guessing you'll be fine. If it becomes a problem we'll try to reach out. Thanks for asking! 😄
