### ISSUE TITLE
Obtaining ownership of an abandon gem: 'freight'

### ISSUE THREAD

**Issue by wanchic** [rubygems/rubygems.org#2134]
Hey All,

  I am new to this group...hello! Sorry ahead of time if this is not the place to post this.

My name is Eric Wanchic and I've been looking for a base name to start a new gem package. I think I found it with 'freight'.

I feel that this has been severely abandoned, and this gem had no real purpose to begin with.

- It's currently at version 0.0.0.
- There have been zero changes.
- Downloading the gem gives you an empty file, freight.rb. No class description or anything, just blank.
- It has been like this for over 6 years (Established 12/12/12).

It's currently owned by a Tim Cull. I sent him an email last week with no reply (trcull@pollen.io). I called him today and left a message. I have a feeling he has moved on to greener pastures, and probably doesn't care to go through the steps need to properly transition the gem name.

Is there anyway I can obtain ownership of this gem? my account name is 'wanchic', (ewanchic@gmail.com)

Thank you for any and all help.

  Eric

**Comment by dwradcliffe** [comment]
Our helpdesk is really the appropriate place for this discussion, can you submit a ticket over on https://help.rubygems.org please? Thanks!
