### ISSUE TITLE
What is the proper way to load an extra CSS file?

### ISSUE THREAD

**Issue by Goudarz** [rubygems/rubygems.org#2138]
I am working on translation to Persian, which is Right-to-left language. For that, I need to customize the CSS to load the pages in the proper format.

**Comment by simi** [comment]
Hello!

I think there's no need to load extra CSS file, but you can add new class to body (https://github.com/rubygems/rubygems.org/blob/db88e2345979938561d8d71788d737a9284bb73a/app/views/layouts/application.html.erb#L25) if rtl language is used and scope rtl styles under that css class.

**Comment by bronzdoc** [comment]
@Goudarz I'm going to close this now since Simi answered your question. Let us know if the answer helped you.
