### ISSUE TITLE
Consider extending https://rubygems.org/notifier to add an option for users to disable unwanted emails from rubygems.org

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2139]
> To aid detection of unauthorized gem changes, we email you each time a
> new version of a gem you own is pushed. By receiving and reading these
> emails, you help protect the Ruby ecosystem.

Hmmm.

The problem is that I am actually subscribed to my own gems, mostly 
because it gives me a way to sort stuff, e. g. to find out when the
last update happened (e. g. when I went to bed, wake up and don't
remember what I did in the last 72 hours or so).

With that change, I now get spammed by my own activity. :\ :/

I was looking for a way to disable this, but there was none that I
could find. So whenever I push a new gem, rubygems.org sends me
an email which I did not want to receive to begin with, nor does
it help me in any way really. I also disagree that by spamming me,
I "help protet the Ruby ecosystem".

I should clarify that I am all in favour of protecting USERS - but
NOT at the expense of usability. We have had problems before in the
past here, e. g. with the levensthein distance match or something
against typo-squatting annoying people; we also have seen discussion
from requiring "two factor authentification" or so, which ... 
requires a smartphone (which I don't have); and now this.

Please - if you really feel a need to make such changes then CONSIDER
EXISTING AND OLD DEVELOPERS who do not want to subscribe to all these
changes.

I actually logged in here just to see whether there is a simple way
to disable the notifications; and I could not find any. There is a
an individual entry for all gems, but I am not going to click
through +80 entries manually just to tick off all these email
notifications.

Anyway, now to suggestions how to change this:

- Add a SIMPLE way to disable all of these email notifications in
one go, somewhere. I guess a logical URL would be this one:

https://rubygems.org/notifier

but it could go elsewhere too. A simple form or so with a select
check button (or any other fitting form). When the user has selected
it to off, that user will no longer receive any email-updates.

You can of course say that this is useful, which may be; but to
me, whenever I am pushing new gem releases of my own gems,
rubygems.org spams me with this, which just is ... pointless. I'd
rather add a filter to get rid of rubygems.org than manually
tick off the individual entries ... :\ :/

So please, consider the UI of rubygems.org as a whole! Thanks.

PS: I should also add that I do not often check emails in general;
this is largely due to the way how I work (sorry). Right now I am
cleaning up all the gazillion emails in my gmail account in general,
which is quite boring and tedious; that is not the fault of rubygems.org
of course, but I can not change the infrequency of using emails in
general. (I actually much prefer issue trackers, webforum etc... 
han oldschool emails in general)

**Comment by simi** [comment]
Would you mind to contribute this feature? I think you can inspire at https://github.com/rubygems/rubygems.org/commit/5e8e32fe8badbe8ddb516fba18f3b238288c695f#diff-5354a099931d64748967998ea42d1fc1, add button to do bulk operation at https://rubygems.org/notifier (disable all, enable all) and also select default value for new gems. I can help you if needed, feel free to ping me with any question.

**Comment by sonalkr132** [comment]
>  I am not going to click through +80 entries manually just to tick off all these email notifications.

> I'd rather add a filter to get rid of rubygems.org than manually tick off the individual entries ...

sound like you already found a solution to the issue you faced.
I am going to close this for a lack of interest or support from any other user. I personally don't want to encourage disable all push emails among users.
Just a suggestion, may be more people would actually read the issue if it wasn't so long.
