### ISSUE TITLE
Difficulty yanking gems - but also a proposal to change the current behaviour to register the "yank gem" activity, but simply re-schedule it for later if the server is overloaded, rather than completely failing the gem command here

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2145]
Since about ~30 hours or so I am no longer able to yank old gems.

Whenever I try, I now get the error message:

"Retry later"

Has something changed in the last ~7 days or so in this regard?
Perhaps some timeout that I was using was not considered long
enough or something.

It may also be some problem on my part since I had difficulties
with openssl and my www-connection in general, but, for example,
youtube is working fine for me and most other websites are 
working as well; yanking gems does not work though.

I assume that some of the changes in general were made to not
overload the webservers that are used to host the gems-infrastructure,
which is fine by me - but at the same time, as a user, I am here
restricted in how I can delete my own gems.

I think I have explained why I delete my own gems in the past but
I will briefly do so again. I am fine if other people host my gems
(the licence is all permissive and allows for that) and I am also
fine if rubygems wants to host any of my "yanked" (removed) gems,
but I like keeping a clean state of versions that I support with
my own time; and many of the code changes I make are very small,
often just fix a single thing, then upload it. A bit like other
people use git, in some ways, although of course not as sophisticated
what I do here.

At any rate, might it be possible to allow for a change in the code
in general, when it comes to yanking my gems?

To me, as a developer in this context, I don't quite care at which
point rubygems.org removes the gem, but when I made the decision to
yank a gem, then I think it would be MUCH better if this wish is
registered by rubygems.org, rather than rejected and meant to 
"retry later". It is highly unlikely that I would change my mind
when I have already decided to yank a gem.

So my proposal would be to amend the current behaviour to the
following new behaviour instead:

1) Keep the current policy that users can not overload the server,
so the actual ACTION is not yet done (that is, to remove the gem
at the time of when the command is done), if the same reason for
refusal of yanking the gem exists, e. g. "too many uses" of 
yanks done. So this part remains the same.

2) But, change the current behaviour TOWARDS acknowledging the
fact that the rubygem maintainer wanted to remove that gem, so
REGISTER this activity, and do it at a LATER time when there is
less activity. In other words, to re-schedule this to occur at
a later time.

Benefit of this change:

- I, as a developer, can, via the commandline, still de-register
a gem that I created/maintain, without having to re-run the same
command at a later time, due to the "Retry later" fail message
that I get right now.

If you want to, you could disallow this if there is only one
gem left, so that people may be more sure when the de-register
action occurs; personally I mostly care about this functionality
for gems that have several versions, so that I can remove the
obsolete versions. It does not have to be removed instantly,
I am fine if rubygems.org would schedule to remove this within
the next 76 hours or so, when the server is not overloaded or
whenever it fits.

As it is right now, though, I have to re-do these yank-commands,
and that can be a bit tedious.

Note that my feature proposal here, is not necessarily connected
to any issues I have right now in regards to yanking gems, but
I think that my change may be the better approach in the long
run anyway, since it allows developers to not have to re-do
the same command at a later time, as opposed to the current
behaviour.

I hope I have managed to explain the issue. It is not a big
deal, necessarily, but still a slight improvement IMO to the
current status quo.

I am not entirely sure where to file this report, though;
perhaps it would be better filed at rubygems directly
rather than rubygems.org, but I mostly monitor my gems
via rubygems.org, in particular at the /version URL, so
I thought it might be better to file it here. But it may
be related to rubygems as-is, due to the behaviour being
part of "gem", I think (the message "Retry later", I assume,
is part of the gem code directly).

**Comment by dwradcliffe** [comment]
I'm not really sure what's going on here, the only thing I can think of is that you're hitting short-term rate limits. Other than that it must be something with your connection. If you're still having issues you can open a ticket on https://help.rubygems.org with more details and we can try to look at logs.
