### ISSUE TITLE
https://rubygems.org/notifier appears to keep track of yanked gem and displays them

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2158]
When looking at https://rubygems.org/notifier just now, I noticed that 
it also keeps track of gems that I have already removed (yanked) before.

So for example:

-------------------------------------------------------------------------------

colour_e

On (recommended)
Off

-------------------------------------------------------------------------------

Something seems strange. I assume that the information about past owners
of gem is kept, which is fine; but that information is also displayed to
the former site owner on that /notifier route, which I think does not make sense,
since that site owner (gem author) already yanked/removed the gem. So even
IF the site owner could want to toggle this (let's just assume this), it would not
make sense since the gem is already gone completely, so even if set to "On",
there would never by any notification anyway. The notification would only
be triggered if a gem would be yanked, but if the last gem was yanked and
the namespace past the 100 days delay, the site author could not do much
with non-existing gems. So this seems like a no effect
situation.

I would recommend to change the affected code here - add a way to determine
whether the gem has already been yanked or not. And if it has been yanked
before, skip the display of it on the "notifier" route.

On a somewhat related note - since we can already manually toggle 
on/off on a per-gem basis here, I believe it should be simple to
add a new button for "toggle all off", which could be a bit of
javascript, doing all the manual action that we'd do right now
by pressing the "Off" checkbox there. That way new code additions would
be kept at a minimum.

**Comment by bronzdoc** [comment]
@rubyFeedback Do you have more versions of that gem which are not yanked? 

What you suggest `/notifier` displays when there is multiple versions of a gem and only one of those version is yanked?
