### ISSUE TITLE
potential caching issue with aws-sdk-sso ?

### ISSUE THREAD

**Issue by mullermp** [rubygems/rubygems.org#2162]
Customers are still having issues: aws/aws-sdk-ruby#2159.
We've got the spec dependency - https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-resources/aws-sdk-resources.gemspec#L180

But current status is when installing aws-sdk, aws-sdk-sso is never fetched. Is this some caching problem? The gem is published: https://rubygems.org/gems/aws-sdk-sso

Opening new issue for visibility.

**Comment by mullermp** [comment]
I've yanked the offending version.

**Comment by awood45** [comment]
One question I'd pose is - what could be done to prevent this from happening again? Even when aws-sdk-sso was published, it seemed that for some reason the aws-sdk-resources dependency tree didn't resolve properly. Is there something that can be done from our end to cause that dependency to resolve properly?
