### ISSUE TITLE
[New service gem]: Name 'aws-sdk-sesv2' is too close to typo-protected gem: aws-sdk-ses

### ISSUE THREAD

**Issue by cjyclaire** [rubygems/rubygems.org#2168]
request whitelisting for the typo protection, thanks!
```
There was a problem saving your gem: Name 'aws-sdk-sesv2' is too close to typo-protected gem: aws-sdk-ses
```

similar issue before #2161

**Comment by mullermp** [comment]
Our pipelines internally are blocked because publishing later would still result in problems. See: https://github.com/rubygems/rubygems.org/issues/2162

**Comment by dwradcliffe** [comment]
Done 👍

**Comment by mullermp** [comment]
https://github.com/rubygems/rubygems.org/pull/2163/files looks to be a solution in the works?

**Comment by simi** [comment]
@mullermp yes, that's initial draft. I'll try to find some time to finish that.

**Comment by mullermp** [comment]
Thank you both @dwradcliffe and @simi for the quick responses on these. I'm hoping there won't be too many more of these before reInvent.

**Comment by cjyclaire** [comment]
Thanks to all, although it broke us, still want to thank you for making the efforts to protect us! :)
