### ISSUE TITLE
There was a problem saving your gem: Name 'aws-sdk-wafv2' is too close to typo-protected gem: aws-sdk-waf

### ISSUE THREAD

**Issue by mullermp** [rubygems/rubygems.org#2181]
Please whitelist

@simi @dwradcliffe @qrush @sferik @evanphx @arthurnn

**Comment by mullermp** [comment]
@simi @dwradcliffe

**Comment by mullermp** [comment]
I feel bad for all of this. I'm going to push for AWS sponsorship of Rubygems if I have any authority to do so.

**Comment by mullermp** [comment]
This is blocking our V3 release. Please someone look at this soon if you can.

**Comment by dwradcliffe** [comment]
Done.

**Comment by mullermp** [comment]
@dwradcliffe THANK YOU!!

If it's not too much trouble to ask, could you check in every now and then up until re-invent? Unfortunately there may be more services that will need whitelisting.. :(

BTW - check your email - following up on sponsorships.

**Comment by mullermp** [comment]
Our releases start around 11 am PST and can go until 2pm or so.
