### ISSUE TITLE
help.rubygems.org

### ISSUE THREAD

**Issue by tcd** [rubygems/rubygems.org#2183]
@drbrain @evanphx @qrush @dwradcliffe @sferik 

I opened a *typo-protected gem*-related issue on `help.rubygems.org` [9 days ago][ginny-issue], along with asking about how to address the problem over on [issue #2058][2058]. As far as I can tell no one from the Support Staff has been on the help site since November 6th. I know that y'all are volunteers, but that's almost three weeks. Not sure if there's anything to do; I just wanted to say something about it.

Thanks

[ginny-issue]: https://help.rubygems.org/discussions/problems/37131-gem-push-name-too-close-to-typo-protected-gem
[2058]: https://github.com/rubygems/rubygems.org/issues/2058#issuecomment-557316669

**Comment by bronzdoc** [comment]
You question has been addressed by @sonalkr132 in https://help.rubygems.org/discussions/problems/37131-gem-push-name-too-close-to-typo-protected-gem
