### ISSUE TITLE
[New Feature / Functionality for rubygems.org] Proposal: add a way for the user / visitor of individual gems on rubygems.org to display the content of a gem, via an associated URL / Link

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2190]
There was recently a discussion on reddit (not started by me) about this gem here: 

https://rubygems.org/gems/make

The discussion can be seen here:

https://old.reddit.com/r/ruby/comments/e9smst/is_there_a_process_for_getting_a_gem_yanked_from/

The problem described was e. g. to have a **bin/make** entry that may be installed at the locally existing "make".

I personally don't think it is a big problem; I tend to use --user-install anyway and then just manage the bin/ files in my home directory. But it got me thinking ...

Would it be possible and useful to add an entry to an individual rubygems page, and give users a way to display the content (of that particular gem) online? In particular bin/ entries - a bit like github navigation but just simpler (the information can be obtained from the .gemspec file I assume or wherever else the files are being stored, so it does not need to be any "live" navigation as in github).

This is mostly for _convenience_ IMO.

It could be a new entry on the bottom right area, perhaps under the entry "Reverse dependencies" - some entry such as "Installed files" or some such. My primary use case for the description here is to let ruby users quickly see, online, which bin/ entries are installed.

It is not only related to the discussion on reddit, though - more of a general convenience feature to be had. (Not sure how problematic the issue description at reddit was, but I think we can decouple that from the suggestion here, since my aim is really convenience, not preventing any user action or anything - hence why it was filed here on  rubygems.org github, rather than rubygems github).

**Comment by sonalkr132** [comment]
dup of #1563.
