### ISSUE TITLE
Content Security Policy blocking application javascript

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2196]
The CSP is currently blocking application javascript on the page and is breaking certain functionality like the advanced search.

Visit the homepage and open the console log and you will see the error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

**Comment by simi** [comment]
I can't reproduce this. Which browser do you use?

But I can see different errors like:

```
Refused to connect to 'https://fastly-insights.com/api/v1/config/3e63c3cd-fc37-4b19-80b9-65ce64af060a' because it violates the following Content Security Policy directive: "connect-src 'self' https://s3-us-west-2.amazonaws.com/rubygems-dumps/ https://*.fastly-insights.com https://api.github.com".
```

What about those?

**Comment by colby-swandale** [comment]
This is occurring in Firefox

**Comment by simi** [comment]
Ahh, ok. I can confirm I see the same error in Firefox related to `script-src`.

**Comment by Jorgeptz** [comment]
User

**Comment by Jorgeptz** [comment]
> Ahh ok. Puedo confirmar que veo el mismo error en Firefox relacionado con `script-src`.
