### ISSUE TITLE
Extra text about MFA availability for 2.x rubygems users

### ISSUE THREAD

**Issue by ecnelises** [rubygems/rubygems.org#2203]
Some people enabled MFA in the site but their local gem version is 2.x which can't support MFA. Our current reponse is:

```
You have enabled multifactor authentication but no OTP code provided. Please fill it and retry.
```

We should add some text to notify that only >3.0 supports this feature.

ref: https://github.com/rubygems/rubygems/issues/3078

**Comment by hsbt** [comment]
Unfortunately, RubyGems 2.x is EOL now. The latest supported versions are 3.1-3.3.
