### ISSUE TITLE
Sponsor logos aren't displaying properly

### ISSUE THREAD

**Issue by joshuap** [rubygems/rubygems.org#2205]
It looks like the old [/sponsors.png](https://github.com/rubygems/rubygems.org/blob/master/public/sponsors.png) is being cached in production, so the sponsor logos aren't displaying correctly (the RubyCentral logo is duplicated at the end):

<img width="960" alt="image" src="https://user-images.githubusercontent.com/474649/72477288-05d17a00-37a4-11ea-8716-627cbecccca0.png">

Two potential fixes:

1. Invalidate the CDN cache for /sponsors.png, if possible
2. Add a cache buster to the sprite in [the CSS](https://github.com/rubygems/rubygems.org/blob/master/app/assets/stylesheets/modules/footer.css#L82):
    ```
    background-image: url(/sponsors.png?v2);
    ```

@dwradcliffe @colby-swandale do either of these work? I'll send a PR for 2) just in case.

**Comment by colby-swandale** [comment]
@joshuap we're looking into purging `sponsors.png` from the fastly cache

**Comment by dwradcliffe** [comment]
I've purged the URL, and it looks correct to me. It might take a little bit to clear out of browser caches but I don't think it will be long. Thanks @joshuap for noticing!
