### ISSUE TITLE
Refused to connect to 'https://fastly-insights.com/api/v1/config/3e63c3cd-fc37-4b19-80b9-65ce64af060a'

### ISSUE THREAD

**Issue by vill** [rubygems/rubygems.org#2214]
Hi there.
I'm getting the following errors:

![Screen Shot 2020-02-09 at 10 34 05](https://user-images.githubusercontent.com/2039461/74095865-516c0f00-4b29-11ea-83cb-02a2cc6ae876.png)
![Screen Shot 2020-02-09 at 10 48 55](https://user-images.githubusercontent.com/2039461/74095897-d9521900-4b29-11ea-8c1a-a7f16047b965.png)

**Comment by colby-swandale** [comment]
Thanks for raising this issue. I can confirm this issue on the latest Google Chrome browser.
