### ISSUE TITLE
Can we add a redirect from /users to /profiles

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems.org#2240]
Previously going to https://rubygems.org/users/schneems would show the content now at https://rubygems.org/profiles/schneems. Can we add a redirect from one endpoint to another?

**Comment by rajdeep26** [comment]
Hi Everyone, I would like to raise a PR for this. Please allow me a day or 2 for the same.

**Comment by dwradcliffe** [comment]
When did this change? I don't remember this being a valid route but my memory might be failing me.

**Comment by schneems** [comment]
I have a link there on https://schneems.com/ but I’m not sure. It might be possible I had a typo there and no one noticed for a few months but I’ve gotten PRs on that sidebar in the same time frame.

**Comment by schneems** [comment]
Added here about three months ago https://github.com/schneems/schneems/blame/master/_includes/more.html#L17

Is there a way to ask google if there are any links that start with that prefix? I might have just been having an off day when I published that

**Comment by rubyFeedback** [comment]
Makes sense to me, unless the rubygems.org team wants to reserve users/ for something else (but then I think this should be documented the moment the change happens). As I am unaware of that, to me personally what schneems wrote makes a lot of sense so I agree with the PR.

**Comment by dwradcliffe** [comment]
We're pretty sure it never existed, but I don't see any harm in adding a redirect from /users to /profiles.

**Comment by colby-swandale** [comment]
Do we want to add a redirect or do we just want to have both `/users` and `/profiles` just work?

**Comment by dwradcliffe** [comment]
Redirect. Same content shouldn’t exist at two urls for SEO reasons.

**Comment by simi** [comment]
Sorry for being pessimistic in here, but what would be the reason for having this redirect? If I understand it well @schneems for some reason did a mistake by publishing wrong link (per @dwradcliffe comment explaining that route has never existed), that can be fixed on his side and I don't see any additional benefit making this redirect. Am I missing something?

**Comment by dwradcliffe** [comment]
After thinking about this more I think I've changed my mind. I agree with the concerns here and in the PR and I don't think we should add this. Thanks to everyone here for your feedback and opinions.
