### ISSUE TITLE
Take-over request for namespaces of standard libraries

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems.org#2259]
```
abbrev
base64
coverage
english
fiber
find
mkmf
monitor
observer
prettyprint
prime
profile
profiler
thread
time
timeout
tracer
uri
yaml
```

The above gems are reserved now. So, the original author couldn't release the new version. But the users can still download them from rubygems.org. They are completely different libraries with the Ruby standard libraries. I hope to resolve them with the default gems.

In the other side, They block the new release of default gems like this https://github.com/ruby/prime/issues/11

There is no response to transferring request by me over the 2 years. I need to release them as default gems this year because Ruby 3 will be released.

@dwradcliffe @sonalkr132 @indirect Can you add `hsbt@ruby-lang.org` to these gems?

**Comment by indirect** [comment]
I think @colby-swandale said he can do this. Thanks Colby!

**Comment by colby-swandale** [comment]
Done.

**Comment by hsbt** [comment]
@colby-swandale I appreciate your quick action. I confirmed to adding my account to them.
