### ISSUE TITLE
[Feedback on https://stats.rubygems.org/] Just some feedback - I recommend to close this issue at the least at ~May 2020 or so, give or take

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2266]
To the new:

https://stats.rubygems.org/

Some feedback here from me (I can not comment on reddit as I am banned
there and way too lazy to create a new account just to work around 
trigger-happy power-tripping ego-mods on reddit).

So first - this is a very good idea, huge props to all the folks who
implemented it. I think I have suggested this before, perhaps more
generally, e. g. to also include functionality from the ruby toolbox
in the long run; I think there are daily-download stats on bestgems.org
too, so ... the reason why I think this would ideally best sit on 
rubygems.org is simply due to convenience. From a user's perspective,
I think it would be best to make rubygems.org the primary target 
for all gem-related things. I don't like to visit many different
websites, to get useful information; I am more inclined to write
a ruby script that gathers this for me, if I need this more regularly
anyway. :P

Ok now a bit of feedback - feel free to pick what is useful and disregard
the rest:

1) The top panel seems to occupy a bit too much space. This may be my
personal taste, but if you look at text such as "Logs produced by
rubygems.org, processed by kirby, and displayed by ecosystem.", the
icon on top, and the padding/spacing, and then also the padding/spacing
below that, seems to occupy too much space, IMO. I would recommend 
reducing this a little, perhaps by 10% or 20% or so. Right now it
fills like 50% of my default screen size on my desktop computer
system here.

2) The "Version breakdowns" in the middle of the page seems a bit
verbose, but ok. I'd also push this a bit to the top, and perhaps
make the width a bit larger. Right now it seems to be middle-centric
alone.

3) The colours are VERY hard to notice in the graph. Also the font
size is VERY small. I would recommend increasing this a bit and
intensify the bold/depth/hue/shadow situation. It's cool that this
is interactive, but I'd prefer slightly larger font sizes. Yes I
can change the font size in the tab via middle-mouse scroll wheel
but I am sooo lazy ...

4) For Traffic Comparisons I would recommend to add a 6 months
option, and change the default from 3 months to 6 months or
even 12 months. The 3 months curve seems quite flat and not so
interesting; 12 months looks more interesting IMO.

5) I'd also perhaps recommend to see if the functionality from
bestgems could be included there, or a per-gem stats viewer 
from rubygems.org - but I understand that this was a lot of
work so I don't want to recommend more work.

At any rate this is quite nice - only small visual improvements
should occur here and there.

Cheers!

PS: I recommend to close this issue here after a month or two;
perhaps others may want to add feedback too, but I don't want
to add open issues that just remain open, so I would like to
recommend to close this issue at the latest in May 2020, or
earlier at the discretion of those maintaining/running the
website (aka those who do most of the real work on rubygems.org
that is).

**Comment by colby-swandale** [comment]
stats.rubygems.org is a separate project. https://github.com/rubytogether/ecosystem
