### ISSUE TITLE
Unexpected results from /search

### ISSUE THREAD

**Issue by dentarg** [rubygems/rubygems.org#2303]
The search https://rubygems.org/search?utf8=%E2%9C%93&query=aws-sdk-r is only returning `resize-aws-instance` 

<Details><Summary>(Same results from the JSON endpoint)</Summary>

````
$ curl -s https://rubygems.org/api/v1/search.json\?query\=aws-sdk-r | jq
[
  {
    "documentation_uri": "https://github.com/Altiscale/resize-aws-instance/blob/master/README.md",
    "metadata": {},
    "homepage_uri": "https://github.com/Altiscale/resize-aws-instance",
    "bug_tracker_uri": "",
    "project_uri": "https://rubygems.org/gems/resize-aws-instance",
    "version": "0.2.0",
    "sha": "cd7077a48153173c34c48b48dbad0b59d74dcb4430a3f8025d1e108e497c6f04",
    "platform": "ruby",
    "changelog_uri": null,
    "source_code_uri": "https://github.com/Altiscale/resize-aws-instance",
    "licenses": [
      "Apache 2.0"
    ],
    "gem_uri": "https://rubygems.org/gems/resize-aws-instance-0.2.0.gem",
    "downloads": 2983,
    "mailing_list_uri": "",
    "name": "resize-aws-instance",
    "wiki_uri": "",
    "version_downloads": 1623,
    "authors": "Tucker",
    "info": "Simple tool to resize AWS instances with EBS root."
  }
]
````
</Details>

I expected it to return results starting with `aws-sdk-r`, like `aws-sdk-resources`, `aws-sdk-route53`, `aws-sdk-rds` etc.

The search https://rubygems.org/search?utf8=%E2%9C%93&query=aws-sdk- returning results that start with `aws-sdk-` at the top.

**Comment by rubyFeedback** [comment]
I think I reported something similar some time ago (but I don't remember offhand).

I agree with your expectation, so I think this is a very minor bug (or perhaps usability deficiency). I am not even sure why resize-aws-instance is returned; that does not seem to match onto aws-sdk-r at all.

Perhaps some test cases should be included if the bug can be discovered.

**Comment by sonalkr132** [comment]
yes, dup of #1662. I will look into this tomorrow. Thank you for reporting.

**Comment by sonalkr132** [comment]
see #2308
