### ISSUE TITLE
Correct link to homepage for builder gem

### ISSUE THREAD

**Issue by tiendo1011** [rubygems/rubygems.org#2323]
Gem link: https://rubygems.org/gems/builder
Currently, this gem is being maintained under this link: https://github.com/tenderlove/builder
But the homepage in rubygems.org still point to the old one: https://github.com/jimweirich/builder

**Comment by simi** [comment]
1. this is not rubygems.org problem, but problem of the gem gemspec itself and this issue should be raised at gem repo, not here
2. looking at gem repo gemspec, it is probably already fixed and it will be updated on rubygems.org with next release (https://github.com/tenderlove/builder/blob/d04452e4d0ae2b61183ea265409a2f2347d51729/builder.gemspec#L43-L52)

**Comment by sonalkr132** [comment]
Yes, nothing to do here. This should be fixed when builder releases a new version.
