### ISSUE TITLE
A few suggestions for UI improvements for https://stats.rubygems.org/ - but these are just minor, feel free to disregard/close at any moment 

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2338]
This issue request refers to:

  https://stats.rubygems.org/

(1) First, a small personal preference; the upper part on my
desktop monitor occupies, on first visit, occupies more
than 50% in height, but the interesting parts are 
displayed below. I do not know if there are conflicting
design constraints, but I would recommend decreasing
the upper parts a bit, perhaps cut it by 5% or 10% or
so. But this is a minor thing, I just wanted to mention
it briefly.

Next to a slightly more "serious" opinion:

(2) Several stats are displayed, and they work fine in my
browser (palemoon), but one thing that I find difficult
is, aside from the smallish font, the contrast. The
default contrast on the webpage seems to be dark grey
font colour on a light grey background colour. I find
this hard to read, perhaps also due to small font size.

I am not sure if a slight increase in font size would
help; may help me, but this may depend on the way how
people access things. I exclusively use oldschool 
desktop system, so I'd love larger fonts and more
contrast. While the size of fonts may be an issue of
preference, I believe the contrast isn't good. Could
the fonts be black instead of greyish perhaps?

(3) Next smaller issue is:

We have:

 2w 1m 3m 12m 

Would it be possible to add 6m as well?

There are all very minor UI suggestions. Not sure if
everyone agrees to that but I wanted to give an opinion.

I find the stats-page very useful, in particular
Platform - I wasn't aware that Linux was used so 
widely there!

By the way, CI provider seems to fluctuate a lot - 
may be interesting to see some explanation of this,
because right now this confuses me. Though it is more
a question of curious note; not that I think knowing
the CI provider is very vital for most folks who read
that page. :)

Thanks for reading.

PS: Oh, almost forgot one thing: stats distribution 
may be also interesting. Right now I use "bestgems"
and it is fine, but I think ultimately it would be
best if that could be integrated into rubygems itself.

I understand lack of manpower and resources though.

**Comment by dwradcliffe** [comment]
As we told you before, stats.rubygems.org is a separate project with a different GitHub repo: https://github.com/rubytogether/ecosystem
