### ISSUE TITLE
edit profile: flash message is barely visible

### ISSUE THREAD

**Issue by terceiro** [rubygems/rubygems.org#2340]
I just got an email from rubygems.org suggesting to enable MFA. I just did it, and that worked fine. While I was at it, I decided to update my email address as I intend to deactivate the one currently in use by rubygems.org). However, clicking update has no effect.

![edit-profile](https://user-images.githubusercontent.com/30027/80632950-5789d180-8a2e-11ea-9158-b9a698af0a8c.gif)

**Comment by sonalkr132** [comment]
You need to enter your password (last field in the form) to update profile. You should be seeing following flash message:
> This request was denied. We could not verify your password.

Let us know why this was not sufficient for you to figure out the error.
Additionally, your new email will go through ownership verification. New email will be updated on your profile after verification.

**Comment by terceiro** [comment]
ah :facepalm: 

I would say the flash message does not stand out in comparison with the site header. I would make it a different color, and the same width as the form itself instead of the full screen width, and maybe put it below the "Edit profile" heading.

**Comment by sonalkr132** [comment]
Hi terceiro,

Your input is duly noted. I am going to close this for now. We can invest time on fixing this it at least one more user complains something similar.
Thank you for your explanation.
