### ISSUE TITLE
Api versions endpoint is slow for gems with a lot of versions

### ISSUE THREAD

**Issue by simi** [rubygems/rubygems.org#2342]
For example `/api/v1/versions/sorbet-static.json` is slow since this gem has 3189 versions when page is not cached.

Majority of time is spend on serialization all versions to json.

Suggested solutions:
1. do nothing since it is not problem for cached page
2. introduce pagination for this endpoint (is that breaking change?)
3. use more optimized serialization (for example [oj gem](https://github.com/ohler55/oj))

```ruby
print Benchmark.measure { Rubygem.find_by_name('sorbet-static').public_versions.to_json }
  1.052366   0.012946   1.065312 (  1.105208)
# vs
print Benchmark.measure { Oj.dump(Rubygem.find_by_name('sorbet-static').public_versions.as_json) }
  0.622339   0.020997   0.643336 (  0.677367)
```

@sonalkr132 is this problem worth it any next action?

**Comment by sonalkr132** [comment]
I doubt we should be making any significant change to support one gem with the most versions on our site. There are only 5 gems with more than 1000 versions and second gem with most ( `116687`) with most versions (1171), takes less than 500ms. 
```
print Benchmark.measure { Rubygem.find(116687).public_versions.to_json }
 0.365846   0.004290   0.370136 (  0.441932)
```
Perhaps fastly shield could help with fewer requests landing on rails app. Alternatively, we can cache response in rails cache for this one gem only.

cc: @dwradcliffe

**Comment by 0x2C6** [comment]
Although it reduces db hit count, wouldn't it be cumbersome to cache all that data, page? there are over 159,704 gem hosted now.

**Comment by sonalkr132** [comment]
To clarify, I don't agree with the title of the issue. 
> slow for gems with a lot of versions

There is only one gem where I would consider the versions endpoint is slow and I am suggesting to cache the response for this one gem only.
> we can cache response in rails cache for **this one gem only**.

I suggested this after I pointed out that complexity or additional dependency is not worth fixing this for one gem at the moment.

**Comment by simi** [comment]
I did some testing and even this one gem with enormous amount of versions responds in reasonable time today.
