### ISSUE TITLE
emergency unyank gem

### ISSUE THREAD

**Issue by mullermp** [rubygems/rubygems.org#2400]
please unyank aws-sdk-core 3.99.0

**Comment by mullermp** [comment]
@simi @dwradcliffe

**Comment by simi** [comment]
I can't do that, but I can notify people able to do that to take a look at your request.

**Comment by mullermp** [comment]
please do that as soon as you can. it's about to break a bunch of people

**Comment by mullermp** [comment]
the api is broken, getting this back from the service:

This version of the Gemcutter plugin has been deprecated.Please install the latest version using: gem update gemcutter

**Comment by mullermp** [comment]
same with the library

[8] pry(main)> c.unyank('aws-sdk-core', '3.99.0')
Gems::GemError: This version of the Gemcutter plugin has been deprecated.Please install the latest version using: gem update gemcutter
from /Users/alexwoo/.gem/ruby/2.6.5/gems/gems-1.2.0/lib/gems/request.rb:77:in `body_from_response'

**Comment by indirect** [comment]
Hi. I'm taking a look now.

**Comment by indirect** [comment]
It's back: https://rubygems.org/gems/aws-sdk-core/versions/3.99.0

**Comment by mullermp** [comment]
THANK YOU

**Comment by mullermp** [comment]
Any chance unyank API could be fixed for those who need to use it?

**Comment by indirect** [comment]
Unfortunately, the unyank API is not broken—we removed it entirely several years ago.

Yanking and unyanking causes a huge amount of frantic churn in the systems that are all trying to serve millions of gems a day, and providing direct API access meant that we were effectively letting gem authors DoS us whenever they wanted. While it is technically fixable, it's not a high priority because legitimate unyanking is very uncommon.

However, if someone from AWS wants to volunteer to do the development, ops, and maintenance work needed to keep it functional over time, we'd probably be open to that. :)

**Comment by mullermp** [comment]
We're not opposed to taking up this work when we get the available bandwidth. We're a fairly small team owning all of the AWS Ruby SDK products. When unyank existed, did the current rate limiting mechanisms exist for yanking and publishing? Is unyank something a whitelisted account could have access to (including no rate limiting)?

**Comment by indirect** [comment]
We do have better rate limiting, or rate limit permissions, on our list, but we are also an extremely small team who all have actual day jobs doing something else to pay the rent.

If someone from your team is interested in helping with per-account rate limits, or providing unyank only to pre-authorized accounts, or other things like that, I think we would welcome the help.

**Comment by mullermp** [comment]
Account whitelisting has been a pain-point for us - some days we release 200+ gems and occasionally get throttled. We are interested in taking that on. If unyank can be available to whitelisted accounts then that would be a sweet bonus. Right now we're being asked to do re:Invent work this early into the year so that currently has our attention. Is there any special information that we would need to get started to develop on your site?

As an aside, there was another casualty yesterday - aws-sdk-batch-1.5.0 .. could I please ask for one more unyank?

**Comment by sonalkr132** [comment]
> there was another casualty yesterday - aws-sdk-batch-1.5.0 .. could I please ask for one more unyank?

done

**Comment by mullermp** [comment]
Thank you!!

**Comment by simi** [comment]
> Account whitelisting has been a pain-point for us - some days we release 200+ gems and occasionally get throttled. We are interested in taking that on. If unyank can be available to whitelisted accounts then that would be a sweet bonus.

@mullermp I think currently throttle is reset on successful gem push. I did some work on whitelisting accounts, but it was related to gem name squatting, which was disabled recently.

I have revived my work partially at https://github.com/rubygems/rubygems.org/compare/master...simi:verified-users-2. Anyway I'm not sure which feature could benefit from that for now.

If you have any idea feel free to ping me at https://bundler.slack.com and we can discuss it in there.

**Comment by mullermp** [comment]
@simi Thanks! I will take a look when I can.

**Comment by BuonOmo** [comment]
Hey, I bit unsure if should open a new issue or continue down that thread, tell me and I'll move to an issue.

Anyway, I get that you removed the unyanking process altogether, however I think the message when trying to push a gem that already exists is really misleading then:

```
$ gem push fast-polylines-*.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   ...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

This lead me to yanking thinking I'd be able to push back afterward.

I could open a PR to change:

https://github.com/rubygems/rubygems.org/blob/e536610693aa427f91e7dbcca0799c810effeb14/app/models/pusher.rb#L145-L146

Into something like:

```
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases, you cannot undo this action nor push the same version again.

**Comment by deivid-rodriguez** [comment]
I think I'd rather remove the `gem yank` suggestion and instead recommend to push a new release? Maybe something like

> Repushing of gem versions is not allowed.
> Please bump the version number and push a new different release.

**Comment by BuonOmo** [comment]
Yes definitely more appropriate! I'll open a PR this afternoon giving us room to discuss the details if any 🙂
