### ISSUE TITLE
Possible small bug in "Total downloads" displayed? (For the REXML gem)

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2401]
Hey folks,

I am not sure if there is a bug, but let me just report it
anyway - others can then confirm or reject whether this is
a bug.

See REXML homepage on rubygems.org:

https://rubygems.org/gems/rexml

If you look at it right now you see:

"Total downloads 0
For this version 5,512,916"

Well, evidently logic fails here, because if the downloads
for this version are +5.5 million, then the total downloads
must be AT THE LEAST at 5.5 million. Instead 0 is displayed,
which can not be possible if there were downloads, as is
the case here. So I assume the display 0 is incorrect, for
whatever the reason.

I am not sure why or how this bug is caused. May it be related
due to the decision to have rexml external to stdlib? Either 
way I believe that such a bug should not exist in the
first place. At the least the minimum reported value should
be the same as the for all "This version" downloads, in
my opinion.

Thanks!

**Comment by sonalkr132** [comment]
Thank you for reporting this. see #2404
