### ISSUE TITLE
Password used in User#block! may not be secure enough to be blocked

### ISSUE THREAD

**Issue by esparta** [rubygems/rubygems.org#2416]
At the beginning this look like a flaky test, but seems like it may be having  two issues:

- The random password used to block a user may be not enough because there's a small change it will have an entry on the [HIBP](https://haveibeenpwned.com/) breached database of passwords, impeding the blocking of the given user.
- The unit test may or may not be pinging HIBP?

I got this by coincidence when Travis-ci had the test suite failed when it should not be failing (no changes in code):
```
Error
UserTest#test_: with a user two factor authentication when enable should can be blocked. :
ActiveRecord::RecordInvalid: Validation failed: Password has previously appeared in a data breach an should not be used
      app/models/user.rb:226:in `block_in_block!'
      app/models/user.rb:222:in `block!'
      test/unit/user_test.rb:300:in `block (5 levels) in <class:UserTest>'
      test/test_helper.rb:45:in `assert_changed'
      test/unit/user_test.rb:299:in `block (4 levels) in <class:UserTest>'
      test/unit/user_test.rb:311:in `instance_exec'
      test/unit/user_test.rb:311:in `block in create_test_from_should_hash`
```
![image](https://user-images.githubusercontent.com/1037088/85219764-666c7080-b35b-11ea-93a6-382b67f9dfa2.png)

The culprit was just a not-so-highly improbable coincidence with `SecureRandom.alphanumeric`, since the defaults returns a string with only 16 chars long.

https://github.com/rubygems/rubygems.org/blob/0239bd6d1053aea8189c12f65a24b6a7c8cb5992/app/models/user.rb#L221-L233

The first issue looks like solvable using a longer password (`SecureRandom.alphanumeric(45)`) or even a hex version: `SecureRandom.hex(32)`

For the second, it may be solvable with a config change I can research on [`unpwn`](https://github.com/indirect/unpwn). IMO, unit test should not be using the internet tubes at all.

If rubygems.org maintainer consider this important I can take care of these issues.

**Comment by simi** [comment]
Can we just skip validations in block! method update?

**Comment by esparta** [comment]
> Can we just skip validations in block! method update?

Yes, that's another option. Adding a separated update_attribute for password...
```diff
index 7c6b2541..20c41982 100644
--- a/app/models/user.rb
+++ b/app/models/user.rb
@@ -223,8 +223,8 @@ class User < ApplicationRecord
       update_attribute(:email, "security+locked-#{SecureRandom.hex(4)}-#{id}-#{handle}@rubygems.org")
       confirm_email!
       disable_mfa!
+      update_attribute(:password, SecureRandom.alphanumeric)
       update!(
-        password: SecureRandom.alphanumeric,
         remember_token: nil,
         remember_token_expires_at: nil,
         api_key: nil
```
 it will skip the current validation for password:

https://github.com/rubygems/rubygems.org/blob/0239bd6d1053aea8189c12f65a24b6a7c8cb5992/app/models/user.rb#L46-L50

The only nitpick would be about this will issue another update to the database. But since is not a hot path, I think should be just fine.

I though about overwrite `:skip_password_validation?` but discard it because it will definitely will impact all other areas where a password update is issued (and validated).

**Comment by esparta** [comment]
This first part bypassing the update_attribute was done on #2437

**Comment by simi** [comment]
If I understand it well, also the second part was also implemented at https://github.com/rubygems/rubygems.org/pull/2805. :pray:
