### ISSUE TITLE
Add captcha for signup & password reset forms

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2420]
As per title, we should look at adding a captcha to the signup & password reset forms to better protect against brute force and scripts from abusing the site.

Maybe we also add a captcha to the login page as well if someone has failed successfully login after > 3 tries.

I've heard good things about http://hcaptcha.com, or maybe we look at rolling our own solution.

**Comment by vachhanihpavan** [comment]
Hey!!
I would like to work on the issue.
Why not use [reCaptcha](https://developers.google.com/recaptcha/docs/v3)?
