### ISSUE TITLE
Other gem-related websites, potential for fishing-related websites? [Credibility of such websites; display credible websites on rubygems.org and warn about websites that are not associated with rubygems.org)

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2426]
I was googling for some gem news, via google (duh), and semi-randomly found:

    https://gems.ruby-china.com

I almost logged in because ... well, it looks similar to rubygems.org. But then I
wondered whether this site had anything to do with rubygems.org. It could
be, but perhaps not.

IF it is not related to rubygems.org then perhaps it is trying to fish for information -
and sometimes people are confused. For example, when I wake up, I am still
tired usually and not at full mental powers. ;) And perhaps others may also have
oddities at times, and perhaps log in and pass their credentials to other sites?

Anyway. What I would suggest is to make it more prominent for rubygems.org
whether there are any OTHER sites that have the same credibility / credentials
as rubygems.org has. If so then perhaps these websites could be listed
specifically, and if it is not, some warning could be shown on rubygems.org
as a disclaimer. Or something similar (I am just trying to brainstorm a little
here).

Again - no idea if this is an issue, whether that website is credible or not - I
am more thinking of displaying that information on rubygems.org so that
ruby users don't get confused. Even if the above website is ok, other websites
could look 1:1 like rubygems.org but just be fishing for information, and I
have a hard time believing that ANYONE fishing for such information has
"good intentions" ...

**Comment by dwradcliffe** [comment]
There are no other sites or domain names with the same credentials. I’m not sure there is anything else we can do to make this more clear for users.
