### ISSUE TITLE
Enable TLSv1.3 ?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems.org#2427]
## Is your feature request related to a problem?

No.

## Describe the solution you'd like

Enable TLSv1.3.

Per the Fastly document, TLSv1.3 is more efficient.  Given that almost all MRI Ruby versions on GitHub Actions support  TLSv1.3, that alone would lessen traffic, as most jobs are connecting to rubygems.org to verify gem version info.

Also, the only version of OpenSSL that is not EOL (1.1.1) supports TLSv1.3.

## Describe alternatives you've considered

NA

## Additional context

https://docs.fastly.com/products/tls-service-options#tls-13-and-0-rtt

**Comment by MSP-Greg** [comment]
I just checked, and most 'developer oriented' sites respond to TLSv1.3 connections.  As to popular 'normal' sites, some do, some only support TLSv1.2.

**Comment by dwradcliffe** [comment]
It's still not GA so don't expect it to roll out this week but I'll add it to my list. Thanks for bringing it up!

**Comment by sonalkr132** [comment]
rubygems.org supports TLS 1.3 now. please let us know if you face any issues.

**Comment by MSP-Greg** [comment]
Odd timing.  I just ran a check (had issues with RubyGems & GitHub Actions this morning), and noticed the TLSv1.3 connection.  Thanks for updating.
