### ISSUE TITLE
[Documentation efforts] rubydoc.info may sporadically cause issues, preventing ruby users from reading the documentation

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2493]
Hello rubygems.org maintainers and other ruby users in general,

Every now and then the documentation on rubydoc.info does not
appear to be working. For example, in the last some days when
I was to go to **a newly released gem**, such as (as **an** **example**)
https://www.rubydoc.info/gems/rbt/0.8.66 I would get:

"Error 503 Service Unavailable

Service Unavailable
Guru Meditation:

XID: 98625265

Varnish cache server"

So in other words, an error message.

For me, personally, this is not a big deal because I know my 
gems :D - but I think for people who may find a gem, they may
depend on documentation. If we compare rubydoc.info to 
github (yes, unfair comparison), then github is more reliable;
I can not remember many instances where the documentation on
github was not working.

Granted, I assume that rubydoc is doing more than github does
with plain markup files, but I believe ultimately static files
are generated, yes? Perhaps we gem authors could do so before
pushing a gem automatically, which could also help bypass the
"rendering" step, which sometimes seems to hang.

So why do I file an issue request here? After all, I believe,
rubygems.org is only looking at publishing .gem files and
making them available, not necessarily the documentation per
se. Or perhaps the documentation should be on github, but I 
actually find gem + rubygems.org muuuuuuuch simpler than 
git. My personal preference would actually be to have everything
tied into rubygems.org, but no worries, my aim here is not to
add more work to the rubygems.org maintainers.

Ultimately this issue request is more an encouragement to people
to think about the documentation infrastructure in ruby in 
general, which may (secondarily) also affect rubygems.org (see
the example of documentation on github, versus documentation 
on rubydoc.info).

I don't know how it is for other people, but if I find a new 
.gem, I look at the documentation - and if there is no 
documentation, or only a sparse documentation, then I do not
bother (usually) investing more time. In my opinion, if we 
want to see more ruby folks, and compete e. g. with python,
documentation should be really, really rock-solid for ruby.
(I am aware that documentation is primarily the responsibility
of the author at hand, but problems such as rubydoc not
available is something that potentially affects many ruby
users/developers, even those that do have an excellent 
documentation. I am also aware that many projects use 
github, including the wiki area and so forth, but personally
I'd actually prefer this ideally to be also handled by 
rubygems.org - but as said, my intention is not to add more
work, I am mostly just trying to raise awareness. Perhaps 
this goes away in the coming days or weeks.)

Please do feel free to close this issue request here at any
moment in time, so that the bug tracker is not growing too
much with not-simple-to-resolve issues. Thank you.

PS: Perhaps if it is possible, we could build all the documentation
before publishing a .gem, and then that built documentation could
also be uploaded somewhere; or as a backup. But I believe this
may require some coordination with the binary "gem" tool and
then perhaps a longer discussion. For the purpose of this issue
request, though, I wanted to not have a larger discussion, but 
more something of an encouragement, raise awareness of the
issue and so forth. So my aim was smaller here - I'd love if people
could think about the issue at hand though, e. g. what happens
if documentation is unavailable for days or weeks, what can be
done, and so forth. Apologies for the short line, I wrote this in my
local editor; the browser textarea fields I find too cumbersome)

**Comment by simi** [comment]
rubydoc.info works well, but it has some troubles recently. I have found out some related issues - https://github.com/docmeta/rubydoc.info/issues/147. Instead of rethinking whole documentation eco-system I would be for proposing help to rubydoc.info to make it stable again. I'm enjoying browsing documentation in there as well and I have faced similar troubles today.

**Comment by sonalkr132** [comment]
I agree with simi. No site on the internet can guarantee a perfect uptime. We don't want to tie everything on rubygems.org.
