### ISSUE TITLE
Search results artificially limited to 3000? 

### ISSUE THREAD

**Issue by olivierlacan** [rubygems/rubygems.org#2501]
![image](https://user-images.githubusercontent.com/65950/92985230-aa64a280-f47e-11ea-9b96-4d446c017376.png)

## Steps to Reproduce

1. visit https://rubygems.org/search
2. enter nothing in the Search input field and press `Enter`
3. you will see `DISPLAYING GEMS 1 - 30 OF 3000 IN TOTAL`

## Expected Behavior

There should be more than 3,000 gems, especially when a search for `Rails` also returns 3000 total results: https://rubygems.org/search?utf8=%E2%9C%93&query=rails

The Gems browse page lists 10,808 gems in total: https://rubygems.org/gems

![image](https://user-images.githubusercontent.com/65950/92985290-324aac80-f47f-11ea-9e8a-43ead5b51272.png)

## Current Behavior

There are only ever 3000 gems maximum returned from a search result.

## Possible Solution

There might be an artificial hard limit somewhere.

## Environment
Browser and its version: Version 85.0.4183.102 (Official Build) (64-bit)
RubyGems version: Irrelevant

**Comment by sonalkr132** [comment]
Elasticsearch limits the result size to 10,000 records. We didn't find any legitimate usecase for increasing this limit. Please check #1604

Perhaps you can use the public data dump if you need the complete result set?

**Comment by olivierlacan** [comment]
I'm not sure that elasticsearch limiting result sizes to 10,000 would explain why the max record count for any query is 3,000.

I don't need the full result set but I'd wager the search results being returned may be incomplete if elasticsearch truncates them (prior to or after doing its querying logic) returning them to the search results page. 

My goal was to quantify how many gems include the term `rails` in their name or description and this fairly trivial task seems impossible if elasticsearch truncates results. I understand that this is achievable with the data dump for sure. It just seems odd.

I could understand a 10,000 record limit given there are roughly 10,000 gems in existence, it's harder to justify 3,000 as a limit as it may be due to an optimization back when we only had roughly 3,000 gems.

**Comment by sonalkr132** [comment]
10,000 is the reason we chose to [limit it to 100 pages](https://github.com/rubygems/rubygems.org/pull/1604#issuecomment-299625125), we could have done 333 pages. 
>  the search results being returned may be incomplete if elasticsearch truncates them

> Loading the 10,000th page is very costly for Elasticsearch, since it has to fetch all the results, and skip and throw out the 9,000 "pages". ([source](https://github.com/rubygems/rubygems.org/pull/1604#issuecomment-299126123))

I sincerely doubt ES would not be going through all documents given that this the default behavior. Results are ordered by relevance along with any other overrides we have added, and limit exists only on fetching the result set part.

> My goal was to quantify how many gems include the term rails in their name or description and this fairly trivial task seems impossible if elasticsearch truncates results

The count shown in filters should be accurate and is what you are looking for.
> search for rails
FILTER: NAME (5346) DESCRIPTION (12567) SUMMARY (12737) UPDATED LAST WEEK (72) UPDATED LAST MONTH (230)

**Comment by olivierlacan** [comment]
Oh, so the default "Relevance" filter is what's truncating results to 3,000 perhaps? 
> DISPLAYING GEMS 1 - 30 OF 3000 IN TOTAL

I guess that's what's not obvious at all prior to click on any of the alternative filters like "Name", "Description", etc.

**Comment by sonalkr132** [comment]
The Elasticsearch limit is 10,000 results, we deliberately chose to limit to 3000 results (or [100 pages](https://github.com/rubygems/rubygems.org/blob/master/config/application.rb#L74)) Please check the PR I am linking in this discussion, that has all the recommendations and rationals for limits we have set.

> DISPLAYING GEMS 1 - 30 OF 3000 IN TOTAL

There should be a way to limit the pagination/results and still show the correct count of matched results (`page_entries_info`). Would that be any better? To me, it seems like it would be even more confusing to show that there are more results but just can't show them to you.

**Comment by olivierlacan** [comment]
I've looked at the PR and I understand the 10,000 count limit. I'm not questioning that. What's already confusing to me is being initially offered a total a 3000 results but also being told I can filter those results to a larger amount of results by filtering on the gem name (`FILTER: NAME (5346)`) which then results in another search page which *also* only returns 3,000 results despite previously telling me there would be 5,346.

This is not really a pagination problem I'm discussing here.

First results with `rails`: https://rubygems.org/search?utf8=%E2%9C%93&query=rails
![image](https://user-images.githubusercontent.com/65950/92986904-1b5e8700-f48c-11ea-8f53-55a5a51b7a54.png)

Filtered by `name: rails`: https://rubygems.org/search?query=name%3Arails 
![image](https://user-images.githubusercontent.com/65950/92986908-20233b00-f48c-11ea-932a-a2b4064d3a6c.png)
This should say: 
> Displaying 1 - 30 gems of 5,346 in total

Filtered by `description: rails`: https://rubygems.org/search?query=description%3Arails
![image](https://user-images.githubusercontent.com/65950/92986914-2b766680-f48c-11ea-8ebe-83c44fe35570.png)
This should say: 
> Displaying 1 - 30 gems of 12,567 in total (truncated to 10,000)

It's not more confusing to tell users there are more results than can be shown, it's accurate. It would be trivial to link to the same Issue/PR that you linked me to on the text that mentions the truncation so that users can learn more about the limitations of the Search interface and discover they can use a data dump instead if they need to. 

But going back to what I describe in this issue, I believe this is a bug. That bug results in fewer (3,000 max) than the total actual results (5,346) being returned and paginated. From what you explained this should have nothing to do with the 10,000 ES limit.

**Comment by sonalkr132** [comment]
>  results in another search page which also only returns 3,000 results despite previously telling me there would be 5,346.

I think we would be open to accepting a fix for this. I think dropping `page_entries_info` altogether from the page should be fine as well.

>  That bug results in fewer (3,000 max) than the total actual results (5,346) being returned and paginated. From what you explained this should have nothing to do with the 10,000 ES limit.

I am not sure if we should consider this a bug if we have intentionally limited results to 3000 records. The rationale being that fetching records from the end of the result set has poor performance on ES and users trying to visit past 100 pages of the search results is an extremely rare usecase. 
I mentioned the 10,000 record limit of ES to justify our 3000 record limit since the reason behind both of them is the same. sorry if it was not clear.

**Comment by sonalkr132** [comment]
> results in another search page which also only returns 3,000 results despite previously telling me there would be 5,346.

as of what should be the fix for this is a matter of opinion. IMHO, `Displaying 1 - 30 gems of 12,567 in total (truncated to 10,000)` is too much info (hence confusing) for something most users won't care about otherwise. I would suggest that we either update filters to limit to `3000` as well or just drop the `page_entries_info` line.

**Comment by sonalkr132** [comment]
I suppose `Displaying 1 - 30 gems of 12,567 in total` (without truncated part) is also acceptable. Github search results are limited to 1000 records (100 pages) even tho [it says it found 419,204 records](https://github.com/search?p=100&q=some&type=Repositories). Google search result is similar, it says it found [10,15,00,00,000 results](https://www.google.com/search?hl=en&source=hp&ei=NZ9cX-DPEJ7E4-EPhIqKsAQ&q=some&oq=some&gs_lcp=CgZwc3ktYWIQAzIFCAAQsQMyAggAMgIIADIFCAAQsQMyBQgAELEDMgIIADICCAAyAggAMgUIABCxAzICCAA6CAgAELEDEIMBUNIKWJsOYL8PaABwAHgAgAHxAYgBqQWSAQMyLTOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwigvsrisOPrAhUe4jgGHQSFAkYQ4dUDCAc&uact=5) but [pages stop at 46](https://www.google.com/search?q=some&ei=gp9cX6T1MN2Q4-EPwvuQ8A8&start=450&sa=N&filter=0&ved=2ahUKEwikvsaHsePrAhVdyDgGHcI9BP44mgMQ8tMDegQIDBBC&biw=1482&bih=759)

I understanding it is not consistent to say we had 12, 567 but only show 3000 of them, however, I think it would be a bad impression to bother users with implementation details/limitations when limiting actual results shown in standard practice and not really a concern for most of the users.
If you don't agree with any of the solutions I suggest, we can wait for more opinions on this.
