### ISSUE TITLE
Development setup procedure is ambiguous and incomplete

### ISSUE THREAD

**Issue by jhsu802701** [rubygems/rubygems.org#2504]
I'm having extreme difficulty setting up this app in my local development environment.  I understand that all or most of the collaborators are relying this app on a host OS.  I don't, because not being able to reset everything willy-nilly is a deal-breaker for me.

I have a GitLab repository for providing a Vagrant setup for this app at https://gitlab.com/jhsu802701/vagrant-rubygems-org .  (It comes with Node, RVM, and Docker pre-installed.  It also comes with Xfce, LXTerminal, Geany, and other GUI apps.)  While I prefer Docker, a Vagrant box has the advantage of behaving more like a host OS than Docker does.  (For example, Docker can run within a Vagrant box but not within a Docker container.)  Install Vagrant on your machine, and run the login.sh script to set up the development environment.

My fork of this app is at https://github.com/jhsu802701/rubygems.org.  In the "vagrant" branch, I've started a build.sh script for setting everything up.  I'm having difficulty both with running the tests and with running the app on the local server.  I understand that the Docker setup is for the latter but not the former.

What do I need to add to the build.sh script to get all the tests to pass?  (And do I need extra terminal tabs to run ElasticSearch and MemCached?)

What do I need to provide in a server.sh script to get the app to run on the local server?

**Comment by sonalkr132** [comment]
> Development setup procedure is ambiguous and incomplete
> What do I need to add to the build.sh script to get all the tests to pass?

It would be helpful for us if you could be more specific. Steps for setting up rubygems.org on a Debian host exist [here](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#environment-linux---debianubuntu). Can you please let us know which steps did you try and what didn't work for you or any error you saw?

>  do I need extra terminal tabs to run ElasticSearch and MemCached?

Not necessarily. You can run them as daemon processed using system them. If you install these with apt, a service file gets added and you need to run `sudo service elasticsearch start` (same for memcached)

**Comment by sonalkr132** [comment]
Hi, I am going to close this for lack of response. docker-compose is our recommended way of setting up dev env. Without further clarification about your use case, we can't help you with an alternate setup. 
Feel free to reopen this or hop over to https://bundler.slack.com/ if you need help.
