### ISSUE TITLE
Vagrant setup

### ISSUE THREAD

**Issue by jhsu802701** [rubygems/rubygems.org#2525]
I'd like to provide an OPTIONAL Vagrant setup (Vagrantfile) and scripts for setting up this project.  The current setup instructions involve installing Ruby and Rails on the host system.  (It's impossible to run a Docker container within a Docker container.)  I've learned NOT to rely on the host system for my development environment and to use a virtual environment instead.  Relying on the host system means not having the freedom to reset it willy-nilly, and that's a deal breaker for me.

Things I intend to include:
1.  A Vagrantfile that provides a Debian or Ubuntu base box and provisioning with RVM, Ruby, bundler, Docker, and other essential tools.  All you have to do is enter "vagrant up" to log in.
2.  A build script consisting of a reminder to run "docker-compose up", the "bundle install" command, the database migrations, running the script/setup script, running the tests, running RuboCop, database seeding, etc.  After you log into the Vagrant box, all you have to do is enter "vagrant/build; vagrant/server" to set everything up, run all the tests, and start up the Rails server.

I understand that I have the option of just maintaining my own special branch, but I'd like to help others get started contributing to this project.

**Comment by simi** [comment]
> It's impossible to run a Docker container within a Docker container.
It is possible with shared host docker environment.

I don't think Vagrant file is needed for your purpose. It should be possible to also start rubygems.org inside docker and connect it to services in [docker-compose.yml](https://github.com/rubygems/rubygems.org/blob/0576f154ac5283c8590344dcf3241a3a61eda9bc/docker-compose.yml). That part is just missing in current docker-compose.yml for now.

More info for example at https://www.digitalocean.com/community/tutorials/containerizing-a-ruby-on-rails-application-for-development-with-docker-compose (see mainly app section in docker file, that's the one missing currently).

**Comment by jhsu802701** [comment]
I'm sure that there's a way to get Rails to work in Docker instead of the host system, but I've been unable to figure it out.  The Vagrant way is the compromise that I'm working on.  Of course, once I get things working under the Vagrant way, I'll be in a stronger position to fully Dockerize everything.

**Comment by sonalkr132** [comment]
I think it would be nice to stick with docker for development as well. See #2525 for the discussion on how to go about this. Thank you for your suggestion.
