### ISSUE TITLE
Sponser logos in footer, botton row and website redirects doesn't match on rubygems.org

### ISSUE THREAD

**Issue by sahilister** [rubygems/rubygems.org#2535]
## Steps to Reproduce

1. Open <https://rubygems.org/>
2. In footer, sponsor section, click on bottom row sponsor logos.

## Expected Behavior

1. "gauges" logo should redirect to https://get.gaug.es/ (taken from https://guides.rubygems.org)
3. "Runscope" logo should redirect to https://www.runscope.com/
4. "fastly" logo should redirect to https://www.fastly.com/
5. "DataDog" logo should redirect to https://www.datadoghq.com/
6. "Travis CI" logo should redirect to https://travis-ci.org/
7. If honeybadger is still a sponsor, a logo of that should be present.

## Current Behavior

1."gauges" logo, redirect to https://www.runscope.com/
2. Click on "Runscope" logo, redirects to https://www.fastly.com/
3. Click on "fastly" logo, redirects to https://www.datadoghq.com/
4. Click on "DataDog" logo, redirects to https://travis-ci.org/
5. Click on "Travis CI" logo, redirects to https://www.honeybadger.io/

## Environment
Browser and its version: Mozilla Firefox 78.3.0esr (64-bit), Brave Browser 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
RubyGems version: Not applicable.

## Additional Context

Sponser logo on https://blog.rubygems.org/ and https://guides.rubygems.org/ displays correctly.

**Comment by simi** [comment]
I can confirm it is shifted.

Current approach is hardcoded in sponsors.png (contains sprite based logos). It will be nice to get this somehow automated.

https://github.com/rubygems/rubygems.org/blob/259a9f90d5fca3e87c3bae3c11d82eb18f580d19/app/assets/stylesheets/modules/footer.css#L77-L153

**Comment by simi** [comment]
> this is broken still @sonalkr132 @simi

Can you provide more details? What's wrong currently?

**Comment by samdenty** [comment]
the urls are stilll mixed up

**Comment by simi** [comment]
@samdenty can you be please more specific? Which urls where exactly?

**Comment by hsbt** [comment]
@simi The all of logs are incorrect link after RubyTogether. 

![Screenshot 2023-03-02 at 8 36 49](https://user-images.githubusercontent.com/12301/222291414-a5db3ec6-286f-4e34-b501-b970f91f3d2b.png)

see down of left url. It's RubyTogether link.
