### ISSUE TITLE
Return yanked versions (with flag) for `/versions` API end-point

### ISSUE THREAD

**Issue by AlexWayfer** [rubygems/rubygems.org#2552]
## Is your feature request related to a problem?

I want to get and print all versions, including yanked ones (with marks about this).

## Describe the solution you'd like

Get an array of all versions, including yanked ones, with `yanked: (true|false)` flag.

https://guides.rubygems.org/rubygems-org-api/#gem-version-methods

## Describe alternatives you've considered

I don't see any way to get them.

## Additional context

Probably related to #406

**Comment by simi** [comment]
@AlexWayfer Can you share your usecase for this feature?

**Comment by AlexWayfer** [comment]
> @AlexWayfer Can you share your usecase for this feature?

https://github.com/AlexWayfer/gem_toys/commit/e0b012fb7b1d8b189d38ea981fcc997a83bbeecb

**Comment by sonalkr132** [comment]
Hi, it is very unlikely we will be able to change `/api/v1/versions/` to list yanked versions as well. It is too big a change.
We can add a v2 however your usecase doesn't seem very clear (or common). You also seem to have moved on to an [alternate method for finding current versions](https://github.com/AlexWayfer/gem_toys/blob/master/lib/gem_toys/template/release.rb#L70). 
> I want to get and print all versions, including yanked ones (with marks about this).

It is not clear what do you mean by marks and why the user may be interested in marks for versions which are not installable. Please consider using our [data dump](https://rubygems.org/pages/data) where you can find yanked versions as well.

**Comment by AlexWayfer** [comment]
> You also seem to have moved on to an [alternate method for finding current versions](https://github.com/AlexWayfer/gem_toys/blob/master/lib/gem_toys/template/release.rb#L70).

I was talking about versions list functionality, not about current version or version update.



> It is not clear what do you mean by marks and why the user may be interested in marks for versions which are not installable.

Example:

```
> toys gem versions
0.3.0 (unreleased)
0.2.0 (2020-10-25)
0.1.0 (2020-09-15) (yanked)
```

For now, there is no `0.1.0` version, and it's not clear why the first gem's version is `0.2.0` and not `0.1.0`.

Also I think there should be a consistency between site and API: I have an ability to see yanked versions on site, but can't via API. It's weird.

> Please consider using our [data dump](https://rubygems.org/pages/data) where you can find yanked versions as well.

When I work on a specific gem — I'm not interested in all gems data, and I don't think that user of this command would be interested in downloading and updating 200+ MB of data and slow parsing of this.

**Comment by sonalkr132** [comment]
> Also I think there should be a consistency between site and API: I have an ability to see yanked versions on site, but can't via API. It's weird.

API is for programmatic clients, which at the moment are working on the assumption that the response will only have indexed versions. There hasn't been any usecase so far where a programmatic client would do something with yanked versions.
yanked versions are shown in UI so that humans don't get confused when their `gem push ..` fails.
I hope it is clear that given that all exists clients are working on the assumption that we will only respond with indexed versions, it is not possible to change this behavior. 
If you really want this feature, please open a new issue requesting for a v2 endpoint that has yanked versions. Before that, I would recommend reconsidering if you really need to show yanked versions in your tool. yanked versions are as good as non-existent and we only keep the record around to ensure that same version can't be pushed again.

**Comment by AlexWayfer** [comment]
I thought about your comment, there are my thoughts: for backward compatibility we can add an option for `/versions` API end-point, like `yanked=true`, which will include yanked versions in result. False by default, yes.



> Before that, I would recommend reconsidering if you really need to show yanked versions in your tool. yanked versions are as good as non-existent and we only keep the record around to ensure that same version can't be pushed again.

Good point. I can agree, I think. But still I like consistency and flexibility. So, with accounting my previous suggestion, do you still think it's a V2 feature request or it can be V1? I can create an issue in any case.

**Comment by sonalkr132** [comment]
`versions` endpoint is fairly popular and I would be very reluctant to make changes to it or add more complexity than absolutely necessary. `if.. else` with a param is almost the same as two actions to me.
I suppose what would be easiest for us to add would be a v1 endpoint just for yanked versions. I hope you agree that making changes to an established API is justifiable if there is "popular" demand for it or if it can be done at no "cost".

**Comment by AlexWayfer** [comment]
> `if.. else` with a param is almost the same as two actions to me.

Entities and format are the same, so it's logically should be one action with filtering.



> I suppose what would be easiest for us to add would be a v1 endpoint just for yanked versions. I hope you agree that making changes to an established API is justifiable if there is "popular" demand for it or if it can be done at no "cost".

I actually don't force you to add some v1 end-point, v1 param or even v2 end-point, I just faced with the case and suggested some solutions. I can agree that yanked versions generally are not too important, but I also still think that API should return the same data as available via web-interface or something else.

And I see no serious performance or support penalty for solution via param with current behavior default: there is an addition condition, but it should not be heavy for CPU (just HTTP param check).
