### ISSUE TITLE
[Feature request] Viewing the content of a .gem via rubygems.org

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2574]
This is a feature request.

I maintain several gems, and some of my larger gems come with different commandline-scripts,
under bin/. These work fine too, but I realized today that users do not seem to have a simple
way to see which files are part of a .gem, actually, before installing or downloading it. Of course
gem authors can use github, and many do, but I think it may be better if rubygems.org itself
could also have a basic feature: the **ability to look which files are part of a .gem file** that is.

I am thinking of something simple like archlinux pkgview:

https://www.archlinux.org/packages/extra/x86_64/gtk3/

See the "Package Contents" part. This only lists the files installed by that package.

Of course having something like github, where we can view content and stuff,
would be nicer, BUT this is probably also much harder to implement, so I don't
suggest that; let's keep it simple, also simpler to implement. A simple way to
just display the contents of a .gem file, via rubygems.org (of the homepage
of the particular .gem at hand).

I believe the implementation should not be too difficult, because I assume the
content is already registered somewhere when a .gem is either created, or
uploaded. So we only need to query that information; once this has been done,
it should be simple to display it.

The name for this action could be "View contents" or something similar, perhaps
just "Content" or so. It could reside as a link next to the other links, such as 
unsubscribe, "Review changes" and so forth.

So I suppose, the first step is to ask folks, especially the rubygems.org maintainers,
what they think about such as basic (keep it simple) functionality. Obviously there
is always a trade-off between time investment, and the functionality as such.

Last but not least, to "respond" to an argument that github offers this already
as-is - yes, I understand that; yes, it is useful, but I think the question is whether
something should not be implemented because another website is better 
already, and then we can wonder why we'd need to have rubygems.org, if
we can all use github, which is why I think rubygems.org itself should have
that functionality as well. (Additionally not everyone is actually using github,
for various reasons. So I don't think the discussion should be solely around
"alternative functionality" alone, without considering other potential trade-offs
involved. For example, git itself is not necessarily trivial; "gem" on the other
hand is MUCH, much simpler, and github essentially requires knowledge 
about git for the most part, at the least for the project owner and some 
actions that don't have a web-interface equivalent)

**Comment by simi** [comment]
:thinking: I think this would be nice idea for 3rd party service like https://my.diffend.io/ lightly integrated into rubygems.org by link on gem version page.

**Comment by sonalkr132** [comment]
sorry, showing the content of the gem doesn't fit well without goals. as mentioned by simi if someone creates a third party service for it, we would be happy to link to it.
also, it would be very kind of you if you can follow the issue template.
