### ISSUE TITLE
Notify authors before certificates expire

### ISSUE THREAD

**Issue by svoop** [rubygems/rubygems.org#2589]
Trying to be a good Ruby world citizen, I've signed my gems and use Bundler with `bundle config --trust-policy MediumSecurity` only. As of now, this means that the following has become kind of a running gag: 

```
The gem foobar can't be installed because the security policy
didn't allow it, with the message: certificate
/CN=foo/DC=bar/DC=com not valid after 2019-08-03 21:34:05
UTC
```

It would help a lot if gem authors were notified say 1 month prior to the expiration of the cert. Looking at the code, there's no CRON-like scheduler in place, but it should be possible to do without, for instance:

When a gem version is published, read the cert. If for whatever reason this is not possible, notify the author immediately. Otherwise, create a notification mail and delay it with `.delay(queue: 'expiration_notifications', run_at: expires_on - 1.month)` via Delayed::Job. The downside: Every push will queue a new notification, so it's necessary to check for existing notification jobs prior to adding a new one to the queue. While possible by inspecting what's in the queue, it might be better not to touch these internals and just add a separate model for such lookups.

What do you think, useful or not?

(As a side note: This is just one brick in a bigger wall to build in order to make the whole signing business become more widely used. Unfortunately, there's not much going on in that field and I'm not crypto savvy enough to plot a path.)

**Comment by rubyFeedback** [comment]
Just for a clarification, a question: is this specific to bundler only? For example I am just using "gem" and have not signed any of my gems.

> This is just one brick in a bigger wall to build in order to make the whole signing business become
> more widely used. Unfortunately, there's not much going on in that field and I'm not crypto savvy
> enough to plot a path.

I can't speak for others but I am usually very lazy - I try to go the minimal route, so adding more
obstacles isn't good for me. I agree that it is great for users who want to rely on code though.

When "gem" was designed initially, I assume the biggest goal was to distribute ruby code; 
security was probably not the very first idea. This is perhaps where the website could be
useful, rather than commandline, to provide an overview for ruby authors to see what
can be done to improve things. This also starts with documentation by the way; ruby 
has been rather notorious in not having great documentation everywhere. I would not
even know where to read up on this. :)

**Comment by svoop** [comment]
@rubyFeedback This is not Bundler specific, signing gems is a feature of Rubygems. Configuring the trust policy with Bundler makes sure, it is enforced whenever Bundler installs gems via Rubygems.

> When "gem" was designed initially, I assume the biggest goal was to distribute ruby code;
security was probably not the very first idea.

Yep, I also remember the days of ISCABBS over plain Telnet... but we've all [suffered trough 2020](https://en.wikipedia.org/wiki/2020_United_States_federal_government_data_breach) and it's 2021 now.

> This also starts with documentation by the way; ruby
has been rather notorious in not having great documentation everywhere. I would not
even know where to read up on this. :)

Not in this case, there's a Security Guide on rubygems.org. There's certainly lots of room for improvement, but it's a good start:

https://guides.rubygems.org/security/

**Nonetheless, let's focus on the notification idea and not the OT side note, thanks!**

**Comment by matiaskorhonen** [comment]
Sounds like a good idea. Currently the gem signatures aren't validated at all. As in it's possible to push a gem with a completely mangled signature without any complaints from RubyGems.org.

I have an open PR that would add signature verification and also save a copy of the certificate chain to the database (#2444) but it hasn't received much attention. This would also allow the expiration dates to be recorded.

**Comment by simi** [comment]
Since the latest plans of current certificates functionality, would it be ok to consider this feature as frozen and subject of removal @indirect (and thus is it ok to close this issue)?

**Comment by indirect** [comment]
Yes, I think so. Our plans to support signed gems in the future will most likely be based on sigstore.dev.
