### ISSUE TITLE
[Question, sort of] Odd download numbers suddenly? Or is it not odd?

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2602]
Hey guys,

This is more a question than a feature request or anything.

In the last ~5 days or so, I have suddenly noticed that some of my gems have 
SIGNIFICANTLY more download numbers.

Let me give you an example:

https://rubygems.org/gems/multimedia_paradise

I did a new release yesterday, and there are suddenly 342 downloads for that
version.

Before that, I would usually have 100-150 downloads AFTER ABOUT THREE
WEEKS or so. So I can not explain the numbers. I'd be flattered to think my
projects are much more useful, but I doubt this ;) - the awkward thing is
that I notice this sudden increase in downloads for almost all of my gems.
And I can not explain WHY.

Has something changed recently? Some count mechanism or something?

I am aware that most downloads are probably from scripts/bots anyway,
but even then I am confused why the numbers are suddenly so different.

If anyone has an idea what might explain this, perhaps that could be
explained. (Or perhaps it was the ruby 3 release? But I am not yet
using ruby 3, largely because the ruby-gtk bindings are not yet adapted,
and I am adding a LOT of ruby-gtk3 code recently to all my projects
specifically; I transition to ruby 3 when I can work with ruby-gtk3 too).

Anyway, please as always, feel free to close this at any moment in
time; but since it is a question, I would recommend to close it
before a month or so has passed. Hope it is ok to ask a question
still.

**Comment by sonalkr132** [comment]
There have been no changes in our downs count processing. 
Your gem seem to be getting downloaded multiple times from the same client IP and user-agent multiple times https://ui.honeycomb.io/ruby-together/datasets/rubygems.org/result/aqNr8Vw5Rh4

I don't see any unusual increase in overall download trends https://ui.honeycomb.io/ruby-together/datasets/rubygems.org/result/dzbfauYCDRx
