### ISSUE TITLE
[A cosmetics change, mostly] Consider changing the owner-message indicating whether something is using MFA or not a bit (see description in the issue itself)

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2624]
Small cosmetic change: from "some owners" to "the owner".

Hey rubygems-maintainers and others reading this.

Right now if you look at a gem webpage, you can see this:

"Owners:
* Some owners are not using MFA. Click for the complete list."

This is ok in the sense that you notify other users whether
the gem author is using MFA or not. No problem there.

There is, however had, a bit of nitpicking done by me here,
I admit it. :)

I believe that, IF there is only one owner, then it may 
be better to indicate this as well.

So my suggestion, in pseudo-code, would be:

    if owners?.size == 1
      "The owner is not using MFA. Click for the complete list."
    else
      "* Some owners are not using MFA. Click for the complete list."
    end

Something like that.

I know, I know, not really important since it is just cosmetics,
but I think slightly more accurate descriptions would be helpful,
as technically "some owners" is inaccurate if there is only
one owner. But the good side is that this would be trivial to
change too!

**Comment by rubyFeedback** [comment]
(Perhaps if this change is approved, the "Click for the complete list"
in the first case could also be changed, as "complete" may no longer
be necessary since it is only one owner. But anyway, enough
nitpicking from me here.)

**Comment by deivid-rodriguez** [comment]
This makes sense to me!

**Comment by simi** [comment]
@rubyFeedback can you provide PR? It makes sense to me as well.

**Comment by kiranmahale** [comment]
@rubyFeedback  https://github.com/rubygems/rubygems.org/pull/2646
I have created a PR for this. Can you please check once?

**Comment by sonalkr132** [comment]
closed by #2646
