### ISSUE TITLE
Declare language in HTML

### ISSUE THREAD

**Issue by Goudarz** [rubygems/rubygems.org#2650]
Hello,
The `lang` attribute does not change in HTML when I select a language.

**Comment by simi** [comment]
Hello @Goudarz, would you mind to contribute this change?

I think it should be enough to make lang attribute dynamic according to `I18n.locale`.

https://github.com/rubygems/rubygems.org/blob/cf6b01cdf71c77b28cd8907ad228e622445c3064/app/views/layouts/application.html.erb#L2

**Comment by sonalkr132** [comment]
closed by #2666
