### ISSUE TITLE
Required ruby version  miss-reported in rubygems.org ?

### ISSUE THREAD

**Issue by bronzdoc** [rubygems/rubygems.org#2651]
Im seeing the required ruby version for the `skunk` gem to be `>= 0` in rubygems.org https://rubygems.org/gems/skunk/versions/0.4.2 

<img width="185" alt="Screen Shot 2021-02-18 at 9 36 11 PM" src="https://user-images.githubusercontent.com/4595174/108454237-a0b34800-7231-11eb-924a-7f2d1718e8de.png">

but it has a specific ruby requirement specified in the gemspec https://github.com/fastruby/skunk/blob/main/skunk.gemspec#L17

Is this expected behavior?

**Comment by sonalkr132** [comment]
Replied on the linked issue. closing this.
