### ISSUE TITLE
Unable to view gem "thread" on rubygems.org

### ISSUE THREAD

**Issue by mockdeep** [rubygems/rubygems.org#2654]
When clicking the link to view [the gem `thread`](https://rubygems.org/gems/thread) on rubygems.org it displays the message "This namespace is reserved by rubygems.org."

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
It's expected. thread is reserved by ruby-core and rubygems team.
