### ISSUE TITLE
Improve MFA options by ranking and contextualizing them 

### ISSUE THREAD

**Issue by olivierlacan** [rubygems/rubygems.org#2686]
Right now the flow for MFA options is quite confusing even for someone who's familiar with MFA because it's not clear what options are more secure than others. 

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/65950/113060049-281f9f80-917e-11eb-874f-a105a3f92c8c.png">

This is classic example of choice paralysis. Is `UI and gem signing` less secure than `UI and API`? Is it offered because it can be cumbersome to have any API request require MFA? This feels like a design that was arrived to by a little too much consensus. It could easily be assisted by some context.

Right now this option menu doesn't even offer a link to https://guides.rubygems.org/setting-up-multifactor-authentication/#authentication-levels which clearly explains the differences. 

<img width="725" alt="image" src="https://user-images.githubusercontent.com/65950/113060370-8c426380-917e-11eb-8654-6a525857d02d.png">

The least should at the very least read like this (in this least-to-most order): 
- `Disabled (Not Secure)`
- `UI only (More Secure)`
- `UI and gem signin`
- `UI and API (Most Secure)`

But really, the reason for the existence of these options is leaking through. I could bet the `UI and gem signin` option is there for people who use an account for systems where the credentials are used by an automated system which can't supply MFA credentials (a CI/CD system). But who not make this obvious to help people make better decisions? 

Ideally, let's just please put those descriptions in the interface even if that makes localization harder. Don't make people seek out documentation when it could be in the tool.

**Comment by rubyFeedback** [comment]
Guess that change may be useful compared to the current status quo indeed.

**Comment by sonalkr132** [comment]
> Right now this option menu doesn't even offer a link 

Adding a `read more` kind of link would a good improvement.
The options are ordered from most to least secure. Would adding related icons specifying the level of security be acceptable? Adding "(recommended)" text only would be preferable for me.

**Comment by ecnelises** [comment]
Drafted https://github.com/rubygems/rubygems.org/pull/2710 for comments.

<img width="978" alt="Screenshot" src="https://user-images.githubusercontent.com/10329663/117180387-b682e300-ae06-11eb-8ab1-8d53ddd32b14.png">

**Comment by olivierlacan** [comment]
@ecnelises Lovely!

**Comment by sonalkr132** [comment]
closed be #2710
