### ISSUE TITLE
Everything is in french now! (I think it is a small bug but it is actually quite amusing to me right now :D )

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2735]
Hey there rubygems.org maintainers,

I may have found a tiny bug in the "search" functionality.
(I initially thought it is only the search functionality,
but now all of rubygems.org is in french ... I don't know
why that is the case...)

The URL I was using is this one here:

https://rubygems.org/search?query=audio

The results I got were in french, which is super-strange.

For example, I get results such as:

"Recherche avancée"

I did the following partial screenshot to indicate the
result I got: 

https://i.imgur.com/Tm8lPN6.png

(Browser is palemoon, default bundle; english all the
time. While german is my native tongue, I really do 
just about everything in english, so I am totally
confused why I get a result in french.)

I did not seem to get this a few months ago, or perhaps
I did not notice it, but either way I think this may be
a small bug. Perhaps it assumes some default to french?
No real idea, but I tend to prefer english in general
mostly because more people use english compared to 
languages such as german or french. :D

Anyway, this is just for information, feel free to 
close/handle this in any way you see fit. I am just
confused that something would opt for french here,
which is quite peculiar to me.

I also tested "https://rubygems.org/settings/edit"
which also shows this in french. Super confusing to
me! I am not even sure what these options mean. :P
Perhaps some button could be used for english? Or
I have to use babelfish to revert this back ...
(I can not remember doing so deliberately; it would
not be useful to me so I don't think I did change
this manually. The old default was english, and I
would not switch it to any other language since 
english is more useful to me. All applications I
use also run in english. It's quite a funny bug
though! Now rubygems.org makes me learn french,
until I find out where to change this! :D )

**Comment by sonalkr132** [comment]
Hi, I can't reproduce this. We can reconsider this if you can share steps to reproduce.
You can fix your issue by clicking on "English" from the footer or deleting your cookies.
