### ISSUE TITLE
More restrictions on API keys

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems.org#2755]
Expanding on https://github.com/rubygems/rubygems.org/pull/2601

I think ideally what I'd like is:

- [x] API key specific to one or more gems (minimise blast radius if compromised).
- [x] Enable/disable OTP requirement per key (allow for automated use).
- [x] ~~Ability to specify key via command line e.g. ENV (don't need to write it into `~/.gem/credentials`).~~

The value in this is to allow per-project API keys which can publish gems.

Edit: third point is already supported. use --otp or GEM_HOST_OTP_CODE env rubygems/rubygems#4697

**Comment by jchestershopify** [comment]
Should this be a single issue or broken down into standalones? I ask because I can think of at least two other wishlist items: that push tokens can _only_ push (because token leaks are likely to occur in CI/CD), and that all tokens expire without exception (following the Let's Encrypt precedent).

**Comment by ioquatix** [comment]
As long as token expiration is something decent like 12 months I'd be fine with it.

**Comment by jchestershopify** [comment]
I'd argue for more frequently -- 12 months is long enough that people totally forget about how they rotated the token last time. Let's Encrypt set their expiries at 90 days to encourage routines and automation.

**Comment by duckinator** [comment]
To me, an expiration time of 90 days or 6 months seem like the best options. 12 months might be okay.

It feels like a "sweet spot" where the maintenance burden for not automating it is only a _periodic_ concern, but the tokens still gets cycled regularly.

**Comment by simi** [comment]
API scoped gems were added at https://github.com/rubygems/rubygems.org/pull/2944, closing for now :muscle:
