### ISSUE TITLE
Gem limit for v1 dependencies causes aws-sdk to fail to install

### ISSUE THREAD

**Issue by neilsimon** [rubygems/rubygems.org#2765]
Installing the aws-sdk via gem install fails after receiving a `422 Unprocessable Entity` response from rubygems.org

## Steps to Reproduce

See https://github.com/aws/aws-sdk-ruby/issues/2574
1. `# gem install -V aws-sdk --source=https://www.rubygems.org`

## Expected Behavior
Installation of the appropriate gem

## Current Behavior
Takes an extremely long time and does not seem to complete.

## Possible Solution
See:
https://github.com/rubygems/rubygems.org/pull/2470
Increase the limit again to address the fact that aws-sdk-resources added new dependencies.

## Environment
Ubuntu 18.04
ruby 2.5.1p57

**Comment by simi** [comment]
https://rubygems.org/gems/aws-sdk-resources -> 277 deps. Is it anyhow useful to use this gem directly instead of picking only needed deps?

Anyway I think we can again increase limit similar to https://github.com/rubygems/rubygems.org/pull/2470/commits/ab83ba90aad7ab29df0696e8eeac553f20bceade to 300 now.

**Comment by neilsimon** [comment]
Thanks, that increase should help for now.

The Chef aws cookbook (https://supermarket.chef.io/cookbooks/aws/versions/8.4.0) is dependent on the aws-sdk gem. The ideal solution would be for the cookbook to follow the approach you describe, only loading the gems it needs, as needed. I have entered an issue for the cookbook (https://github.com/sous-chefs/aws/issues/441), but such is a significant change, and in the interim it is impossible to use this cookbook.

**Comment by sonalkr132** [comment]
#2767 was deployed. Let us know if the issue still exists. Thank you for reporting this and the PR.
