### ISSUE TITLE
`/versions` endpoint out-of-date

### ISSUE THREAD

**Issue by ankane** [rubygems/rubygems.org#2808]
Hi, thanks for maintaining Rubygems.org! I wanted to report that the `/versions` endpoint seems to have stopped updating. This is leading to issues like https://github.com/ankane/lockbox/issues/139.

## Steps to Reproduce

1. Visit https://index.rubygems.org/versions

## Expected Behavior

Recently published versions of gems to be listed and `created_at` to be recent.

## Current Behavior

Recent versions aren't listed and `created_at` is 40 hours ago.

```text
created_at: 2021-09-28T02:51:38+00:00
```

**Comment by sonalkr132** [comment]
Hi, you should be able to install lockbox 0.6.6 now. We need to make a few changes to resolve this permanently.

**Comment by ankane** [comment]
Great, thanks @sonalkr132!
