### ISSUE TITLE
Pusher accepts signed gems having a valid signing certificate and an expired root certificate

### ISSUE THREAD

**Issue by rochlefebvre** [rubygems/rubygems.org#2830]
https://github.com/rubygems/rubygems.org/pull/2444 added signature verification to signed gems, but only against the signing (i.e. leaf) certificate.  If the cert chain contains more than one certificate, any of the root and/or intermediate certs may be expired or otherwise invalid. See [`Pusher`](https://github.com/rubygems/rubygems.org/blob/f84c2e741e233a55a2e3ac0f2f96c9fb2f7a1913/app/models/pusher.rb#L161) and [`LowSecurityPolicy`](https://github.com/rubygems/rubygems/blob/2f48d60afe050862258212d0c68530f39fb5fdfa/lib/rubygems/security/policies.rb#L46-L47).

## Steps to Reproduce
Let's create a signed gem with a valid signing certificate, `child_cert.pem`. This cert has been signed with an old CA certificate, `expired_root_cert.pem`.  We then push the gem and check the response.

1. Copy these test fixtures from rubygems:
  - [child_cert.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/child_cert.pem) - signing certificate
  - [child_key.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/child_key.pem) - private key for signing certificate
  - [expired_cert.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/expired_cert.pem) - root certificate
  - [private_key.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/private_key.pem) - private key for root certificate, used to sign child_cert.pem
2. Sign your signing certificate:
```
gem cert -K private_key.pem -C expired_cert.pem --sign child_cert.pem
```
3. Add these two certs to the `cert_chain` of a gemspec, along with the child_key.pem as the `signing_key`. Here is an example:
```ruby
# ./expired_root_cert-0.0.0.gemspec
Gem::Specification.new do |s|
  s.name          = "expired_root_cert"
  s.version       = "0.0.0"
  s.platform      = "ruby"
  s.require_paths = ["lib"]
  s.authors       = ["Anthony The Tiger"]
  s.summary       = "A very bar gem"
  s.signing_key   = "child_key.pem"
  s.cert_chain    = ["expired_cert.pem","child_cert.pem"]
end
```
4. Build the gem.  **I had to modify my local `rubygems`' [`SigningPolicy`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/security/policies.rb#L98) by setting `verify_root = false`**, otherwise I can't create a new signed gem with an expired entry in the chain.  Pretend that the gem was generated at a point in time where all certs were valid.
```
ruby -Icustom/rubygems/lib custom/rubygems/bin/gem build expired_root_cert-0.0.0.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  no homepage specified
WARNING:  no files specified
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: expired_root_cert
  Version: 0.0.0
  File: expired_root_cert-0.0.0.gem
```
5. Push `expired_root_cert-0.0.0.gem` to your local rubygems.org
```
RUBYGEMS_HOST=http://localhost:3000 gem push expired_root_cert-0.0.0.gem
Pushing gem to http://localhost:3000...
Successfully registered gem: expired_root_cert (0.0.0)
```
6. Try to install this gem locally with a MediumSecurity policy or higher:
```
gem install expired_root_cert-0.0.0.gem  -P MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=nobody/DC=example not valid after 1970-01-01 00:00:00 UTC
```
So the server accepts this gem but the client rightfully rejects it.

## Expected Behavior
On step 5, we should get an response similar to what we see in Step 6:
```
RUBYGEMS_HOST=http://localhost:3000 gem push expired_root_cert-0.0.0.gem
Pushing gem to http://localhost:3000...
RubyGems.org cannot process this gem.
Please try rebuilding it and installing it locally to make sure it's valid.
Error:
certificate /CN=nobody/DC=example not valid after 1970-01-01 00:00:00 UTC
```

## Current Behavior
See Step 5.

## Possible Solution
Don't use LowSecurity in Pusher when vetting a signed gem.  Don't use MediumSecurity either, as that one requires the root cert in the chain to be in the trust store.  None of the predefined policies in `rubygems/security/policies.rb` really do what we want.

Let's instantiate a custom Policy for the duration of the push operation:
```ruby
  def gem_security_policy
    @gem_security_policy ||= begin
      # Verify that the gem signatures match the certificate chain (if present)
      policy = Gem::Security::Policy.new(
        'Pushing Policy',
        :verify_data      => true,
        :verify_signer    => true,
        :verify_chain     => true,
        :verify_root      => true,
        :only_trusted     => false,
        :only_signed      => false
      )
      # Silence warnings from the verification
      stream = StringIO.new
      policy.ui = Gem::StreamUI.new(stream, stream, stream, false)
      policy
    end
  end
```
**Spoiler alert!: Expect a PR doing just that soon. Also, the main protagonist was dead all along.**

## Environment
Browser and its version: Chrome Version 94.0.4606.81 (Official Build) (x86_64)
RubyGems version: 3.2.20
Ruby version: 2.7.4

**Comment by sonalkr132** [comment]
> gem install expired_root_cert-0.0.0.gem  -P MediumSecurity

Can you please elaborate on why should rubygems.org only support gems which pass medium or above security levels? IMO, publishing and installing gems that only pass LowSecurity is a legitimate use case.
If we really want to use a custom policy, I think we should define it in rubygems and then use it in rubygems.org.
