### ISSUE TITLE
Some test call `assert_equal` with `expected` and `actual` in the wrong order

### ISSUE THREAD

**Issue by rochlefebvre** [rubygems/rubygems.org#2850]
Follow up to #2847, #2848, and #2849.

`assert_equal` statements should be of the form
```ruby
assert_equal expected_value, actual_value
```
But there are tests which flip those values around.  Many have been fixed in previous PRs, but I did see some in https://github.com/rubygems/rubygems.org/blob/master/test/unit/version_test.rb.  There may be other instances as well.

## Expected Behavior
```ruby
assert_equal ["is too long (maximum is 255 characters)"], @version.errors.messages[:required_rubygems_version]
```

## Current Behavior
```ruby
assert_equal @version.errors.messages[:required_rubygems_version], ["is too long (maximum is 255 characters)"]
```

**Comment by Ashvith** [comment]
Can I look into this @rochlefebvre ?

**Comment by Ashvith** [comment]
I would like to leave this issue to someone else @rochlefebvre.
