### ISSUE TITLE
[Small Enhancement] It is proposed to extend "https://rubygems.org/profile/adoptions" a bit with more information

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2892]
I just noticed this:

https://rubygems.org/profile/adoptions

I assume this is somewhat new?

The content right now is:

"Ownership Calls:
You have not created any ownership call for any of your gems.

Ownership Requests:
You have not created any ownership request. "

I propose to add more information to this.

Either as an additional link towards a page that explains what this means;
or as some on-hover or some other mini animation perhaps. But I think
a simple link may suffice.

Explanation: I think if you, as a user or visitor, don't know this new functionality yet
then you may  have a question what this is all about. In particular right now I don't
know the difference between an ownership call, and an ownership
request. I assume there is a difference but right now I don't know it. This is
why I think more explanation may be useful, if not on the same page then
perhaps on some other page, FAQ entry or some such.

I also have a suggestion to be able to add a gem from right that
webpage as such, but I believe this may come, if necessary,
at a later time, with a separate suggestion. So for this issue
request, it is really confined to providing more information about
this. I believe other ruby users may benefit from more information
in this regard, perhaps if there was a discussion too, to link from
that - but mostly just to explain what the difference is between
these two, how to use it and so forth.

**Comment by sonalkr132** [comment]
see #2910

**Comment by sonalkr132** [comment]
closed by #2910
