### ISSUE TITLE
[Minor bug] - Strange inconsistency in regards to language display on rubygems.org/profiles/id

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#2902]
First let me show the image:

https://i.imgur.com/vz7bEGs.png

Hopefully that works upon clicking (hosted on imgur).

Next I will describe this a bit - that hopefully helps understanding the issue.

Some time ago I reported that I see settings in french. Now, suddenly, it is
... in german. I have no idea why. I do not remember having changed 
anything at the settings, so to me this is super-weird that suddenly german
is shown. I'd like to keep this all in english. But different to the french
variant before, the weird thing here is that it is inconsistent. Let me
explain this - look at the picture to understand what I mean.

On the middle/left side you can see "Settings", "Adoptions" and
"Edit Profile". This is all in english. But on the right side you can 
read "GEMS INSGESAMT" (aka total gems), "DOWNLOADS
INSGESAMT" (aka total downloads), and on top you can read
"Dokumentation" which is actually "Documentation" (almost
like english, just with the 'k' rather than the 'c').

So to me it seems as if rubygems.org is TRYING to display
german (for whatever the reason, I have no idea), but some
parts are incomplete.

If anyone wants to translate the missing parts:

"Settings" = "Einstellungen"
"Adoptions" = (not easy to translate in a single word ... the german
verb would be "adoptieren" but this mostly refers to adopting a
kid or something ... so some other word may have to be used
instead).
"Edit Profile" = "Verändere das Profil" or "Profil modifizieren" or
something like that.

Anyway. Perhaps if one of you guys has the time it may be nice
to simply have an additional setting at rubygems.org where
we can change the locale for use at rubygems.org. I'd love
to set it to english at all times - simplifies a lot of things. To me
it is super-weird, though, why suddenly languages shown 
change. I do not remember doing anything at rubygems.org
nor locally via "gem", other than removing my gems from the
commandline, so ... to me this is super-strange, like magic
that it changes sometimes. I'll try to monitor the next time it
changes suddenly; usually when I remove my .gem directory
then it goes back to how it is (I think, but I am not 100% sure).

**Comment by sonalkr132** [comment]
> where we can change the locale for use at rubygems.org. 

You can click the language names at the footer to change it back to your preferred language. 
I am not sure I understand the issue reported here. Please recreate it while following our suggested issue template and keep it to the point.
