### ISSUE TITLE
 recovery code

### ISSUE THREAD

**Issue by xiayuanquan** [rubygems/rubygems.org#2939]
I don't have my recovery code, but I need multiple authentication to log in. I can't log in now. How can I get my account back.

**Comment by xiayuanquan** [comment]
so, I need how to do ?

**Comment by xiayuanquan** [comment]
@hsbt ,  so, I need how to do ?

**Comment by xiayuanquan** [comment]
Who can help me and tell me how to log in? thanks a lot !!!

**Comment by sonalkr132** [comment]
replied on the support site.
