### ISSUE TITLE
Please support Ukraine 🇺🇦

### ISSUE THREAD

**Issue by gatamar** [rubygems/rubygems.org#2977]
Hi Team, thank you for all the work you do for the RubyGems to be accessible by everyone!
I'm from Ukraine and Russian army is bombarding our cities and killing our children, doing acts of terror.
And Russian IT stays neutral because "it's not them who kill people".  
Please help us to raise their awareness by signing this petition and restricting any traffic from Russia for some time:
https://github.com/stop-war-in-ukraine/stop-russia-it

**Comment by digiom-ceo** [comment]
You should not support any idiots in any wars. This request kindles the hatred of a large number of smart people towards Ukraine. I had a better opinion of her. Ukrainians are inciting hatred based on fakes and wars of their rulers.

**Comment by hsbt** [comment]
It violates OSS philosophy. Rubygems.org have no plan to ban Russia.
