### ISSUE TITLE
Take stale gems offline then delete them

### ISSUE THREAD

**Issue by mslinn** [rubygems/rubygems.org#2992]
## Problem
rubygems.org has many stale gems that have not been updated in 10 or 20 years, and are not downloaded by humans.

## Describe the solution you'd like
 1. Attach a warning to the description. Example: 
     ```**WARNING** This stale gem has been flagged for deletion. It has not been updated since 2001-01-01, when Ruby 1.6 was current. Unless this gem is updated it will be taken offline on YYYY-mm-dd and deleted on YYYY-mm-dd.```
 2.  Notify authors by email; if email bounces back, add that to the description Example:
    ```Email sent to author(s) bounced back on YYYY-MM-dd```
 3. On YYYY-MM-dd, take the old gem offline. This means the web entry would still be visible for 3 months, but requiring it would fail, and the description would read
      ```**ERROR** This stale gem has been taken offline. It has not been updated since 2001-01-01, when Ruby 1.6 was current. Unless this gem is updated it will be deleted on YYYY-mm-dd and there will be no trace of it on RubyGems.org after that```
  4. On YYYY-mm-dd remove all reference to the stale gem on RubyGems.org. 
 
## Describe alternatives you've considered
I am unaware of anyone discussing this publicly.

## Additional context
I have not specified the time intervals between dates. One possibility is that 3 months elapse between scheduled events. This should be discussed before implementing.

**Comment by simi** [comment]
@mslinn hello. Personally I don't see any problem with hosting old gems on rubygems.org at least for archiving purpose. This could be part of some kind of bundler check if welcomed. Currently it can be implemented as bundler/rubygems plugin if I understand it well. Anyway I think this kind of proposal would make sense as a RFC. Would you mind to open this as a RFC at https://github.com/rubygems/rfcs?
