### ISSUE TITLE
Allow Usernames to Start With a Number

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems.org#3020]
## Is your feature request related to a problem?

My username everywhere online is `70m4c`. This username works on every website except the RubyGems site. It's frustrating that on RubyGems.org I'm forced to put an arbitrary letter at the start of my username.

## Describe the solution you'd like

I'd like to be able to have a username that starts with a number on RubyGems.org.

## Describe alternatives you've considered

I put an `x` in front of my username to make it `x70m4c`. But this is a different username than what I'd like.

## Additional context

- The limitation is enforced by this code: https://github.com/rubygems/rubygems.org/blob/master/app/models/user.rb#L42
- The limitation was created by this commit with no obvious reason: https://github.com/rubygems/rubygems.org/commit/42c8c74d49f04008785505c40accba613bec3ffd
- I don't know what technical reason there might be to not allow usernames to start with a number.
- I know the same limitation prevents usernames from starting with a dash or underscore. I don't really have any opinions on that, but perhaps it would be good to consider if those limitations are necessary.

Thank you for your consideration.

**Comment by 70m4c** [comment]
After some more searching, I found this duplicate request: https://github.com/rubygems/rubygems.org/pull/532

Doing some basic address bar manipulation, it seems the _user ID as handle alias_ situation continues to exist. I don't know how many people rely on linking to their profiles using a backend user ID, but it definitely seems like an unfortunate design flaw.

Not wanting to give up, I'll suggest: allowing usernames to start with numbers as long as they have at least one non-numeric character. That might take some regex kung-fu but it's possible and would satisfy my feature request.

**Comment by rubyFeedback** [comment]
IMO it should be allowed that user names start with a number. Perhaps we may have to think of users trying to use names that are problematic, but other than that for legit users wanting a leading number I think it's ok to allow for numbers.

**Comment by simi** [comment]
> Doing some basic address bar manipulation, it seems the user ID as handle alias situation continues to exist. I don't know how many people rely on linking to their profiles using a backend user ID, but it definitely seems like an unfortunate design flaw.

Sadly there are legacy uses with no handle and without this id "fallback" there will be no way to link to their profiles.

> Allow usernames to start with numbers as long as they have at least one allowed non-numeric character.

Yes, this would be possible if implemented carefully, but I'm not sure the risk is worth it. Since there is super low interest for this feature, I'm going to close this for now as not planned. Feel free to add comment if you think this needs to be reopened.
