### ISSUE TITLE
`rake environment elasticsearch:import:all` fails

### ISSUE THREAD

**Issue by sato11** [rubygems/rubygems.org#3029]
## Steps to Reproduce

Follow [Development Setup](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#development-setup) and run `bundle exec rake environment elasticsearch:import:all DIR=app/models FORCE=y` accordingly.

## Expected Behavior

```
[IMPORT] Loading models from: app/models
[IMPORT] Processing model: Rubygem...
[IMPORT] Done
```

## Current Behavior

```
[IMPORT] Loading models from: app/models
[IMPORT] Processing model: Rubygem...
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/sato11/src/github.com/rubygems/rubygems.org/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.2.3/lib/active_record/relation/batches.rb:128:in `find_in_batches'
/Users/sato11/src/github.com/rubygems/rubygems.org/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.2.3/lib/active_record/querying.rb:22:in `find_in_batches'
/Users/sato11/src/github.com/rubygems/rubygems.org/vendor/bundle/ruby/3.1.0/gems/elasticsearch-model-7.1.1/lib/elasticsearch/model/proxy.rb:121:in `method_missing'
...
```

## Possible Solution

Apply `bundle update elasticsearch-rails` in local to let it pass. See #3028

## Additional Context

I was about to submit PR when I found it had already been done at #3028. Thank you @simi 
Submitting an issue is perhaps redundant but I bet it's better than nothing in case someone like me comes across 🙂

**Comment by simi** [comment]
@sato11 it would be great if you can try #3028 and leave a comment in there.

**Comment by simi** [comment]
#3028 had to be reverted. I'll take a look at better fix. :pray:

**Comment by sato11** [comment]
Thank you for working on it 👍

**Comment by choncou** [comment]
The rake task worked for me after switching to the branch on #3036
