### ISSUE TITLE
certificate verify failed (certificate rejected) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com ...

### ISSUE THREAD

**Issue by joshunger** [rubygems/rubygems.org#3037]
We're seeing this in the build logs this morning -

```
Fetching rake 10.5.0
Retrying download gem from http://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate rejected) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/rake-10.5.0.gem)
Retrying download gem from http://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate rejected) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/rake-10.5.0.gem)
Retrying download gem from http://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate rejected) (https://oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com/gems/rake-10.5.0.gem)
```

![image](https://user-images.githubusercontent.com/2301847/164987747-fee7fc80-40f8-4976-b049-c96baa25ca4d.png)

**Comment by sonalkr132** [comment]
Hi Josh,
Can you please share the command you ran or steps to reproduce? end users are not suppose to use the s3 url. It would also help if you can share the output of command with --verbose flag.

**Comment by joshunger** [comment]
@sonalkr132 Hello! It looks like the build system is running `bundle install` but I just noticed that our `Gemfile` has the http url `source 'http://rubygems.org'` maybe that is causing issues? I'll kick off a new build pointing to https.

**Comment by cmwilson88** [comment]
@joshunger Did switching to `https` resolve the issue?

**Comment by joshunger** [comment]
@cmwilson88 that resolved the issue for me. Let me know if it works for you.

**Comment by sonalkr132** [comment]
Hi, we have renabled the change which led to this issue. This time we have ensured that we handle oregon.production.s3.rubygems.org.s3-us-west-2.amazonaws.com correctly. Please let us know if you face any issues.

**Comment by joshunger** [comment]
@sonalkr132 thank you
