### ISSUE TITLE
Draft copy for emails about MFA Phase 2 rollout

### ISSUE THREAD

**Issue by bettymakes** [rubygems/rubygems.org#3050]
Contributes to [MFA RFC](https://github.com/rubygems/rfcs/pull/36/files#diff-3d5cc3acc06fe7e9150fdbfc43399c5ad42572c122187774bfc3a4857df524f1R46-R67)

We will create a mailer that will notify affected users about the impending changes around the new MFA policy. The initial announcement will outline [Phase 2's](https://github.com/rubygems/rfcs/pull/36/files#diff-3d5cc3acc06fe7e9150fdbfc43399c5ad42572c122187774bfc3a4857df524f1R46-R67) plan – recommending MFA for Top-100 Rubygems package maintainers.

As part of the communications effort, @sonalkr132 [has also recommended](https://bundler.slack.com/archives/C0HJMKWH4/p1648655028990669?thread_ts=1648491986.485729&cid=C0HJMKWH4) that we create an issue to draft the email copy and to further discuss execution plan (e.g. When should we send the email? How frequently should we be sending it? etc.)

### 📝 To Do's
- [ ] Align on messaging for email copy
- [ ] Align on email execution plan

**Comment by sonalkr132** [comment]
I think we should update our existing emails to include the recommendation that user should enable mfa (gem push/yank, owner add/remove, api key create).
As for phase 2 rollout email, I think one off email should be fine. It can be rake task we run manually. Based on adoption, we can decide on sending repeat email.

**Comment by bettymakes** [comment]
Hey Aditya!

My Team & I had discussions this past Friday about who we should target for the initial email blast about the blog post. While we considered many options, we ultimately aligned on sending the email to **all RubyGems users**. 

This is the copy I've written for that email. What do you think?

> Hi there,
> 
> Today, we’ve announced our security-focused ambitions to the community. Attacks on the software supply chain are increasing and the second most common attack is account takeovers.
> 
> We are officially recommending maintainers of packages with more than 165 million downloads enable MFA. On August 15, 2022, we will begin to enforce this policy. 
> 
> While this policy impacts specific RubyGems users, everyone can do their part to help to combat account takeovers 🙏. **Please enable multi-factor authentication on your RubyGems account.** We recommend setting the [MFA level](https://guides.rubygems.org/setting-up-multifactor-authentication/#authentication-levels) to `UI and API`. However, `UI and gem signin` is acceptable too.
> 
> For more information, check out [our announcement](#link-to-blog-post-tbd).
> 
> ❤️ Thank you for making the RubyGems ecosystem more secure

**Comment by simi** [comment]
If I understand it well, this has already happened, closing.
