### ISSUE TITLE
README in the gem's page.

### ISSUE THREAD

**Issue by a-chacon** [rubygems/rubygems.org#3071]
## Is your feature request related to a problem?
Not exactly, but sometimes the description of a gem is not enough for understanding it, so you need to go to GitHub or wherever is the documentation to understand what it does. Why not have the README in rubygems too?

## Describe the solution you'd like
Show the README in the gem's page. Maybe under the description or replacing it?

I was looking if this was included in another proposal and I didn't find, so I create it like another feature request. But if this is duplicated, please tell me and I close this.

**Comment by sonalkr132** [comment]
This is being discussed at https://github.com/rubygems/rubygems.org/issues/2503. Please leave your comments/support on that.
