### ISSUE TITLE
Gem versions page picks history of a yanked gem

### ISSUE THREAD

**Issue by siaw23** [rubygems/rubygems.org#3074]
## Steps to Reproduce

1. Visit https://rubygems.org/gems/ilias/versions

## Expected Behavior

I expect only the version history I related to my gem.

## Current Behavior

Currently my gem's version page picks up the version history of a yanked gem. The gem with "0.0.1 - July 30, 2014 (6 KB) yanked" is not mine.

## Possible Solution

Ideally, if a gem is yanked, it's there was only one version of it, the version history should be "yanked" from RubyGems as well otherwise I'm attached to history that has nothing to do with my gem's history.

## Environment
Browser and its version:
RubyGems version:

**Comment by sonalkr132** [comment]
>  the version history should be "yanked" from RubyGems as well

This is not recommended because gem releases are immutable. Publishing same version in place of previously yanked version would be a security concern. yanked version signifies a state that it existed at some point and same version number can't be used again (even if owners changed).
