### ISSUE TITLE
`gem push` and `rake release` no longer prompt for OTP

### ISSUE THREAD

**Issue by ankane** [rubygems/rubygems.org#3096]
## Steps to Reproduce

Push a gem with MFA-enabled on your account

```sh
gem push mygem-0.1.0.gem   
```

## Expected Behavior

Prompts for OTP

## Current Behavior

Outputs

```text
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication but no OTP code provided. Please fill it and retry.
```

And exits

## Possible Solution

I believe it's due to the recent change of `multifactor` to `multi-factor`, which affects [this method](https://github.com/rubygems/rubygems/blob/e3a465b62e0bdca9bcb708270b579ad9d3cf3d02/lib/rubygems/gemcutter_utilities.rb#L121) in Rubygems.

For now, users can use:

```sh
gem push mygem-0.1.0.gem --otp 123456
# or
GEM_HOST_OTP_CODE=123456 rake release
```

## Environment
Browser and its version: N/A
RubyGems version: 3.3.7

**Comment by simi** [comment]
Hello @ankane. It seems related to update of https://github.com/rubygems/rubygems.org/commit/933b2213682e41a7891d9bdeedb4b5a8ba5f7a42#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd7b4cd7R26. I'll revert this for now to fix this problem. Thanks for the report.

**Comment by simi** [comment]
@ankane fix was deployed to production. Feel free to re-check.

**Comment by ankane** [comment]
Works great. Thanks for the quick fix, and all the work on Rubygems!
