### ISSUE TITLE
Add WebAuth / FIDO2 / security key support

### ISSUE THREAD

**Issue by paulschreiber** [rubygems/rubygems.org#3097]
## Is your feature request related to a problem?
Currently, rubygems.org only supports TOTP as a second factor. This is not phishing-resistant.

## Describe the solution you'd like
* Add support for WebAuthn / security keys as a second factor.
* Ensure users can register multiple keys
* Ensure users can disable TOTP if desired.

## Additional context
Security keys are support by Google, Microsoft, Facebook, Twitter, Dropbox, GitHub, AWS, WordPress.com and others.

**Comment by hsbt** [comment]
Thanks for rising this. Can you discuss this topic on https://github.com/rubygems/rubygems.org/discussions/2792?

**Comment by paulschreiber** [comment]
Looks like https://github.com/rubygems/rubygems.org/pull/2108 has work done, but is stale.

**Comment by aellispierce** [comment]
I've reopened https://github.com/rubygems/rubygems.org/pull/2865 and am working on getting that up to date so we can push forward with WebAuth support
