### ISSUE TITLE
[Not sure if bug or missing feature] Possible bug or shortcoming in stats API e. g. an URL such as https://rubygems.org/stats?page=11: "Page number is out of range. Redirected to default page."

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#3106]
When I do query this via the following URL:

    https://rubygems.org/stats?page=11

I get redirected to this URL:

    https://rubygems.org/stats?page=1

With the message:

    "Page number is out of range. Redirected to default page."

Is this really intended behaviour? If so then it means that we
can only list 10 of these sub-pages, each displaying 10 gems.
Thus, we can see the first 100 gems, but no more than that.

Is it really the case that the stats-page only allows us to
see the first 100 gems? Is there a rationale for this? Can
the limit be increased to the first 500 or 1000 gem
perhaps? Just to get a better overview. I understand that
the use case for knowing all these stats diminishes, e. g.
the first 50 gems are more useful to know than gem
range from 5050 to 5100, so it is not that I do not 
NOT understand the counter-rationale as such. But 
100 is a bit low, in my opinion.

The current limit seems to be at 100, e. g. via this info:

"DISPLAYING GEMS 1 - 10 OF 100 IN TOTAL"

I am not sure why this is restricted to only 100 gems
though. Extending this to the first 500 to 1000 gems should
be fine, if you are too worried about people getting
the whole dataset (but perhaps there is already an
API to do so, so this would then merely be an UI
inconvenience if it is restricted to 100). Or perhaps no
limitation, but perhaps there is some rationale - I just
don't understand why I can not see beyond the top
100 that way. Gems from 101 to 150 would interest
me as well due to potentially asking some of the 
folks there (if they may have a github account) about
their background and use case(s) potentially.

Thanks for reading anyway.

**Comment by sonalkr132** [comment]
Yes, this is intentional. Please follow our issue template if you would like us to read why do you think we should change it.
