### ISSUE TITLE
Command gem install rdiscount --platform=ruby : ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by shjustinzhang** [rubygems/rubygems.org#3125]
Hi All,

I am trying to install the gem install, and I get the following failure, I notice there is a lot of people having the similar issue, but I don't see an official answer for that. anybody can point me ?

What I have done, run these command and setup window environment variables, 

![image](https://user-images.githubusercontent.com/50476078/176133199-b7ca435c-a4de-4680-a8f5-9db290f08def.png)

C:\DevKit>ruby dk.rb init
[INFO] found RubyInstaller v2.2.6 at C:/Ruby22-x64

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.

C:\DevKit>ruby dk.rb install
[INFO] Updating convenience notice gem override for 'C:/Ruby22-x64'
[WARN] Skipping existing DevKit helper library for 'C:/Ruby22-x64'

C:\DevKit>gem install rdiscount --platform=ruby
Building native extensions.  This could take a while...
ERROR:  Error installing rdiscount:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20220628-27996-3qh845.rb extconf.rb
checking for random()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-rdiscount-dir
        --without-rdiscount-dir
        --with-rdiscount-include
        --without-rdiscount-include=${rdiscount-dir}/include
        --with-rdiscount-lib
        --without-rdiscount-lib=${rdiscount-dir}/lib
C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:1020:in `block in have_func'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:1019:in `have_func'
        from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdiscount-2.2.0.2 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/rdiscount-2.2.0.2/gem_make.out

**Comment by simi** [comment]
This is `rubygems.org` repository, but your problem seems to be relate dto rubygems itself and ruby installer (devkit). It seems you're using really old Ruby (2.2 ?). I suggest to try to use latest version (https://rubyinstaller.org/downloads/) and report problems back in there (https://github.com/oneclick/rubyinstaller2).

**Comment by shjustinzhang** [comment]
Yeah, 2.2.6, well, issue get resolved, the point is to match the corresponding DevKit.
