### ISSUE TITLE
Run `load-pg-dump` when using docker

### ISSUE THREAD

**Issue by rwehresmann** [rubygems/rubygems.org#3175]
Hi! I have my setup done with the [docker environment](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#environment-docker) and now I'm trying to run `./script/load-pg-dump -d rubygems_development ~/Downloads/public_postgresql.tar`:

```
Loading "/Users/rwehresmann/Downloads/public_postgresql.tar," into database "rubygems_development," as user "postgres"
,Dropping database rubygems_development
dropdb: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
```

How can I make that work? Thanks

**Comment by sonalkr132** [comment]
Add `-H 127.0.0.1` to your command.
