### ISSUE TITLE
[Small usability improvement suggestion for gems hosted at rubygems.org]: Add a simple indicator as to whether a project is not available in the listed dependencies

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#3181]
This suggestion relates to the online homepage of gems, shown
typically at:

    https://rubygems.org/gems/name_of_the_gem_here

In the center, on the right side of that center, you typically
then see:

    Runtime Dependencies (7):
    cliner >= 0
    colours >= 0
    find_line_in_file >= 0
    html_tags >= 0
    opn >= 0
    prawn >= 0
    xorg_buffer >= 0

(Don't worry about the missing version number, I just copy/pasted
from an existing gem as such.)

If the gems exist then this is all fine.

However had, sometimes some gems may be yanked. Or a typo may
be added to the .gemspec file accidentally (both happened to
me too). Then after some days you may forget what you did
and missing/broken dependencies are the consequence. I then
notice this indirectly, e. g. when I try to download one of my old
gems on my windows machine, and realise that the dependency
chain was broken for a longer time (because I simply forgot
updating the individual .gemspec file as-is).

Now, this is a minor thing either way, so this suggestion should
have a LOW priority. It's not that important. But it is also a
small suggestion so should be trivial to add if approved.

Anyway.

What is the proposed change or suggestion I would like to
make?

Well - if such a gem is NOT registered on rubygems.org,
then the display should be changed a little bit, with
some extra indicator, such as.

(This gem is currently not hosted on rubygems.org).

Or something like that. You could fine-tune the message
here; if it was yanked, then this could be added as
an additional display.

That display should happen on the same line as the
gem, so after the dependency. Or, if you don't like
the text, perhaps add an unicode alert symbol or
a small div element or button which shows a on-mouse-hover
event tool indicating that the gem is currently not hosted
on rubygems.org or something like that.

As to how to style it: to keep it simple, I suggest
to keep it as text for now. You could, however had,
use a small HTML div tag with some slight border and
a slight visual indicator to make this a bit more
prominent. It should fit into the rest of the 
website design, as otherwise people may be surprised
about it. And it should be a SLIGHT hint, not a 
huge one, just a bit more information.

I think that concludes this feature request. I don't
want to make this more complicated - keep it simple,
a very small user improvement idea. Thank you for
reading.

**Comment by simi** [comment]
I tried to find a gem with missing dep on rubygems.org.

This is the current state (it also changes cursor pointer to :question:).

![image](https://user-images.githubusercontent.com/193936/213054340-7981ffb5-b09a-4e10-bd98-584fb2ce550c.png)

https://rubygems.org/gems/flights_gui_tests

Do you think that's enough? It could be possible probably also add a tooltip with a little explanation. WDYT?

**Comment by simi** [comment]
closing for now, seems fixed :pray:
