### ISSUE TITLE
/versions compact index is out of date

### ISSUE THREAD

**Issue by TAGraves** [rubygems/rubygems.org#3203]
## Steps to Reproduce

1. Visit https://index.rubygems.org/versions
2. Observe `created_at` is `2022-08-01T00:00:12Z`

## Expected Behavior
`created_at` should be at most a few hours old

## Current Behavior
`created_at` is a month old

## Additional Context
Based on some issues like https://github.com/rubygems/rubygems.org/issues/1877, it seems like the intention is for this page to be mostly up to date? I observed the data is actually out of date as well -- for example, `puma` 5.6.5 was released last week, but /versions shows 5.6.4 as the latest version.

**Comment by sonalkr132** [comment]
> created_at should be at most a few hours old

created_at can be upto a month old. It gets updated mostly when we deploy. The file is appended with new versions whenever you run gem push.

> puma 5.6.5 was released last week, but /versions shows 5.6.4 as the latest version.

Please make sure that you are checking all entries. There will be multiple lines for most gems. Expecation is that versions endpoint should be updated within a minute of new release. If you can provide a more recent example of this, I can check again. puma is showng 6.0.0 as of now.

**Comment by simi** [comment]
@TAGraves have you been able to see any delay in recent weeks/months?

**Comment by simi** [comment]
closing due to no response, everything looks ok in last monhts
