### ISSUE TITLE
Inaccurate canonical urls for each gems

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems.org#3209]
## Steps to Reproduce

1. Set your browser language setting as English. for Google Chrome, refer https://support.google.com/chrome/answer/173424?hl=en
2. Remove all cookies for the search engine you are using from the browser you are using (or just use [browse in private or incognito](https://support.google.com/chrome/answer/95464?hl=en).)
3. Search some gem on rubygems.org from a non-english speaking country like Switzerland e.g., `thor` from your browser in English from Zurich, similarly to: https://www.google.com/search?q=thor%20gem&hl=en&gl=ch
4. And you will get `https://rubygems.org/gems/thor/versions/0.19.1?locale=de` in the results.

## Expected Behavior

You will never get any `?locale=en` URLs from (any) search engines.

## Current Behavior

You got URLs with `?locale=de` from Google search engine.

## Possible Solution

- Fix Google's behavior to respect `hl` over your location 🌎 🌍 🌏 .
- Fix #910's implementation.

## Environment

Browser and its version: Google Chrome 105

## Additional Context

- Sometimes known as `hreflang` issue or `alternate` tag: https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en

**Comment by tnir** [comment]
I do not think so. #3210 would resolve it soon.

**Comment by simi** [comment]
> Just 1 year later, due to #3210 I found Google is now returning the results as expected! 🎉

Good to know! Thanks for confirming it works as intended. :muscle:
