### ISSUE TITLE
Firing hooks without a gem name fires gemcutters hooks

### ISSUE THREAD

**Issue by sferik** [rubygems/rubygems.org#322]
Ever since a97751e76a9b740a1023d6aa680ac02b9a77cfa4, when test firing a web hook via the API without specifying a gem name (or with an invalid gem name or with `*`, as [specified in the documentation](http://guides.rubygems.org/rubygems-org-api/#webhook)), the API has fires the web hooks for gemcutter itself.

[This line](https://github.com/rubygems/gemcutter/blob/master/app/controllers/api/v1/web_hooks_controller.rb#L45) was likely inserted for debugging purposes but never removed.

Functionality to fire web hooks for all gems when `*` is passed as the gem name should be implemented as part of the resolution to this issue.

**Comment by simi** [comment]
This is fixed now (confirmed by cURL and API calls).
