### ISSUE TITLE
Proxy user Gravatar images

### ISSUE THREAD

**Issue by jenshenny** [rubygems/rubygems.org#3278]
## Is your feature request related to a problem?

A report has been submitted describing that a user's email can be disclosed through their gravatar URL since it uses the md5 hash of the email. 

## Describe the solution you'd like

These images should be proxied through RubyGems.org to hide the md5 hashes.

**Comment by simi** [comment]
:thinking: we can inspire at https://github.com/superfly/gravitas

**Comment by damien** [comment]
Hey folks! I'm on Shopify's infrastructure security team and I'm spending some spare cycles looking into this. Expect a PR of questionable quality sometime in the near future. :joy:

**Comment by damien** [comment]
Hey folks! After discussing this issue with @jenshenny I've decided to:

1. Use the default Gravatar image for accounts that decide to keep their emails private.
2. Remove the dependency on chrislloyd/gravtastic as the project has been archived and inactive for quite some time. I'll probably just replace it with a self-contained class or helper that implements the subset of the functionality of that gem RubyGems.org actually uses.

Regarding the usage of Gravatar for emails with private account, the conclusions I came to here are as follows:
1. A user setting their email to private can be assumed to desire some level of privacy or confidentiality around their email and possible their identity in general (the latter is more speculation, but I think it's a reasonable assumption).
2. Gravatar by it's nature is leaky, as it allows an identity to be tied to multiple websites and enables reverse-image lookups of an individual's Gravatar even if we proxy the image to avoid leaking the email's md5 hash.
3. Taking the previous two points into consideration, we may be able to assume that a user setting their emails to privacy are opting out of having that email being associated with their public RubyGems identity.

Thoughts? Commentary? If nobody has strong opinions I'll just proceed as stated. Cheers! 🍻

**Comment by technicalpickles** [comment]
> Remove the dependency on chrislloyd/gravtastic as the project has been archived and inactive for quite some time. I'll probably just replace it with a self-contained class or helper that implements the subset of the functionality of that gem RubyGems.org actually uses.

I was curious if there are any alternatives that weren't archived. I did find https://github.com/mdeering/gravatar_image_tag which uses md5 hash already. Admittedly, it's not particularly active, but that could also be a sign of stability 😅
