### ISSUE TITLE
A bug on a gem homepage: the dependency link is wrong

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#3302]
Consider this webpage:

https://rubygems.org/gems/rails

Go visit it please.

On the right side, or rather in the middle, you can read this:

"RUNTIME DEPENDENCIES (13):"

And then various links.

"[actioncable](https://rubygems.org/gems/rails) = 7.0.4"

However had, the link seems wrong. It points at gems/rails.

I believe it should link to:

https://rubygems.org/gems/actioncable

Instead. Same for all other dependencies - they all seem to
point to self, which is weird. I think in the past it pointed
at the dependency correctly. Now these links are all pointing
to the homepage of this gem. Has there been an erroneous
change?

**Comment by mensfeld** [comment]
I can confirm. Same for me and all the gems.

**Comment by simi** [comment]
Thanks for the report!
