### ISSUE TITLE
Inconsistent use of ' and "

### ISSUE THREAD

**Issue by fulldecent** [rubygems/rubygems.org#3317]
These two things are said by Ruby so they should be in the same voice. However as current they are contradictory statements.

Please pick one, document that choice and use it consistently.

<img width="1440" alt="Screenshot 2022-12-28 at 16 42 10" src="https://user-images.githubusercontent.com/382183/209875437-542b6133-f945-4e66-b0b2-65544b1b5d83.png">
<img width="1379" alt="Screenshot 2022-12-28 at 16 44 06" src="https://user-images.githubusercontent.com/382183/209875438-a5989bb4-feb9-4349-bbc1-10089d36e62e.png">

**Comment by simi** [comment]
What do you suggest to fix this @fulldecent? The cli output is defined in [specification policy](https://github.com/rubygems/rubygems/blob/3586d716d0f8b6707afdafab37a6eb26033fffd2/lib/rubygems/specification_policy.rb#L207-L217).  On the other side related guides related code lives in [markdown in guides repo](https://github.com/rubygems/guides/blob/29b40ec93fd9a522d3f12654bf1e2824bcbc3961/make-your-own-gem.md#L65-L77).
