### ISSUE TITLE
User cannot verify webauthn credentials after error is returned

### ISSUE THREAD

**Issue by jenshenny** [rubygems/rubygems.org#3335]
When an error does get hit in `sessions#webauthn_create` eg. `login_failure("Credentials required")`, the ensure block is run which deletes `session[:webauthn_authentication]`. 

When the user tries to authenticate again, `@user = User.find(session.dig(:webauthn_authentication, "user"))` will blow up with an ActiveRecord record not found error and will fail to authenticate or fail to display any error.

### Sessions controller
```ruby
def webauthn_create
    @user = User.find(session.dig(:webauthn_authentication, "user"))
    @challenge = session.dig(:webauthn_authentication, "challenge")

    if params[:credentials].blank?
      login_failure("Credentials required")
      return
    end

    @credential = WebAuthn::Credential.from_get(params[:credentials])

    @webauthn_credential = @user.webauthn_credentials.find_by(
      external_id: @credential.id
    )

    @credential.verify(
      @challenge,
      public_key: @webauthn_credential.public_key,
      sign_count: @webauthn_credential.sign_count
    )

    @webauthn_credential.update!(sign_count: @credential.sign_count)

    do_login
  rescue WebAuthn::Error => e
    login_failure(e.message)
  ensure
    session.delete(:webauthn_authentication)
  end
```

## Steps to Reproduce

If you set `params[:credentials]` to be blank, `Credentials required` will appear. When trying to authenticate again, the page does not change. The behaviour is the same if you go pass the [15 min login session](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/sessions_controller.rb#L14) expiry.

## Possible Solutions

- only delete `session[:webauthn_authentication]` when webauthn authentication is successful
  - caveat: what if the session variables are the problem? User would always fall into a loop of failures
- Redirect back to login with a flash banner.
  - flash banner won't surface due to this issue https://github.com/rubygems/rubygems.org/pull/2865#discussion_r1035366844
- refresh session variables and re-render the page
  - not sure if there are any consequences in this solution

**Comment by simi** [comment]
Is this still problem @jenshenny, any idea?

**Comment by jenshenny** [comment]
I'm pretty sure it is, I think the appropriate solution will be refreshing session variables and re-rendering the page. I can put up a fix for this.

**Comment by simi** [comment]
fixed by https://github.com/rubygems/rubygems.org/pull/3962
