### ISSUE TITLE
RubyGems Github Auth Connection

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#3361]
## Summary

We want to build GitHub OAuth into RubyGems.org in order to later build admin and support actions directly on the website. The GitHub OAuth should verify that the authenticating user is a member of the GitHub "rubygems" organization, as well as a member of the "rubygems.org" team within that organization.

### Current situation

Today, the UX of handling support and admin tasks is pretty bad:
- you have to be a maintainer with AWS and Kubernetes access fully set up
- you have to SSH to a production Kubernetes pod
- on the production pod, you have to use one of the scripts, or the raw Rails console, to complete your task

### Goals

We have a few goals around improving admin tasks:
1. We want to enable support agents who do not have access to any of our infrastructure, which means building a web UI (or possibly a Slack UI?) for support and admin tasks.
2. We also want to make maintainers' lives easier, letting them reset passwords or remove bad gems with a single click rather than a lengthy SSH+manual commands process.
3. We want to keep all of this as secure as we can, and best practice says we should not grant admin permissions attached to regular RubyGems.org accounts.

We should be able to accomplish all three of those goals at the same time by building an admin web UI, secured by GitHub OAuth. This story will not check for any particular users or permissions, just verify that we have a valid GitHub auth.

### Justification

Using GitHub to authenticate our admin tools has several advantages:
- we don't need to build another account system
- we don't need to handle password resets etc for another account system
- we can assign and review permissions directly alongside access to the source repositories
- we won't forget to update admin permissions on the admin tools when we update permissions on the repos
- we get to re-use GitHub's already-built UX for users, teams, membership, and permissions

### Current State
We have no section of RubyGems.org authenticated by GitHub account. 

### Desired State
A new section (currently empty) on RubyGems.org, with access authenticated and authorized via GitHub OAuth login.

## Acceptance Criteria

These can easily be their own tickets, if you want to roll that way, or you can use this list as a checklist.

1. Create three OAuth Apps owned by the RubyGems Organization (not your personal GitHub account). One for local development, one only for staging, one only for production. [Docs Link: [Creating an OAuth App](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app)]
1.A Add staging application ID and secret to staging
1.B Add production application ID and secret to production
1.C Add development application ID and secret to ??? for local development (credentials? dotenv? other?)
1.D Set up [the omniauth-github gem](https://github.com/omniauth/omniauth-github) using the env vars with the app ID and secret.
2. Ensure we can use that OAuth token to successfully discover BOTH repos and orgs for the user 
[Docs Link: [Discover resources for a user](https://docs.github.com/en/rest/guides/discovering-resources-for-a-user)
RubyGems.org will be able to use the user’s Github OAuth token to get relevant information about that user’s authorization to specific github projects/teams/repos (or lack thereof) and decide to display the Admin/Maintainer Tools page or not.
3. HandleAuthorization Failure Scenarios (Failure Scenarios: 1, 2, 5)
4. Create Authorization Logic & Flows
4.A If user is successfully authorized to Github, then use their Github OAuth token to determine what Orgs, Teams and Repos they are a part of/have access to
4.B If they are a part of the correct Org and Team (see below), then display the Admin Tools Page (and allow the user to navigate directly to the Admin Page URL)
5. Handle "Missing Scopes" Failure Scenarios (3, 4)

### GitHub OAuth scopes
1. read:user	         Grants access to read a user's profile data.
2. read:org               Read-only access to organization membership, organization projects, and team membership.

### Required Membership to Authorize
Github user is a member of:
1.  Rubygems organization AND
2. Rubygems.org team

#### Start: 
Attempt to navigate to RubyGems.org admin tools page, get redirected to Github's OAuth login flow

#### Initial Authorization Success Scenario: 
User Successfully Authenticates to Github and Rubygem.org can now use their Github API token to get information about their access to orgs and repos, so we can use that information to decide to display Admin tools or not (separate task! This task is just about verifying the user is logged in via a GitHub account.)

#### Success Outcomes: 
1. User is logged in via GitHub.
2. Empty placeholder for admin tools index page is shown.

##### Outcomes:
1. User is redirected back to the admin login / auth with GitHub page, with an error message explaining what happened
2. Attempting to access the admin tools index directly should not work.

##### Outcomes:
1. User is redirected back to the admin login / auth with GitHub page, with an error message explaining what happened
2. Attempting to access the admin tools index directly should not work.

##### Outcomes: 
1. User is redirected back to the admin login / auth with GitHub page, with an error message explaining what happened
2. Attempting to access the admin tools index directly should not work.
 
##### Outcomes: 
1. User is redirected back to the admin login / auth with GitHub page, with an error message explaining what happened
2. Attempting to access the admin tools index directly should not work.

##### 5. A user that was previously successfully authenticated with Github (RubyGems.org has an OAuth token for) -- their token is now invalid for some reason

(Example reason: [Token revoked by the user](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#token-revoked-by-the-user))

1. User is redirected back to the admin login / auth with GitHub page, with error explaining what happened.
2. Attempting to access the admin tools index directly should not work.

**Comment by rubyFeedback** [comment]
> letting them reset passwords or remove bad gems with a single click rather than a lengthy SSH+manual
> commands process.

For what's it worth, while being able to use/navigate mouse/keyboard may be nice to have, I think the
commandline is not that problematic even for not-so-savvy users.

I use a ruby script to help me remove old gems; here I just type:

    remove_gem ''

And between the '' I simply copy/paste the version I want to remove (I get the info from going to
rubygems.org first for the respective .gem at hand; that script I can also use to remove several
outdated gems).  Not that I would mind a clickable way to remove my gems either - that as 
functionality would be convenient.

**Comment by indirect** [comment]
@rubyFeedback I think you have fundamentally misunderstood this ticket, which is about a web UI for support agents to use to help users who have lost the ability to log in to their rubygems account.
