### ISSUE TITLE
Issue: Incorrect Total Downloads Number on Individual Gem Version Pages

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#3369]
**See Example Here:** 
https://drive.google.com/file/d/1-eEmEFZWOutNsq8x_Gha5fJM2k4PT7ib/view?usp=sharing

**Current State:** 
Different Versions of the same gem show different "Total Download" numbers. 
This may just be an issues with the way the data is being accessed or summed and the underlying data may be correct, OR the underlying data may be incorrect an the math to figure total downloads needs to be fixed. 

**Desired State**
All versions of a gem should show the same number for "Total Downloads" and that number should be correct. 
Correct means that "total downloads = sum (downloads for every version)"

**Relevant Codes**
* The sidebar for the Gem Version Page: 
https://github.com/rubygems/rubygems.org/blob/037bb4d9753db192e71ee6b4364dd9ddbe85ccc5/app/views/rubygems/_aside.html.erb

* The API to get Download numbers by Gem and Version:
https://github.com/rubygems/rubygems.org/blob/98a1c882d5d10d0b27285d73a27bc5fe896587cb/app/controllers/api/v1/downloads_controller.rb

* The Model for Downloads:
https://github.com/rubygems/rubygems.org/blob/c5f0c4b4b506740aba7e823f28395cde9027ae45/app/models/gem_download.rb

* Test file: https://github.com/rubygems/rubygems.org/blob/01ee51b3228e4548e248b369d3694b4109cc1d31/test/unit/gem_download_test.rb

* Looks like the original script used to set total downloads for all gems when this UI piece was added: 
https://github.com/rubygems/rubygems.org/blob/0d557dba8a50a811aa62d1b4557c3a4d1bc019c9/lib/tasks/gemcutter.rake

* Stats View (not sure how this fits in): 
https://github.com/rubygems/rubygems.org/blob/f9f246e31140df003ee5b0c1228e87579b0b1286/app/views/stats/index.html.erb

* Home_Controller (not sure how this fits in): 
https://github.com/rubygems/rubygems.org/blob/f9f246e31140df003ee5b0c1228e87579b0b1286/app/controllers/home_controller.rb

**Comment by indirect** [comment]
If I open three different versions at the same time, I see the same total downloads numbers. Perhaps you opened those tabs at different times, and didn't refresh all of them very close together?



![Image](https://user-images.githubusercontent.com/78/214177631-be2ebb2e-dd83-4f46-aa81-1372b8d7349e.png)


If you have some other way to reproduce this, please let us know!

**Comment by jchestershopify** [comment]
There might be a hidden problem here, which is that "total downloads" can be misinterpreted as "total downloads for this version", rather than "for all versions".
