### ISSUE TITLE
404'ing gems.

### ISSUE THREAD

**Issue by cmeiklejohn** [rubygems/rubygems.org#337]
attribute-kit-0.1.0.gem
engen-0.1.3.gem
ghostplus-0.0.1.gem
routo-0.0.1.gem
vj-sdk-0.6.2.gem

**Comment by simi** [comment]
I think this is handled better now https://github.com/rubygems/rubygems.org/blob/0afbde79d2ffd3e77f45315afe82609c299553bd/app/models/pusher.rb#L27-L44.

**Comment by dwradcliffe** [comment]
Yeah, I think we're handling this better now. These gems still need to be yanked. I'll get that done in the next few days and then we can close this.

**Comment by qrush** [comment]
I think we permanuked all of these gems right? Is this still an issue?
