### ISSUE TITLE
Add a model to audit admin actions

### ISSUE THREAD

**Issue by arunagw** [rubygems/rubygems.org#3391]
To have an audit and capture some of information we will need to add a new model/table to store information. 

We will want to store:
- admin user information (email? GitHub username? human name?)
- when the admin action happened
- a note written by the admin user
- what rubygems user or gem was impacted by the action
- what action was taken (unblock gem, reset 2fa, yank gem, block user, etc)

**Comment by rubyFeedback** [comment]
Just as short info - the link you gave above does not work for me, I get a 404.
