### ISSUE TITLE
Improper action with `bin/fill-locales` for avo files

### ISSUE THREAD

**Issue by ericherscovich** [rubygems/rubygems.org#3437]
Running `bin/fill-locales` will trigger everything in the avo files to be deleted. This appears to be a bug that was introduced in the PR https://github.com/rubygems/rubygems.org/pull/3405. 

## Steps to Reproduce
1. Add a translation to the `.en` file
2. Run `bin/fill-locales`
3. In the avo files, you will see that all existing translation are wiped from them when this is ran

## Expected Behavior
Running the command should create a single entry for the translation added in .en to the .avo files, while persisting all the other translations.

## Current Behavior
Instead, it will delete all the translations in the .avo files.

## Possible Solution
A quick and easy fix would be ignoring `.avo` files in the `fill-locales` script: https://github.com/Shopify/rubygems.org/blob/master/bin/fill-locales. But this may not be a good long term solution.

**Comment by simi** [comment]
this seems to be fixed by https://github.com/rubygems/rubygems.org/pull/3482/files#diff-7d0468dd4b4cf7038dd88851e57a7cc651505dac93c1f265070e493a12653ace
