### ISSUE TITLE
Webauthn for the CLI 

### ISSUE THREAD

**Issue by aellispierce** [rubygems/rubygems.org#3453]
## Is your feature request related to a problem?

While multi-factor authentication with OTP codes is a great security feature, it can at times be inconvenient to use, as one has to keep another device handy and manually input the codes. WebAuthN has already[ been made available for the UI ](https://github.com/rubygems/rubygems.org/pull/2865) and should now be made available for the CLI as well. This would make it more convenient to protect sensitive actions like gem signin, push, yank, etc. 

## Describe the solution you'd like
Adding WebAuthn to Rubygems will make strong auth more accessible for gem maintainers and provide a better user experience than current TOTP codes. This should be available for all sensitive actions in the CLI (gem signin, push, yank, etc.). 

WebAuthn allows web services to offer their users strong authentication via security keys or platform authenticators. WebAuthn is highly resistant to phishing attacks in ways that TOTP codes are not. WebAuthn is also more convenient than TOTP codes. When Google rolled out security keys [they found](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45409.pdf) that it led to an increased level of security and user satisfaction, as well as a decrease in support requests.

WebAuthn for Rubygems will reduce the support burden of multifactor auth and improve the UX, while providing superior protection. 

## Describe alternatives you've considered

For this task we will manually implement webauthn on the Rubygems CLI. Clarion, an existing library was considered but ultimately we decided against it for several reasons, most of those boiling down to the fact that it's a standalone application that would not reuse any of the existing webauthn/totop verification functionality on Rubygems.org. For this reason, it made more sense to implement the flow ourselves while using Clarion as a reference point. 

We also created several prototypes [[1](https://github.com/Shopify/rubygems.org/pull/56),[2](https://github.com/Shopify/rubygems.org/pull/67),[3](https://github.com/Shopify/rubygems.org/pull/68)] to investigate different ways of communicating between .org and the CLI (manually pasting totp codes, opening a websocket connection to get the code, or polling for the code). We ultimately decided that sockets provided the best user experience, as well as additional security benefits (resistance to phishing). 

## Additional context
Demo: 
https://user-images.githubusercontent.com/42748004/207650014-12cc10af-cbf1-4ab2-85a5-d09db9a6b5f9.mov

**Comment by aellispierce** [comment]
WIP Feature Branch: https://github.com/rubygems/rubygems.org/pull/3298

**Comment by simi** [comment]
@aellispierce if I understand it well, this is ready to be closed as completed. Can you confirm?

**Comment by simi** [comment]
@jenshenny maybe you'll know :pray:

**Comment by aellispierce** [comment]
@simi yes, I believe this work is completed so I'm going to close this out 🎉
