### ISSUE TITLE
List of all gems (either static file or through API)

### ISSUE THREAD

**Issue by gitgitwhat** [rubygems/rubygems.org#3487]
## Is your feature request related to a problem?

There's a search feature on the website and through the API but it would be very handy to have just a simple list available of gem names and current versions that is easily accessible.  Most other repos provide this information but I can't seem to find it for Ruby.

## Describe the solution you'd like

A static file (preferably JSON) updated at least once a day that contains the list of all gems and the latest versions.

## Describe alternatives you've considered

Paginating through search results but even that limits the total results.

**Comment by indirect** [comment]
Are you familiar with `https://rubygems.org/names`? It's just a list of all the names. If you want a list of all the names plus versions, it is available from `https://rubygems.org/versions`.

**Comment by gitgitwhat** [comment]
@indirect 
Thank you and apologies for wasting your time!  I don't know how I missed that.

**Comment by indirect** [comment]
No worries!

**Comment by simi** [comment]
If you need more, you can also download anonymized daily data dump at https://rubygems.org/pages/data. That contains info about all gems and versions.
