### ISSUE TITLE
rubygems.org push/yank: We are having a bad problem and the app server will not talk to us.

### ISSUE THREAD

**Issue by xuan-cao-swi** [rubygems/rubygems.org#3605]
### Describe the problem as clearly as you can

Every time I do push or yank, it was successfully (pushed/yanked) but I got the following msg (tl.tr: We are having a bad problem and the app server will not talk to us.)
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <!--[if IE 7]>
      <link href="/stylesheets/ie7.css" media="screen" rel="stylesheet" type="text/css" />
    <![endif]-->
    <title>Unicorn! | RubyGems.org</title>
  </head>
  <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <div style="margin-right: auto; margin-left: auto; width: 90%; max-width: 940px;">
      <div style="padding-top: 60px; position: relative;">
        <object height="530" type="image/svg+xml" alt="503 error" style="width: 100%;" data="/images/sea_level.svg"></object>
      </div>
      <div style="margin-right: auto; margin-bottom: 120px; margin-left: auto; max-width: 680px; text-align: center;">
        <h1 style="margin-top: 25px; margin-bottom: 8px; font-weight: 200; font-size: 60px; ">Unicorn!</h1>
        <p style="font-weight: 300; font-size: 18px; line-height: 1.66; ">We are having a bad problem and the app server will not talk to us.</p>
        <a href="/" style="font-weight: 300; font-size: 18px; line-height: 1.66;  text-decoration: none; color: #e9573f;">Back to RubyGems.org</a>
      </div>
    </div>
  </body>
</html>
```

### Post steps to reproduce the problem

Any gem I push from either my machine or azure (via github action)

### Which command did you run?

```
gem signin
gem push gem-name.gem 
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   *******

```
### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.6 (2022-04-12 patchlevel 219) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/username/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/username/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/username/.rbenv/versions/2.7.6/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/username/.rbenv/versions/2.7.6/bin
  - SPEC CACHE DIRECTORY: /Users/username/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/username/.rbenv/versions/2.7.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - arm64-darwin-21
  - GEM PATHS:
     - /Users/username/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0
     - /Users/username/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/username/.rbenv/versions/2.7.6/bin
     - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
     - /opt/homebrew/opt/openjdk/bin
     - /Users/username/anaconda3/condabin
     - /Users/username/.rbenv/shims
     - /Users/username/.rbenv/bin
     - /opt/homebrew/bin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/go/bin
     - /usr/local/munki

```

**Comment by simi** [comment]
Hello, can you share the gem you're pushing? It could be problem with gem content.

**Comment by xuan-cao-swi** [comment]
Hi, I was trying to make the gem that follow the [tutorial](https://guides.rubygems.org/make-your-own-gem/). I only changed the gemspec

gemspec
```
Gem::Specification.new do |s|
  s.name        = "hola-xuan"
  s.version     = "0.0.1"
  s.summary     = "Hola!"
  s.description = "A simple hello world gem"
  s.authors     = ["Xuan Cao"]
  s.email       = "xuan.cao@nowhere.com"
  s.files       = ["lib/hola.rb"]
  s.homepage    =
    "https://rubygems.org/gems/hola-xuan"
  s.license       = "MIT"
end
```

**Comment by simi** [comment]
@xuan-cao-swi thanks for the info, can you also please upload somewhere the gem file you're pushing?

**Comment by mullermp** [comment]
FWIW We've gotten this a few days ago when trying to publish one of our gems. We've just retried it and updated our release code to handle 503 with a sleep 30 and retry. I do think this error is weird because I would expect an error in JSON (since it's a JSON API) but instead it's some HTML.

**Comment by xuan-cao-swi** [comment]
Thanks @simi , you can download it [here](https://github.com/xuan-cao-swi/sample-ruby-gem/blob/main/hola-xuan-0.0.1.gem).

Thanks @mullermp , after you retried, the problem faded away? 
For my case, even with this msg, my gem was still pushed, which means I can't retry/re-push with same version.

**Comment by mullermp** [comment]
Was there a change to cached response policies Simi? When we encountered this error, immediate automated retry did not work for us because we had already published the gem. We found that adding the cache-control header yesterday fixed the issue for us, but I remember retrying in the past within a few minutes was usually a fresh response.

>Thanks @mullermp , after you retried, the problem faded away?
Sort of, but yes. It may be true it's related to Gem content, but we certainly have seen this intermittently in the past and also just recently.

Checking logs we saw this one on 3/9/23 20:32 - 3/9/23 20:34 (UTC?) when publishing aws-sdk-sesv2.

**Comment by xuan-cao-swi** [comment]
Having set the cache-control header (e.g. `cache-control: 'max-age=0'`, `cache-control: ''`, etc.) still produce the issue.
If this is related to Gem content, how do I know which part is causing the problem?

**Comment by alextwoods** [comment]
@simi  - looks like we are experiencing the same issue again - getting a 503 with html content with "We are having a bad problem and the app server will not talk to us."

**Comment by xuan-cao-swi** [comment]
response from the push
#<Net::HTTPServiceUnavailable 503 first byte timeout readbody=true>

**Comment by mullermp** [comment]
@simi we're seeing this 503 app server issue again today trying to publish AWS SDK gems and is becoming an ops pain. Can you investigate?

**Comment by mullermp** [comment]
@sonalkr132 @indirect sorry for wider ping, but this 503 app server issue has borked three of our releases this week. Something fishy is happening!

**Comment by mensfeld** [comment]
Guys I can confirm with Karafka. Just released, same issue.

**Comment by segiddins** [comment]
Let me take a look! I haven't been paged for high 503s which is a bit curious

**Comment by segiddins** [comment]
It looks like we're seeing a bunch of 409 CONFLICT on gem pushes.... im investigating

**Comment by segiddins** [comment]
DB is completely overloaded. going to see what I can do

**Comment by segiddins** [comment]
Deploying now...

**Comment by segiddins** [comment]
ok, deployed, let's give it a go

**Comment by segiddins** [comment]
Looks resolved from the metrics

**Comment by mullermp** [comment]
The 409 conflicts might be because of caching! We've seen this too when retrying our gem pushes.

**Comment by mullermp** [comment]
Could you please investigate https://github.com/rubygems/rubygems.org/issues/3609 @segiddins
