### ISSUE TITLE
Copy snippet on version page to point to the exact version

### ISSUE THREAD

**Issue by adrianthedev** [rubygems/rubygems.org#3631]
## Is your feature request related to a problem?

When you visit a gem's version page (`https://rubygems.org/gems/avo/versions/2.28.2.pre.pr1642`), the `Gemfile` snippet displayed on the page points to `~> VERSION_NUMBER`, which allows `bundle` to install a higher version, not that exact version.

My train of thought is if someone clicks that version, they are looking for information about that exact version. 
Having the gem version point to the exact version expresses that too.

## Describe the solution you'd like

On a gem's version page (`https://rubygems.org/gems/avo/versions/2.28.2.pre.pr1642`), point to the exact version instead of "approximately this version or greater".

```ruby
# Instead of this
gem 'avo', '~> 2.28.2.pre.pr1642'

# Have this
gem 'avo', '2.28.2.pre.pr1642'
```

## Additional context

I can ship a PR for this feature, I just need the "ok" from you guys.

Thank you!

![CleanShot 2023-03-23 at 18 00 59@2x](https://user-images.githubusercontent.com/1334409/227262990-0d3e8a43-1b42-484c-98a1-2ed820f87056.png)

**Comment by simi** [comment]
Hello @adrianthedev, it makes sense to me on individual version page show suggestion to lock to that version.
