### ISSUE TITLE
Ruby gem named this-gem-does-not-exist contains huge text(smilies) under authors field

### ISSUE THREAD

**Issue by nareshdevasani** [rubygems/rubygems.org#3632]
## Steps to Reproduce

1. https://rubygems.org/gems/this-gem-does-not-exist/versions/0.1.0
2. https://rubygems.org/gems/this-gem-does-not-exist/versions/0.2.0
3. https://rubygems.org/gems/anti-war-handbook-gem/versions/0.1.1
4. https://rubygems.org/gems/anti-war-handbook-gem/versions/0.1.3

## Expected Behavior

Limit the text size under authors field. Add some validation to not add some random characters.

## Current Behavior

The field size seems to be unlimited. The size of the text under authors for the above mentioned gems (point#1) is more than 100KB. And all of these gems metadata is included in everyday's postgresql db_dump.

## Possible Solution

1. Delete these mentioned gems if they are not useful.
2. Limit the text size under authors field. Add some validation to not add some random characters.

## Environment
Browser and its version:
RubyGems version:

**Comment by simi** [comment]
@nareshdevasani hello! What kind of limit do you suggest?

**Comment by nareshdevasani** [comment]
@simi IMO there need to be couple of dimensions on limits:
1. Length of fields 
2. Type of chars 

Below are some details on the length of text:
 - 256 authors maximum for the given gem version
 - each authors name is 64 chars long (64bytes)
 - total length of authors text would still be 16KB.
 - Considering all other metadata is of 34KB, total gem metadata in rubygems.org will be maximum of 50KB for any gem.
 
Where as the gems mentioned above particularly `this-gem-does-not-exist` is more than 100KB.

Also to restrict type of chars, can we not allow to add smilies to begin with?

**Comment by nareshdevasani** [comment]
Another request: Can we delete the discovered gems which are simply dumping the random and huge text.
Are we not allowed to delete the above mentioned gem from DB or rubygems.org?
Is that gem (this-gem-does-not-exist) looking like we need to keep it in rubygems.org?

**Comment by simi** [comment]
@indirect @hsbt any opinion about both problems (adding limitations to authors, amount of authors, overall gemspec size and removing related gems)?

**Comment by hsbt** [comment]
Restriction for only author field is no make sense. Anyone can do fill text to another field like description. If we restrict all of metadata like https://github.com/rubygems/rubygems.org/blob/master/db/schema.rb#L317, We should consider their limits each field.

**Comment by indirect** [comment]
I do not think we should add restrictions unless they are needed for technical or security reasons.

@nareshdevasani we do not delete existing gems from rubygems.org unless they contain malware.

**Comment by hsbt** [comment]
> we should add restrictions unless they are needed for technical or security reasons.

Agreed. "This gem is useless" is not reason we restrict it.

**Comment by indirect** [comment]
Since the RubyGems team does not consider long author names a bug, I will close this now. 

@nareshdevasani please do not open a third ticket about this issue. If you do, we will block your GitHub account from this organization for at least 1 month.
