### ISSUE TITLE
Incorrect/outdated metadata links on gem page

### ISSUE THREAD

**Issue by cyclotron3k** [rubygems/rubygems.org#3676]
## Steps to Reproduce
1. Navigate to the gem page for [`net-sftp`](https://rubygems.org/gems/net-sftp)
2. Click the "Documentation" link - notice that it takes you to https://net-ssh.github.com/net-sftp - an invalid link since [2013](https://github.blog/2013-04-05-new-github-pages-domain-github-io/)
3. Download the latest version of `net-sftp` and open - notice that there is no reference to the above URL
4. Get confused

## Expected Behavior
The invalid documentation URL is not used by RubyGems.

## Additional Context
The only time that URL has existed in the codebase was in README.rdoc, and it was removed in [May 19, 2021](https://github.com/net-ssh/net-sftp/commit/59caa0d0e0aa103d2d095924926289b9b155fad1), and there have been two releases since then.

**Comment by rubyFeedback** [comment]
You are right - that's interesting.

The .gemspec file has this entry:

    spec.homepage      = "https://github.com/net-ssh/net-sftp"

Perhaps there needs to be some additional routine to check specifically whether the
URL shown on rubygems.org needs to be updated; I assume it has had to be stored
at one point in the past, as you indicate e. g. in 2021 or so. Perhaps some other older
gems also have that problem.

Aside from this, I think it would be pretty neat if we could have autogenerated documentation
at rubygems.org for gems too. I don't know if we have enough resources for that, 
but I have had issues with external documentation before -  often the gems I publish,
where the documentation is on, https://www.rubydoc.info/gems/, is often lagging behind,
or sometimes claiming that it does not exist, even though I pushed the gem just recently.
So there is some delay. Would be neat if there would be no delay and all could be contained
on rubygems.org directly, without having to depend on anything external (github, rubydoc
and so forth).

**Comment by rubyFeedback** [comment]
Ah, .homepage is for the homepage, not the documentation of course. All my own gems get the default documentation link e. g. via https://www.rubydoc.info/gems/NAME_OF_THE_GEM_GOES_IN_HERE.  I guess a new routine should check whether this entry is still specified or not; and if not, delete it (unless it was specified e. g. in the .gemspec file).

**Comment by simi** [comment]
Uff, this was though one to resolve, but I think I got it.

Before 2019, it was only possible to maintain those links (like docs) manually using WEB UI form, but that was removed at https://github.com/rubygems/rubygems.org/pull/1815.

[net-sftp](https://rubygems.org/gems/net-sftp) gem has this value still filled in.

```ruby
irb(main):001:0> Rubygem.find_by(name: 'net-sftp').linkset
=> 
#<Linkset:                               
 id: 0,
 rubygem_id: 0,
 home: "https://github.com/net-ssh/net-sftp",
 wiki: "",
 docs: "http://net-ssh.github.com/net-sftp",
 mail: "",
 code: "https://github.com/net-ssh/net-sftp",
 bugs: "https://github.com/net-ssh/net-sftp/issues",
```

To override those values, net-sftp gem should utilize gemspec metadata. Logic picking on one of the values (from old linkset or modern metadata lives in [links model](https://github.com/rubygems/rubygems.org/blob/d61c1d63938287a2139fc611f75b6d3867d2ea59/app/models/links.rb#L61-L72).

If I understand it well, there is nothing to do on rubygems.org side to fix this. :thinking:
