### ISSUE TITLE
Dependencies API is not working

### ISSUE THREAD

**Issue by mullermp** [rubygems/rubygems.org#3683]
Dependencies API seems to be broken.

## Steps to Reproduce
Using the example from: https://guides.rubygems.org/rubygems-org-api/

https://rubygems.org/api/v1/dependencies?gems=rails,thor

## Expected Behavior
I get dependencies of the gems

## Current Behavior
404, Site cannot be reached

## Possible Solution
Not sure

## Environment
Browser and its version: Chrome, latest
RubyGems version: N/A

## Additional Context
https://status.rubygems.org/ Status website has NOT been showing issues that we've encountered the last couple weeks.. Is there alarming setup for this API?

**Comment by simi** [comment]
@mullermp this API is deprecated for some time already and now being slowly off-boarded. See https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html for more info.

**Comment by mullermp** [comment]
Wow ok, did not know about this. We're seeing this when trying to install gems with internal software. I think Amazon's proprietary/internal code/build system has an old rubygems version. Sorry for the noise.

**Comment by simi** [comment]
no problem @mullermp, feel free to ping us on Slack if any help is needed
