### ISSUE TITLE
Retirement of Dependencies API breaks gemstash clients that cannot access rubygems

### ISSUE THREAD

**Issue by tedgarb** [rubygems/rubygems.org#3697]
Although https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html says gemstash clients will not be affected by the dependency API retirement, this turns out to not be true for clients that cannot directly access the rubygems API. I have opened a ticket with more details in the gemstash project at https://github.com/rubygems/gemstash/issues/336 , but politely request that consideration be made for delaying the dependency API retirement until they can address the issue.

**Comment by tedgarb** [comment]
Hi,

I was getting 404s from the Dependency API a couple hours ago when I filed these tickets, and assumed that the change had been un-delayed, but I guess that was simply transient, as my clients are getting 200s back now instead of gemstash choking on a 404 from rubygems.org

Edward

**Comment by tedgarb** [comment]
Reopening this again because the issue with gemstash at https://github.com/rubygems/gemstash/issues/336 still persists, and the documentation still incorrectly states gemstash is not affected. Can the documentation at least be updated to clarify that the API deprecation has entirely broken gemstash for clients that do not also access rubygems.org directly?

**Comment by tedgarb** [comment]
Could I get an update on this?

**Comment by simi** [comment]
@tedgarb let's continue in gemstash issue. Feel free to open PR in there (at least with notice about the current state). There is nothig to fix on rubygems.org side for now if I understand it well.
