### ISSUE TITLE
Blog: Broken link in "Introducing Security Device support on RubyGems’ CLI" blog post

### ISSUE THREAD

**Issue by marcotc** [rubygems/rubygems.org#3710]
Following the link to Bundler's Slack does not work in the latest blog post: https://blog.rubygems.org/2023/04/11/security-device-cli-support.html.

## Steps to Reproduce

1. Visit https://blog.rubygems.org/2023/04/11/security-device-cli-support.html
2. Click the [Bundler Slack workspace](https://slack.bundler.io/) link at the last paragraph of the page.

## Expected Behavior

The link goes to the Bundler Slack page.

## Current Behavior

503 HTTP response:

![Screenshot 2023-04-13 at 11 11 22 AM](https://user-images.githubusercontent.com/583503/231847315-c9b56dec-1299-4b4d-ab47-6f6e788b8289.png)

## Possible Solution

Visit https://bundler.slack.com/ instead.

## Environment
**Browser and its version:**
Name: Firefox
Version: 111.0.1
Build ID: 20230321111920
Distribution ID:
Update Channel: release
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
OS: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar 6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
Rosetta Translated: false

**RubyGems version:** None

**Comment by jenshenny** [comment]
Thanks @marcotc! I put up a PR to change the link
