### ISSUE TITLE
Include port number in development mailer links

### ISSUE THREAD

**Issue by jenshenny** [rubygems/rubygems.org#3728]
When working with [mailer links locally](http://localhost:3000/rails/mailers/), the redirect does not append :3000 to the end of localhost (eg. `http://localhost/gems/test-gem/owners/confirm?token=f26c33fd3f888e481a7407f9c3050bbd2292242a`).
<img width="577" alt="Screenshot 2023-04-23 at 12 13 35 PM" src="https://user-images.githubusercontent.com/42748004/233851306-1177b7f3-285c-4196-a0c1-56359de3f860.png">

This leads to the page not being found and you would need to append the port to the link manually.

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on it. Is it available?

**Comment by 2022H1030042G** [comment]
Can anyone suggest where the changes are required and how to implement those changes? I am new to open source development.

**Comment by simi** [comment]
@2022H1030042G feel free to join us on Slack to discuss the approach on this. You can find link at the end of https://bundler.io/ page.
