### ISSUE TITLE
Looks like Google Safe Browsing has marked rubygems.org as unsafe

### ISSUE THREAD

**Issue by etherbob** [rubygems/rubygems.org#3791]
https://transparencyreport.google.com/safe-browsing/search?url=rubygems.org&hl=en-US

![Screen Shot 2023-05-11 at 2 41 12 PM](https://github.com/rubygems/rubygems.org/assets/5025990/c694b041-816a-4a7c-a9ac-fa47de54f202)

Apologies if this not the best place to report this, but it seemed worth sharing.

**Comment by ngan** [comment]
We're seeing this as well
![image](https://github.com/rubygems/rubygems.org/assets/16579/f6080de3-05ba-4bf5-bc5a-2fbd15f488c8)

**Comment by gaffneyc** [comment]
Can report it as a false positive here: https://safebrowsing.google.com/safebrowsing/report_error/?tpl=mozilla&hl=en

**Comment by segiddins** [comment]
At this time, Google is no longer reporting rubygems.org as malicious. Thank you for your patience, and if further issues arise please let us know!

https://transparencyreport.google.com/safe-browsing/search?url=rubygems.org&hl=en-US

**Comment by ewdurbin** [comment]
Hello from PyPI! We were caught up in this as well. Any notes on who you contacted at google, @segiddins?

**Comment by indirect** [comment]
@ewdurbin sorry to hear you're having the same problem; we used the Google Search Console to get detailed info on the specific problem, used the "request review" button to explain why we believed the malware flag was a mistake, and then recruited several friends of friends who worked on the Chrome team and the Safe Browsing team to internally escalate the appeal and argue on our behalf. unfortunately no real contacts or playbook to offer based on that. :/

**Comment by lastgabs** [comment]
@ewdurbin when did Pypi get affected?

**Comment by ewdurbin** [comment]
Yesterday afternoon, around 5 eastern

**Comment by lastgabs** [comment]
I'm assuming you opened a ticket and also got it resolved, right?

**Comment by lastgabs** [comment]
Aha, just saw that they partially resolved it for you. I've added you on Twitter if you'd like to have a conversation over dms and share info.

**Comment by ewdurbin** [comment]
Thanks @lastgabs! I'm not using twitter anymore, but appreciate the connection.

We filed notices at https://safebrowsing.google.com/safebrowsing/report_error/ but haven't heard back.

I've done a little network shaking to find our own insider with knowledge of safe browsing team... hopefully they can help us find our way.

**Comment by 0x446f6d** [comment]
> Thanks @lastgabs! I'm not using twitter anymore, but appreciate the connection.
> 
> We filed notices at https://safebrowsing.google.com/safebrowsing/report_error/ but haven't heard back.
> 
> I've done a little network shaking to find our own insider with knowledge of safe browsing team... hopefully they can help us find our way.

Following up on this even though it has been a while - we're facing the same issue with our own site atm. Did you happen to find someone who was able to help you with this issue?

**Comment by indirect** [comment]
@0x446f6d nope, we were never able to get a response from anyone at Google.
