### ISSUE TITLE
Decoupling MFA level and Devices

### ISSUE THREAD

**Issue by ericherscovich** [rubygems/rubygems.org#3800]
## Is your feature request related to a problem?
Currently, you can use webauthn on the UI and CLI, but they are currently coupled together in the code. OTP must be enabled for webauthn to work correctly, and MFA levels are associated to TOTP. 

## Describe the solution you'd like
We created a prototype for this here: https://github.com/Shopify/rubygems.org/pull/204. The commits show the different parts and the sequence of the changes we need to make.

## Additional context
Demo can be found here: https://github.com/Shopify/rubygems.org/pull/204#issuecomment-1550297877

**Comment by jenshenny** [comment]
Remaining items to be shipped in this order:

###  1
- [ ] Merge and deploy documentation changes for OTP decoupling https://github.com/rubygems/guides/pull/339
- [ ] Merge and release polling fallback for the CLI https://github.com/rubygems/rubygems/pull/6774

### 2
- [ ] Merge and deploy Safari guide changes https://github.com/rubygems/guides/pull/338

### 3
- [ ] Merge and deploy blog post https://github.com/rubygems/rubygems.github.io/pull/164

### 4
- [ ] Merge and deploy banner https://github.com/rubygems/rubygems.org/pull/3945
