### ISSUE TITLE
Vodafone Secure net is blocking https://rubygems.org

### ISSUE THREAD

**Issue by wallymathieu** [rubygems/rubygems.org#3822]
### Describe the problem as clearly as you can

Try either one of:

- Try to install gem
- Browse https://rubygems.org through Chrome 113.0.5672.126
- Browse https://rubygems.org through Safari

### Did you try upgrading RubyGems?

Does not seem to be related to version of rubygems but the hosting of rubygems.

### Steps to reproduce the problem

Try to build the following dockerfile:

```Dockerfile
FROM ruby:${VARIANT:-3.2-buster}
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates\
    ruby

RUN gem install bundler
```

### Which command did you run?

- gem install bundler
- navigate through browser

### What were you expecting to happen?

- For bundler to be installed
- For rubygems to be displayed

### What actually happened?

Error related to certificates:

```
#0 0.362 ERROR:  SSL verification error at depth 0: self signed certificate (18)                                                                          
#0 0.362 ERROR:  Certificate /C=US/ST=USA/L=New York/O=Optimization/OU=Optimization/CN=tomcat is not trusted                                              
#0 0.412 ERROR:  SSL verification error at depth 0: self signed certificate (18)
#0 0.412 ERROR:  Certificate /C=US/ST=USA/L=New York/O=Optimization/OU=Optimization/CN=tomcat is not trusted
#0 0.467 ERROR:  SSL verification error at depth 0: self signed certificate (18)
#0 0.467 ERROR:  Certificate /C=US/ST=USA/L=New York/O=Optimization/OU=Optimization/CN=tomcat is not trusted
#0 0.469 ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
#0 0.469           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 peeraddr=62.74.130.28:443 state=error: certificate verify failed (self signed certificate) (https://rubygems.org/specs.4.8.gz)
#0 0.531 ERROR:  SSL verification error at depth 0: self signed certificate (18)
#0 0.531 ERROR:  Certificate /C=US/ST=USA/L=New York/O=Optimization/OU=Optimization/CN=tomcat is not trusted
#0 0.589 ERROR:  SSL verification error at depth 0: self signed certificate (18)
#0 0.589 ERROR:  Certificate /C=US/ST=USA/L=New York/O=Optimization/OU=Optimization/CN=tomcat is not trusted
------
```

### Run `gem env` and paste the output below

Note the Dockerfile above.

**Comment by deivid-rodriguez** [comment]
Could this be related to #3791?

**Comment by wallymathieu** [comment]
That's what I think. Could be that their flagging of Ruby Gems is out of date.

**Comment by wallymathieu** [comment]
What we did was to ask them to remove the service "Secure Net" for us.

**Comment by wallymathieu** [comment]
So no, we did not find a way.

**Comment by julitrows** [comment]
Thanks, ended up doing the same

**Comment by simi** [comment]
@wallymathieu @julitrows is this still problem? rubygems.org itself is not marked as unsafe for now by google safe browsing status. But some subpages (like https://rubygems.org/gems/metasploit-payloads) are still marked as unsecured.

**Comment by julitrows** [comment]
@simi I had to request the deactivation of Secure Net for me so I can use rubygems. Haven't tried to put it up again.

But chances are it's still blocked.

**Comment by rudgal** [comment]
Still blocked for me today, how can I request deactivation, is there some official form or so?
(I'm actually not from ES and using a shared WiFi atm)
Thanks a lot! 🙇

**Comment by rudgal** [comment]
> @simi I had to request the deactivation of Secure Net for me so I can use rubygems. Haven't tried to put it up again.
> 
> But chances are it's still blocked.

Still blocked for me today, how can I request deactivation, is there some official form or so?
(I'm actually not from ES and using a shared WiFi atm)
Thanks a lot! 🙇

**Comment by duckinator** [comment]
I've been talking with Vodafone. Hoping to have this resolved soon.

**Comment by duckinator** [comment]
I've been talking to Vodafone about this the last few days. They're looking into it.

**Comment by duckinator** [comment]
Got this response from Vodafone on Monday (August 21st):

> We've had a response from the Secure net team who confirmed that these websites are currently classified as computing so they are not blocked.

So in theory Vodafone Secure Net should no longer block rubygems.org or index.rubygems.org.

**Comment by simi** [comment]
Is anyone able to check Vodafone is not blocking RubyGems.org anymore?

**Comment by wallymathieu** [comment]
Perhaps time to close the issue and reopen if there is anything we can do.

**Comment by rudgal** [comment]
thanks @duckinator 🙏  
@simi yes, seems to be working, vodafone-block has vanished and the url is accessible now (at least from my end).

**Comment by f-naranjo** [comment]
Hi everyone, after hours of troubleshooting I finally found this issue and I have to say that Vodafone secure net was the problem. I was connected to my home WiFi network where I had Secure Net enabled, and the error was occurring. Then, I switched to my iPhone hotspot where Secure Net is disabled, and everything is working.

**Comment by duckinator** [comment]
Well, that didn't last long. Not even 4 whole months before Vodafone started blocking us again.

Thanks for letting us know, @f-naranjo.

**Comment by duckinator** [comment]
I reached out to Vodafone. Again. We'll see how that goes.

**Comment by duckinator** [comment]
@f-naranjo can you check whether you're still having this problem? if you are, can you provide me a screenshot I can pass along to Vodafone?
