### ISSUE TITLE
Making download statistics available, in bulk

### ISSUE THREAD

**Issue by RichMorin** [rubygems/rubygems.org#384]
sferik's "gems" gem allows an external site to request certain statistics (eg, total_downloads).  This is very cool, but I'd like to track this sort of thing for all 170K gems.  Making that many requests (eg, on a daily basis) seems Wrong, so I'm looking for a better option.

One possibility would be to create text files, updated nightly, that contain the statistics.  Ideally, these would be both human- and machine-readable.  I'd prefer a simple YAML format, to allow extensibility and provide self-documentation. If the files were stored on GitHub, folks could examine the files online, go back and pick up any that they might have missed, etc.

These files could get rather large, so it might be useful to break them up in some manner. For example, I've been putting mirrored gems into buckets by the first two (downcased) characters of the name (eg, "12/12_hour_time").  For details, see
http://cfcl.com/twiki/bin/view/Projects/SPARQLy/Gems/File_Layout#Bucket_distribution

**Comment by qrush** [comment]
We have https://rubygems.org/pages/data now. I'll let @dwradcliffe close this once we have Redis on there for download stats!

**Comment by knappe** [comment]
@dwradcliffe Looks like Redis data is now being shown on https://rubygems.org/pages/data.  Is this good to close?
