### ISSUE TITLE
Issue with authentication with proxy

### ISSUE THREAD

**Issue by tysonite** [rubygems/rubygems.org#391]
I try to authenticate on proxy using the following method:
export http_proxy='http://DOMAIN\login:password@192.168.205.2:8080'

and it doesn't work with the following message:
[root@host]# gem update
Updating installed gems
ERROR:  While executing gem ... (URI::InvalidURIError)
    bad URI(is not URI?): http://DOMAIN\login:password@192.168.205.2:8080

However, if I exclude "DOMAIN\" string from http_proxy variable it tries to authenticate, but fails (because proxy requires domain name to be included for the user):

[root@host]# export http_proxy='http://login:password@192.168.205.2:8080'  
[root@host]# gem update
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Proxy Authentication Required 407 (http://rubygems.org/latest_specs.4.8.gz)

I guess that proxy settings parser should be extended to understand domain name.

rubygems version is
[root@host]# gem -v
1.8.15

**Comment by etxzay** [comment]
@MartinMa Thank you!

**Comment by ken-sands** [comment]
or url encode that backslash using %5C as below

http://DOMAIN%5Clogin:password@192.168.205.2:8080
