### ISSUE TITLE
Search input show query or something like that.

### ISSUE THREAD

**Issue by a-chacon** [rubygems/rubygems.org#4217]
I'm not sure if this is an issue; I also didn't see anything similar in the open issues. However, when searching for a gem and then applying filters such as 'updated last month' or 'updated last week,' it adds to my search as part of the query parameter, like a 'where' clause.

## Steps to Reproduce
1. Search  a gem.
2. Then press "UPDATED LAST MONTH"

## Expected Behavior

Don't show that in the search parameter, use another hidden for the user.

## Current Behavior

![imagen](https://github.com/rubygems/rubygems.org/assets/39093711/40170b6f-4bab-4a49-9f03-afafd3736c34)

## Environment
Browser and its version: firefox 119.0.1 (64-bit)
RubyGems version:

**Comment by colby-swandale** [comment]
We always show the search query in the subtitle field, including any conditions / filter params that may be part of the query. See https://github.com/rubygems/rubygems.org/commit/583227ba2e451b2dd53b3b1b3bebc428c491176d
