### ISSUE TITLE
`https://index.rubygems.org/info/:name` cache not always busted

### ISSUE THREAD

**Issue by Earlopain** [rubygems/rubygems.org#4230]
About 4 hours ago the gem [httpx](https://rubygems.org/gems/httpx) published a new version which I'm not able to install at the moment. The UI shows 1.1.5 as the latest while doing `gem install httpx` pulls down 1.1.4

## Steps to Reproduce
Access https://index.rubygems.org/info/httpx and observe that the latest version is 1.1.4

```sh
$ gem install httpx -v 1.1.5 --verbose
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/httpx
200 OK
ERROR:  Could not find a valid gem 'httpx' (= 1.1.5) in any repository
GET https://rubygems.org/latest_specs.4.8.gz
304 Not Modified
ERROR:  Possible alternatives: httpx
```

## Possible Solution

I have found #3593 but I doubt this isn't already being done here.

## Environment
Browser and its version: n/a
RubyGems version: 3.4.22

**Comment by simi** [comment]
https://github.com/rubygems/rubygems.org/pull/4231

**Comment by simi** [comment]
@Earlopain hello and thanks for the report. We were able to track down the issue to https://github.com/rubygems/rubygems.org/pull/4231. Meanwhile this is deployed (few minutes from now), I have manually updated info file for httpx gem. Can you confirm it works now as intended and gem can be installed?

**Comment by Earlopain** [comment]
Hi @simi, it looks good now.

Nice to see that a fix was found so quickly, great work on that @segiddins
