### ISSUE TITLE
Avo `3.0.4` issue

### ISSUE THREAD

**Issue by Paul-Bob** [rubygems/rubygems.org#4234]
### Describe the problem as clearly as you can

Hello! It seems to be an issue on the recent Avo [`3.0.4` release](https://rubygems.org/gems/avo/versions/3.0.4). Some folks are complaining that blunder do not find the latest version. Check [issue comments here](https://github.com/avo-hq/avo/issues/2047).

`bundle --full-index` seems to work and fetch the latest version but only `bundle` result on this message:

![image](https://github.com/rubygems/rubygems/assets/69730720/be38c9f3-be80-4831-88b4-5d73fbfdf063)

Is there anything that we can do ti fix this?

Thank you!

**Comment by Paul-Bob** [comment]
@simi it seems to be fixed on my side

> I see also avo released new version meanwhile. 

we released `3.0.5` hopping to solve the issue

Thank you

**Comment by simi** [comment]
Thanks for the info.
