### ISSUE TITLE
Add endpoint for claiming gems

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#424]
This is a biggie!

![](http://www.secsportsfan.com/images/mark-richt-billy.jpg)

RG 2.0's plan is add a new step when pushing gems, `gem claim`. The workflow for pushing a *new* gem will be:

```
gem claim [gem name]
           ▼
gem push [local .gem file]
           ▼
gem install [gem name]
```

This fixes two big issues:

1. Adds a verification step for creating a gem, which will stop "mistake", "oops" pushes of internal gems
2. Allows developers to "reserve" gem names

The workflow for existing gems doesn't change, it's just `gem push` like normal. This is for *new* gems only.

This issue actually will involve several little steps:

* New `Gem::Command` for `gem claim`
* Endpoint and implementation of this logic (soft requirement now, hard requirement once RG 2.0 is out)
* A way to contact the author of a claimed gem to get them to release the gem (probably will require another endpoint)

Pinging @sferik @cldwalker @cmeiklejohn for feedback, also heads up to @evanphx @drbrain!

**Comment by simi** [comment]
Was this idea rejected?

**Comment by qrush** [comment]
It wasn't rejected...more like never got off the ground. Closing since it's been stale for a while.

:bread:
