### ISSUE TITLE
Inconsistent gem availability for stringio

### ISSUE THREAD

**Issue by colinbruce** [rubygems/rubygems.org#4247]
### Describe the problem as clearly as you can

Dependabot has opened PRs on multiple repos for `stringio v3.1.0 this morning but none of them are successful.

`gem list stringio --remote --all`
returns
```shell
*** REMOTE GEMS ***

rubysl-stringio (2.3, 2.2, 2.1, 2.1.0, 2.0.0, 1.0.1, 1.0.0)
stringio (3.1.0 ruby java, 3.0.9 ruby java, 3.0.8 ruby java, 3.0.7 ruby java, 3.0.6 ruby java, 3.0.5 ruby java, 3.0.4 ruby java, 3.0.3 ruby java, 3.0.2 ruby java, 3.0.1, 3.0.0, 0.1.4, 0.1.3, 0.1.0, 0.0.2, 0.0.1)
```
Which appears to show 3.1.0.

Locally running: `gem install stringio -v 3.1.0` or `gem install stringio -v 3.1`
Results in 
```shell
ERROR:  Could not find a valid gem 'stringio' (= 3.1) in any repository
ERROR:  Possible alternatives: stringio
```

Attempting `bundle update stringio` manually returns:
```shell
Bundler attempted to update stringio but its version stayed the same
```

Other gems are updating fine. Is this an issue with rubygems?

I have raised an [stringio](https://github.com/ruby/stringio/issues/73) with the stringio team and they have indicated that they received unicorn errors while publishing

### Did you try upgrading RubyGems?

Yes
`gem update --system`
```Latest version already installed. Done.```

### Post steps to reproduce the problem

Ruby `3.2.2`
RubyGems `3.4.22`

`gem list stringio --remote --all` - you should see 3.1.0 listed

`gem install gem install stringio -v 3.1.0` will fail

### Which command did you run?

`gem install gem install stringio -v 3.1.0`

### What were you expecting to happen?

The installation of the gem listed by `gem list`

### What actually happened?

Message saying `Could not find a valid gem`

### Run `gem env` and paste the output below

RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.22
  - RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [x86_64-darwin22]
  - INSTALLATION DIRECTORY: /Users/myname/.rvm/gems/ruby-3.2.2
  - USER INSTALLATION DIRECTORY: /Users/myname/.gem/ruby/3.2.0
  - RUBY EXECUTABLE: /Users/myname/.rvm/rubies/ruby-3.2.2/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/myname/.rvm/gems/ruby-3.2.2/bin
  - SPEC CACHE DIRECTORY: /Users/myname/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/myname/.rvm/rubies/ruby-3.2.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-22
  - GEM PATHS:
     - /Users/myname/.rvm/gems/ruby-3.2.2
     - /Users/myname/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/myname/.rvm/gems/ruby-3.2.2/bin
     - /Users/myname/.rvm/gems/ruby-3.2.2@global/bin
     - /Users/myname/.rvm/rubies/ruby-3.2.2/bin
     - /Users/myname/.rvm/bin
     - /usr/local/opt/openssl@3/bin
     - /Users/myname/.nvm/versions/node/v16.15.0/bin
     - /usr/local/opt/openssl@1.1/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/myname/Library/Python/3.9/bin
     - /usr/local/MacGPG2/bin
     - /Library/Apple/usr/bin
     - /Applications/Postgres.app/Contents/Versions/latest/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

**Comment by simi** [comment]
Seems https://github.com/rubygems/rubygems.org/pull/4231 have not fixed all problems. I have fixed this gem manually for now.
