### ISSUE TITLE
Something in `rubygems_mfa_required` changed recently, causing token pushes to fail

### ISSUE THREAD

**Issue by gjtorikian** [rubygems/rubygems.org#4264]
## Steps to Reproduce

1. Have a gem with `rubygems_mfa_required = true`
2. Create an API token, which can `push`, and which does not require 2FA
   <img width="370" alt="Screenshot 2023-12-03 at 11 21 15" src="https://github.com/rubygems/rubygems.org/assets/64050/04f4c476-9468-4745-9c64-e324f3f9a0d2">

3. Attempt to push the gem

## Expected Behavior

I have my gem set to require 2FA, but my token has never been 2FA backed. That's because I have the token stored in a GitHub Secret, and use an action to automatically deploy the gem on command ([these logs, for example](https://github.com/gjtorikian/commonmarker/actions/runs/7073182603/job/19252806479#step:4:62)). As of about a week ago, this worked fine.

## Current Behavior

Gem does not push and instead you see the error:

```
Rubygem requires owners to enable MFA. You must enable MFA before pushing new version.
```

Curiously as well, when pushing for a specific platform, the same error message is returned, but the exit code is `0`, indicating success ([these logs](https://github.com/gjtorikian/commonmarker/actions/runs/7073182603/job/19252806636#step:5:16)). Note also that the line below it says the gem was successfully pushed. 

## Additional Context

Based on recent PRs, I suspect this might have been caused by #4210 or #4213 cc @segiddins 

Perhaps another question is, should this have ever worked in the first place? What's the recommended security procedure for asking CD to release a gem using a token?

**Comment by simi** [comment]
@jenshenny maybe knows as well what's intended behaviour in here 🤔

**Comment by indirect** [comment]
My understanding of the desired behavior is: tokens generated with MFA turned off should not require MFA to use. This is specifically to allow the workflow mentioned here, pushing gems from CI.

**Comment by jenshenny** [comment]
This is the PR that introduced the feature: https://github.com/rubygems/rubygems.org/pull/2242

It says that publishing and other actions require MFA https://guides.rubygems.org/mfa-requirement-opt-in/ (which is the behaviour at the `ui_and_api` level) , but looking at the tests for the PR, they are only checking if MFA is enabled (and not specifically on the API level / on a per token basis).

I think it makes sense allow MFA to be turned off for keys as for the reasons @indirect mentioned. I can update the docs to clarify that owners are required to have their MFA enabled at the `ui_and_gem_signin` level if that makes sense for all of us.

**Comment by indirect** [comment]
@jenshenny sounds great, thank you!

**Comment by segiddins** [comment]
I will try to fix the regression tomorrow, my apologies for the inconvenience!
