### ISSUE TITLE
Providing checksums in the API

### ISSUE THREAD

**Issue by ushis** [rubygems/rubygems.org#427]
I am currently working on a small tool, that creates PKGBUILDs from the rubygems API. PKGBUILDs are used to build packages for Arch Linux. The main intention is to to manage the system wide installed gems with pacman - the Arch Linux package manager - and not with gem.

In the PKGBUILDs we are using checksums (md5 or sha1) to check the integrity of the downloaded source file. So is it possible to provide a checksum in your API? I know that there are tools like ```gem check --verify```, but i dont want to download the gem, i just want to create file with some info about it, so that we can easily build packages.

Thanks for thinking about, ushi

**Comment by simi** [comment]
`sha` was added to API in https://github.com/rubygems/rubygems.org/pull/911 and it is deployed already. I think this can be closed now.

**Comment by arthurnn** [comment]
Yes, sha256 is already in production.
thanks all
