### ISSUE TITLE
Please include username and email address in password resets

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#4281]
I just got this password reset email, but it went to a mailing list, and I can't figure out which account or email address it was actually sent to 😅 

Can we include the RubyGems.org username and email in the password reset email, so the email recipient knows what account is being reset?

![Image](https://github.com/rubygems/rubygems.org/assets/78/350ec395-1876-4ae7-99ef-328f5bcae0c6)

**Comment by simi** [comment]
Handle should be visible. Is it possible there is nil handle on your profile?

https://github.com/rubygems/rubygems.org/blob/8ce6c46d5aa64635de06e481f8655ae898c505f2/config/locales/en.yml#L164

https://github.com/rubygems/rubygems.org/blob/8ce6c46d5aa64635de06e481f8655ae898c505f2/app/views/clearance_mailer/change_password.text.erb#L1

**Comment by indirect** [comment]
Thanks for checking on this! Maybe we can fall back on email address if handle is nil? Or maybe we can update the message the message to include an email address, perhaps:

```
Someone, hopefully you, requested a password reset link for the account <%= @user.handle %>, with the email address <%= @user.email %>. You can use this link to reset your RubyGems.org password:
```

**Comment by jenshenny** [comment]
Fixed by: https://github.com/rubygems/rubygems.org/pull/4517 🎉
