### ISSUE TITLE
Address trusted publishing feedback

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#4283]
###
- [x] Pending trusted publishers section is not present on user settings page at https://rubygems.org/settings/edit
![Image](https://github.com/rubygems/rubygems.org/assets/78/b2dea98b-5802-4aa7-8d3f-9603f132c47c)

### https://guides.rubygems.org/trusted-publishing/
- [x] Links at the top (both "Adding a trusted publisher to an existing gem" and "Pushing a new gem with a trusted publisher" do not go anywhere
- [x] Text has not been updated after being copied from PyPi: "Trusted publishing is a mechanism for uploading gems to PyPi without using long-lived secret credentials."
- [x] Stop linking to PyPI's "internals" docs, because it does not describe the internals of RubyGems' implementation: https://docs.pypi.org/trusted-publishers/internals/

### https://guides.rubygems.org/trusted-publishing/adding-a-publisher/
- [x] The "your profile page" link goes to "rubygems.org". Update it to the actual profile page.
- [x] The text says "you’ll see a link to Trusted publishers on the right side", circle or otherwise highlight the sidebar link in the screenshot
- [x] Change this text: "To enable trusted publishing for this gem, you’ll need to tell RubyGems.org how to trust it. GitHub Actions (the only currently supported trusted publisher) requires the repository owner’s name, repository name, and the name of the workflow that will be pushing the gem." to this text instead: "Providing the owner name, repository name, and GitHub Actions workflow name allows RubyGems to securely accept uploaded gems from the GitHub Actions infrastructure. If you have multiple workflows that push gems, you can create one Trusted Publisher for each workflow."
- [x] Update description "A publisher can be registered for multiple gems, and a gem can have multiple publishers." with an example of the many-to-many relationship
- [x] Add a link at the end of the page pointing to the sample GitHub workflow YAML, with the text "Now that you've created a Trusted Publisher, create a GitHub Actions workflow to publish your gem. You can [use our example workflow as a starting point]."

### https://guides.rubygems.org/trusted-publishing/pushing-a-new-gem/
- [x] Add a link at the end of the page pointing to the sample GitHub workflow YAML, with the text "Now that you've created a Trusted Publisher, create a GitHub Actions workflow to publish your gem. You can [use our example workflow as a starting point]."

**Comment by segiddins** [comment]
>  Pending trusted publishers section is not present on user settings page at https://rubygems.org/settings/edit

That's currently intentional, right now it's only shown if you have a pending trusted publisher. Probably makes sense to remove that now tho given we have guides etc

**Comment by segiddins** [comment]
>  The "your profile page" link goes to "rubygems.org". Update it to the actual profile page.

is there a generic "your profile" endpoint I can link to?
