### ISSUE TITLE
Dependencies listed multiple times when using conditionals in gemspec

### ISSUE THREAD

**Issue by colszowka** [rubygems/rubygems.org#430]
Jeweler has this habit of making Gemspecs use a lot of if/else conditionals depending on the Rubygems version. An example of this is https://github.com/TACSUO/event_calendar/blob/master/event_calendar_engine.gemspec. While it seems to me that this is unneccessary since all non-conditional gemspecs work just fine, I assume there's a reasoning behind this.

Unfortunately, on Rubygems.org these gems get their dependencies listed multiple times (see  https://rubygems.org/gems/event_calendar_engine) in such cases. I'm not sure how Gemcutter parses gemspecs, but I assume they are not actually being executed, but just get parsed, which leads to the if/else statements getting ignored. 

This problem bubbles up through the API, so in the Ruby Toolbox I end up with the same problem (https://www.ruby-toolbox.com/gems/event_calendar_engine). While of course I could work around that myself, I think it would make sense to fix this problem at the root.

As probably the gemspec parsing is not easily changed to full-on Ruby execution I would like to suggest to make the Dependency reference list uniq each time it is being saved. Also, probably once the existing data is fixed, it would make sense to add a unique index on the join table, but that just might be me fancying my PG consistency constraints :)

**Comment by bradly** [comment]
So rubygems.org uses the Rubygems Gem::Specification class to pull a gem's dependencies. It would ideal for this issue to be opened in with rubygems/rubygems and see what they think. Here is a gist replicating the problem with rubygems itself: https://gist.github.com/bradly/dc8820d90dbae3f15678

@qrush We could work around this by uniquing the gem_id and requirements. What do you think?

**Comment by qrush** [comment]
It would be nice to have the root problem fixed, and when RubyGems wraps up the gem, it does a `uniq` call itself.

**Comment by dwradcliffe** [comment]
This has nothing to do with if statements. This gemspec is actually repeating dependencies. I don't think this is common enough for us to change anything.
