### ISSUE TITLE
Add option to display profile avatar without displaying email

### ISSUE THREAD

**Issue by dentarg** [rubygems/rubygems.org#4318]
## Is your feature request related to a problem?

Profile avatar can only be displayed if email is also displayed

## Describe the solution you'd like

To display your avatar (Gravatar) you need to check `Show email in public profile` on your profile edit page

I don't mind displaying my avatar (despite the info leak concerns) but I would like to not display my email in plain text on my profile page.

## Describe alternatives you've considered

Allow upload of avatars (actually @simi that mentioned this in Slack but the thought has crossed my mind too)

## Additional context

* https://github.com/rubygems/rubygems.org/pull/4104
* https://github.com/rubygems/rfcs/pull/51

**Comment by rubyFeedback** [comment]
Would also be nice if we could have some additional way to specify a small-ish Avatar without gravatar. Not sure
how small. Perhaps it could be hosted at imgur if it is small in size. Right now many Avatars are showing the
generic one. I used gravatar in the past, but these days I have become a bit lazy, so I can't even bother to 
specifically upload anything at gravatar yet alone make a new account. Anyway, that is semi-off-topic so I end
that comment here.
