### ISSUE TITLE
Newly Pushed Gem Versions Cannot Be Resolved in Certain Cases

### ISSUE THREAD

**Issue by evman182** [rubygems/rubygems.org#4331]
## Steps to Reproduce

1. A gem exists that hasn't been updated since the last monthly version file update
2. Install that gem in a project using `bundler`
3. Push a new version of that gem
4. Update the `gemfile` to require the new version of the gem
5. Run `bundle install`

## Expected Behavior

- The versions file includes the new version with an updated "info checksum"
- The new version of the gem is found and installed

## Current Behavior

- The versions file includes the new version but still has the previous "info checksum"
- Bundler's local cache of the gem's info is not updated, and the new version cannot be installed.

## Possible Solution
I think this is related to the following PR: https://github.com/rubygems/rubygems.org/pull/4255. 

I believe it's specifically related to this change
https://github.com/rubygems/rubygems.org/pull/4255/files#diff-61977d248b654178763e77a2fddc09152a20b85b1aecfc8222ef4233564593fcL269

and this, which is used to gather all the versions to generate the "info checksum":
https://github.com/rubygems/rubygems.org/blob/c204f62b560b263239d8cb196a331b3ea96b4463/app/models/gem_info.rb#L126

That the query is looking for `indexed = true`, but with the changes in the above PR that I linked to, that indexed value isn't being set until later.

If you look at this code block, that indexed attribute use to be set true on line 164, but now it's not set until the `AfterVersionWriteJob` executes. However, the query looking for index=true executes on line 182:
https://github.com/rubygems/rubygems.org/blob/c204f62b560b263239d8cb196a331b3ea96b4463/app/models/pusher.rb#L164-L182

**Comment by evman182** [comment]
@segiddins FYI

**Comment by simi** [comment]
Thanks for the report @evman182, finally I do see your point.

looking at output

```
[retro@retro  rubygems.org (fix-rubocop-line $%=)]❤ curl -# "https://rubygems.org/versions" | grep "temporal_tables"
#######################################################################################                                                                                                  47.7%
mariadb_temporal_tables 0.1.0,0.1.1,0.1.2,0.1.3,0.2 71caf9a7e0d7b318374c19688b5c97ce
#######################################################################################################################################################                                  82.8%
temporal_tables 0.6.1,0.6.2,0.6.3,0.6.4,0.6.6,0.6.7,0.6.9,0.6.10,0.7.0,0.7.1,0.8.0,0.8.1,1.0.1,1.0.2,1.0.3,1.1.0,2.0.0 9ae3399947223af03c118646e5817fb2
#######################
temporal_tables 3.0.0.pre.rc.1 9ae3399947223af03c118646e5817fb2
################################################################################################################################################################ 100.0%
```

Last 2 entries share the same info checksum - `9ae3399947223af03c118646e5817fb2`.

**Comment by simi** [comment]
@evman182 I have reverted related PR and recalculated info checksum for gems pushed after original PR deploy until now. Can you check all looks good now?

**Comment by evman182** [comment]
@simi Yes, looks good now
