### ISSUE TITLE
RFE: Support for conditional GET / If-Modified-Since header

### ISSUE THREAD

**Issue by atodorov** [rubygems/rubygems.org#436]
I have an application which does send lots of GET requests to your website.

To minimize network load and bandwidth usage I'm sending If-Modified-Since header with every request. Unfortunately the API doesn't seem to support that (or it be configured at present). Please fix it.

I'm using the JSON interface, .e.g. GET http://rubygems.org/api/v1/versions/PACKAGE.json

**Comment by arthurnn** [comment]
Yes, we should add more `stale?` checks on our API, however the versions API already have that check https://github.com/rubygems/rubygems.org/blob/master/app/controllers/api/v1/versions_controller.rb#L10-L12 .
And seems like it is working for me:
```
curl -i https://rubygems.org/api/v1/versions/rails.json --header 'If-None-Match: "944a74b63f8cfdf4ec5d9521ed003ba0"'
```

**Comment by dwradcliffe** [comment]
This is working for me too. Closing since it is stale. (pun intended)
