### ISSUE TITLE
WebAuthn appears to be hanging.

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems.org#4393]
## Steps to Reproduce

```
Enter PEM pass phrase:
  Successfully built RubyGem
  Name: io-endpoint
  Version: 0.6.0
  File: io-endpoint-0.6.0.gem
 4.88s     info: Bake::Gem::Helper [oid=0xa78] [ec=0xa8c] [pid=68502] [2024-01-26 13:44:04 +1300]
               |   gem push pkg/io-endpoint-0.6.0.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please visit https://rubygems.org/webauthn_verification/apz[snip] to authenticate via security device. If you can't verify using WebAuthn but have OTP enabled, you can re-run the gem signin command with the `--otp [your_code]` option.
ERROR:  execution expired
```

## Expected Behavior

A week ago this was working, but now WebAuthn doesn't work and appears to hang during `gem push`.

## Current Behavior

On visiting the link, I press the authorize button and it says "Success!" but the gem push process does not continue forward.

## Environment
Browser and its version: Safari Mobile
RubyGems version: 3.5.5

## Additional Context

Using `--otp` does work for the same gem package:

```
> gem push --otp xxxyyy pkg/io-endpoint-0.6.0.gem 
Pushing gem to https://rubygems.org...
Successfully registered gem: io-endpoint (0.6.0)
```

**Comment by ioquatix** [comment]
I tested this on both my desktop (Linux) and laptop (macOS) and the problem is still present.

**Comment by rubyFeedback** [comment]
Working fine for me without MFA. \o/

(I know that does not help ioquatix but I could not resist!)
