### ISSUE TITLE
Menu Javascript broken, logging out impossible

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#4420]
Trying to open the "User profile" menu does not work:

<img width="208" alt="image" src="https://github.com/rubygems/rubygems.org/assets/78/ea4b61eb-cc43-46aa-bc79-6d0c14e14208">

In the console, the error is:

> Unhandled Promise Rejection: Error: tooltipContainer does not exist

As a side effect of broken javascript and no menu, it is not possible to log out.

**Comment by bettymakes** [comment]
Is this resolved? I was trying to reproduce but couldn't. If the bug still persists, @indirect, what was the last action you did or view you visited?

**Comment by indirect** [comment]
I believe this was due to switching to importmap-rails and is now resolved, thanks for checking on it!
