### ISSUE TITLE
Changing dependencies didn't change it on the gem page

### ISSUE THREAD

**Issue by danielmorrison** [rubygems/rubygems.org#4578]
We changed our runtime dependencies in [audited](https://rubygems.org/gems/audited) in 5.5.0, but the website is still showing the old ones. New set: 
```
"activerecord", ">= 5.2", "< 7.2"
"activesupport", ">= 5.2", "< 7.2"
```

It is currently showing the `request_store` which 5.5.0 removed. 

## Expected Behavior

Show the current set of runtime dependencies. 

## Current Behavior

Shows the previous set.

## Possible Solution

Caching issue?  I'm willing to believe my gemspec is the problem, but it really doesn't seem like it. 

## Environment
Browser and its version: Safari 17.3.1
RubyGems version: n/a

## Additional Context

Everything else on the page seems correct.

**Comment by simi** [comment]
Hello, I have downloaded gem (https://rubygems.org/downloads/audited-5.5.0.gem), extracted (it is tar + gzip) and inspected metadata and there is still request_store, see attached picture.

![image](https://github.com/rubygems/rubygems.org/assets/193936/8db06277-f13c-4c3b-ac21-6e318e5f6934)

Are you 100% sure proper gemspec was pushed?

**Comment by danielmorrison** [comment]
no, I guess I'm not sure anymore. 

I think I found a bug in our publishing process. Closing this.
