### ISSUE TITLE
Remove or replace Twitter/X from email footer

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems.org#4600]
### Discussed in https://github.com/rubygems/rubygems.org/discussions/4277

<div type='discussions-op-text'>

<sup>Originally posted by **svoop** December  8, 2023</sup>
I've just pushed a gem release and got the email confirming it. In the footer:

<img width="621" alt="image" src="https://github.com/rubygems/rubygems.org/assets/7255/5e35b802-e24d-4d38-ac27-043821c87d6a">

Now, put aside the new management and tone of Twitter/X for a moment, it's not possible to view the Rubygems Twitter/X profile without having logged in to Twitter/X. This renders this microblog useless for folks like me who – for one reason or another – have decided to leave Twitter/X.

Obviously, I can't see whether there's anything interesting happening on the Rubygems Twitter/X profile, so I can't tell which of the following actions would be appropriate:

* Drop Twitter/X without replacement.
* Drop Twitter/X in favor of Mastodon – there's already a (not very active) profile there on https://ruby.social/@rubygems

What do you think?</div>

**Comment by jenshenny** [comment]
At RailsConf, it was decided that we can replace the twitter icon with a Mastodon one. https://github.com/rubygems/rubygems.org/pull/4695 will first drop the twitter icon!
