### ISSUE TITLE
Dashboard Atom feed link broken

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems.org#4601]
### Discussed in https://github.com/rubygems/rubygems.org/discussions/4220

<div type='discussions-op-text'>

<sup>Originally posted by **delphaber** November  3, 2023</sup>
Hello :)

I don't know if I should open an issue on this repo. So I'll start with a discussion first

It looks like the feed link containing subscrited gems updates is broken

![CleanShot 2023-11-03 at 10 40 53@2x](https://github.com/rubygems/rubygems/assets/139284/42d911a6-b1ae-4a24-8306-e17b5936281e)

e.g. https://rubygems.org/dashboard.atom?api_key=<TOKEN>

When testing the url with `curl`, for instance, I've got redirected to the sign in page. Is the token expired somehow? I did not find a way to update it though

Thanks!</div>

**Comment by jenshenny** [comment]
Hey @delphaber, if you're still running into this, the issue was reported here https://github.com/rubygems/rubygems.org/issues/3816. 

The key in the link was used for legacy purposes and you need to create a token with the show_dashboard scope https://rubygems.org/profile/api_keys/new.

**Comment by delphaber** [comment]
Got it :) thanks!
