### ISSUE TITLE
Display last released version

### ISSUE THREAD

**Issue by markets** [rubygems/rubygems.org#4624]
Hello 👋🏼 

When you visit your profile page, Which is the version displayed for each of your gems? It seems arbitrary 🤔?

Example (https://rubygems.org/profiles/markets):

<img width="1039" alt="Captura de pantalla 2024-04-18 a las 22 19 00" src="https://github.com/rubygems/rubygems.org/assets/576701/154f7c85-e748-4e27-be48-1358439eccc9">

---

<img width="672" alt="Captura de pantalla 2024-04-18 a las 22 20 47" src="https://github.com/rubygems/rubygems.org/assets/576701/2c0b90c4-0179-4e3b-9b59-d9055f9966ac">

## Steps to Reproduce
Visit any profile page, like: https://rubygems.org/profiles/markets
 
## Expected Behavior
Each gem should display last released version.

## Current Behavior
Not sure which version is displayed right now 🙏🏼, but 100% sure it's not the last one.

## Possible Solution
Just display last version ✔️

**Comment by markets** [comment]
Tracking down the code, I think the related line is the following:

https://github.com/rubygems/rubygems.org/blob/2a9ad86185c3d899762e80382b5a39814699b1a4/app/views/profiles/_rubygem.html.erb#L6

So, apparently this `most_recent_version` method doesn't work as expected?

https://github.com/rubygems/rubygems.org/blob/2a9ad86185c3d899762e80382b5a39814699b1a4/app/models/rubygem.rb#L30-L36

**Comment by dancristianb** [comment]
Hi @markets ! Nice catch, thanks for reporting 🙏 I'm jumping in as I think this might be related to some of the updates I helped push out in https://github.com/rubygems/rubygems.org/pull/4544

I've checked the gems page and it looks like the latest `invisible_captcha` version seems to be reported correctly there see https://rubygems.org/gems?letter=I&page=94 

<img width="1587" alt="Screenshot 2024-04-19 at 12 54 07" src="https://github.com/rubygems/rubygems.org/assets/32739319/35cc85a2-1322-4dc7-bf46-42c9204478e0">

We use different queries to load the gems on the profile page and gems page

- For the [gems page](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/rubygems_controller.rb#L15) we use the `#latest_version` 
- For the [profiles page](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/profiles_controller.rb#L12) we use the `#most_recent_version` and `strict_loading` 

I've pulled the gems locally and switched to using the `#latest_version` and `strict_loading` on the profiles page as well and we now seem to render the correct "latest" version. I'm not sure of any other side effects though 😀 The diff looks something like this:

```diff
diff --git a/app/controllers/profiles_controller.rb b/app/controllers/profiles_controller.rb
index 82a3c1a2d..1adbf2338 100644
--- a/app/controllers/profiles_controller.rb
+++ b/app/controllers/profiles_controller.rb
@@ -9,7 +9,7 @@ class ProfilesController < ApplicationController

   def show
     @user = User.find_by_slug!(params[:id])
-    @rubygems = @user.rubygems_downloaded.includes(%i[most_recent_version gem_download]).strict_loading
+    @rubygems = @user.rubygems_downloaded.includes(%i[latest_version gem_download]).strict_loading
   end

   def me
diff --git a/app/views/profiles/_rubygem.html.erb b/app/views/profiles/_rubygem.html.erb
index c8fa121d2..3fa8e2582 100644
--- a/app/views/profiles/_rubygem.html.erb
+++ b/app/views/profiles/_rubygem.html.erb
@@ -3,7 +3,7 @@
     <span class="gems__gem__info">
       <a href="<%= rubygem_path(rubygem.slug) %>" class="gems__gem__name">
         <%= rubygem.name %>
-        <span class="gems__gem__version"><%= rubygem.most_recent_version %></span>
+        <span class="gems__gem__version"><%= rubygem.latest_version %></span>
       </a>
     </span>
     <p class="gems__gem__downloads__count">
```

So this is what I see locally without the above diff applied

<img width="1257" alt="Screenshot 2024-04-19 at 13 07 43" src="https://github.com/rubygems/rubygems.org/assets/32739319/353fe79c-257d-47e1-a19e-6a23fb253f2a">

This is what the page looks like with the above diff applied

<img width="1236" alt="Screenshot 2024-04-19 at 13 02 30" src="https://github.com/rubygems/rubygems.org/assets/32739319/0e5a8106-79cf-4a3e-b938-3898a4f7a547">

`Prosopite` doesn't seem to report any n+1s ✅ I'm not sure why we're not using the `#latest_version` there 🤔

**Comment by markets** [comment]
Thanks for looking into this @dancristianb! Yes, that seems a good fix, but unfortunately I'm not familiar with this app, so I don't know if that is 100% correct or it has any side effect.

**Comment by rubyFeedback** [comment]
It is most likely a bug. I think it used to always show the latest release of a given gem in the past; at the least I think it used to be that way.

(Note that conceptually I am not sure what the difference should be between .most_recent_version and .latest_version; just the names itself may lead to confusion. IMO .most_recent_version seems more clear, or one could make it even more verbose, e. g. .most_recently_published_version - but I could not tell what the difference to .latest_version would be. It may be easier to use only one name here, in the event this could otherwise lead to confusion.)

**Comment by markets** [comment]
Definitely that's a bug, it's really strange to not display latest version in profile pages.

For example, visiting DHH profile, you can also see different versions for the different Rails core gems:

<img width="795" alt="Captura de pantalla 2024-04-19 a las 19 28 52" src="https://github.com/rubygems/rubygems.org/assets/576701/76e8b8e3-8689-48c5-ae23-7d20b41c83bb">

It would be really nice to fix this.

**Comment by dancristianb** [comment]
> It is most likely a bug. I think it used to always show the latest release of a given gem in the past; at the least I think it used to be that way.

> Definitely that's a bug, it's really strange to not display latest version in profile pages.

+1

> unfortunately I'm not familiar with this app, so I don't know if that is 100% correct or it has any side effect.

Same here, barely scratching the surface 😀 I'll draft a PR so we can see if the updates don't break anything else and hopefully we'll get the ball rolling with this one 😀
