### ISSUE TITLE
Incorrect gem metadata

### ISSUE THREAD

**Issue by pointlessone** [rubygems/rubygems.org#4827]
Yesterday I pushed a *new* gem to RubyGems: [Gort](https://rubygems.org/gems/gort). Today I noticed that its metadata doesn't match specified in the [gemspec](https://github.com/pointlessone/gort/blob/0f204669c53401256e745e19944c8d9843cbde82/gort.gemspec).

## Steps to Reproduce

1. Go to [Gort](https://rubygems.org/gems/gort) gem page
2. See that metadata is different to that provided in the [gemspec](https://github.com/pointlessone/gort/blob/0f204669c53401256e745e19944c8d9843cbde82/gort.gemspec)

## Expected Behavior

Metadata from the gemspec is displayed on the page.

## Current Behavior

Gem's page lists the following metadata:

Homepage: http://jolshevski.github.io/gort

No Source Code link. No Changelog link.

In the gemspec I have the following (excerpt):

```ruby
# spec.homepage = "TODO: Put your gem's website or public repo URL here."
# spec.metadata["homepage_uri"] = spec.homepage
spec.metadata["source_code_uri"] = "https://github.com/pointlessone/gort"
spec.metadata["changelog_uri"] = "https://github.com/pointlessone/gort/blob/main/CHANGELOG.md"
```

I don't have homepage specified at all but I get one anyway. It's not available on gh but gh doesn't have such user at the moment so someone might register and create the page.

I have Source Code and Changelog specified but they're not showing up on the gem's page.

## Possible Solution

My first guess would be that this is some leftover metadata from a gem that was removed since. But I'd also expect metadata to be updated on push so I have no idea.

## Environment

Browser and its version: any
RubyGems version: 3.5.9

## Additional Context

I'm not sure if this exactly the same issue but it looks a bit similar to #3676.

**Comment by colby-swandale** [comment]
@pointlessone could you please open a new ticket on our support at: support@rubygems.org
