### ISSUE TITLE
Dark mode (please)

### ISSUE THREAD

**Issue by paddor** [rubygems/rubygems.org#4902]
Please provide a dark mode. The website's background is literally white and it's killing my eyes at night.

**Comment by martinemde** [comment]
Working on it as we speak. We have a new design in the works and we are planning to ship dark mode with it.

I'll close this for now since there's nothing else to do besides wait for the new design. Thanks!

**Comment by paddor** [comment]
Five months have passed and the pages that actually matter haven't changed. 👎

**Comment by martinemde** [comment]
We're happy to accept contributions of money or time. We're mostly volunteer and those of us who are paid are focused on security.
