### ISSUE TITLE
make owner --add work with rubygems.org username

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#509]
So i can do
```
gem owner --add grosser
```
without needing to know what email this person is signed up with / without telling people my email

**Comment by jkeiser** [comment]
@qrush the stronger argument at the moment is that I'd like to be able to automate the adding / removing of owners to my rather large set of gems ... and some of the APIs (like `api/v1/owners/USERNAME/gems.json`) refer to users by usernames and some (like `api/v1/gems/GEMNAME/owners.json`) refer to users by email.  It would nice to be able to use one of these as the identity throughout--would make my life simpler--but if not, I could use an API (profile API?) to find out the user's email from their username (or vice versa).

**Comment by jkeiser** [comment]
@qrush there is also the fact that apparently you can hide your email.

It also occurs to me: we don't seem to even report the username of the owner in the rubygems owners API.  Is there any way at all to get the username of a user from the email?

**Comment by indirect** [comment]
FWIW, this has also been a problem for me in the past, because my public email address and my rubygems email address aren't the same. I would like to be able to add and remove by username.

**Comment by qrush** [comment]
Those all seem like reasonable arguments.

**Comment by jkeiser** [comment]
@qrush I'm going to reopen this based on your last comment ... please feel free to open a more specific bug if you feel one of the alternate solutions would work better :)

**Comment by jkeiser** [comment]
Oh!  It looks like I can't reopen.  @qrush would you prefer that I make a new one, or would you rather reopen?

Thanks!

**Comment by qrush** [comment]
:+1:
