### ISSUE TITLE
Notify Users of Bcrypt Password Length Limitation

### ISSUE THREAD

**Issue by kedi** [rubygems/rubygems.org#5093]
## Is your feature request related to a problem?
Yes. When logging in or changing a password, the input can exceed 72 characters. However, Bcrypt silently truncates the password to 72 characters. This means that if a password is 100 characters long, it can still be used to log in with only the first 72 characters.

Example:
Change your password to `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx` (128 characters long).

Log in with `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst` (72 characters long, within Bcrypt's limit).
Result: You are able to log in with the truncated version of the password, which differs from the original one you set.

Alternatively:

Change your password to a 128-character string of non-ASCII characters (e.g., `𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽𩸽`).
Log in using only the first 18 characters of this password, which meets the 72-byte limit (18 characters * 4 bytes = 72 bytes).
Result: You can log in with a password 110 characters shorter than the one originally set.

## Describe the solution you'd like
Users should be notified about Bcrypt's current limitation through a disclaimer.

## Describe alternatives you've considered
An alternative is to enforce a password character limit of 72 characters to avoid this confusion altogether.

**Comment by martinemde** [comment]
This makes sense to me. I'd just put a simple rails validation on the password input when setting the password (but allow longer when authenticating so we don't break existing passwords).

**Comment by Kuanchiliao1** [comment]
Hi! I'd like to work on this issue. Is it still available?

**Comment by martinemde** [comment]
Hi @Kuanchiliao1, please go ahead.
