### ISSUE TITLE
Consider formalizing the process of taking over old, outdated and no longer maintained gems (e. g. +15 years or so).

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems.org#5193]
So this is just a comment mostly; I'll close it too to keep the issue
tracker somewhat clean.

Say there is a gem called "image".

It can be found here:

https://rubygems.org/gems/image

Last release 2007, so 17 years ago, soon 18 years. Not even a github
homepage.

I believe we can safely assume it is abandoned.

Also does not have a lot of downloads - only 6248.

The "namespace" called 'image' is quite nice though. I was thinking
of an API such as:

    Image.resolution?
    Image.new('foobar.jpb').resolution?

Or Images (which is another gem).

Regardless, "image" is currently occupied by that gem. I am not saying
one has to remove old gems, just because a single person wants to take
over the name for his or her own projects, mind you. After all one has
to consider the original author; as well as the possibility of other
users wanting to have the same "namespace". And then, of course, what
other people who may use a gem have to say about it. I understand 
that.

Still, though, I believe there should be some kind of formal process
where old gems can be removed while a new project owner would take
over that namespace, even if it is a different gem.

I have no good and simple suggestion to make how this should work in
practice, but perhaps the rubygems.org teams could begin to formalize
this a little bit, especially if a new author may upload a new project.

So my comment here is about NOT solely just removing an old gem, but
removing AND offering a new gem.

Steps that could be formalized such as:

1) Formalize this for projects that have been for x time without 
a new release. Say +15 years should now suffice (that can be changed).
I think it is reasonable to assume 15 years mean "the person has
abandoned the project on rubygems". 

2) Use a button for a gem author to request such a deprecation.

3) This process can take a little while, say 30-90 days waiting
time.

4) After the waiting time a decision is made. This could be 
automatic but also manual review. In most cases we would expect
the old gem to be removed.

5) The new author has a grace period of, say, 2 weeks to upload
his project. The moment that author does so, the gem officially
becomes the new gem. At the same time notifications are made,
and backups, e. g. the old gem will be archived, old data either
deleted or kept in a backup. At the same time the new gem is
published, new owner stated etc... 

Downstream code could also automatically be adjusted, e. g.
gem and bundler. This part is independent of rubygems.org, though,
as they can handle (disallow / allow) changed projects. Also note
that I refer to OLD, abandoned projects here. The only malicious
use I can think of is when people try to take over "namespaces"
with a malicious purpose, but gem/bundler can handle this and 
e. g. require folks to review things in that case. So my concern
here is only about good people really. (Ultimately nobody can trust
any external code, anyway, but we have this with all software in
general really, so it is not solely confined to just rubygems.)

Hmm. I probably have forgotten about a few things, but these can be
added when discovered an issue. I'd like to see a more formal process
specifically in the case of abandoned projects.

Also, we really need a way for "ownership" in ruby itself - not as
a hard "may not change modules", but as an "ok, gem foobar was 
initially created by Joe, but Pete also uses the same namespace,
so let gem itself handle such situations".

**Comment by simi** [comment]
@rubyFeedback was this closed by mistake? Also please can you open discussion for feature requests instead of issue in the future?
