### ISSUE TITLE
Undocumented "Maintainer" role

### ISSUE THREAD

**Issue by sergio-bobillier** [rubygems/rubygems.org#5196]
The documentation here: https://guides.rubygems.org/managing-owners-using-ui/ does not say anything about owners having roles and it doesn't explain what a "Maintainer" role can or cannot do.

## Steps to Reproduce

1. Go to one of your gems and select "Ownership" from the right menu
2. Confirm your password
3. In the "Add Owner" form there is a "Role" dropdown. One of the possible roles is "Maintainer"

In the documentation link provided above there is no mention of said dropdown nor an explanation of what the difference is between an "Owner" and a "Maintainer"

## Expected Behavior
There should be at least some brief description of what the roles are and what are the differences between them.

**Comment by colby-swandale** [comment]
Hello! You caught one of our new features after we had hit the deploy button. I've updated the Rubygems guides now with information about the maintainer role.

**Comment by sergio-bobillier** [comment]
Thank you. ❤️

**Comment by parkr** [comment]
Requesting more complete documentation in #5270, thanks!
