### ISSUE TITLE
Cannot push gems: "Platform can't be blank"

### ISSUE THREAD

**Issue by mattbrictson** [rubygems/rubygems.org#5355]
## Steps to Reproduce

1. Attempt to publish a new gem version by running `rake release` (using the standard `bundler/gem_tasks`)
2. Enter OTP code
3. Push to rubygems fails: "There was a problem saving your gem"

## Expected Behavior

I expect the "Pushing gem to https://rubygems.org" step of the `release` gem task  to succeed.

## Current Behavior

```
$ rake release
jess 1.4.2 built to pkg/jess-1.4.2.gem.
Tagged v1.4.2.
Pushed git commits and release tag.
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   ******
There was a problem saving your gem: Platform is invalid, Platform can only include letters, numbers, dashes, and underscores, Full name can not end with a period, dash, or underscore, Platform can't be blank
```

Full list of errors:

- Platform is invalid
- Platform can only include letters, numbers, dashes, and underscores
- Full name can not end with a period, dash, or underscore
- Platform can't be blank

## Environment

RubyGems version: 3.6.1
Bundler version: 2.6.1

## Additional Context

It seems that something is causing the platform value to be interpreted as a blank value. My gemspecs do not explicitly set a platform, so I would expect the default platform to be used, as documented here: https://guides.rubygems.org/specification-reference/#platform=

Did something change recently that is causing the default platform value to no longer populate?

**Comment by deivid-rodriguez** [comment]
There was a change related to platforms in the client that we suspect may have caused some regression. Can you reproduce this if you use RubyGems 3.5.23?

**Comment by deivid-rodriguez** [comment]
I just verified the problem and confirmed that downgrading RubyGems fixes it. I'm going to revert the offending commit and release new versions.

**Comment by mattbrictson** [comment]
Thanks for the quick fix! I confirmed that downgrading to rubygems 3.5.23 fixes the problem. I'll test again once 3.6.2 is released.

**Comment by mattbrictson** [comment]
Yes, I just confirmed that 3.6.2 fixes the issue. Thanks!

**Comment by deivid-rodriguez** [comment]
Thanks for confirming!

**Comment by skatkov** [comment]
Ran into a similar issue and can confirm that 3.6.2 fixed it.

**Comment by chaitanyag1-c** [comment]
I ran into the similar issue ,Here's what worked for me.

You can force to set platform manually while building.

Update the .gemspec file

- Add this line before Gem::Specification.new do |spec|

```
require 'rubygems/package'
Gem::Platform::RUBY
```

- Then inside the Gem::Specification block, add:

`spec.platform = Gem::Platform::RUBY`
