### ISSUE TITLE
Gemspecs missing from S3

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#581]
There are some gems whose gemspecs are not available from S3, including (but possibly not limited to):

  - http://production.s3.rubygems.org/quick/Marshal.4.8/rroonga-3.0.3-x86-mingw32.gemspec.rz
  - http://production.s3.rubygems.org/quick/Marshal.4.8/sauce-connect-3.0.1.gemspec.rz
  - http://production.s3.rubygems.org/quick/Marshal.4.8/selenium-connect-1.9.2.gemspec.rz

Any theories as to why?

**Comment by arthurnn** [comment]
Problem here is that the `Pusher` is not resilient, so if S3 have problems, or redis, or the delayed-job we would have inconsistent data between the database , s3 (gemspec and index). I think the solution is to only mark the version as indexed, when we are sure everything is in place. I will work on that this weekend, and write a lots of functional/integration tests to try to cover most of the failure cases.

**Comment by simi** [comment]
@arthurnn was this fixed?

**Comment by dwradcliffe** [comment]
I'm going to close this. I believe we have removed any missing gems at this point.
