### ISSUE TITLE
Cannot gem push (HTTP Basic: Access Denied)

### ISSUE THREAD

**Issue by JuanitoFatas** [rubygems/rubygems.org#583]
I'm using Ruby 2.0.0-p247 with Gem 2.1.0.

First I `curl` my credential via:

    curl -u JuanitoFatas https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
    Enter host password for user 'JuanitoFatas': *******

I got my `:rubygems_api_key`. It's okay. Then I tried to release my gem:

    rake release

But it says:

```
Pushing gem to https://rubygems.org...
Access Denied. Please sign up for an account at http://rubygems.org
/Users/Mac/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:150:in `sh'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:84:in `rubygem_push'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:78:in `release_gem'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:50:in `block in install'
```

Then I `rm` my credentials, try to do it manually:

```bash
$ gem build mygemname.gemspec
$ gem push mygemname.gemspec
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up
   Email:   katehuang0320@gmail.com
Password:
HTTP Basic: Access denied.
```

I checked that I could login on website (https://rubygems.org/) by either using my `username` or `email`.

In sum:

My key authentication is failed (Access denied). I have tried reset my key. Also http authentication is also failed (Access denied).

Am I missing something? When I reset my API key, I see there is a flash message said I need to add something to `.gemrc` but did not know what should I add. Thank you!

**Comment by arthurnn** [comment]
I am clueless on how to simulate this. Thats what I tried
- ruby 1.9.3p448 / rubygem 2.1.0 / without `~/.gem/credentials` /  with a password that contains a '*'

And it all worked, this is my logs:
```
[arthurnn@ralph blankblank]$ ruby -v
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin14.0.0]
[arthurnn@ralph blankblank]$ gem --version
2.1.0
[arthurnn@ralph blankblank]$ gem push --host http://127.0.0.1:3000 -V --backtrace --debug --verbose pkg/blankblank-0.0.5.gem
Exception `OptionParser::InvalidOption' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1542 - invalid option: no-ri
Exception `OptionParser::InvalidOption' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1356 - invalid option: --no-ri
Exception `OptionParser::InvalidOption' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1542 - invalid option: no-rdoc
Exception `OptionParser::InvalidOption' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/optparse.rb:1356 - invalid option: --no-rdoc
Enter your http://127.0.0.1:3000 credentials.
Don't have an account yet? Create one at http://127.0.0.1:3000/sign_up
   Email:   arthurnn@gmail.com
Password:
GET http://127.0.0.1:3000/api/v1/api_key
Exception `Errno::EAGAIN' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:141 - Resource temporarily unavailable - read would block
200 OK
Signed in.
Exception `ArgumentError' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/psych/scalar_scanner.rb:91 - invalid value for Integer(): "4ad15bc2817b447a774386851ed15ce5"
Exception `Errno::EEXIST' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/fileutils.rb:247 - File exists - /Users/arthurnn/.gem/specs/rubygems.org%443
HEAD https://rubygems.org/latest_specs.4.8.gz
Exception `OpenSSL::SSL::SSLError' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:174 - read would block
302 Moved Temporarily
HEAD https://s3.amazonaws.com/production.s3.rubygems.org/latest_specs.4.8.gz
Exception `OpenSSL::SSL::SSLError' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:174 - read would block
304 Not Modified
Pushing gem to http://127.0.0.1:3000...
POST http://127.0.0.1:3000/api/v1/gems
Exception `Errno::EAGAIN' at /Users/arthurnn/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:141 - Resource temporarily unavailable - read would block
200 OK
Successfully registered gem: blankblank (0.0.5)
```

any help on simulating this would be wonderful, otherwise I cannot fix it.. thanks

**Comment by LouisSayers** [comment]
An idea: It might be on the update of the gem - did you try push after it's already created?

**Comment by gregtaylor99** [comment]
All - this is a reported issue that was driving me crazy until I found the solution reported here  - 
https://github.com/geminabox/geminabox/issues/153

You have to add a ~/.gems/credentials file with a blank ruby gems.org API key - it fixed my issues 100%

**Comment by qrush** [comment]
This has become a big help thread. If you are having trouble with your account, please open an issue at help.rubygems.org and we'll be happy to help you figure it out! Closing this issue for now since it's not related directly to the code/data/etc at the rubygems.org rails app.

**Comment by zotherstupidguy** [comment]
Faced similar problems today trying to update a gem. and help.rubygems.org gives 404

**Comment by joegiralt** [comment]
I Had the same issue, I had this substring '##' in my password, and it kept denying me access.

**Comment by rokkuran** [comment]
On windows: I had this issue when using git bash, problem solved when switching to cmd.

**Comment by swapnilmdoshi** [comment]
gem update --system worked for me.
