### ISSUE TITLE
Add a Report link to all gems

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems.org#608]
Add a simple "Report" link to the show view for gems, which simply links to `mailto:abuse@rubygems.org` or to https://help.rubygems.org/.

**Comment by bradly** [comment]
@dwradcliffe I took care of this in #912 so this should be good to close. Thanks!

**Comment by arthurnn** [comment]
Thanks @bradly

**Comment by dwradcliffe** [comment]
Thanks!!

On Monday, March 30, 2015, Arthur Nogueira Neves <notifications@github.com>
wrote:

> Closed #608 <https://github.com/rubygems/rubygems.org/issues/608>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/issues/608#event-268992826>.
>


-- 
---
David Radcliffe
radcliffe.david@gmail.com
dwradcliffe.com
