### ISSUE TITLE
Connect handshake intermittent failures during past few months

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems.org#615]
Some time in the past few months (or weeks, unsure) we started to get reports from JRuby users that they were having intermittent failures fetching gems from RubyGems.org. The issue manifests itself as a low-level SSL exception of "bad_record_mac" or "bad record mac", usually during the first connection handshake to fetch a gem.

I have been able to reproduce this on JRuby versions as far back as JRuby 1.7.2, which was released last winter. Here's my command line:

```
jruby -ropen-uri -e "Thread.abort_on_exception = true ; 10.times { Thread.new { loop { open('https://rubygems.org/gems/dicks-0.03.gem').read; p :ok } } }; sleep"
```

It takes dozens or hundreds of requests to fail, but eventually fails on every version of JRuby I have tried.

If I switch to http:// it works fine.

If I upload the gem to s3 and fetch from there, it works fine.

See also #613 which may be related.

Notes from my exploration of the problem:
- Some posts indicated it was a buggy version of OpensSSL
- Some posts said it was a problem where Java's secure socket logic was using a different protocol for SSL than the server wanted (for example, choosing TLS instead of SSLv3), especially when the server only supported SSLv3.
- Most information points to this being a problem during handshaking.
- Some posts seem to indicate this could be some sort of race condition in OpenSSL, but there's not a lot of evidence.
- There's at least one bug filed against Ruby 1.9.2 reporting the same issue against a server that only supports SSLv3.
- There's an old issue filed against JRuby for a server that only supports SSLv3.

**Comment by jordansissel** [comment]
An update for posterity - I see this error frequently on Java 1.7.0_45 on OSX, but if I upgrade to Java 1.7.0_75 the problem appears to be resolved.
