### ISSUE TITLE
Include gem checksum in versions template

### ISSUE THREAD

**Issue by bf4** [rubygems/rubygems.org#628]
Let's make it easier for end-users to verify a gem checksum.

What are your thoughts of calculating and surfacing a SHA512 checksum of gems on rubygems.org (next to the gem version)?

Calculating and verifying SHA512 checksums is now included in the RubyGems security guide http://guides.rubygems.org/security/#building_gems

It would make it easier for some end users to compare the checksum of their downloaded gem to the expected checksum, particularly as most gem authors don't provide this service themselves.

Sure, it's not perfect, but I think it would be better than the current status, esp. until everyone is using [TUF](https://github.com/rubygems/rubygems/pull/719).

If there's interest, I'm happy to work on this as a PR

I would think that calculating the checksum would be some async part of pushing a gem (from client or server side?) and also optionally on demand

- [original google group proposal](https://groups.google.com/d/msg/rubygems-org/2aluSzFd-9M/y9nEpW9LIl4J)
- Where the checksum would be surfaced, if available https://github.com/rubygems/rubygems.org/tree/master/app/views/versions

**Comment by bradly** [comment]
@indirect @bf4 Is this issue resolved by #872?

**Comment by arthurnn** [comment]
yeah. now we have sha256 in all gem versions.
thanks all.

**Comment by tknerr** [comment]
@bf4 @indirect @arthurnn now that the SHA256 sums are available on https://rubygems.org, are they automatically checked upon `gem install` or `bundle install`?

I found no references that this would be the case and the security guide still explains how to manually verify the SHA sum:
http://guides.rubygems.org/security/#using-gems

Quoting @indirect  from above, which I fully agree to:
> That said, I think that expecting anyone to manually check checksums is foisting security off on the user, which is (in practice) the same as not having it. 

Scratching my head whether there is really no integrated process to verifies the checksum upon installation, now that they are readily available on rubygems.org...

**Comment by segiddins** [comment]
Bundler 1.14 checks them, if it has downloaded the metadata from the new index

**Comment by tknerr** [comment]
@segiddins nice, thanks for quick reply!

So the current behaviour for `gem install` is to not verify them, right?

**Comment by segiddins** [comment]
Correct, since gem install does not yet use the new index

**Comment by tknerr** [comment]
Thanks @segiddins !
