### ISSUE TITLE
Versioning scheme doesn't comply with SemVer requirements.

### ISSUE THREAD

**Issue by arbox** [rubygems/rubygems.org#639]
We reed in the SemVer definition:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. 

But the hyphen is not allowed in the GemSpec definitions giving us:

```
Invalid gemspec in [abc.gemspec]: Malformed version number string x.y.z-rc1
ERROR:  Error loading gemspec. Aborting.
```

Affects:

```
$ gem -v
$ 2.0.14
```

**Comment by perlun** [comment]
For reference, some of the background to this can be found here: https://github.com/rubygems/rubygems/issues/592
