### ISSUE TITLE
production data dump

### ISSUE THREAD

**Issue by moredip** [rubygems/rubygems.org#649]
Is there any way to get access to a reasonably recent production database dump for rubygems.org?

I'd like to play with loading data about gems and their dependencies into a graph DB to do some visualization and analysis. Seems an easy way to do that would be to take the raw data from a production dump and extract the dependency information from there. I looked around to see if there was such a dump available, but couldn't find anything.

**Comment by arthurnn** [comment]
https://rubygems.org/pages/data done by @dwradcliffe
