### ISSUE TITLE
After Signing In, visiting via HTTP will sign you out

### ISSUE THREAD

**Issue by knappe** [rubygems/rubygems.org#680]
To duplicate:
- Sign in via the default login (https://rubygems.org/sign_in)
- You'll be forwarded to https://rubygems.org/dashboard
- Manually remove the 'https://' from the address, ala rubygems.org/dashboard, and hit enter

You should now be **signed out** and forwarded back to https://rubygems.org/.

While unlikely to happen in production, you can duplicate this in development and it is *terribly* confusing to someone just coming into the project.  I struggled with this when trying to work on the profile page because it would constantly sign you out.

Here is what fixes this problem and allows you to **stay** logged in while working in development.

````
knappe@Tylers-MacBook-Pro-2:~/git_repos/rubygems.org$ git diff
diff --git a/config/initializers/clearance.rb b/config/initializers/clearance.rb
index e4695dd..b440bf2 100644
--- a/config/initializers/clearance.rb
+++ b/config/initializers/clearance.rb
@@ -1,7 +1,7 @@
 unless Rails.env.maintenance?
   Clearance.configure do |config|
     config.mailer_sender = "donotreply@rubygems.org"
-    config.secure_cookie = true
+    config.secure_cookie = false
     config.password_strategy = Clearance::PasswordStrategies::BCryptMigrationFromSHA1
   end
 end
knappe@Tylers-MacBook-Pro-2:~/git_repos/rubygems.org$
````

Here is the bug I believe is creating the problem:

https://github.com/thoughtbot/clearance/issues/338
https://github.com/thoughtbot/clearance/pull/347

**Comment by arthurnn** [comment]
this should be open, as it is not fixed yet.. after https://github.com/thoughtbot/clearance/commit/3a1244346524d9610105c2e5411bb759c6c05869 is released in 1.6.1 this should be fixed.

**Comment by derekprior** [comment]
Clearance 1.6.1 is out.

**Comment by arthurnn** [comment]
Solved. and deployed.
