### ISSUE TITLE
Feature: Checksums in API queries

### ISSUE THREAD

**Issue by cstrahan** [rubygems/rubygems.org#712]
As a package manager for [NixOS](nixos.org), I need hashes (either md5 or sha256; preferably the latter, if not both) for all *.gem files (NixOS packages are deterministic, so we can't fetch a gem without the hash). In the meantime, the maintainers can scrape rubygems.org and compute the hashes; of course, that would be quite a waste of bandwidth and compute resources for both ends, so ideally RubyGems.org would store the hashes once and provide them via the API.

**Comment by bradly** [comment]
@indirect @skottler I believe I took care of this with #911 and this can be closed. Thanks!

**Comment by skottler** [comment]
Awesome work @bradly! Thanks.
