### ISSUE TITLE
rubygems.org api should make link to code repository read from gem-spec available

### ISSUE THREAD

**Issue by fwolfst** [rubygems/rubygems.org#718]
I proposed a new Gem::Specification key to specify a gems source code location in
rubygems/rubygems#1007 ("Gem::Specification should allow to specify source code repository/location").

Eric Hodel suggested using an agreed-at key for the existing "metadata".

It follows a slightly adapted mail to the mailing list (https://groups.google.com/forum/#!topic/rubygems-org/NMzNWYwLAVM) with details

As a Gem-Maintainer I would like to be able to specify the location to the repository a gem was created from (lets assume github for now), in the gemspec.
As a potential contributor or consumer of a gem I have deep interest in the repository location; maybe a bug was fixed already or a commit message explains implementation details not found in documentation or code comments. Also, I might want to work on it without having to search the installed code, e.g. in ~/.rvm/gems/.... .

The rubygems.org web-interface allows specification of a "Source Code"-link. But in contrast to the "Home Page" link it is not backed by the rubygems specification.

I created an issue (https://github.com/rubygems/rubygems/issues/1007) for it, where Eric Hodel suggested to use the meta-data field in the Gem-Specification.

I see following minor difficulties:
1) Agree on a key for the metadata tag (Eric saw that too ;) )
2) Handle cases where the source code link was set "by hand" via the rubygems.org interface
3) Deal with forks and repository moves

Without much brainpower spent on this, I would propose

1) spec.metadata[:origin_repository_url] = "http://github.." # or even "svn+ssh:///..."
2)+3) be defensive: if it is possible to find out if an existing source code link was set by hand or automatically, prefer by hand.
    if is not possible, add a new link type to link-set "source code repository".
3) forks that result in gem publication should update the gemspec anyway..

Michał Papis responded to my mail with "why not spec.metadata[:sources_url] = "http://github.." - or at least drop the "origin" part"

Enjoy
Felix

**Comment by kbrock** [comment]
@fwolfst / @mpapis Turns out [rubygem.rb][] does define these keys. I changed the keys in the PR. (You probably already saw this over there, but I wanted it here for completeness.)

- `homepage_uri`
- `wiki_uri`
- `documentation_uri`
- `mailing_list_uri`
- `source_code_uri`
- `bug_tracker_uri`

aside: my fingers are crossed that `changelog_uri` (per #728) gets into there as well.

[rubygem.rb]: https://github.com/rubygems/rubygems.org/blob/63d43b660aa8430320c0db430b15e2def306e3ac/app/models/rubygem.rb#L162-L167

**Comment by qrush** [comment]
Looks like this has fizzled a little. I just remarked on #906 that I would love to see a proposal...and here it is! cc @AaronLasseigne

#724 is a pretty beefy PR. I'll try to work through it too.

**Comment by kbrock** [comment]
There are a number of URIs in the rest api. Thought we could just use those keys to pull out of the metadata and fall back to the links table. After a while, just dump the links table and just use the metadata.

This is stalled. Not sure why as I didn't think it introduced anything new or revolutionary. If you could share where you want it to go I can pick back up.

**Comment by qrush** [comment]
It's not anything new or revolutionary, it's just we haven't had a lot of bandwidth lately to handle big new features. Volunteer-run OSS...FTW? :confounded: Thanks for your patience @kbrock. I'm going to try and review the PRs over the next few days.

**Comment by kbrock** [comment]
@qrush I guess I was complaining. Sorry.

**Comment by sonalkr132** [comment]
Closed by #1815

Check [guide](https://guides.rubygems.org/specification-reference/#metadata) for how to.
