### ISSUE TITLE
Gems present in index but not found in API

### ISSUE THREAD

**Issue by bappelt** [rubygems/rubygems.org#730]
I have run into some gems that I can find and download at rubygems.org or in the index, but API calls tell me the gem cannot be found. For example:

https://rubygems.org/api/v1/gems/aws-tools.json

returns "This gem does not exist.", but it is here: https://rubygems.org/gems/aws-tools

similar results for gtl-sluggable, mailosaur, ruby-daj, and safenav

**Comment by maclover7** [comment]
Issue appears to have been resolved because all gems listed in the original issue scenario are all rendering normally.

**Comment by dwradcliffe** [comment]
We've updated things and fixed other bugs so maybe this was related to one of those things. Glad it's fixed now!
