### ISSUE TITLE
Font renders weird on Linux

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems.org#732]
When rendering normal text, the font renders oddly under Linux. Tested with Fedora 20 Linux.

Note the difference between `S` and `N` characters.

### Firefox 33.1

![Example 1](http://i.imgur.com/kfMsYR3.png)
![Example 2](http://i.imgur.com/eQ97H3q.png)

### Chrome (Stable) 39.0

![Example 1](http://i.imgur.com/Pz3up4q.png)
![Example 2](http://i.imgur.com/8GBxCRZ.png)

**Comment by simi** [comment]
Is this render expected?

![screenshot-rubygems org 2015-02-18 00-58-57](https://cloud.githubusercontent.com/assets/193936/6239955/8d1671da-b709-11e4-8ec8-d5ae0e48db13.png)

**Comment by postmodern** [comment]
@simi hinting looks odd on the "e" and "total downloads" looks inconsistent.

**Comment by qrush** [comment]
Looks related to #785. Is this still happening, or maybe Typekit has updated the font? :pray:

**Comment by simi** [comment]
Last deploy fixed this for me.

**Comment by dwradcliffe** [comment]
@postmodern Can you take a look now?

**Comment by postmodern** [comment]
@dwradcliffe on Firefox 42.0 the font looks muuuuch better! ![Screenshot](http://i.imgur.com/Vgyiu4u.png)

**Comment by nateberkopec** [comment]
:tada: woop woop!
