### ISSUE TITLE
Description escaping changed

### ISSUE THREAD

**Issue by derekprior** [rubygems/rubygems.org#740]
The `&` character is allowed in gemspecs but is escaped to `&amp;` when the description or summary is output.

See https://rubygems.org/gems/clearance

**Comment by olivierlacan** [comment]
Well. If we don't trust user input why is the `&` HTML entity from [kaminari's description](https://github.com/amatsuda/kaminari/blob/master/kaminari.gemspec#L13) escaped on the search index and not on the gem show page?

![image](https://cloud.githubusercontent.com/assets/65950/6096540/437bd0f2-af97-11e4-9a13-99aa78872c06.png)

![image](https://cloud.githubusercontent.com/assets/65950/6096542/4ae215c2-af97-11e4-90d2-a9d57616e5fe.png)

- gem search: https://rubygems.org/search?utf8=%E2%9C%93&query=kaminari
- gem show: https://rubygems.org/gems/kaminari
