### ISSUE TITLE
Base64-encoded images on error pages make them slow

### ISSUE THREAD

**Issue by sferik** [rubygems/rubygems.org#769]
The [404](http://rubygems.org/404), [500](http://rubygems.org/500), and [other](https://github.com/rubygems/rubygems.org/tree/master/public) error pages include inlined, base64-encoded PNG images that measure over 200 KB in size. Because these images are inlined, they block the page from loading, creating a rather slow user experience (see timeline screenshot timeline below). If we trust the application server to serve these static HTML pages from `public`, can’t we also trust it to serve image assets from that directory? This would have the additional benefit of making those images cacheable. I’m happy to make this change if everyone agrees it is the correct path forward.

![screen shot 2014-11-26 at 23 16 31](https://cloud.githubusercontent.com/assets/10308/5209732/5db0b686-75c2-11e4-871f-cff3054d02ed.png)

**Comment by simi** [comment]
@dwradcliffe so is this possible?

**Comment by qrush** [comment]
+1 for not base64 encoding images like this that will rarely change. We can just throw them on S3/CF if we need to.

**Comment by sferik** [comment]
> I really don't get the pirate theme on these pages. Am I the only one?

I think the reference is gems are like hidden treasure.

**Comment by dwradcliffe** [comment]
I can't remember exactly what I wanted to check on. I'm totally ok moving these images to s3 though. :+1:
