### ISSUE TITLE
Gem page layout change: links right below versions, dev dependencies under runtime ones

### ISSUE THREAD

**Issue by vassilevsky** [rubygems/rubygems.org#770]
Hello :)

I took a screenshot of a gem page and edited it:

![gem_page_vertical_dependencies](https://cloud.githubusercontent.com/assets/252023/5216818/ed9dd774-7649-11e4-860f-30cf69f3334b.png)

I think this layout lets me get to the important info quicker and with less confusion.

* In order to get to the gem's homepage or GitHub page, I just need to look down, not all the way right and down
* All dependencies are listed in one column. Development dependencies are still separated.

What do you think?

I can make actual changes if you like it.

**Comment by qrush** [comment]
So this design has simmered for quite a few months now. I'm pretty happy with it. Showing the ruby version is already in and done. If there's something more concrete let's crack open a new issue and make it happen.
