### ISSUE TITLE
Visual inconsistency with gemfile/install text boxes

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems.org#778]
### FireFox 33.1

![has scroll bars](http://i.imgur.com/SfjPu0w.png)

### Chrome Stable

![text is hidden simply hidden](http://i.imgur.com/YK52Q0H.png)

I recommend using [BrowserStack](http://www.browserstack.com/) to test against both FireFox and Chrome, on a variety of display dimensions.

**Comment by buren** [comment]
I tested this on Chrome 40 and Firefox 35 on borh Windows 7 (using browserstack) & OSX 10.10 and __they look, to me, consistent__ (disregarding the resolution difference):

## OSX

#### Firefox 35

![firefox-osx-rubygems](https://cloud.githubusercontent.com/assets/922411/6992857/fbd0ae4c-dae0-11e4-8adc-9444d5fb646a.png)

#### Chrome 40

![chrome-osx-rubygems](https://cloud.githubusercontent.com/assets/922411/6992859/03fd9c74-dae1-11e4-982d-cdea73af9a5f.png)

## Windows 7 (BrowserStack)

#### Firefox 35

![firefox-win7-rubygems](https://cloud.githubusercontent.com/assets/922411/6992863/13710ace-dae1-11e4-9f52-6970023845f0.png)

#### Chrome

![chrome-win7-rubygems](https://cloud.githubusercontent.com/assets/922411/6992865/179d6ebc-dae1-11e4-93ec-d83d413b0b55.png)

**Comment by knappe** [comment]
@postmodern Can you please double check you findings?

I'm also not seeing any discrepancies in Chrome vs Firefox on OS X, minus the lack of the copy to clipboard 'widget' in Firefox.

Firefox 38.0.1:
![screen shot 2015-05-20 at 9 43 12 pm](https://cloud.githubusercontent.com/assets/138048/7741197/522f37be-ff39-11e4-9a15-e398853e9442.png)

Chrome 43.0.2357.65 (64-bit):
![screen shot 2015-05-20 at 9 44 32 pm](https://cloud.githubusercontent.com/assets/138048/7741211/7906a318-ff39-11e4-9adc-ca23cac58918.png)

**Comment by postmodern** [comment]
Tested on a fresh Fedora 21 install.

### Firefox 38 (stable)

![Firefox 38](http://i.imgur.com/Y94pCZ2.png)

### Chrome 43 (stable)

![Chrome 43](http://i.imgur.com/nL7ZH1w.png)

Maybe it has something to do with my resolution (1366x768)?

**Comment by knappe** [comment]
It looks like the issue with the scrollbars has been fixed which, at least in my eyes, was the biggest issue.

@postmodern are there any issues, besides what looks like some font differences?

**Comment by postmodern** [comment]
Only other difference are the missing copy/paste icons in Firefox. Chrome correctly renders those. I'm guessing it's a silly margin/padding issue.

**Comment by knappe** [comment]
They're hidden.  My guess is that they're disabled in FF because they rely on flash which is not installed.  Hiding it when disabled would be the best course of action in my eyes.  You can double check if flash is installed: http://isflashinstalled.com/.
![screen shot 2015-05-20 at 10 21 06 pm](https://cloud.githubusercontent.com/assets/138048/7741620/96189970-ff3e-11e4-8e68-5e5fc29e18cb.png)

**Comment by qrush** [comment]
Is this still happening?

**Comment by knappe** [comment]
@qrush Yes.

Firefox 38.0.5 without Flash installed:
<img width="426" alt="screen shot 2015-07-06 at 11 01 59 pm" src="https://cloud.githubusercontent.com/assets/138048/8539010/0b059db4-2433-11e5-9a66-9a6ed9111edd.png">

I would say this is expected behavior and not a bug.

**Comment by knappe** [comment]
@postmodern @qrush We have a workaround for [zeroclipboard](https://github.com/rubygems/rubygems.org/blob/78353a6b2a1e2129ff8a00f316cd4987d3f4649e/lib/assets/javascripts/ZeroClipboard.js#L3), if we use [clipboard.js](https://github.com/zenorocha/clipboard.js/), _but_, the reason zeroclipboard uses flash is to avoid [clipboard poisoning](https://github.com/zeroclipboard/zeroclipboard#user-interaction-required).  If we don't think that is a risk, we could swap to clipboard.js and avoid the need to have flash installed to copy to clipboard.

Optionally, we could use the html5 solution, which does appear to be widely supported. http://caniuse.com/#feat=document-execcommand

http://updates.html5rocks.com/2015/04/cut-and-copy-commands

Personally, I do not like the idea of having our users needing to install flash to use the site fully.  Flash has a critical vulnerability almost once a month. https://helpx.adobe.com/security.html#flashplayer

**Comment by jvanbaarsen** [comment]
@knappe I did investigate clipboard.js #1072 . Problem with that is that it doesn't work in safari. We decided to put that on hold for now.

**Comment by knappe** [comment]
Gotcha.  Do we have A) statistics on browser percentages and B) an idea of how many users don't have flash installed (I imagine this is actually really hard to determine).  I'd hazard a guess that the number of users without flash installed, because of the number of security vulnerabilities (https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#tbm=nws&q=uninstall+adobe+flash), is greater than the percentage of users using Safari.

**Comment by simi** [comment]
I think it will be worth it to hide copy buttons when they're not supported by browser (Sefari) and switch to non-flash solution anyway.

**Comment by jvanbaarsen** [comment]
@qrush Is there anyway to get those statistics at this point? Of not would you be open to a PR implementing a way to gather those numbers?

**Comment by arthurnn** [comment]
I would be interested to know what GitHub uses. Maybe we should do the same.

**Comment by jvanbaarsen** [comment]
@arthurnn When looking at the code it seems like they use zeroclipboard as well. But they don't have any flash on the page. So maybe they created their own version? I also can't seem to find an option in zeroclipboard to make it only use JS.

**Comment by dgraham** [comment]
We use the zeroclipboard Flash fallback in IE and Safari and [native copy-to-clipboard](https://gist.github.com/dgraham/cda03d4a4a528d2b4d17) JavaScript in Edge, Chrome, and Firefox.

<3

**Comment by jvanbaarsen** [comment]
@dgraham Thanks for explaining! I'll take another look at this!

**Comment by arthurnn** [comment]
We moved to clipboard js. I guess this should be fixed now. Please re-open if not.
