### ISSUE TITLE
Font rendering issues on Windows

### ISSUE THREAD

**Issue by arteezy** [rubygems/rubygems.org#785]
Letters `i` and `j` are lacking space between the dot and the actual letter. In case of `i` it's impossible to distinguish it from `l`, which I think is a serious bug. I attached a screenshot, where `rails` looks exaclty like `ralls`

![win_font_bug](https://cloud.githubusercontent.com/assets/192247/5297304/9975588c-7bd7-11e4-9a17-f3fbe2bf0e3e.png)

Tested on Chrome and Firefox; Win 8.1 and Win 10

I think `Aktiv Grotesk Std` is not very friendly font for Windows, maybe it requires some more font-weight tuning (bold/xbold) to look correctly across all platforms

**Comment by qrush** [comment]
Yikes. Is this still happening?

**Comment by arteezy** [comment]
Yes it is.

**Comment by nateberkopec** [comment]
Since we just use Arial here now, this is fixed. Confirmed on my local Windows PC.
