### ISSUE TITLE
gem push errors are html

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems.org#791]
A `gem push` error results in the html 500 error returned into the terminal.

**Comment by qrush** [comment]
Closing until we see something repeatable.

**Comment by dwradcliffe** [comment]
I was able to get a failing test. Looks like we require redis for gem push to work. Apparently we store version information in redis too?

https://github.com/rubygems/rubygems.org/blob/d41469d2e47517fd0a1d6554ef5e40f5188e8d6b/app/models/version.rb#L317-L320

Seems to track back to this commit: https://github.com/rubygems/rubygems.org/commit/478de56a06be1513061820989affadf9829d99c0

**Comment by dwradcliffe** [comment]
Here's another case of this: https://github.com/rubygems/rubygems/issues/1564
