### ISSUE TITLE
rendering issue with the navigation bar (Safari)

### ISSUE THREAD

**Issue by mattwarrenrnp** [rubygems/rubygems.org#797]
![9aa39fe3-2ef5-40ca-bb4e-5821c2023c14-1559-00001365bc800f5d](https://cloud.githubusercontent.com/assets/5222520/5531208/42303886-89e6-11e4-8151-1abf6747fe39.gif)

my username and photo wrapped down to new line (can't see username white on white), and dropdown menu placement is off.

This is on Safari 8.0.3

**Comment by arthurnn** [comment]
not sure if this was fixed already, because it works fine on Safari 8.0.3 in my machine.
