### ISSUE TITLE
Occasionally redirected to a 404 when signing in

### ISSUE THREAD

**Issue by knappe** [rubygems/rubygems.org#814]
I see a 404 thrown and end up on `https://rubygems.org/session` when I sign in.  I'll see if I dig into this further and get more details.

**Comment by arthurnn** [comment]
Finally got how to simulate this... it happens when you go to http://rubygems.org/sign_in (see this is http, and not https) and then submit the form, it will log you in, and 302 to https://rubygems.org/session . will work in a fix for it.

**Comment by carstengehling** [comment]
Ouch! Don't know how you host this, but I would probably fix this in the webservice in front of Rails. I.e. make sure that all http requests are redirected immediately to https. Instead of doing anything in the Rails app.
