### ISSUE TITLE
listing dependents 

### ISSUE THREAD

**Issue by shime** [rubygems/rubygems.org#836]
I love how NPM lists dependents for specific module ([example for minimist](https://www.npmjs.com/browse/depended/minimist)). I would love to see something similar on Rubygems.

Would you accept a PR in that direction?

**Comment by arthurnn** [comment]
I dont know why I would use such functionality to be honest. But, other people might use it, as we have those in the database I think adding it is fine. Send the PR I would say.
thanks

**Comment by simi** [comment]
I think this good idea. I'm watching every dependency before adding gem into project and this will be useful.

@shime are you able to send PR? I can do that also.

**Comment by shime** [comment]
@simi I'll push something soon.

**Comment by arthurnn** [comment]
bundler-api has an endpoint for that, as far as I can tell. And thats what they are using for the new index. So we might wanna unify those things/ ?!? 
cc @indirect

**Comment by indirect** [comment]
@arthurnn Bundler API does not have an endpoint for finding dependents, only for finding dependencies.

**Comment by jimmycuadra** [comment]
There's already an API for this: http://www.jimmycuadra.com/posts/how-lita-io-uses-the-rubygems-and-rubygems-org-apis

**Comment by farukaydin** [comment]
@shime if you don't have enough time to contribute anymore, I'd like to work on it.

**Comment by qrush** [comment]
The `reverse_dependencies` endpoint definitely needs documentation. http://guides.rubygems.org/rubygems-org-api/

**Comment by vassilevsky** [comment]
VersionEye (external service) has such a page. For example:

https://www.versioneye.com/ruby/rake/references

**Comment by arthurnn** [comment]
@farukaydin fell free to add the docs, and CC me on the PR.. thanks :heart:

**Comment by farukaydin** [comment]
@arthurnn It's already done. https://github.com/rubygems/guides/pull/127 :heart: :yellow_heart: :blue_heart:

**Comment by arthurnn** [comment]
LOL

thanks
