### ISSUE TITLE
Cannot edit sidebar info links

### ISSUE THREAD

**Issue by drbrain** [rubygems/rubygems.org#842]
Steps to reproduce:

1. Go to a gem you own

1. Click edit in the sidebar

1. Change the documentation URL (to, say http://example)

1. Click Update

1. Hover the Documentation URL in the sidebar

Expected results:

Go to new URL

Actual results

The old URL is used.

**Comment by NARKOZ** [comment]
+1, same issue. Also, is there any way to update links via API?
