### ISSUE TITLE
Search in discription as well

### ISSUE THREAD

**Issue by dennisvandehoef** [rubygems/rubygems.org#847]
To make it more easy finding the gem that does what you want. It might be good that we search in the description as well.

A simple example, look at the gem unf (https://rubygems.org/gems/unf)
The description is short, but has the keywords i would like to be able to seach with, but unable to find it with: https://rubygems.org/search?utf8=%E2%9C%93&query=Unicode+Form

**Comment by dwradcliffe** [comment]
Yep, our search is pretty bad. It's on our list for 2015 and hopefully we'll have something to show soon. :)
