### ISSUE TITLE
Invalid Download Count

### ISSUE THREAD

**Issue by LouHenryAlvarez** [rubygems/rubygems.org#860]
rubygems.org is not tracking gem installs correctly.  I have had several of my friends install gems while watching the page for the gem without it updating at all.

**Comment by evanphx** [comment]
Do you have an example of a gem that you don't see the count updating?

**Comment by LouHenryAlvarez** [comment]
Hi,

Yes, the example I've been using is Jackbox.

**Comment by evanphx** [comment]
I just tested it against jackboot 0.9.5.6 and it seems to work fine. What are you seeing?

**Comment by LouHenryAlvarez** [comment]
I'll try it right now!

Well, it was 102 before: gem install jackbox, and it's still 102 now

**Comment by evanphx** [comment]
What gem server are you using?

**Comment by evanphx** [comment]
Because if I use `curl -I https://rubygems.org/gems/jackbox-0.9.5.6.gem` then the download count goes up. Rubygems should be hitting that to download the gem unless you've got some other gem server configured.

**Comment by LouHenryAlvarez** [comment]
This is the output of gem env:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [x86_64-darwin13.1.0]
  - INSTALLATION DIRECTORY: /Users/seamon/.rvm/gems/ruby-2.0.0-p481@dev
  - RUBY EXECUTABLE: /Users/seamon/.rvm/rubies/ruby-2.0.0-p481/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/seamon/.rvm/gems/ruby-2.0.0-p481@dev/bin
  - SPEC CACHE DIRECTORY: /Users/seamon/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/seamon/.rvm/gems/ruby-2.0.0-p481@dev
     - /Users/seamon/.rvm/gems/ruby-2.0.0-p481@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/seamon/.rvm/gems/ruby-2.0.0-p481@dev/bin
     - /Users/seamon/.rvm/gems/ruby-2.0.0-p481@global/bin
     - /Users/seamon/.rvm/rubies/ruby-2.0.0-p481/bin
     - /Users/seamon/.rvm/bin
     - .
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/X11/bin
     - /Applications/RubyEncoder.app/Contents/MacOS
➜

**Comment by evanphx** [comment]
Well the download counter of your gem has jump to 160 so I'd say it's working.

**Comment by LouHenryAlvarez** [comment]
That's odd.  What in the...

What do you think the problem, could have been?

**Comment by LouHenryAlvarez** [comment]
Tried it again.  Nope!  Same problem...

**Comment by evanphx** [comment]
This is clearly a problem in your environment. Can you run 'gem install -V -d  jackbox' and gist the output?

**Comment by LouHenryAlvarez** [comment]
Here is the gist: https://gist.github.com/LouHenryAlvarez/c2e023354df4bc0b98d1

But, why would my environment cause the count to jump 60 points in a matter of minutes when it hasn't changed all day.

**Comment by evanphx** [comment]
I assume people were downloading it. The count is definitely live, I tested it. It's not incrementing for you because the gem is in your cache dir. Add "-i temp" and I think you'll see it downloaded.

**Comment by LouHenryAlvarez** [comment]
Hmm, no because a couple of my friends tried on different machines with the same result, unless it's in their cache too...

I'll keep on eye on it.

Thanks dude.
