### ISSUE TITLE
Update blog style

### ISSUE THREAD

**Issue by arthurnn** [rubygems/rubygems.org#863]
https://github.com/rubygems/rubygems.github.com/ (blog) needs to use the new style from rubygems.org .

**Comment by davydovanton** [comment]
ok, i can try this :sweat_smile:

**Comment by acacheung** [comment]
hey! @arthurnn @davydovanton i did this when we redesigned the whole site back in november

**Comment by davydovanton** [comment]
@acacheung hello! :smiley: I was thinking that @arthurnn wanted update navbar and footer like in main site

**Comment by dwradcliffe** [comment]
@acacheung I thought you did...but where is it? Did we just forget to merge it in?

**Comment by acacheung** [comment]
@dwradcliffe ha yea i believe we forgot. it probs needs some catching up though. will ping you when i get  wrap that up hopefully this weekend :)

**Comment by acacheung** [comment]
closing issue because it belongs here: https://github.com/rubygems/rubygems.github.com/

**Comment by arthurnn** [comment]
thanks @acacheung , I didnt open the issue there, because there is no issue tracker there! =)

**Comment by indirect** [comment]
@acacheung hey, did you by any chance manage to wrap up the blog redesign? I realize it's been a while, but our original plan did include a new design for the blog...

**Comment by arthurnn** [comment]
Should I reopen this? as there is no issue tracker in the other repo?

**Comment by acacheung** [comment]
@indirect @arthurnn will take a look soon!

**Comment by dwradcliffe** [comment]
ping @acacheung

**Comment by acacheung** [comment]
@arthurnn @dwradcliffe https://github.com/rubygems/rubygems.github.com/pull/22 !!!

**Comment by chasecoolman** [comment]
This has been resolved thanks to @acacheung
