### ISSUE TITLE
Docs contradiction? Cannot append to .files accessor?

### ISSUE THREAD

**Issue by dogweather** [rubygems/rubygems.org#865]
I'm learning to make gems, and reading http://guides.rubygems.org/specification-reference/ for gemspec .files, it says,

> You cannot append to this accessor, you must assign to it.

But then the code example contains,

```ruby
# or without Rake...
spec.files = Dir['lib/   *.rb'] + Dir['bin/*']
spec.files += Dir['[A-Z]*'] + Dir['test/**/*']
spec.files.reject! { |fn| fn.include? "CVS" }
```

Isn't that appending to the accessor?

**Comment by indirect** [comment]
This is really a Ruby question, and has nothing to do with Rubygems. That said, the answer is no. The += operator does not append, it creates a new array and assigns it.

**Comment by davefp** [comment]
I suggest this issue be closed.

Note: The guides have their own repo where issues like this can be raised: [rubygems/guides](https://github.com/rubygems/guides)

**Comment by arthurnn** [comment]
thanks @indirect and @davefp for answering this.
