### ISSUE TITLE
Specification Reference 'required gemspec attributes' not correct

### ISSUE THREAD

**Issue by dogweather** [rubygems/rubygems.org#866]
The docs seem to be wrong here. ( http://guides.rubygems.org/specification-reference/ ) I.e., `platform`, `require_paths`, and `rubygems_version` all have default values and are not required in a gemspec file.

The example gemspec file at the top of that page does not include these attributes.

REQUIRED GEMSPEC ATTRIBUTES

 author=
 authors=
 files
 name
 platform=
 require_paths=
 rubygems_version
 summary
 version

**Comment by davefp** [comment]
I think you have a valid point, but he guides are a separate repo [rubygems/guides](https://github.com/rubygems/guides). Please open an issue there and close this one. Thanks!

**Comment by dogweather** [comment]
Thanks! Done.
