### ISSUE TITLE
:hover effect on gem owners is misaligned in Firefox and IE

### ISSUE THREAD

**Issue by polamjag** [rubygems/rubygems.org#871]
Firefox (35.0.1, Linux):
![screenshot_2015-02-07_19-12-00](https://cloud.githubusercontent.com/assets/685936/6091838/5099e0ca-af02-11e4-83b6-9a960b38bcd1.png)

![screenshot_2015-02-07_19-41-13](https://cloud.githubusercontent.com/assets/685936/6091836/433ef0dc-af02-11e4-8e4f-265ce12a43fb.png)

![screenshot_2015-02-07_19-41-20](https://cloud.githubusercontent.com/assets/685936/6091837/4748cc34-af02-11e4-9632-add70f64e653.png)

IE11:
![untitled](https://cloud.githubusercontent.com/assets/685936/6091841/5d1cc376-af02-11e4-82c2-3d124ad9ea2a.png)

You know, this should be correct (Chromium 40.0.2214.111):
![screenshot_2015-02-07_19-31-35](https://cloud.githubusercontent.com/assets/685936/6091835/3afeb768-af02-11e4-8bd6-a4ea296f8f43.png)

I'm sorry but i cannot recognize what's going wrong, and cannot make pull request :(

**Comment by arthurnn** [comment]
fixed by https://github.com/rubygems/rubygems.org/pull/873
thanks
