### ISSUE TITLE
Duplicated URL for latest gem version

### ISSUE THREAD

**Issue by simi** [rubygems/rubygems.org#888]
Hello!

For example those two URLs have same content:
https://rubygems.org/gems/routing-filter/versions/0.5.0
https://rubygems.org/gems/routing-filter/

It will be good to prioritize one of those url and redirect to the second one or at least use [canonical link element](http://en.wikipedia.org/wiki/Canonical_link_element).

I would like to send patch for this if you're interested.

**Comment by dwradcliffe** [comment]
I'd :+1: adding the canonical link element. Not sure about the redirect. It's nice to be able to link to the specific version URL even if it is the latest.

**Comment by simi** [comment]
Cannonical url should be the full one with version?
