### ISSUE TITLE
jquery.easing.js still being used?

### ISSUE THREAD

**Issue by knappe** [rubygems/rubygems.org#890]
https://github.com/rubygems/rubygems.org/search?utf8=%E2%9C%93&q=easing

It doesn't look like we're using it anywhere, though I'm less sure of this after the redesign.  It looks to be safe to delete.

**Comment by arthurnn** [comment]
I would say this is indeed safe to be removed.
Wanna create a PR @knappe ?
thanks

**Comment by knappe** [comment]
Will do!

**Comment by arthurnn** [comment]
thanks all.
