### ISSUE TITLE
Small: count and display only gems that were not completely removed (yanked)

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#893]
Heya guys,

I just yanked one of my many gems (I do have too many, I admit
that). There were 4000 downloads. The interesting thing is
that on the main page, the old counter is still displayed.

I think the real counter should instead be x - 4000 here.

I yanked the old gem, so I assume that the counter also 
includes already yanked gems.

My proposal is this:

Do not count gem projects that were completely yanked.

My project page:

https://rubygems.org/profiles/shevy

The old yanked gem project is:

https://rubygems.org/gems/konsole_colours

This is probably a simple if-check, unfortunately
I am unfamiliar with the rubygems.org code to 
find out where the counter is:

"add_to_counter(n_downloads) if gem_still_exists?"

**Comment by dwradcliffe** [comment]
I don't think I agree. The downloads happened - they can't be un-downloaded just because the version was yanked.

**Comment by arthurnn** [comment]
agree with @dwradcliffe
