### ISSUE TITLE
Search only searches gem names

### ISSUE THREAD

**Issue by andrewhamon** [rubygems/rubygems.org#899]
A recent experience:

Search "one time password" - no results

Search "two factor" - three results

Search "otp" - 27 results.

It seems the descriptions of the gems are not being searched, merely the titles. This isn't very ideal from a user experience perspective.

**Comment by simi** [comment]
related to https://github.com/rubygems/rubygems.org/pull/455

**Comment by dennisvandehoef** [comment]
https://github.com/rubygems/rubygems.org/issues/847

**Comment by jirutka** [comment]
+1

**Comment by qrush** [comment]
We've been back and forth on search for years. There's been a lot of proposals and some PRs that have fizzled. I think Google has done a good job but we could do better. It's been hard lately since it's only until recently have we been running at full steam with a team that can handle operations smoothly.

I seem to recall search was in the works - @dwradcliffe maybe i'm thinking wrong? Or are we at search zero™ still?

**Comment by segiddins** [comment]
Might I suggest having a look at picky, @floere's gem that powers CocoaPods search?

**Comment by qrush** [comment]
We had a PR for picky a while ago as well. I'd rather go with whatever search tool our ops team is most comfortable with running.

**Comment by orta** [comment]
FWIW, I've only dealt with Picky from the creating-a-front-end perspective but it's been a dream to work with. Your dataset is a scale of magnitude larger than CocoaPods' but every time I've wanted to build a feature with search it's turned out well.

**Comment by jirutka** [comment]
[Picky](http://pickyrb.com/) looks very interesting, but don’t forget to consider performance and scalability. However, [stories](http://pickyrb.com/enterprise.html) on Picky’s website looks promising in this area. I see a downside in that it’s an one-man-show project that is not widely used. However, RubyGems would be a great opportunity to change this…

Another option would be ElasticSearch (it powers Stack Exchange, Logstash, …). It’s a very mature solution, but it runs on JVM. There’s a good support for Ruby: official “low-level” client [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby) and “high-level” abstraction [chewy](https://github.com/toptal/chewy).

**Comment by dwradcliffe** [comment]
There is active development happening on this problem. We're going to use Elasticsearch. Hopefully we'll have v1 ready for review soon!

**Comment by floere** [comment]
@jirutka @dwradcliffe One man show here… ;) I am looking forward to your first version – curious what you guys come up with with Elasticsearch, especially regarding the the UI. All the best! :)

**Comment by floere** [comment]
Btw, I believe @karmi once wrote an Elasticsearch version for RubyGems. Perhaps you can profit from his efforts?

**Comment by dwradcliffe** [comment]
Yes, @karmi did put a lot of effort into several PRs for this in the past. Unfortunately we didn't take advantage at the time. :disappointed: The ecosystem has changed a bit since then, so we can't directly use it but the current code is inspired by @karmi's original PRs.

**Comment by jirutka** [comment]
@floere Great to see you here! Please don’t get me wrong with that “one-man-show statement” etc., I really appreciate your work on Picky, love its simplicity and flexibility, and I’d be happy if Picky become more widespread. However, when I look at [contributors graph](https://github.com/floere/picky/graphs/contributors), I’m worried about the future of the project. :(

**Comment by floere** [comment]
@dwradcliffe Great to hear you can make use of @karmi's efforts :)
@jirutka No worries mate! :) Sincerely curious what you all come up with!

**Comment by pixelastic** [comment]
Hey guys,

I work at [Algolia](https://www.algolia.com/) and was considering sending you a PR which adds search to rubygems.org. I'm glad I found that topic before starting anything.

We're an hosted search engine, and we've already provided free accounts to popular open-source projects that we use and love. You can see them live on [Laravel](http://laravel.com/docs/5.1), [HackerNews](https://hn.algolia.com/?query=rubygems&sort=byPopularity&prefix&page=0&dateRange=all&type=story), [FontAwesome](https://fortawesome.github.io/Font-Awesome/icons/) or [cdnjs](https://cdnjs.com/) for example.

Going back to the original issue, the search will be able to search the name as well as the description, display them as you type, handling typos, plurals, synonyms and order them by popularity. We have adapters to automatically sync with most databases.

I just wanted to check with you first if this is something you'd be interested in, and what would be the best way to move forward together. If so, I'd be happy to start working on it. We would of course give you full, free and unlimited access to your account. We're just asking for a small "powered by Algolia" logo in exchange.

If you want to move this forward, or have any other questions, just ask, I'm really motivated to work on this.
