### ISSUE TITLE
Password reset email is not linked

### ISSUE THREAD

**Issue by mperham** [rubygems/rubygems.org#908]
Looks like it needs some line breaks to read better.  If on its own line, I suspect Gmail will hyperlink it.

![screen shot 2015-03-18 at 10 10 11](https://cloud.githubusercontent.com/assets/2911/6714751/3effaf2a-cd57-11e4-836c-0c2125c84d6f.jpg)

**Comment by arthurnn** [comment]
interesting, I just tested this and Gmail hyperlinked just fine for me.

**Comment by mperham** [comment]
Yeah, I was actually pretty surprised, IME any Gmail links anything that looks vaguely hyperlinkish.

**Comment by farukaydin** [comment]
I think it can be closed, thoughtbot/clearance@41f06be will fix the issue.

**Comment by arthurnn** [comment]
Thanks @farukaydin . I will keep watching clearance for the next release.

**Comment by derekprior** [comment]
Clearance 1.9.0 is out and includes this change.
