### ISSUE TITLE
Reminder: Recommit metadata branch when hstore is enabled

### ISSUE THREAD

**Issue by jimmycuadra** [rubygems/rubygems.org#914]
Commit e81a2976bb416b51acd789d2869a287e890b129b reverted #858, citing that hstore is not available in production yet. I'm creating this issue as a reminder to recommit the branch when possible, just so it doesn't get lost in the shuffle! :)

**Comment by dwradcliffe** [comment]
The server is ready so we can do this anytime now.

On Friday, March 27, 2015, Jimmy Cuadra <notifications@github.com> wrote:

> Commit e81a297
> <https://github.com/rubygems/rubygems.org/commit/e81a2976bb416b51acd789d2869a287e890b129b>
> reverted #858 <https://github.com/rubygems/rubygems.org/pull/858>, citing
> that hstore is not available in production yet. I'm creating this issue as
> a reminder to recommit the branch when possible, just so it doesn't get
> lost in the shuffle! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/issues/914>.
>


-- 
---
David Radcliffe
radcliffe.david@gmail.com
dwradcliffe.com

**Comment by arthurnn** [comment]
just revert-revert on master https://github.com/rubygems/rubygems.org/commit/a72bc3b6506ffbdb5aeb1ec3f23d88c69ce05851 and am deplying this to produciton right now.

thanks
