### ISSUE TITLE
Search should handle encoded amp;

### ISSUE THREAD

**Issue by lloydde** [rubygems/rubygems.org#916]
http://kitchen.ci/docs/getting-started/next-steps links to
`https://rubygems.org/search?utf8=%E2%9C%93&amp;query=kitchen-`
which has no results, whereas the expected results are 
`https://rubygems.org/search?utf8=%E2%9C%93&query=kitchen-`
has the expected results.

**Comment by bradly** [comment]
@lloydde I'm think this is working correctly. See this test link: https://jsfiddle.net/k93e6t04/2/ . Looking at the href on your page ```<a href="https://rubygems.org/search?utf8=%E2%9C%93&amp;amp;query=kitchen-">``` it looks like the & is double escaped.

**Comment by lloydde** [comment]
@bradly sorry, you are correct.
