### ISSUE TITLE
Remove webhooks with too many failures automatically

### ISSUE THREAD

**Issue by vassilevsky** [rubygems/rubygems.org#934]
Hello :)

I don't have a clear picture of how much resources are wasted on failed attempts to send webhooks. I failed to understand where can I see graphs that *statsd* collects.

*If* it's wasting too much resources, I could implement automatic cleanup of webhooks that have a really big number of failures.

Also, maybe this number should be reset after each success, so that we have a better picture. If the number only means *consecutive* failures, it's easier to decide when the webhook is dead.

The job coould also notify the user who installed the webhook after a certain threshold, and delete the webhook only after another threshold.

What do you think?

**Comment by simi** [comment]
You can inspect `web_hooks` table from [production dump](https://rubygems.org/pages/data).

**Comment by qrush** [comment]
I don't feel like this is a big problem we have. Maybe for a larger service, or something like Slack. Closing this until there's more evidence it is a problem.

**Comment by dwradcliffe** [comment]
Yeah, we honestly don't have a lot of webhooks, and although we do have failures, it's not clogging up the system. Thanks for asking though!

**Comment by vassilevsky** [comment]
Alright :) I was just feeling sorry for 6K failures on my webhook to a VM that was deleted because I stopped paying for it. I deleted the webhook as well now.
