### ISSUE TITLE
Full gem dependencies tree (can be as separate view)

### ISSUE THREAD

**Issue by Gedrovits** [rubygems/rubygems.org#937]
Hello.

I know that there is ruby eco-systems where gem dependencies is quite important issue and decision to use or not use some gem highly depends on it's dependencies and requirements.

A view, where user can see a recursive list tree of dependencies / requirements for exact gem.
Currently this can be achieved by going through links for all gems and it's dependencies to build a 'tree' in mind.

Performance-wise it's not that bad, because it's a separate view only people who needs this will use it.

So the questions are:
- Someone else needs this kind of info? Maybe suggestions?
- Will it be merged if proper pull request provided?

**Comment by IsmailM** [comment]
+1

**Comment by qrush** [comment]
Would #945 help?

I think we're in a better spot with regards to our systems + operations - so of course we would consider it if there's a PR!

**Comment by matk0** [comment]
Is anyone working on this? I would take it up.

**Comment by sonalkr132** [comment]
@matk0 No one is working on this. Have at it :white_check_mark:

**Comment by matk0** [comment]
@sonalkr132 do I get it right that the label needs-pr means that the feature as such is approved and it's just waiting to be taken up by someone? This label is not explained in the the CONTRIBUTING.rdoc. I can put it there if you like.

**Comment by sonalkr132** [comment]
> Do I get it right that the label needs-pr means that the feature as such is approved and it's just waiting to be taken up by someone?

Yeah, Thats what they generally mean.

> This label is not explained in the the CONTRIBUTING.rdoc. I can put it there if you like.

I don't speak for rubygems team. I am only giving you what information I have :blue_heart:

**Comment by jcrben** [comment]
For Python, I've been using https://github.com/naiquevin/pipdeptree - I suppose Python code is too different to be much inspiration, but perhaps there might be some UX inspiration

**Comment by ecnelises** [comment]
Any progress on this? I'm interested on it.

**Comment by sonalkr132** [comment]
closed by #2029
