### ISSUE TITLE
Profiles need overflow on user names

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#941]
Via http://help.rubygems.org/discussions/suggestions/7810-usernames-longer-than-15-characters-look-ugly-on-profile-page

**Comment by gurgelrenan** [comment]
@jdax Did you submit a pull request?

**Comment by timbreitkreutz** [comment]
It looks like two two commits above (https://github.com/jdax/rubygems.org/commit/002875185a3f2d39506735f7b2b8e1373a9f85c4 and https://github.com/jdax/rubygems.org/commit/819c78f4d257a375747cbab7165d200226734332)  fixed it to me.   Can this be closed?

Screenshot from live site attached


<img width="1014" alt="wide" src="https://cloud.githubusercontent.com/assets/42360/11099315/7e870c1a-885f-11e5-96ce-b2de25de0e05.png">
<img width="798" alt="narrow" src="https://cloud.githubusercontent.com/assets/42360/11099316/7eaf5dfa-885f-11e5-8db4-a562d568f515.png">
