### ISSUE TITLE
Missing dependency names

### ISSUE THREAD

**Issue by andrew** [rubygems/rubygems.org#948]
I noticed something a little strange on the [carrierwave_securefile](https://rubygems.org/gems/carrierwave_securefile) gem:

![screen shot 2015-05-03 at 7 07 07 pm](https://cloud.githubusercontent.com/assets/1060/7446163/e68cfee8-f1c7-11e4-9214-958e8694e785.png)

The name of the dependency (crypt19 according to the [gemspec on github](https://github.com/dougc84/carrierwave_securefile/blob/master/carrierwave_securefile.gemspec#L49)) is missing but the requirement is still there.

Looks like, from https://github.com/dougc84/carrierwave_securefile/pull/5, crypt19 was deleted and then added again as [crypt19-rb](https://rubygems.org/gems/crypt19-rb), I suspect it should either show the name, perhaps unlinked or ~~striked~~ or remove the line completely?

It also shows up as `null` in the api, https://rubygems.org/api/v1/gems/carrierwave_securefile.json, which is how I initially discovered the issue.

**Comment by arthurnn** [comment]
What will happen if we try to install that gem? I think it will fail because will not find the dependency right?

I think we should remove the line completely from the UI and API. Thoughts @sferik @dwradcliffe

**Comment by andrew** [comment]
Yep, you get: 

```
$ gem install carrierwave_securefile
ERROR:  Could not find a valid gem 'crypt19' (= 1.2.1) in any repository
ERROR:  Possible alternatives: crypt, crypt19-rb, crypt3, crypto, cryptor
```

**Comment by farukaydin** [comment]
@arthurnn if you didn't started to working on it, I can take a look ?

**Comment by qrush** [comment]
Wow nice catch. Definitely needs some work.

**Comment by farukaydin** [comment]
@qrush @arthurnn we can remove the lines from both api and ui, but we should also notify users like "gem dependency is removed from rubygems.org" from ui to inform user about why the gem isn't installed. Any thoughts?

**Comment by arthurnn** [comment]
@farukaydin I didnt start working on it yet...
thanks
