### ISSUE TITLE
Version built datetime

### ISSUE THREAD

**Issue by andrew** [rubygems/rubygems.org#949]
Versions currently have a built_at attribute that's provided as a date via the API, is it possible to get the time that the version was created as well?

I'm using built_at on https://libriaries.io at the moment but it doesn't work so well when showing recently created/updated gems as they all show as being published at midnight.

I'd be happy to send a PR to add `created_at` to `Version#payload` if it's addition is approved.

**Comment by qrush** [comment]
Sounds good. :+1:

**Comment by andrew** [comment]
:dancer: Thanks @arthurnn!

**Comment by arthurnn** [comment]
:dancers:
