### ISSUE TITLE
Development dependencies for older versions

### ISSUE THREAD

**Issue by andrew** [rubygems/rubygems.org#950]
You can currently see the dependency list for every version of a gem via the web interface but the dependency list is only available on via the API for the latest version as far as I can see.

Two ways I can see for making this available:

1. Adding dependencies to `Version#payload` for the existing version api endpoints
or
2. Added a separate endpoint for just the dependencies for a version of a gem

I'd be happy to contribute to either, option 1. being much easier but potentially adding quite a bit of weight to an endpoint that gets hit a lot already?

**Comment by farukaydin** [comment]
LGTM. I prefer separate dependencies endpoint like reverse dependencies in version api.

**Comment by andrew** [comment]
@farukaydin just working on this now, there aren't many examples of route formats an end point for a particular version, would you prefer:

`/api/v1/gems/[GEM NAME]/dependencies.json` with `version` passed as a parameter or default to latest

or something more like:

`/api/v1/versions/[GEM NAME]/[VERSION]/dependencies.json`

**Comment by farukaydin** [comment]
For downloads endpoint ```/api/v1/downloads/[GEM NAME]-[GEM VERSION].(json|yaml)``` was used.

So you can use ```/api/v1/versions/[GEM NAME]-[GEM VERSION]/dependencies.json```

**Comment by balasankarc** [comment]
@farukaydin @andrew  Any plan on implementing this? I am also waiting for such a feature.

**Comment by andrew** [comment]
@balasankarc I've not had time to pick this up yet, feel free to take it on instead.

**Comment by balasankarc** [comment]
@andrew  Let me see if I can. I am not a Ruby/RoR developer by profession, so there are chances of me making a mess. :) . Let me try to read/understand the code.

**Comment by balasankarc** [comment]
@srih4ri said he will try to help in implementing this. He's a Ruby dev and got a better chance in doing it than me. :)

**Comment by dwradcliffe** [comment]
We have the dependency API which should solve this I think.
https://rubygems.org/api/v1/dependencies.json?gems=rack

**Comment by balasankarc** [comment]
No. Dependency API doesn't list the development dependencies. It only lists runtime dependencies. Please reopen the issue.

**Comment by dwradcliffe** [comment]
Ahh, didn't realize that was the goal.

**Comment by sonalkr132** [comment]
This was implemented in #1392. You can see runtime and development dependencies at: https://rubygems.org/api/v2/rubygems/activerecord/versions/5.0.0.json
