### ISSUE TITLE
Useless response for gem owners/profiles API for users with empty handle and hidden email

### ISSUE THREAD

**Issue by antlypls** [rubygems/rubygems.org#951]
This issue is related to #927.

Gem owners and profiles api return json like `{"handle":null}` if user has empty handle and hidden email.
Such response doesn’t make much sense. Maybe it’s better to return `display_handle`?

**Comment by qrush** [comment]
Definitely a bug. Yep.

**Comment by arthurnn** [comment]
this should be fixed by https://github.com/rubygems/rubygems.org/pull/955
