### ISSUE TITLE
platform gems do not get shown

### ISSUE THREAD

**Issue by kares** [rubygems/rubygems.org#954]
... in search or the gem detail page.

e.g. jruby-openssl changed it's  `gem.platform = 'java'` since **0.9.5**
so that MRI/Rubinius users do not attempt to gem install ... it's clearly a platform specific gem.

search (list) shows **0.9.4** https://rubygems.org/search?utf8=%E2%9C%93&query=jruby-openssl
as well as the detail page https://rubygems.org/gems/jruby-openssl (on top), the newer versions are correctly ordered and listed under VERSIONS

**Comment by qrush** [comment]
This is expected behavior - we're just not showing the platform gems on search and on the gem detail page. If there's only one platform then we show that platform. The default is to always show the normal Ruby platform version.

**Comment by kares** [comment]
Thanks Nick, please this is really annoying for gems such as jruby-openssl - they had previously not had platform specific releases but now they do (and they only have a platform specific *-java* release) - users do not see the latest versions of those ;( ... how is this expected behavior - could you maybe reconsider?
