### ISSUE TITLE
Owners API does not accept user id.

### ISSUE THREAD

**Issue by antlypls** [rubygems/rubygems.org#956]
Not sure is this a bug, or it's designed this way. Owners API only accepts user `handle` to identify user, requests with `id` like `http://rubygems.org/api/v1/owners/12345/gems.json` return 404.
That is not consistent with profiles API that accepts both `id` and `handle`.

**Comment by simi** [comment]
It should be easy to achieve this by using `User.find_by_slug!` here https://github.com/rubygems/rubygems.org/blob/28a96d949e3d83ee04335ecde19b006fa58fd5bd/app/controllers/api/v1/owners_controller.rb#L37.

But it will be great to keep this consistent across whole API. I'm not sure what's preferred way.

**Comment by qrush** [comment]
Nice catch. +1.
