### ISSUE TITLE
Background-color without color

### ISSUE THREAD

**Issue by Mazwak** [rubygems/rubygems.org#969]
Hi

A background color is set in the body, without setting the color attribute. It makes the pages almost unreadable if base color is white or light grey.

It can happen if you have custom CSS, and recently it's default on Fedora 22 if you choose the dark Gnome theme and use Firefox.

It would be nice to set color to black or near black.

**Comment by arthurnn** [comment]
I think we are not going to change the design again, as it was changed already not that long ago.
:-1: from me on this.

**Comment by indirect** [comment]
I think this was just a request to explicitly set the text color, rather than relying on the browser to default it to black. That seems reasonable to me...

**Comment by arthurnn** [comment]
Thanks for clarifying @indirect .. I was not sure if I had understood it right.
@Mazwak fell free to open a PR for this.

**Comment by nateberkopec** [comment]
Example - here's what the Status page looks like if the user stylesheet has set `color` to `pink`:

![screen shot 2015-10-14 at 9 16 24 am](https://cloud.githubusercontent.com/assets/845662/10484666/54b9450e-7254-11e5-96e4-d01d85698014.png)
