### ISSUE TITLE
http://uptime.rubygems.org/ down

### ISSUE THREAD

**Issue by simi** [rubygems/rubygems.org#976]
try http://uptime.rubygems.org/

![screenshot-uptime rubygems org 2015-06-09 10-18-31](https://cloud.githubusercontent.com/assets/193936/8053437/ee831a0c-0e90-11e5-8a10-585fb38df84b.png)

**Comment by dwradcliffe** [comment]
Assigning this to @qrush since you have the pingdom account.

**Comment by qrush** [comment]
I tweeted at their support. I can't figure out where in the pingdom UI this was configured in the first place.

**Comment by qrush** [comment]
It's back up. Apparently they removed the feature for the plan we were on so they switched the plan for us to the one that does.

**Comment by simi** [comment]
Bombastico!
