### ISSUE TITLE
SSL error while installing jekyll

### ISSUE THREAD

**Issue by Awake99** [rubygems/rubygems.org#982]
So I am trying to install jekyll on my mac, and after disabling the firewall and putting in the command: $ gem install jekyll, it ran for about 15 minutes and I received this error:ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read finished A

I would appreciate any help! I ran this from the root account and I have Ruby and RubyGems updated and installed as part of OS X Yosemite. Thanks.

**Comment by dwradcliffe** [comment]
Sorry you're having trouble! It would be better to open a help ticket at help.rubygems.org since this is the repository/issues for the RubyGems.org application itself.
