### ISSUE TITLE
"latest" API reports old version of gem

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems.org#987]
Checking the curb version [1], the "latest" API call returns 0.5.8.0 version where the "gems" returns properly version 0.8.8.

```
$ curl http://rubygems.org/api/v1/versions/curb/latest.json
{"version":"0.5.8.0"}

$ curl http://rubygems.org/api/v1/gems/curb.json
{"name":"curb","downloads":3105943,"version":"0.8.8","version_downloads":67959,"platform":"ruby","authors":"Ross Bamford, Todd A. Fisher","info":"Curb (probably CUrl-RuBy or something) provides Ruby-language bindings for the libcurl(3), a fully-featured client-side URL transfer library. cURL and libcurl live at http://curl.haxx.se/","licenses":[],"metadata":{},"sha":"ec3b5880d92c9a9140555fc5c86524025474a905e6548e1c37816247ad60903e","project_uri":"http://rubygems.org/gems/curb","gem_uri":"http://rubygems.org/gems/curb-0.8.8.gem","homepage_uri":"http://curb.rubyforge.org/","wiki_uri":"http://wiki.github.com/taf2/curb","documentation_uri":"http://taf2.github.com/curb/","mailing_list_uri":"http://groups.google.com/group/curb---ruby-libcurl-bindings","source_code_uri":"http://github.com/taf2/curb","bug_tracker_uri":"http://github.com/taf2/curb/issues","dependencies":{"development":[],"runtime":[]}}
```

[1] https://rubygems.org/gems/curb/versions

**Comment by voxik** [comment]
I noticed this since release-monitoring.org [1] recently started to use the "latest" API where it used to use the "gems" API. But may be it was not the best idea ...


[1] https://release-monitoring.org/project/4276/

**Comment by dwradcliffe** [comment]
Yeah, something is off here. Investigating.

**Comment by voxik** [comment]
thx ... the same issue apply for eventmachine, json ...

**Comment by maclover7** [comment]
Is the issue that [here](https://github.com/rubygems/rubygems.org/blob/master/app/controllers/api/v1/versions_controller.rb#L19), we are calling:

```
rg.versions.latest.first
```

Should this be changed to:
```
rg.versions.latest
```

Happy to submit a PR.

**Comment by dwradcliffe** [comment]
@maclover7 Yep, I think you're right. Feel free to submit a PR :)

**Comment by maclover7** [comment]
Awesome. Will submit a PR either today or tomorrow.
