### ISSUE TITLE
Unable to install pry gem on Windows 7

### ISSUE THREAD

**Issue by echristopherson** [rubygems/rubygems.org#989]
I currently (for the past 8 days at least) get an error when trying to gem install pry in Windows 7 using Ruby 2.2.2p95 (32-bit):

    X:\Scripts>gem install pry
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --platform ruby
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --pre
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-1.0.0.pre1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --pre --platform ruby
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-1.0.0.pre1-x86-mingw32.gemspec.rz)

I first noticed this problem on June 17. But I was able to install pry on my Mac that same day with no problems.

**Comment by dwradcliffe** [comment]
I'm pretty sure this is a client problem, but can you tell me what you get from this:
`ruby -e 'puts Gem.platforms.inspect'`

**Comment by dwradcliffe** [comment]
Here's more details before I send this back to [rubygems/rubygems](https://github.com/rubygems/rubygems).

The gems you are referencing are actually only available for platforms `i386-mswin32` or `i386-mingw32` (for windows). For some reason, the urls above are for `x86-mingw32`. We've double checked the server and index and everything is consistent there. So it seems like your rubygems client is requesting the wrong platform/url for some reason.

I'm going to close this so the discussion can continue here: https://github.com/rubygems/rubygems/issues/1293
