### ISSUE TITLE
History of rubygems.org

### ISSUE THREAD

**Issue by anvaka** [rubygems/rubygems.org#993]
@qrush: Nick, what was your inspiration when you started rubygems project?

**Comment by arthurnn** [comment]
I think it started in a RailsConf... @qrush please link any blog post you have in here.. Maybe in the future we could add a INFO page or something.

For now I will close the issue, as it is not an issue.
thanks

**Comment by qrush** [comment]
I talked about this in 2009. I'd be happy to answer any questions about it, just email me! http://confreaks.tv/videos/rubyconf2009-gemcutter-the-next-step-in-gem-hosting

Also I gave a small update this year at RubyNation...hopefully that will be published soon!
